### ISSUE TITLE
deploy minio in standalone mode

### ISSUE THREAD

**Issue by redsigma** [minio/operator#1025]
## Expected Behavior

The below helm configuration should start minio in standalone mode. According to the [documentation of minio](https://docs.min.io/minio/baremetal/installation/deploy-minio-standalone.html?highlight=standalone%20mode) it says:

`The following procedure deploys MinIO in Standalone Mode consisting of a single MinIO server and a single drive or storage volume. Standalone deployments are best suited for evaluation and initial development environments.`

```yaml
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
      - servers: 1
        ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
        volumesPerServer: 1
 
```

## Current Behavior
Deploying the helm chart doesn't deploy anything. But if i use 1 server and 4 volumes, then it gets deployed correctly.

## Context
Doing replication on a limited storage forces you to use 4 disks

## Your Environment

* Version used (`minio-operator`): v4.4.7
* Environment name and version (e.g. kubernetes v1.17.2): v1.19.7
* Server type and version: v1.19
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
Operator is not meant for single drive deployments @redsigma
