### ISSUE TITLE
Default EC parity not applied when using multiple server pools in a tenant

### ISSUE THREAD

**Issue by mshanmu** [minio/operator#1026]
Using https://docs.min.io/minio/baremetal/concepts/erasure-coding.html#storage-classes  as reference.

Created a tenant with 4 servers/1 drive (2 TiB each) pool, as expected it had 2 parity, resulting in 4 TiB of usable capacity. Next, added another server pool, with similar configuration, i.e., 4 servers/1 drive (2 TiB each), resulting in 8 TiB of usable capacity.

Today, added another server pool of 8 servers/1 drive (2 TiB each), I expected a default parity of 4, instead noticed it applied only 2. 

## Expected Behavior

Expected third pool to use 4 as parity based on the default settings.

## Current Behavior

Third pool has only 2 as parity, i.e., at-most only 2 drives can go offline.

## Steps to Reproduce (for bugs)

1. Create a tenant with a 4 server/1drive server pool
2. Notice half the drives being used as  parity
3. Add another 4 servers/1 drive server pool
4. Notice half the drives being used as  parity
5. Add another 8 servers/1 drive server pool
6. Notice only 2 drives being used as parity

## Context

Availability/data resiliency is reduced

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
Only parity will be pools, not data portion. We support the same SLA in a heterogeneous setup. 

You cannot expand that's why 4 shard setup into an 8 shard setup 

This is not allowed since you loose way too much HA.

**Comment by mshanmu** [comment]
@harshavardhana , What does "parity will be pools" sentence mean, Can you please explain it or point me to documentation?

**Comment by harshavardhana** [comment]
> @harshavardhana , What does "parity will be pools" sentence mean, Can you please explain it or point me to documentation?

Your original pool defines the SLA. You setup a toy setup and try to make it production worthy setup is not allowed.

This is called sizing a setup. You haven't done that activity or simply skipped it.

We can't have arbitrary parity on each pool because there is no way for us to provide realistic guarantees on usage and scheduling of I/O.
