### ISSUE TITLE
Openshift OKD 4.9 - operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)

### ISSUE THREAD

**Issue by nnachefski** [minio/operator#1033]
Hello,

Installed the operator from the OperatorHub in Openshift OKD 4.9 and am getting this error from the operator pod after it launches.  Please advise.

I0225 16:37:21.441399       1 main.go:74] Starting MinIO Operator
I0225 16:37:21.646109       1 main.go:146] caBundle on CRD updated
I0225 16:37:21.646710       1 main-controller.go:272] Setting up event handlers
I0225 16:37:21.647099       1 main-controller.go:656] Starting Tenant controller
I0225 16:37:21.647163       1 main-controller.go:659] Waiting for informer caches to sync
I0225 16:37:21.706699       1 main-controller.go:620] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
E0225 16:37:21.723597       1 operator.go:104] Unexpected error during the creation of the csr/operator-openshift-operators-csr: the server could not find the requested resource
I0225 16:37:21.723747       1 main-controller.go:623] Waiting for the operator certificates to be issued the server could not find the requested resource
I0225 16:37:21.847325       1 main-controller.go:664] Starting workers
I0225 16:37:31.729606       1 main-controller.go:620] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
E0225 16:37:31.732131       1 operator.go:104] Unexpected error during the creation of the csr/operator-openshift-operators-csr: the server could not find the requested resource
I0225 16:37:31.732151       1 main-controller.go:623] Waiting for the operator certificates to be issued the server could not find the requested resource
I0225 16:37:41.735848       1 main-controller.go:620] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
E0225 16:37:41.738823       1 operator.go:104] Unexpected error during the creation of the csr/operator-openshift-operators-csr: the server could not find the requested resource

**Comment by kanagarajkm** [comment]
@nnachefski what is the Kubernetes version? minio-operator requires `Kubernetes 1.19 or Later`

**Comment by nnachefski** [comment]
Kubernetes Version: v1.22.1-1829+2cb60681522d23-dirty

**Comment by Alevsk** [comment]
@nnachefski This is probably because of an old version of operator, the following error:

```
Unexpected error during the creation of the csr/operator-openshift-operators-csr: the server could not find the requested resource
```

Is telling us probably the operator is using `v1beta1` version of the `csr` resource to create the certificate, which version of operator are you using? can you upgrade to the latest version?

**Comment by nnachefski** [comment]
Starting version
minio-operator.v4.0.2

Tenant CR:
apiVersion: minio.min.io/v2

**Comment by Alevsk** [comment]
Yes, the problem is that version of the operator still uses `certificates "k8s.io/api/certificates/v1beta1"`, which doesn't exist in kubernetes version `v1.22`, the solution for this is pretty simple, just upgrade you operator to the latest version:

`kubectl apply -k github.com/minio/operator/\?ref\=v4.4.10`

**Comment by nnachefski** [comment]
How do i do this on the OperatorHub?  It is showing that i'm on the latest.

![image](https://user-images.githubusercontent.com/5325779/156041204-c2aaa617-2d85-4cd8-aa6c-43ac801723a6.png)

**Comment by nnachefski** [comment]
Is there an 'alpha' channel i can use in the CSV to try the newer version?

![image](https://user-images.githubusercontent.com/5325779/156041440-4942b4b5-7e3d-4785-83b7-c44947b1229f.png)

**Comment by Alevsk** [comment]
@nnachefski ill investigate this and come back to you

**Comment by Alevsk** [comment]
@nnachefski please try with this one https://operatorhub.io/operator/minio-operator (`4.4.9`)
