### ISSUE TITLE
Upgrade from 4.4.3 -> 4.4.10 Failing on `fetchArtifacts` Check

### ISSUE THREAD

**Issue by mjnagel** [minio/operator#1035]
## Expected Behavior

Currently I'm trying to complete the update from operator 4.4.3 to 4.4.10 as well as a tenant update from `RELEASE.2022-01-08T03-11-54Z` to `RELEASE.2022-02-26T02-54-46Z`. I have all images hosted on a private registry and rebuilt (so the same binaries, but on a "hardened" base container). I would expect this setup and upgrade to work as I've done multiple upgrades in the past without issue.

## Current Behavior

What I'm seeing during the upgrade seems to be a failure on the `fetchArtifacts` check that happens on the operator. The operator itself updates fine, but the tenant does not update to the new image version. Checking the operator logs I initially was seeing:
```
1 main-controller.go:559] error syncing 'minio/<myinstance>': Get "https://<myregistry>": read tcp <IPs>: read: connection reset by peer
```
After adjusting networkpolicies on my cluster the operator was able to hit the registry, at which point I ran into:
```
1 main-controller.go:559] error syncing 'minio/<myinstance>': Tar file extraction failed for file index: 2, with: EOF
```
I dug into the operator code and realized that my "hardened" minio did not contain the minio.sha256sum & minio.minisig files that the operator expects. I rebuilt the image with these files and then ran into this error:
```
1 main-controller.go:559] error syncing 'minio/<myinstance>': Tenant '<myinstance>' MinIO update failed with server update failed with: open /usr/bin/.minio.new: permission denied, do not restart the servers yet
```
I believe this is due to the hardening on the image - file permissions are more locked down to prevent users from writing to files like this.

Ultimately it looks like I could refactor my image a lot to add the things that the operator expects, but in the past an image built the same way worked. I have done upgrades from 4.1.2 -> 4.2.3 -> 4.4.3 without issue, all Minio tenant images were missing the sha and sig files and had the same locked down permissions. 

Is this `fetchArtifacts` check something new that became required? I looked through commit history but was unable to find any major change in functionality for it.

I vaguely remember seeing the initial error of failing to hit my registry in operator logs in the past but the tenant always updated fine regardless. Is there any way to disable this check, given that I am pulling from my own trusted registry and have other ways of validating the image?

**Comment by harshavardhana** [comment]
@mjnagel you have many things wrong here first is 

- you have perhaps wrong security context set that operator doesn't understand
- you are also using a custom MinIO container image.

**Comment by mjnagel** [comment]
@harshavardhana I can definitely look into the securityContext, that might be off of what is used in my image - thanks for the pointer.

With regards to your second point... I am using the Helm chart which allows me to specify a custom repository and tag for the tenant image - https://github.com/minio/operator/blob/master/helm/tenant/values.yaml#L6 . If using a "custom" image is not supported what is the point of adding those fields? I should also mention that I'm able to spin everything up fine on a "clean install" so I know that the operator and tenant images are built properly, its just the upgrade that has issues due to the `fetchArtifacts` mentioned.

**Comment by harshavardhana** [comment]
> With regards to your second point... I am using the Helm chart which allows me to specify a custom repository and tag for the tenant image - https://github.com/minio/operator/blob/master/helm/tenant/values.yaml#L6 . If using a "custom" image is not supported what is the point of adding those values? I should also mention that I'm able to spin everything up fine on a "clean install" so I'm reasonably confident that the operator and tenant images are built properly, its just the upgrade that has issues due to the `fetchArtifacts` mentioned.

fetchArtifacts has issue because your have changed the image from our published images.

**Comment by mjnagel** [comment]
Tracking...I can close this issue. I guess my biggest confusion is still that the function seems to have changed from allowing errors in the past to failing and blocking the upgrade. I didn't see this called out anywhere in the changelog or commit history...are you aware of this behavioral change?

**Comment by dvaldivia** [comment]
per https://github.com/minio/operator/pull/266 if the fetch of artifacts fail, we stop syncing the tenant and stop at that error, a work around is to delete the STS, but I think we should just let the statefulsets roll in this scenario, what do you think @harshavardhana

**Comment by harshavardhana** [comment]
> Tracking...I can close this issue. I guess my biggest confusion is still that the function seems to have changed from allowing errors in the past to failing and blocking the upgrade. I didn't see this called out anywhere in the changelog or commit history...are you aware of this behavioral change?

Well, we did that because we don't want you to end up in some random state.  Our operator is used by upgrade sensitive setups we can't let an upgrade proceed and then fail everything later.  We are in the data business and its critical for us to not do random unexpected things on a production cluster.

So what we did was to avoid mistakes for naive users - there is no reason for us to call this out anywhere, 

The operator works with MinIO published images that's all - if you use your own custom image you are on your own. You should also build your own operator version if needed. 

> per #266 if the fetch of artifacts fail, we stop syncing the tenant and stop at that error, a work around is to delete the STS, but I think we should just let the statefulsets roll in this scenario, what do you think @harshavardhana

@dvaldivia there is no reason to do that IMO - this issue is simply out of scope.

**Comment by mjnagel** [comment]
@dvaldivia yeah I found that workaround to work for me. It seems weird that this check would block rolling out the update in my opinion, but understand if it's seen as out of scope. I can probably validate this further tomorrow but I'm almost certain that in past upgrades I've worked through the check did "fail gracefully" and continue with the update.
