### ISSUE TITLE
No upgrade path from v4.1.0 and minio/minio:RELEASE.2021-06-07T21-40-51Z

### ISSUE THREAD

**Issue by dfsdevops** [minio/operator#1037]
## Expected Behavior
I should be able to upgrade the Operator to latest version without breaking the tenant. There should be clear documentation for upgrading the operator along w/ required Tentant spec changes.

## Current Behavior
When upgrading the operator from `v4.1.0` to `v4.4.9` while still on tenant image `minio/minio:RELEASE.2021-06-07T21-40-51Z`, I get two issues:

Firstly, the operator fails to detect that the version is incompatible with the operator, and it updates the statefulset, this results in:

```
Incorrect Usage: flag provided but not defined: -console-address

NAME:
  minio server - start object storage server

USAGE:
  minio server [FLAGS] DIR1 [DIR2..]
  minio server [FLAGS] DIR{1...64}
  minio server [FLAGS] DIR{1...64} DIR{65...128}
```
  
 Secondly, it also adds a securityContext that is incompatible with the previous volumes.
 
 ```
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
```

## Possible Solution
I have tried upgrading the tenant before upgrading the Operator, but this also fails. It only works with up to version `minio/minio:RELEASE.2021-08-17T20-53-08Z`. The problem with doing this is that the admin interface no longer works and it redirects to an randomized console port.

## Steps to Reproduce (for bugs)

1. Deploy operator version v4.1.0 
2. Deploy minio tenant minio/minio:RELEASE.2021-06-07T21-40-51Z
3. Attempt to upgrade operator to version v4.4.10
4. Observe that the minio operator will put the StatefulSet in a bad state and pods will being to crashloop
5. Update the image on the tenant spec to version RELEASE.2022-01-08T03-11-54Z
6. StatefulSet will remain stuck with version minio/minio:RELEASE.2021-06-07T21-40-51Z until manually updating the image, operator will not reconcile.

## Context
We are currently seeing a critical error on our minio servers during large multi-part uploads and we need to get it upgraded so we can confirm whether it's a bug that still exists on later versions.

## Regression
Don't know

## Your Environment

* Version used (`minio-operator`): v4.1.0 -> v4.4.10
* Environment name and version (e.g. kubernetes v1.17.2): v1.22.5
* Server type and version: docker desktop for mac (for testing)
* Operating System and version (`uname -a`): 
* Link to your deployment file:

**Comment by harshavardhana** [comment]
you need to upgrade operator as well as tenant image @dfsdevops

**Comment by dfsdevops** [comment]
I have tried to do both at the same time, the statefulset image space still seems to be stuck on version `minio/minio:RELEASE.2021-06-07T21-40-51Z` while the tenant spec has the newer version.

**Comment by dfsdevops** [comment]
Ok so I think I am able to get it (sort of) upgraded if I explicitly update the image first in the tenant and update the security context at the same time from minio/minio:RELEASE.2021-06-07T21-40-51Z to quay.io/minio/minio:RELEASE.2022-01-08T03-11-54Z before the operator. I can't really control the order that pods come up declaratively though, I'll have to apply it in two different steps. This makes it difficult to upgrade via gitops.

Is there any danger in updating the image before updating the operator? I see several errors and pods crashing until the operator comes up. Once the operator is up, something seems to kick into gear, however, the operator still has an error getting the cluster info. As shown below


```
minio-operator-687d595cd8-9lclx minio-operator I0303 20:04:17.038773       1 status.go:120] Hit conflict issue, getting latest version of tenant
minio-operator-687d595cd8-9lclx minio-operator I0303 20:05:30.303763       1 monitoring.go:176] 'my-minio/minio' Failed to get storage info: Server not initialized, please try again.
```

The minio pods seem ok but the operator cannot communicate with them.

```
●  minio-ss-0-1.minio-hl.my-minio.svc.cluster.local:9000
   Uptime: 19 minutes
   Version: 2022-01-08T03:11:54Z
   Network: 2/2 OK
   Drives: 2/2 OK

●  minio-ss-0-0.minio-hl.my-minio.svc.cluster.local:9000
   Uptime: 18 minutes
   Version: 2022-01-08T03:11:54Z
   Network: 2/2 OK
   Drives: 2/2 OK

18 MiB Used, 6 Buckets, 5 Objects
4 drives online, 0 drives offline

```

So, I've got it half-working if I update the tenant before upgrading the operator.  If I update the operator first before the tenant, I get the `Incorrect Usage: flag provided but not defined: -console-address` no matter what. The only workaround seem to be patching the statefulset directly with the new image, and I'm not clear on whether messing with the statefulset image directly is safe, or if the operator needs to take special steps to perform the upgrade

**Comment by dfsdevops** [comment]
So I guess my biggest remaining question is, is it normal to see this and then nothing else after it?

```
Hit conflict issue, getting latest version of tenant
```

or is that an issue? when I restart the operator I get that every time

**Comment by Alevsk** [comment]
As @harshavardhana mentioned, you need to upgrade the MinIO image first then operator.
