### ISSUE TITLE
After decommissioning can't remove first pool 

### ISSUE THREAD

**Issue by mihiragrawal** [minio/operator#1043]
We are using minio-operator version **v4.4.10.** We have two pools created **minio-ss-0 & minio-ss-1**.  We want to remove the first pool(minio-ss-0) which is decommissioned successfully.  According to [https://blog.min.io/decommissioning/](blog), we have modified tenant manifest to remove the first pool block(minio-ss-0), but it seems like due to pool is list, so it doesn't understand we want to remove the first pool(minio-ss-0) not second pool(minio-ss-1). Due to this, pods from the first statefulset fails as it's decommissioned. 
## Expected Behavior

There should be a way to remove the first pool from the tenant.

## Current Behavior

Operator don't understand removing first pool from tenant manifest after decommissioning, cause pool it self is a list. So tenant is not healthy due to pods are failing.

## Possible Solution

Possibly with some flags in Tenant pool, and we can use that to remove specific pools.

## Steps to Reproduce (for bugs)

1. Create a tenant with two pools.
2. Decommission the first pool.
3. Modify tenant manifest to remove the block of the first pool from the list after decommissioning success.
4. Pods of first pool will start failing and tenant itself will not healthy.

## Context

Initially, we have provisioned a tenant with a single pool that uses a large amount of volume. After that, we have added a second pool with a small amount of volume. We want to use the decommissioning feature to use the second pool only in a tenant which helps us to save on cost from removing unwanted volume from the first pool. 

## Regression
 No

## Your Environment

* Version used (`minio-operator`): v4.4.10
* Environment name and version (e.g. kubernetes v1.17.2): v1.21.5
* Server type and version: minio:RELEASE.2022-03-03T21-21-16Z
* Operating System and version (`uname -a`): Linux azure-ubuntu-zone-1-5768c796f4-clkmn 5.8.0-1041-azure #44~20.04.1-Ubuntu SMP Fri Aug 20 20:41:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:

**Comment by harshavardhana** [comment]
Operator does not support decommissioning yet @mihiragrawal

**Comment by harshavardhana** [comment]
The first work to support decommission is under way here #1044

**Comment by nirav-chotai** [comment]
Pool decommissioning is working fine in MinIO Operator `v4.4.14` and MinIO `RELEASE.2022-04-26T01-20-24Z`

**Comment by harshavardhana** [comment]
This has been fixed and released.
