### ISSUE TITLE
OCP 4.9.5 install - operator TLS secret not found: secrets "operator-tls" not found

### ISSUE THREAD

**Issue by zuri-lawrence** [minio/operator#1048]
Installing on a Fyre cluster with OCP 4.9.5 with the following `kubectl` and `kubectl minio` versions:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.0-rc.0+a44d0f0", GitCommit:"a44d0f017717d7bdd02c6fb64957e1380b821496", GitTreeState:"clean", BuildDate:"2021-10-22T03:07:44Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl minio version
v4.4.10
```

Installed using the installation steps [here](https://github.com/minio/operator#deploy-the-minio-operator-and-create-a-tenant). Still getting the error that the `operator-tls` secret cannot be found even after upgrading to the latest k8s and kubectl minio versions suggested in this [issue](https://github.com/minio/operator/issues/1033). 
```
I0308 23:13:48.043455       1 operator.go:106] Waiting for the operator certificates to be issued the server could not find the requested resource
I0308 23:13:58.050046       1 operator.go:104] operator TLS secret not found: secrets "operator-tls" not found
E0308 23:13:58.053055       1 operator.go:231] Unexpected error during the creation of the csr/operator-minio-operator-csr: the server could not find the requested resource
```

This seems to be a recurring issue (#1033, #983) and upgrading the k8s and kubectl minio versions is not a viable solution.

**Comment by kanagarajkm** [comment]
@zuri-lawrence can get the output of `kubectl api-resources | grep csr`?

**Comment by Alevsk** [comment]
@zuri-lawrence @kanagarajkm this seems to be a bug in the function that checks for the kubernetes version and select which csr/cert api to use: `v1` or `v1beta1`

The comparison is:

```
useCertificatesV1API = versionCompare(kubeAPIServerVersion.String(), "v1.22.0") >= 0
```

The user reported the kubernetes version is `v1.22.0-rc.0+a44d0f0`:

```
	useCertificatesV1API = versionCompare("v1.22.0-rc.0+a44d0f0", "v1.22.0") >= 0
	```

Will be false so Operator will fallback to `v1beta1` which is deprecated in `v1.22.0`

**Comment by Alevsk** [comment]
A fix for this will be available on the next operator release https://github.com/minio/operator/pull/1054
