### ISSUE TITLE
helm chart creates operator, but then it is stuck.

### ISSUE THREAD

**Issue by cragia** [minio/operator#1055]
## Current Behavior

When I create the operator via the HELM chart, it seems to create it, and then I can even connect to the console... but if I look into the logs of the "leader" operator, I can see it cannot create the "operator-tls" secret, giving me these information:
```
I0320 22:46:12.506438       1 csr.go:189] Start polling for certificate of csr/operator-minio-csr, every 5s, timeout after 20m0s
I0320 22:46:17.510964       1 csr.go:215] Certificate successfully fetched, creating secret with Private key and Certificate
E0320 22:46:17.514296       1 operator.go:248] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
I0320 22:46:17.514383       1 operator.go:106] Waiting for the operator certificates to be issued secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```
and in fact, if I try to create a Tenant afterwards, I simply can't... it seems the creation doesn't even start.

## Possible Solution

I'm not sure, but probably it's missing a RBAC role, but I'm not sure which.

## Steps to Reproduce (for bugs)

1. use the helm chart for the operator in a OKD or OpenShift environment.

## Your Environment

* Version used (`minio-operator`): just cloned the master branch, and used the helm chart here.
* Environment name and version (e.g. kubernetes v1.17.2): OKD 4.9.0-0, Kubernetes v1.22.1-1839

**Comment by harshavardhana** [comment]
> E0320 22:46:17.514296       1 operator.go:248] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
> I0320 22:46:17.514383       1 operator.go:106] Waiting for the operator certificates to be issued secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>

We are not getting any certs from your k8s deployment.

**Comment by cragia** [comment]
mmm I'm not sure if I'm looking in the right place... but if I look for the CSR I can see this:
```
NAME                 AGE   SIGNERNAME                      REQUESTOR                                    REQUESTEDDURATION   CONDITION
operator-minio-csr   3s    kubernetes.io/kubelet-serving   system:serviceaccount:minio:minio-operator   <none>              Approved,Issued
```

or you're referring to something else?

**Comment by harshavardhana** [comment]
> mmm I'm not sure if I'm looking in the right place... but if I look for the CSR I can see this:
> ```
> NAME                 AGE   SIGNERNAME                      REQUESTOR                                    REQUESTEDDURATION   CONDITION
> operator-minio-csr   3s    kubernetes.io/kubelet-serving   system:serviceaccount:minio:minio-operator   <none>              Approved,Issued
> ```
> 
> or you're referring to something else?

See the actual errors in the operator logs, looks like you lack permissions to run operator on your cluster.

**Comment by cragia** [comment]
> > mmm I'm not sure if I'm looking in the right place... but if I look for the CSR I can see this:
> > ```
> > NAME                 AGE   SIGNERNAME                      REQUESTOR                                    REQUESTEDDURATION   CONDITION
> > operator-minio-csr   3s    kubernetes.io/kubelet-serving   system:serviceaccount:minio:minio-operator   <none>              Approved,Issued
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or you're referring to something else?
> 
> See the actual errors in the operator logs, looks like you lack permissions to run operator on your cluster.

yes, I think that's the problem... but I don't know what I'm missing... right now I can see the role "minio-operator-role"... I guess it's missing some permissions on some resource, but I don't understand which... can you help me with that?
how can I retrieve a compact list of the capabilities of that role?

**Comment by srisvk055** [comment]
@cragia by any chance have you got a clue to fix this issue.

**Comment by mKamleiter** [comment]
Hey,

just stumbled over this issue earlier today and wanted to give you an update on how I solved the issue.
Basically the error says it cant set the owner reference to the secret on the parent object.
The parent object is the minio deployment and an owner reference is a finalizer.
To allow a service account to set finalizers on an object, we need to add that to the cluster role.

I modified that part of the Clusterrole:
```
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - get
  - create
  - list
  - patch
  - watch
  - update
  - delete
```

to also represent "deployments/finalizers" like this:
```
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  - deployments/finalizers
  verbs:
  - get
  - create
  - list
  - patch
  - watch
  - update
  - delete
```

That fixed the problem for me.
I also found a redhat bugzilla issue, describing that "permission is _not_ granted to finalizers by default, we need to add them explicitly to the role"
