### ISSUE TITLE
How to deal with expired tenant tls certificates?

### ISSUE THREAD

**Issue by badihi** [minio/operator#1063]
After a year of deploying a tenant using minio operator, the tls certificate that is used for endpoints of nodes became expired and they lost connection to each other.
Removing secrets and trying restarting the operator was not helpful. It said that the tenant is synced, but in fact there was no tls certificate in there to use. Also there were no csr in the cluster related to that.
After a lot of struggling hoping that the operator somehow fixes the situation, I had to create a csr manually and create a secret from the resulting certificate to be able to bring the cluster back up.
This problem implied a down time about an hour.

## Expected Behavior
There must be some mechanism to manage tenant tls certificates with ability to renew automatically.

## Current Behavior
Management and renewal of tls certificates must be done manually.

## Possible Solution
(Mentioned above)

## Steps to Reproduce (for bugs)
1. Deploy a four node tenant
2. Wait for expiration of tls certificate.
3. The cluster will be unavailable.

## Context
The csr related to tenants and its certificates must be monitored during sync operation to ensure there will be no expired certs or any other problem. At least a missing certificate must be regenerated and replaced during sync.

## Your Environment
K8s: v1.21.5
Minio Operator: v4.0.2

**Comment by shellymangla** [comment]
I am also facing the same issue. not finding any alternate to renew the cert. It should be auto renewal

**Comment by Alevsk** [comment]
@badihi Update to the latest version of operator, if you delete the operator-tls secret then operator will automatically try to generate a new one, then you have to manually copy the public.crt portion of the tls secret to the operator-tls secret of each individual tenant

**Comment by badihi** [comment]
@Alevsk I'm talking about the certificate that the nodes of cluster use for their https endpoint. The one that is called `foo-tls` for the tenant called `foo` and is present in its related namespace.
Yes, you are right about the `operator-tls`, as it is being generated automatically if missing, and works pretty well. But I cannot get its relevance to my problem.

**Comment by Alevsk** [comment]
Everything works the same way, upgrade to latest operator, then delete foo-tls and operator will regenerate the secret automatically.

**Comment by ianwijaya** [comment]
> @badihi Update to the latest version of operator, if you delete the operator-tls secret then operator will automatically try to generate a new one, then you have to manually copy the public.crt portion of the tls secret to the operator-tls secret of each individual tenant

Thanks @Alevsk , works for me

**Comment by dberardo-com** [comment]
still facing this issue ... the certificate should be automaticallz tenant renewed bz the operator according to the doc, but this is not happening ...

**Comment by ramondeklein** [comment]
@dberardo-com Which operator version are you using?
