### ISSUE TITLE
MinIO operator produce grow of the goroutines

### ISSUE THREAD

**Issue by OxCom** [minio/operator#1069]
With has few versions the monitoring detects grow of goroutines and as a result FD during a time.
Restart of minio operator pods return MinIO state to normal. Please see ticket in [minio/minio](https://github.com/minio/minio/issues/14529)

## Current Behavior
during 24h number of goroutines grows for ~1k

## Possible Solution
as work around restart minio-operator (bad solution)

## Steps to Reproduce (for bugs)
1. Setup cluster with minio-operator v4.4.12
2. Wait 24h
3. Check open files

## Environment
* Version used (`minio-operator`): v4.4.12
* Environment name and version (e.g. kubernetes v1.17.2):  v1.23.5
* Server type and version: Ubuntu 20.04.3 LTS
* Operating System and version (`uname -a`): ```Linux k8s-head 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
* Link to your deployment file: https://github.com/minio/minio/issues/14529#issuecomment-1079898165

**Comment by harshavardhana** [comment]
@OxCom we still need profiles - it won't be possible to debug this cleanly otherwise

**Comment by OxCom** [comment]
@harshavardhana they were attached to the this comment: https://github.com/minio/minio/issues/14529#issuecomment-1079898165
do you need any other profiles?

**Comment by harshavardhana** [comment]
> @harshavardhana they were attached to the this comment: https://github.com/minio/minio/issues/14529#issuecomment-1079898165
> do you need any other profiles?

Yeah they do not have anything specific, it only looks like keep-alive connections nothing more.

That's what I meant as there won't be any connection leak.

**Comment by OxCom** [comment]
@harshavardhana what other profiles would like like to get? any logs? Looks like minio-operator has logic in background to monitor something.

**Comment by harshavardhana** [comment]
> @harshavardhana what other profiles would like like to get? any logs? Looks like minio-operator has logic in background to monitor something.

Yes it sends calls like `mc admin info` on a regular basis like health check

**Comment by OxCom** [comment]
@harshavardhana looks like connection has not been reused by minio-operator and creates new one. I do not see that it's correct behavior of the applications. Also you pointed we should not hold connections if we do not use them.

is there anyway to force and do not use persistent connection and and recreate new?

**Comment by harshavardhana** [comment]
> @harshavardhana looks like connection has not been reused by minio-operator and creates new one. I do not see that it's correct behavior of the applications. Also you pointed we should not hold connections if we do not use them.
> 
> is there anyway to force and do not use persistent connection and and recreate new?
> 

That might be an issue if the operator did not use any connection pooling.

Can you capture a new profile and attach it here? How far do the goroutines grow?

**Comment by OxCom** [comment]
@harshavardhana atm I turned off the cluster, but I have info that close to every 1-3 seconds we have new connection. max number that I saw was 5k, next time servers we restarted (not by us, I mean they somehow restarted by their own - also not logs for this were in output)

**Comment by harshavardhana** [comment]
> @harshavardhana atm I turned off the cluster, but I have info that close to every 1-3 seconds we have new connection. max number that I saw was 5k, next time servers we restarted (not by us, I mean they somehow restarted by their own - also not logs for this were in output)

Okay that is good

**Comment by OxCom** [comment]
@harshavardhana based on additional investigation of the impact our qa team found that after sometime we have degraded performance with minio (we have internal setup without tuned up of the kernel to extend max connections in system), after drop of the open connections performance went back and we do not expect any issues.

should I expect that investigation will be done on this issue?

**Comment by harshavardhana** [comment]
> @harshavardhana based on additional investigation of the impact our qa team found that after sometime we have degraded performance with minio (we have internal setup without tuned up of the kernel to extend max connections in system), after drop of the open connections performance went back and we do not expect any issues.
> 
> should I expect that investigation will be done on this issue?

I would still need profiles when that happens.

**Comment by OxCom** [comment]
@harshavardhana how can I get this profiles for you?

**Comment by OxCom** [comment]
update with the latest operator does not help :(

**Comment by artazar** [comment]
I am facing exactly the same issue with minio-operator. Established tenant health-check connections keep growing until they start to fail with errors like:

```
Immediate connect fail for 10.233.52.36: Cannot assign requested address
```

because of all sockets used up

```
sh-4.4# ss -ant | wc -l                  
56467
```

This is abnormal and should be fixed.
Please check and let us know what extra info should be provided and how to obtain it. Thanks!

**Comment by dvaldivia** [comment]
@artazar how did you got `ss` into the container? and I see it's also running as root, the latest versions don't run as root, are you using the latest version?

**Comment by artazar** [comment]
@dvaldivia it's not running as root, I just exec'ed from the node via runc and added iproute package there, smth like this:

```
runc --root /run/containerd/runc/k8s.io/ exec -t -u 0 d9a657af9c83d54d5827a3c36e991117a380c4ba9cb29f30b4c50b58cf4534b3 sh

rpm --nosignature -ihv http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/libmnl-1.0.4-6.el8.x86_64.rpm 
rpm --nosignature -ihv http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/iproute-5.9.0-4.el8.x86_64.rpm
```

**Comment by OxCom** [comment]
Please confirm or decline my thoughts (I'm not familiar with Go yet):

This is how ```Transport``` has been configured:
https://github.com/minio/operator/blob/aba849c8e179fdd75a1300fb449acc0cc485836f/pkg/controller/cluster/monitoring.go#L294

First search results by reusing HTTP connections in GO leads to many articles and stackoverflow where everybody mention that we have to release connection before reuse:
https://golang.cafe/blog/how-to-reuse-http-connections-in-go.html
https://stackoverflow.com/questions/17948827/reusing-http-connections-in-go

Now the health check request. There is attempt to reuse existing connections in this function leads to leak of connections:
https://github.com/minio/operator/blob/aba849c8e179fdd75a1300fb449acc0cc485836f/pkg/controller/cluster/monitoring.go#L333

Based on this code we create a client, then do a call and process results, however we do not release connection. So this think tha before return results we have to close it something like this: 

```go
info := &HealthResult{StatusCode: resp.StatusCode, HealingDrives: driveskHealing, WriteQuorumDrives: minDriveWrites}, nil

resp.Body.Close()

return info;
```

Based on articles in this case connection should be released and it should be reused in future.

**Comment by OxCom** [comment]
I would like to confirm that fix working well now. Thanks @harshavardhana
