### ISSUE TITLE
Minio Operator console  Error "Please enter a valid namespace"

### ISSUE THREAD

**Issue by mesobreira** [minio/operator#1070]
When we try to create a tenant through the operator console, it returns an error message "Please enter a valid namespace".
Even when we create it through the operator console. 
We restarted the operator console, but that didn't solve the problem.

Kubernetes version: 1.23.5
Minio Plugin Version : v4.4.4
Image:    minio/console:v0.14.1
Operating system: Centos 8 Stream (4.18.0-373.el8.x86_64)
![Minio-Error-1](https://user-images.githubusercontent.com/78885532/160289355-3cbbe877-297a-4b13-9ab2-a1e03820f400.png)
![Minio-Error-2](https://user-images.githubusercontent.com/78885532/160289358-82a028fb-4ebc-46d1-8105-4d87433fe474.png)
![Minio-Error-3](https://user-images.githubusercontent.com/78885532/160289361-51346433-52a0-4b75-aacf-c3f8436f4210.png)

**Comment by saeid93** [comment]
I'm having the same problem, did you find any solution to it?

**Comment by jrick166fiap** [comment]
Hi guys, i have same problem today, my solution is create the storage class default.
My cluster k8s is on premises 

k get sc  ----  check in cluster exists a storage-class

k create -f ./storage-class/storage-disk-local.yaml
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
After this adjustment the namespace was accepted, I imagine it is some validation of the minio app to not accept a namespace if there is no storage class default.
![image](https://user-images.githubusercontent.com/31735230/167029019-57fb84f1-148a-46c7-825d-4b8bd32f6079.png)

for me this works. I hope it helps you.

**Comment by allanrogerr** [comment]
@mesobreira Are you still facing this issue?

**Comment by allanrogerr** [comment]
Please try again with a later version on the minio operator e.g. >= v5.0.11
