### ISSUE TITLE
`certConfig` unable to be set

### ISSUE THREAD

**Issue by tobiasmcnulty** [minio/operator#1073]
I've tried setting `certConfig` in various ways, both through the operator console and directly in the `Tenant` YAML, and I cannot get any of the keys in this value to "stick." 

## Expected Behavior

Based on the [automatic TLS](https://github.com/minio/operator/blob/master/docs/tls.md#automatic-tls) documentation, I'm assigning a value like so:

```yaml
spec:
  requestAutoCert: true
  certConfig:
    Organization: my-org
    DNSNames: ["my-name.org"]
```

I expect this config to persist and the changes to appear in the cert for the tenant.

## Current Behavior

But when I click "Edit Tenant" in the operator console, all that appears is `certConfig: {}` and I confirmed the org name did not change in the cert. I've tried with only `Organization` and only `DNSNames` and neither is saved on its own, either. I've tried lowercasing the keys (as elsewhere in the definition) and receive the same result.

## Possible Solution
TBD

## Steps to Reproduce (for bugs)
1. Click "Create Tenant" in the operator console and create a new tenant with all the defaults.
2. Wait for the tenant to finish creating
3. Navigate to the tenant and click "Edit Tenant"
4. Add the following YAML to the `spec:`: `certConfig: {Organization: my-org}`
5. Click Save
6. Click Edit Tenant again and observe that `certConfig` is empty (`certConfig: {}`)

## Your Environment

* Version used (`minio-operator`): latest available helm chart (`v4.4.10`)
* Environment name and version (e.g. kubernetes v1.17.2): Microk8s 1.23
* Server type and version: Ubuntu 20.04
* Operating System and version (`uname -a`): `Linux bnode00 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your deployment file: n/a

**Comment by tobiasmcnulty** [comment]
Same result, unfortunately. The CSR shows only the default org name and DNS names:

```
$ kubectl describe csr test-minio-test-csr
Name:               test-minio-test-csr
Labels:             v1.min.io/tenant=test
Annotations:        <none>
CreationTimestamp:  Tue, 29 Mar 2022 16:56:35 +0000
Requesting User:    system:serviceaccount:minio-operator:minio-operator
Signer:             kubernetes.io/kubelet-serving
Status:             Approved,Issued
Subject:
  Common Name:    system:node:*.test-hl.minio-test.svc.cluster.local
  Serial Number:  
  Organization:   system:nodes
Subject Alternative Names:
         DNS Names:  test-pool-0-{0...3}.test-hl.minio-test.svc.cluster.local
                     minio.minio-test.svc.cluster.local
                     minio.minio-test
                     minio.minio-test.svc
                     *.test-hl.minio-test.svc.cluster.local
                     *.minio-test.svc.cluster.local
Events:  <none>
```

This was with the following config:

```yaml
  certConfig:
    Organization: my-org
    DNSNames: ["1.2.3.4"]
```

**Comment by dvaldivia** [comment]
seems like `Organization` is an array, can you try that? I don't see a reason why the `DNSNames` is not being included though

**Comment by tobiasmcnulty** [comment]
No luck either unfortunately. I tried deleting the CSR and `-tls` Secret again, setting `requestAutoCert: false`, and then applying the following config:

```yaml
spec:
  certConfig: {Organization: [my-org]}
  requestAutoCert: true
```

I get:
```
$ kubectl describe csr|grep Org
  Organization:   system:nodes
```

**Comment by tobiasmcnulty** [comment]
Whoops, it looks like the key is `OrganizationName` (not `Organization`), but same result with that too unfortunately. I'm not seeing what might be wrong in the code either...

**Comment by dvaldivia** [comment]
me neither, I see the code appending whatever you enter as long as it's not identical to the list of hosts we run on, thoughts @Alevsk ?

**Comment by tobiasmcnulty** [comment]
FWIW, I tried setting `CommonName: test` and that too is getting wiped. It's possible the issue has to do with that whole block rather than the individual keys.

**Comment by dvaldivia** [comment]
if you set it, can you see what you set when you ask for it back via tenant edit? or cli?

**Comment by tobiasmcnulty** [comment]
Okay, all three keys confirmed working, as returned by `get -o yaml`:

```yaml
  spec:
    certConfig:
      commonName: test
      dnsNames:
      - example.com
      organizationName:
      - my-org
```

Thanks for the help! I opened [a PR](https://github.com/minio/operator/pull/1075) with the proposed doc changes.

**Comment by dvaldivia** [comment]
great that you found a solution, and thanks for your PR!
