### ISSUE TITLE
Automatically add service IP to certificate SAN list when `requestAutoCert` is enabled

### ISSUE THREAD

**Issue by tobiasmcnulty** [minio/operator#1074]
**Describe the solution you'd like**
With the following config:

```
  requestAutoCert: true
  exposeServices:
    minio: true
```

It would be nice if the auto-generated cert included the IP of the service in the certificate's SAN list.

**Describe alternatives you've considered**
I've tried adding the IP manually (see #1073) but am unable to add to the `DNSNames` for the cert. I'm unclear if that will even work, but if it does, adding the IP by default would make for a better overall experience and I don't see any downsides to doing so...

**Comment by dvaldivia** [comment]
this is an interesting one, the certificates ge generate for are meant for internode communication between MinIO pods, they use a headless service to find each other, so I don't think we can add the IPs there, we do leverage that same cert to include the `minio` service, but perhaps if we want to add the ClusterIP of the `minio` service to the SAN list we would need two certificates, one for internode and one for internal k8s traffic through the `minio` service, throughts @Alevsk @aead ?

**Comment by tobiasmcnulty** [comment]
Ah, I think you're right. Assuming it's fine to leave `requestAutoCert: true` with a value set for `externalCertSecret` (which appears to be the case from the code), it seems better to issue a separate cert with the IP and whatever other customization is needed, rather than trying to solve everyone's possible use case with this one setting. 😁 

Thanks again for the lightning fast responses today!
