### ISSUE TITLE
Create MinIO Operator Helm Chart

### ISSUE THREAD

**Issue by dvaldivia** [minio/operator#108]
We need to add a helm chart to install MinIO Operator, just so people using `helm` can quickly install us.

**Comment by damianoneill** [comment]
related request, looking at https://operatorhub.io/operator/minio-operator this is referring to v1.0.3 is there any plans to update this so that olm can be used to do the install?

**Comment by dvaldivia** [comment]
@damianoneill thanks for pointing that out, we updated the `olm` files on the repo, but seems that `operatorhub` didn't pick it up automatically, let me see what we need to do to have it update.

**Comment by siredmar** [comment]
@nitisht @harshavardhana any chance that there is a helm chart for the current version?
As mentioned in #154 operatorhub won't be maintained anymore. Can you point me in the right direction how to install this in a kubernetes cluster? Thanks!

**Comment by harshavardhana** [comment]
> @nitisht @harshavardhana any chance that there is a helm chart for the current version?
> As mentioned in #154 operatorhub won't be maintained anymore. Can you point me in the right direction how to install this in a kubernetes cluster? Thanks!

No @siredmar only one way to do one thing, use our kubectl plugin and we are working with RedHat to update operatorhub.

**Comment by siredmar** [comment]
Thanks!

**Comment by clayrisser** [comment]
@harshavardhana any updates? Seems operatorhub minio is very out of date.

**Comment by harshavardhana** [comment]
We are going to add a helm chart for the operator

**Comment by nitisht** [comment]
Fixed by #505
