### ISSUE TITLE
Minio Operator using Helm : can't login

### ISSUE THREAD

**Issue by nlamirault** [minio/operator#1080]
## Expected Behavior

Install Minio using the Helm chart Minio Operator and Minio Tenant

Version: `4.4.13`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Try to login into the Minio Console with this JWT : 

```
$ kubectl -n storage get secret $(kubectl -n storage get serviceaccount console-sa -o jsonpath="{.secrets[0].name}") -o jsonpath="{.data.token}" | base64 --decode
```

![2022-04-01_07-59](https://user-images.githubusercontent.com/29233/161204019-5a6df09e-3872-42ca-afa6-f77cca4027f7.png)

The logs : 
```
❯ kubectl -n storage logs -f console-85c9fbccfb-x54l4                                                                                                                                                                                        
│I: 2022/04/01 05:44:29 Serving operator at http://[::]:9090                                                                                                                                                                                 
│E: 2022/04/01 05:51:45 original error -> (login.go:53: invalid Login)                                                                                                                                                                        
│E: 2022/04/01 05:54:33 original error -> (login.go:53: invalid Login)                                                                                                                                                                      
│E: 2022/04/01 05:54:40 original error -> (login.go:53: invalid Login)                                                                                                                                                                       
│E: 2022/04/01 05:57:57 original error -> (login.go:53: invalid Login)  
```
## Your Environment

* Version used (`minio-operator`): 

```
$ kubectl minio version
v4.4.13 
```

* Environment name and version (e.g. kubernetes v1.17.2): v1.22.8-rc2+k3s1
* Server type and version: RPI4
* Operating System and version (`uname -a`): Raspberry PI OS
* Link to your deployment file: https://github.com/portefaix/portefaix/tree/feat/homelab-storage/gitops/argocd/charts/storage/minio

**Comment by dvaldivia** [comment]
are you using `k3s` @nlamirault ?

**Comment by dvaldivia** [comment]
I just tested on `k8s 1.23` with the latest helm chart `v4.4.13` and I couldn't reproduce this problem, perhaps the JWT token needs to be retrieved again? can you try that @nlamirault

**Comment by dvaldivia** [comment]
I was able to login properly from a k3s setup, verify the JWT is correct

**Comment by nlamirault** [comment]
ok it works. Sorry for noise.

**Comment by dvaldivia** [comment]
@nlamirault no problem, glad you figured it out
