### ISSUE TITLE
How to set up "minioenv" (MINIO_ARGS)

### ISSUE THREAD

**Issue by pjy324** [minio/operator#1087]
We are trying to create multiple tenants.
Each tenant should have no problem calling share file, pre-signed url, etc. from outside.

However, if you create it with the operator, the "minio env" setting is automatically This makes it impossible to call shareurl from outside.

If you check the statefulset yaml file, it is as follows.

        env:
        - name: MINIO_UPDATE
          value: "on"
        - name: MINIO_UPDATE_MINISIGN_PUBKEY
          value: RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
        - name: MINIO_ARGS
          valueFrom:
            secretKeyRef:
              key: MINIO_ARGS
              name: operator-webhook-secret
        - name: MINIO_ENDPOINTS
          value: http://jin-tenant-test-pool-0-{0...3}.jin-tenant-test-hl.jin-tenant-test.svc.cluster.local/export{0...3}
        - name: MINIO_OPERATOR_VERSION
          value: v4.4.13
        - name: MINIO_PROMETHEUS_JOB_ID
          value: minio-job
        - name: MINIO_CONFIG_ENV_FILE
          value: /tmp/minio-config/config.env
        - name: MINIO_SERVER_URL
          value: http://minio.jin-tenant-test.svc.cluster.local:80

If you select Share File from the web, the following url appears, and this url cannot be accessed from the outside.

http://minio.jin-tenant-test.svc.cluster.local/test/....................

We would like to know how to specify MINIO_SERVER_URL as LoadBalancer URL when creating each tenant.
Alternatively, I would like to know how to change MINIO_SERVER_URL after the tenant is created.

NAME                              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/jin-tenant-test-console   LoadBalancer   10.233.16.77   <pending>     9090:30508/TCP   50m
service/jin-tenant-test-hl        ClusterIP      None           <none>        9000/TCP         50m
service/minio                     LoadBalancer   10.233.62.53   <pending>     80:30680/TCP     50m

operator version : v4.4.13

**Comment by harshavardhana** [comment]
you cannot setup your own MINIO_ARGS sorry that needs to come from operator  

> - name: MINIO_SERVER_URL
>       value: http://minio.jin-tenant-test.svc.cluster.local:80

you need to set your own external ingress URL here @pjy324

**Comment by pjy324** [comment]
The http://minio.jin-tenant-test.svc.cluster.local:80 URL is the internal dns that were accessed externally.
How can shareFile, presigned url be used outside the K8s cluster?

**Comment by pjy324** [comment]
I hope the shear file URL exposed to the user is "http://LoadBalancer IP:Port".

**Comment by dvaldivia** [comment]
there's a `MINIO_SERVER_URL` environment variable you can place in `.spec.env` to reference your own public URL so share URLs look like that @pjy324

**Comment by dvaldivia** [comment]
use the public URL in your deployment @pjy324

**Comment by pjy324** [comment]
@dvaldivia 
Can you tell me how to set up .spec.env when creating tanent through operator?
I want to know how to set it up when I generate it on the web or the example information when I generate it on the cli.

**Comment by dvaldivia** [comment]
@pjy324 if you are using the UI, after creating the tenant, go into the tenant view and then hit `edit tenant` that will show you the YAML, there's no way right now to set the domain during creation, but that's coming

**Comment by pjy324** [comment]
@dvaldivia 
Both statefulset and pod were modified to kubectedit, but they were reset again


NAME                           READY   STATUS    RESTARTS   AGE
pod/jin-tenant-test-pool-0-0   1/1     Running   0          3h11m
pod/jin-tenant-test-pool-0-1   1/1     Running   0          3h11m
pod/jin-tenant-test-pool-0-2   1/1     Running   0          3h11m
pod/jin-tenant-test-pool-0-3   1/1     Running   0          3h3m

NAME                              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/jin-tenant-test-console   LoadBalancer   10.233.16.77   <pending>     9090:30508/TCP   3h11m
service/jin-tenant-test-hl        ClusterIP      None           <none>        9000/TCP         3h11m
service/minio                     LoadBalancer   10.233.62.53   <pending>     80:30680/TCP     3h11m

NAME                                      READY   AGE
statefulset.apps/jin-tenant-test-pool-0   4/4     3h11m
