### ISSUE TITLE
Prometheus Pod is in the Pending state.

### ISSUE THREAD

**Issue by pjy324** [minio/operator#1103]
## Expected Behavior
1. Tenant was created with Operator
2. Later, I enabled monitoring settings through the Web UI
3. Prometheus must be implemented

## Current Behavior
Prometheus Pod is in the Pending state.
PVC is pending and there is no PV.
Do I have to create the pv manually? Is there an example?

[pvc evnet log]
Events:
  Type    Reason         Age                    From                         Message
  ----    ------         ----                   ----                         -------
  Normal  FailedBinding  2m6s (x23125 over 4d)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

## Your Environment

* Version used (`minio-operator`): v4.4.13
* Environment name and version (e.g. kubernetes v1.17.2): v1.22
* Server type and version: 
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by kanagarajkm** [comment]
Do you have a default storage class in your kubernetes environment? 

If you want to set a specific storage class for the prometheus PVC, you can do that as well.

**Comment by pjy324** [comment]
**The default storage class is not set.
So I just changed to direct-csi-min-io class.
It is still in the same state.**

**There is no problem if Prometheus is enabled from the beginning when creating Tenant.
It seems that pv is not properly generated when Tenant is created and later enabled. If I enable it later, are there any settings that need to be set separately?**


[root@node1 ~]# kubectl get sc
NAME                          PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
direct-csi-min-io   direct-csi-min-io              Delete          WaitForFirstConsumer   false                  18h
directpv-min-io               direct-csi-min-io              Delete          WaitForFirstConsumer   false                  18h
local-jenkins-storage-class   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  6d15h
local-storage                 kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  28d



[root@node1 ~]# kubectl get sc
NAME                          PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
direct-csi-min-io (default)   direct-csi-min-io              Delete          WaitForFirstConsumer   false                  18h
directpv-min-io               direct-csi-min-io              Delete          WaitForFirstConsumer   false                  18h
local-jenkins-storage-class   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  6d15h
local-storage                 kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  28d


**The promiscuous pod is still pending.**


[root@node1 ~]# kubectl get pod/dl-dlm-minio-tenant-prometheus-0 -n dl-dlm-minio-tenant
NAME                               READY   STATUS    RESTARTS   AGE
dl-dlm-minio-tenant-prometheus-0   0/2     Pending   0          12m


Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  13m    default-scheduler  0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  13m    default-scheduler  0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  9m34s  default-scheduler  0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  7m48s  default-scheduler  0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  5m39s  default-scheduler  0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  4m1s   default-scheduler  0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  3m11s  default-scheduler  0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  18s    default-scheduler  0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.



**When I see the error, it seems that the pv is not dynamically generated.**

[root@node1 ~]# kubectl describe pvc dl-dlm-minio-tenant-prometheus-dl-dlm-minio-tenant-prometheus-0 -n dl-dlm-minio-tenant
Name:          dl-dlm-minio-tenant-prometheus-dl-dlm-minio-tenant-prometheus-0
Namespace:     dl-dlm-minio-tenant
StorageClass:
Status:        Pending
Volume:
Labels:        v1.min.io/prometheus=dl-dlm-minio-tenant-prometheus
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       dl-dlm-minio-tenant-prometheus-0
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  60m (x9 over 62m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  59m (x2 over 59m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  57m                   persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  53m (x10 over 56m)    persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  51m (x8 over 52m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  41m (x5 over 41m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  36m (x3 over 36m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  33m (x4 over 34m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  32m                   persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  31m (x4 over 31m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  28m (x2 over 28m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  23m                   persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  21m (x2 over 21m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  15m (x9 over 16m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  11m (x2 over 11m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  10m (x4 over 10m)     persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  6m5s                  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  5m12s                 persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  3m5s (x4 over 3m50s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
  Normal  FailedBinding  9s (x10 over 2m24s)   persistentvolume-controller  no persistent volumes available for this claim and no storage class is set


[root@node1 ~]# kubectl get pvc dl-dlm-minio-tenant-prometheus-dl-dlm-minio-tenant-prometheus-0 -n dl-dlm-minio-tenant -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2022-04-21T23:04:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    v1.min.io/prometheus: dl-dlm-minio-tenant-prometheus
  name: dl-dlm-minio-tenant-prometheus-dl-dlm-minio-tenant-prometheus-0
  namespace: dl-dlm-minio-tenant
  ownerReferences:
  - apiVersion: minio.min.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: dl-dlm-minio-tenant
    uid: ae245130-c6d2-40c5-8b98-c7686c0b1e69
  resourceVersion: "9933201"
  uid: 7474f030-f9e8-4456-abbc-da59ff54f95e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
status:
  phase: Pending

**Comment by harshavardhana** [comment]
Error is self evident ..

> Normal FailedBinding 36m (x3 over 36m) persistentvolume-controller no persistent volumes available for this claim and no storage class is set

You do not default storage class set, and there no PVCs available to satisfy your deployment requirements.
