### ISSUE TITLE
deleting namespace when execute the command "kubectl minio delete --namespace=NAMESPACE"

### ISSUE THREAD

**Issue by ahmadgh9** [minio/operator#1112]
## Expected Behavior
Not to delete namespace. because the namespace may contain important components
in my situation deleted many manifests and it was awful

## Current Behavior
deleting namespace

## Possible Solution

absolutely not to delete namespace
## Steps to Reproduce (for bugs)

1. init with another namespace (not the default and use --namespace)
2. try to delete with --namespace
3. and boom! your namespace has been deleted

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by dvaldivia** [comment]
We shouldn't delete the namespace by default, will tweak this
