### ISSUE TITLE
Drives vs Volumes in operator UI / CLI

### ISSUE THREAD

**Issue by kaplanlior** [minio/operator#1116]
## Expected Behavior
Having terms / parameters aligned between operator UI / CLI,
making it easy to use both interfaces interchangeably with ease.

## Current Behavior
When creating a new tenant the UI requires setting both "Number of Servers" and "Drives per Server".
The Resource Allocation window on the right side has "Total Volumes" (servers * drives per server)

The CLI doesn't have drives per server, but has volumes flag which is parallel to "Total Volumes".

```
kubectl minio tenant create -h

'create' command creates a new MinIO tenant

      --volumes int32              total number of volumes in the MinIO tenant
```

When looking on an existing tenant UI summary, metrics and pools tabs has "Total Drives".
In the CLI we have volumes per server, as in the k8s YAML

e.g.
```
# kubectl minio tenant info minio-tenant1

Tenant 'minio-tenant1', Namespace 'minio-tenant-1', Total capacity 1024 GiB

  Current status: Waiting for Log Search Pods to be ready 
  MinIO version: minio/minio:RELEASE.2022-05-08T23-50-31Z 
  MinIO service: minio/ClusterIP (port 443)

  Console service: minio-tenant1-console/ClusterIP (port 9443)

+------+---------+--------------------+---------------------+
| POOL | SERVERS | VOLUMES PER SERVER | CAPACITY PER VOLUME |
+------+---------+--------------------+---------------------+
| 0    | 4       | 12                 | 22906492245         |
+------+---------+--------------------+---------------------+
```

## Problems are:
- Each interface requires different numbers while creating a tenant.
- Different leading terminology for each interface.

## Your Environment

* Version used (`minio-operator`): v4.4.17
* Environment name and version (e.g. kubernetes v1.17.2): v1.22.1
* Operating System and version (`uname -a`): Linux 64bit

**Comment by allanrogerr** [comment]
Discussing with the team
