### ISSUE TITLE
Pod minio1-pool-0-0 with forever status pending

### ISSUE THREAD

**Issue by elissonrusiel** [minio/operator#1119]
The pod pool volumes remain with the pending state forever, even if the PCVs have associated PVs.

## Expected Behavior

After the PCV bound the PV the pool should be able to mount the volumes

## Current Behavior

After installed the directpv to dynamically create volumes I installed minio and after that I create a tenant using the GUI, and the pool pod keep on status pending with the followed error.

`MountVolume.MountDevice failed for volume "pvc-935eb4a5-fb5d-4beb-8513-8b573874a6cd" : rpc error: code = Internal desc = failed stage volume: no such file or directory`

The volumes were created on `/var/lib/direct-csi/mnt/`

## Steps to Reproduce (for bugs)

I'm not sure if the problem is related, but I had the kubelet installed on a non-default path and the only difference from the documentation steps was to change the kubelet path from /var/lib/kubelet to /opt/kubelet

## Your Environment

* Version used (`minio-operator`): v4.4.17
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.20.10
* Operating System and version (`uname -a`): Linux 64bit

**Comment by elissonrusiel** [comment]
Hi @Praveenrajmani any help how to debug the error? Thanks in advance.

**Comment by elissonrusiel** [comment]
I've founded a bind mount error in the logs of the direct-csi container and solved my problem by mounting the microk8s root dir in the directpv daemonset.

**Comment by usersina** [comment]
@elissonrusiel - can you share a code snippet?
