### ISSUE TITLE
Hard-coded namespace in Operator Charts in 4.4.19 Onward

### ISSUE THREAD

**Issue by steve-gray** [minio/operator#1140]
# Issue
There's a hard-coded `namespace: minio-operator` on line 11 of console-ui.yaml. It'll cause anyone with a non-default namespace for installation to have issues/be unable to upgrade.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/14563775/169769872-c7e88bba-72a1-4fb0-834f-57ec63a8408d.png">

# Workaround
Stick to 4.4.19 and below for `minio-operator` chart.

**Comment by dvaldivia** [comment]
this is only for the helm chart right?

**Comment by steve-gray** [comment]
Yeah, anyone who's using fuzzy-versions and not using a namespace of `minio-operator` *and* is not pinned to a specific older release will have breaks (at best, it'll put the resource in the wrong namespace), at worst it'll just not be able to run through to completion. It was spewing out all kinds of crazy in Terraform cloud for me and took a few hours of eyeballing the logs to figure out it was something specific in 4.4.20.

**Comment by steve-gray** [comment]
Just thrown a quick PR for it @dvaldivia / @cniackz but will need a new release cut for the charts to resolve. Can't see any others.
