### ISSUE TITLE
Kes <-> Minio Encryption. Create/set secrets for key and cert

### ISSUE THREAD

**Issue by hornv** [minio/operator#1167]
**Is your feature request related to a problem? Please describe.**
Operator provides options to set up kes as well.
Usually, to cooperate between kes and minio in secret manner, 
we need to create certificate base authentication 
`/kes tool identity new --key=minio.key --cert=minio.crt minio`
and then mount it to minio. Neither minio or kes have this options (this is important when you already have the installed kes container) , and as I saw, didn't create them automatically.

**Describe the solution you'd like**
In case we use them together, Automatically create the key and certificate for access to kes, st it as a secret and mount in minio, set proper values for MINIO_KMS_AUTO_ENCRYPTION,MINIO_KMS_KES_CERT_FILE,MINIO_KMS_KES_KEY_FILE
In case wee want to install minio but have the kes alreay installed, we need options for Minio to set secretRef for Kes key and cert

**Comment by allanrogerr** [comment]
Using the latest operator and kes releases - to date - kes client (minio) cert/key can be created manually or automatically and set as environment variables. 
See https://github.com/minio/operator/blob/master/docs/examples.md#minio-tenant-with-encryption-enabled-using-vault-kms
See also https://github.com/minio/operator/blob/master/docs/examples.md#minio-tenant-with-tls-via-customer-provided-certificates
