### ISSUE TITLE
Documentation: Clarify tenant disk space allocation.

### ISSUE THREAD

**Issue by ScionOfDesign** [minio/operator#1177]
I recently provisioned a Minio cluster using the operator and what should have been a smooth and easy experience was made miserable by the fact that it took forever to debug that directpv was reporting ` ResourceExhausted desc = no drive found for requested topology` when trying to allocate my 256Gi drives as 256Gi volumes. The solution was to allocate 255Gi instead.

**Describe the solution you'd like**
Just a mention that the storage specified is not precise, or a description of the error, or a way to specify exact bytes.

**Comment by allanrogerr** [comment]
Re-reqeusted in team. Tag @balamurugana @Praveenrajmani

**Comment by balamurugana** [comment]
Please try using the latest DirectPV and open a new issue if you see the problem again.
