### ISSUE TITLE
Nil pointer exception if a minio volume spec does not have sources

### ISSUE THREAD

**Issue by inespot** [minio/operator#1178]
Summary: Allow custom "source-less" volumes to be added to minio sts post deployment.

## Current Behavior

minio-operator will throw a nil pointer exception if some of minio stateful set spec template's volumes do not have projected sources defined. 
Where the error is thrown: https://github.com/minio/operator/blob/v4.4.23/pkg/controller/cluster/main-controller.go#L868

## Possible Solution

A check could be added in the loop to verify if the volume considered has the `projected` and `sources` field defined, and if not: continue.

## Steps to Reproduce (for bugs)

1. Add a volume definition to minio sts spec.template.spec.volumes via a patch, eg:
```
volumes:
  - emptyDir: {}
  name: problematic-volume
```
2. Restart minio-operator

## Context

It’s not unexpected nor uncommon in k8s environments for resources to be patched post deployment and/or additional volumes to be added to all pods for security/metadata information.
As an example, HashiCorp's "Injecting Secrets into Kubernetes Pods via Vault Agent Containers" public workflow, described here:

https://learn.hashicorp.com/tutorials/vault/kubernetes-sidecar

leverages the Kubernetes mutating admission webhook to intercept pods that define specific annotations and inject a Vault Agent container to manage these secrets.

## Your Environment

* Version used (`minio-operator`): v4.4.23
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes v1.21.901

**Comment by inespot** [comment]
Hello, did you by any chance have some time to take a look at this? If not, would you be open to a contribution? The PR should be fairly small, and I would be happy to own it if you agree with the change suggested above.

**Comment by harshavardhana** [comment]
> Hello, did you by any chance have some time to take a look at this? If not, would you be open to a contribution? The PR should be fairly small, and I would be happy to own it if you agree with the change suggested above.

Feel free send PR @inespot

**Comment by Alevsk** [comment]
M/erged, thanks for the contribution @inespot
