### ISSUE TITLE
Missing JWT secret on console service account

### ISSUE THREAD

**Issue by passadoreg** [minio/operator#1188]
Hi, I installed the operator in kubernetes using helm. I can reach out the console login screen, but I don't find the JWT secret using the provided command, as a fact the console-sa service account exists but with no secret configured.

Any missing step? Any way to create the missing secret?

Thanks in advance.

**Comment by passadoreg** [comment]
Just to complement my report, these are the steps performed so far:

helm repo remove minio
helm repo add minio https://operator.min.io/
helm install --namespace minio-operator --create-namespace --generate-name minio/minio-operator

No tenant created yet.

**Comment by dvaldivia** [comment]
Are you using `Kubernetes 1.24`?

Beginning  `Kubernetes 1.24`, Service Account Token Secrets are not automatically generated, to generate them manually, users must manually create the secret, for our examples where we lead people to get the JWT from the `console-sa` service account, they additionally need to manually generate the secret via

```shell
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
EOF
```

**Comment by passadoreg** [comment]
Issue solved, thanks!
