### ISSUE TITLE
Certified operator fails to run on OpenShift 4.9

### ISSUE THREAD

**Issue by larsks** [minio/operator#1190]
I installed the MinIO operator from the "Certified Operator" catalog on two OpenShift 4.9 clusters.. In both cases, the operator installs successfully but fails to create a tenant because the `<tenant>-log-search-api` deployment attempts to set a pod `securityContext`, but the operator does not install the necessary RBAC for this to work.

## Expected Behavior

After installing the MinIO operator, I expect to be able to successfully create a tenant when running a command like:

```
oc minio tenant create lars --servers 1 --volumes 1 --capacity 10Gi -n lars-sandbox
```

## Current Behavior

A new `Deployment` is created...

```
$ oc get deploy
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
lars-log-search-api   0/1     0            0           139m
```

...but it fails to start any pods, because:

```
$ oc get deploy lars-log-search-api -o yaml | yq -y .status
[...]
  - lastTransitionTime: '2022-06-30T21:28:55Z'
    lastUpdateTime: '2022-06-30T21:28:55Z'
    message: 'pods "lars-log-search-api-577c97d4bb-" is forbidden: unable to validate
      against any security context constraint: [provider "anyuid": Forbidden: not
      usable by user or serviceaccount, provider "containerized-data-importer": Forbidden:
      not usable by user or serviceaccount, provider restricted: .spec.securityContext.fsGroup:
      Invalid value: []int64{1000}: 1000 is not an allowed group, spec.containers[0].securityContext.runAsUser:
      Invalid value: 1000: must be in the ranges: [1000820000, 1000829999], provider
      "nonroot": Forbidden: not usable by user or serviceaccount, provider "noobaa":
      Forbidden: not usable by user or serviceaccount, provider "noobaa-endpoint":
      Forbidden: not usable by user or serviceaccount, provider "volsync-mover": Forbidden:
      not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden:
      not usable by user or serviceaccount, provider "bridge-marker": Forbidden: not
      usable by user or serviceaccount, provider "machine-api-termination-handler":
      Forbidden: not usable by user or serviceaccount, provider "kubevirt-controller":
      Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden:
      not usable by user or serviceaccount, provider "hostaccess": Forbidden: not
      usable by user or serviceaccount, provider "linux-bridge": Forbidden: not usable
      by user or serviceaccount, provider "nmstate": Forbidden: not usable by user
      or serviceaccount, provider "kubevirt-handler": Forbidden: not usable by user
      or serviceaccount, provider "rook-ceph": Forbidden: not usable by user or serviceaccount,
      provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider
      "privileged": Forbidden: not usable by user or serviceaccount, provider "rook-ceph-csi":
      Forbidden: not usable by user or serviceaccount]'
    reason: FailedCreate
    status: 'True'
    type: ReplicaFailure
[...]
```

This error occurs because the Deployment is trying to set up a `securityContext`:

```
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
```

But the operator has not set up the necessary RBAC for this to work.

## Possible Solution

There are two possible solutions:

1. Set up the necessary RBAC. You would probably need to bind the pods to a serviceAccount in each namespace in order for this to work (and create a RoleBinding dynamically when creating the tenant).
2. Remove the `securityContext`, and design the pod so that it will run with the default random userid that openshift configures when starting unprivileged pods.

I think option (2) is the better choice if you can make it work.

## Steps to Reproduce (for bugs)

(Steps to reproduce are described in the previous section)

## Your Environment

* Version used (`minio-operator`): v4.4.25
* Environment name and version (e.g. kubernetes v1.17.2): OpenShift 4.9.21

**Comment by pjuarezd** [comment]
please upgrade to latest Operator versions available in Redhat Marketplace `log-search-api` is deprecated and latest versions have better handlng on `securityContext` setting on Openshift
