### ISSUE TITLE
Add runtimeClassName support to Tenant CRD

### ISSUE THREAD

**Issue by dnskr** [minio/operator#1194]
**Is your feature request related to a problem? Please describe.**
The feature request related to the problem with files relabeling when MinIO pods run on nodes with enabled SELinux.
The solution described in the [discussion](https://github.com/minio/minio/discussions/14854) and require `runtimeClassName` to be set on MinIO pods.

**Describe the solution you'd like**
Support for `runtimeClassName` needs to be added to Tenant CRD and tenant helm chart.

**Comment by steve-gray** [comment]
As per https://github.com/minio/minio/issues/15217 and the associated discussions, without this work to enable skipping of most of the leg-work of an SELinux relabel, it's essentially impossible to use Minio in any modern managed Kubernetes environment. As most platforms default to an SELinux variant (EKS, OCI/EKS, AKS etc....), it essentially means a restart of Minio with a scaled number of files can take exponential amounts of time, and lead to low availability of the service.

**Comment by dnskr** [comment]
@Alevsk @dvaldivia Hi! Are you planning to work on this issue any time soon? If not, I can try to do it. Unfortunately I'm not familiar with go and operator code base. So I would appreciate your guidance or just one or two similar PRs as the examples.

**Comment by dvaldivia** [comment]
@dnskr it's a sort of an easy issue, I can work on this before the next release `v4.5.0` which is going to be release early next week, or you can give it a try

**Comment by dnskr** [comment]
Great! In this case I would prefer to leave it to you, since I don't feel it's easy for me.

**Comment by dvaldivia** [comment]
@dnskr the PR is up, you can review it to get an idea on how to do this changes, it's sort of straight forward

**Comment by dvaldivia** [comment]
Most of the auto-generate code can be generated with our `Makefile` targets
