### ISSUE TITLE
Console exposes a way to change auth of a Tenant, but that results in an error

### ISSUE THREAD

**Issue by mbrancato** [minio/operator#1199]
## Expected Behavior
If you configure built-in auth, the Console shows a way to change the auth method after the tenant is created. Changing the auth type, filling the required fields, hitting `Save`.
<img width="951" alt="image" src="https://user-images.githubusercontent.com/8493275/178591550-7b5fb9a1-bdee-4510-8ca1-cc7adeabfd34.png">

The user is prompted to restart (the pool StatefuleSets, presumably) services. When selecting `Restart`, the cluster pools should restart witht he new auth config.

## Current Behavior

After hitting restart, the UI will display an error: 
```
Secrets "<tenant-name>-env-configuration" already exists
```
<img width="296" alt="image" src="https://user-images.githubusercontent.com/8493275/178591455-aead0595-af49-447f-b565-3f2895635054.png">

## Possible Solution

This probably should be part of the `Tenant` spec and not left to only the "env-configuration" `Secret`. Then the controller could regenerate the `Secret` when the `Tenant` object changes.

## Steps to Reproduce (for bugs)

1. Create a tenant
2. Attempt to change the auth for the tenant via the web console.

## Your Environment

* Version used (`minio-operator`): minio/operator:v4.4.25
* Environment name and version (e.g. kubernetes v1.17.2): GKE 1.22.8
* Server type and version: 
* Operating System and version (`uname -a`): Google COS
* Link to your deployment file:

**Comment by alee-x** [comment]
Is there any update on this or a workaround? 
Deleting the `"<tenant-name>-env-configuration"` secret causes a `Secrets "<tenant-name>-env-configuration" does not exist` error.

**Comment by id-noblis** [comment]
@alee-x, a potential workaround is to manually add/edit environment variables in the Configuration tab of the tenant in the operator console. Looks like you can save new values and trigger a restart which updates the `<tenant>-env-configuration` secret accordingly without error.

**Comment by shtripat** [comment]
With MinIO operator version v5.0.6 this works as expected and secret `<tenant-name>-env-configuration` gets updated properly.

**Comment by allanrogerr** [comment]
> With MinIO operator version v5.0.6 this works as expected and secret `<tenant-name>-env-configuration` gets updated properly.

@alee-x @mbrancato have you had another look at this?

**Comment by mbrancato** [comment]
@allanrogerr Sorry, I am no longer using this. If you feel its fixed in v5.0.6, I can close it.

**Comment by shtripat** [comment]
@allanrogerr I re-verified with latest MinIO operator version v5.0.11 and it works as expected. This can be closed.
