### ISSUE TITLE
Undocumented requirement to install operator-lifecycle-manager before installing minio/operator

### ISSUE THREAD

**Issue by eigood** [minio/operator#1202]
The docs for installing the operator say to add the helm repo, then to install the chart.  Once it is running, then a tenant can be created.

However, the minio-operator-xxx-xxx failed to start up; I got this error
```
0713 23:15:15.426124       1 main.go:70] Starting MinIO Operator
I0713 23:15:15.686925       1 main.go:169] caBundle on CRD updated
I0713 23:15:15.687681       1 main-controller.go:240] Setting up event handlers
I0713 23:15:15.687768       1 leaderelection.go:243] attempting to acquire leader lease default/minio-operator-lock...
I0713 23:15:15.690363       1 main-controller.go:485] new leader elected: minio-operator-6b44456dd5-bl96v
I0713 23:17:16.730061       1 leaderelection.go:253] successfully acquired lease default/minio-operator-lock
I0713 23:17:16.730129       1 main-controller.go:466] minio-operator-6b44456dd5-tm85l: I've become the leader
I0713 23:17:16.730186       1 main-controller.go:378] Waiting for API to start
I0713 23:17:16.730196       1 main-controller.go:370] Starting HTTP Upgrade Tenant Image server
panic: unable to retrieve the complete list of server APIs: packages.operators.coreos.com/v1: the server is currently unable to handle the request

goroutine 136 [running]:
github.com/minio/operator/pkg/controller/cluster/certificates.GetCertificatesAPIVersion.func1()
        github.com/minio/operator/pkg/controller/cluster/certificates/csr.go:100 +0x1e5
sync.(*Once).doSlow(0x0?, 0x0?)
        sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        sync/once.go:59
github.com/minio/operator/pkg/controller/cluster/certificates.GetCertificatesAPIVersion({0x1ac5630?, 0xc000152160?})
        github.com/minio/operator/pkg/controller/cluster/certificates/csr.go:89 +0x5e
github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1.1()
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:346 +0x4b
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:344 +0xbe
```

OLM is a rather *large* framework, and I was struggling to install it to get keycloak-operator installed(until I found the newer keycloak-operator based on quarkus, where they abandoned OLM).  I ended up abandoning my attempt.

**Comment by harshavardhana** [comment]
> I0713 23:17:16.730196       1 main-controller.go:370] Starting HTTP Upgrade Tenant Image server
> panic: unable to retrieve the complete list of server APIs: packages.operators.coreos.com/v1: the server is currently unable to handle the request
> 
> goroutine 136 [running]:
> github.com/minio/operator/pkg/controller/cluster/certificates.GetCertificatesAPIVersion.func1()
>         github.com/minio/operator/pkg/controller/cluster/certificates/csr.go:100 +0x1e5
> sync.(*Once).doSlow(0x0?, 0x0?)
>         sync/once.go:68 +0xc2
> sync.(*Once).Do(...)
>         sync/once.go:59
> github.com/minio/operator/pkg/controller/cluster/certificates.GetCertificatesAPIVersion({0x1ac5630?, 0xc000152160?})
>         github.com/minio/operator/pkg/controller/cluster/certificates/csr.go:89 +0x5e
> github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1.1()
>         github.com/minio/operator/pkg/controller/cluster/main-controller.go:346 +0x4b
> created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
>         github.com/minio/operator/pkg/controller/cluster/main-controller.go:344 +0xbe

This has nothing to do with OLM - you simply don't have enough permissions to call some operator APIs. Looks like you have some custom k8s here.

**Comment by germetist** [comment]
Is there a solution to the problem?

**Comment by cesnietor** [comment]
we'll try to reproduce and share comments.

**Comment by allanrogerr** [comment]
You have customized your k8s in some way:

> panic: unable to retrieve the complete list of server APIs: packages.operators.coreos.com/v1: the server is currently unable to handle the request

Please test again with a vanilla k8s or k3s, for example, and let us know. This is not reproducible.
