### ISSUE TITLE
Minio operator requested resources fail on GKE Autopilot

### ISSUE THREAD

**Issue by dcode** [minio/operator#1204]
The minio operator deployment fails install during `kubectl minio init` due to too few resources requested. The default GKE Autopilot minimum resource request is `500m`, but `minio-operator` only requests `200m`.

## Expected Behavior
I expected `kubectl minio init` to work out of the box with my GKE Autopilot cluster and if not, allow an override for the settings needed.

## Current Behavior

Currently, the CRD and console otherwise deploy just fine, but the user is left with an error about resource limits.

```commandline
>_ kubectl minio init
namespace/minio-operator created
serviceaccount/minio-operator created
clusterrole.rbac.authorization.k8s.io/minio-operator-role created
clusterrolebinding.rbac.authorization.k8s.io/minio-operator-binding created
customresourcedefinition.apiextensions.k8s.io/tenants.minio.min.io created
service/operator created
Warning: Autopilot increased resource requests for Deployment minio-operator/minio-operator to meet requirements. See http://g.co/gke/autopilot-resources.
serviceaccount/console-sa created
secret/console-sa-secret created
clusterrole.rbac.authorization.k8s.io/console-sa-role created
clusterrolebinding.rbac.authorization.k8s.io/console-sa-binding created
configmap/console-env created
service/console created
Warning: Autopilot set default resource requests for Deployment minio-operator/console, as resource requests were not specified. See http://g.co/gke/autopilot-defaults.
deployment.apps/console created
Error from server ([denied by autogke-pod-limit-constraints]): error when creating "STDIN": admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-pod-limit-constraints]":["workload 'minio-operator' cpu requests '{{250 -3} {\u003cnil\u003e}  DecimalSI}' is lower than the Autopilot minimum required of '{{500 -3} {\u003cnil\u003e} 500m DecimalSI}' for using pod anti affinity. Requested by user: '<REDACTED>', groups: 'system:authenticated'."]}
Error: exit status 1
```

## Possible Solution

I think it'd be useful to offer an argument or some way to set the resource limits during `init`. As a workaround, I saved to YAML using the `-o` flag, edited the `spec.template.spec.containers[0].resources.requests.cpu` of the `deployment/minio-operator` and used `kubectl apply -f` to install it. This seemingly worked as expected.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`): minio/operator:v4.4.25
* Environment name and version (e.g. kubernetes v1.17.2): 
* Server type and version:
```
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.202", GitCommit:"88deae00580af268497b9656f216cb092b630563", GitTreeState:"clean", BuildDate:"2022-06-03T03:27:52Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
> I think it'd be useful to offer an argument or some way to set the resource limits during `init`. As a workaround, I saved to YAML using the `-o` flag, edited the `spec.template.spec.containers[0].resources.requests.cpu` of the `deployment/minio-operator` and used `kubectl apply -f` to install it. This seemingly worked as expected.

Custom deployments such as yours are required to edit YAML manually.

**Comment by dcode** [comment]
Okay, maybe a note in the README to mention that. It wasn't obvious.

**Comment by cesnietor** [comment]
we'll work on updating the docs.
