### ISSUE TITLE
Cannot set node selector labels for node pools with an initial size of 0

### ISSUE THREAD

**Issue by mbrancato** [minio/operator#1205]
When using node autoscaling, the operator console will not allow setting node selector labels for node pools currently scaled to 0.

## Expected Behavior
While I understand that if a label value does not yet exist, you can't add it to a drop down, but a custom entry value should be allowed and no validation should be performed on label values to the extent that they exist in the cluster.

## Current Behavior
I currently have a node pool with `n2-standard-2` instance types created in GKE. However, there is no way for me to select the correct label if the node pool size is 0. There is also no way for me to enter it manually.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/8493275/179261533-8c6b2126-af39-4f53-b691-5b14399e66e3.png">

## Possible Solution
Add a manual label value option.

Work around is to scale the node pool up so that the MinIO console detects the label values.

## Steps to Reproduce (for bugs)

1. Create a cluster 
2. Add a node pool with size 0
3. Attempt to create a tenant targeting labels for the new node pool

## Your Environment

* Version used (`minio-operator`): 4.425
* Environment name and version (e.g. kubernetes v1.17.2): GKE v1.22.8
* Server type and version:
* Operating System and version (`uname -a`): COS
* Link to your deployment file:

**Comment by cniackz** [comment]
@mbrancato PTAL:

Can you add more details in why you need to set pool size to 0? otherwise we can simply set a warning on our UI to mention this is not supported unless you can provide a good reason for this use case.

**Comment by mbrancato** [comment]
It has been a long time since I looked at this, but I can only guess that having the autoscaler handle scale up and down of node pools is why. I probably created the node pool and let the autoscaler manage the scale from 0 to some value.

**Comment by cesnietor** [comment]
we won't support pool size 0 for now. Unless we find a valid use case. Please open a new one with more details if any. Thanks.
