### ISSUE TITLE
http: TLS handshake error from x.x.x.x:x: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by marysrini** [minio/operator#1226]
http: TLS handshake error from x.x.x.x:x: remote error: tls: bad certificate
## Current Behavior

 I am using Minio Operator version 4.4.10. I have 2 pods in minio operator and one of the pod is showing below error continuously, could you please help?-
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`):4.4.10
* Environment name and version (e.g. kubernetes v1.17.2):K8s
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by vadmeste** [comment]
@marysrini are you using auto cert feature or providing your own certificate?

**Comment by marysrini** [comment]
autocert feature only and this issue is happening after our upgrade from 4.0.2 to 4.4.10
Also, container is getting restarted frequently which is restarting pods and disks are getting offline
Not sure, whether this is related, but it happened after upgrade. how to make disks online?

**Comment by marysrini** [comment]
Do you have any suggestions?

**Comment by vadmeste** [comment]
@marysrini can you upload more logs from your pods ?

**Comment by marysrini** [comment]
Log from pod: crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc023501c00, {0xc024c82000, 0x8000, 0x0})
        crypto/tls/conn.go:1277 +0x16f
net/http.(*persistConn).Read(0xc024862120, {0xc024c82000, 0xc0234e1620, 0xc007433d30})
        net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc02387cc60)
        bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc02387cc60, 0x1)
        bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc024862120)
        net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
        net/http/transport.go:1747 +0x1e05

goroutine 2598909 [runnable]:
net/http.(*connReader).startBackgroundRead·dwrap·75()
        net/http/server.go:668
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1
created by net/http.(*connReader).startBackgroundRead
        net/http/server.go:668 +0xcf

goroutine 2562247 [select]:
net/http.(*persistConn).writeLoop(0xc0012d1560)
        net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
        net/http/transport.go:1748 +0x1e65

--------------------------------
Log from minio operator pod:
2022/08/04 10:00:52 http: TLS handshake error from 10.62.17.0:14644: remote error: tls: bad certificate
2022/08/04 10:00:52 http: TLS handshake error from 10.62.10.0:63586: remote error: tls: bad certificate
2022/08/04 10:00:53 http: TLS handshake error from 10.62.12.0:43973: remote error: tls: bad certificate

**Comment by marysrini** [comment]
Do we have any update?

**Comment by marysrini** [comment]
Hi Team, Could you please update us? Not sure, whether the related issue, but we have the container restart issue, Could you please assist?

**Comment by Alevsk** [comment]
@marysrini we need to more details to be able to help, for instance who own the ip addresses:

- 10.62.12.0
- 10.62.10.0
- 10.62.12.0 

`remote error: tls: bad certificate` error means the client is not trusting the operator certificate

**Comment by justinmarygopal** [comment]
What will be possible workaround? should I change the operator certificate?

**Comment by justinmarygopal** [comment]
Do we have any update?

**Comment by enrico2828** [comment]
We have observed this behavior too in our OpenShift environment. I could single out 2 OpenShift services that try to query the Minio operator but fail to do so due to certificate errors:
1) 
`k logs -f -n openshift-kube-apiserver-operator kube-apiserver-operator-74c49f4ddf-xvr7w`
```
E0913 16:42:01.830969       1 degraded_webhook.go:128] x509: certificate is valid for operator, operator.openshift-operators.svc, operator.openshift-operators.svc.cluster.local, not minio-operator-service.openshift-operators.svc
```

As it appears, "minio-operator-service.openshift-operators.svc" is not included as DNS in the Minio operator-tls certificate. This can be fixed easily (by minio team) by including it in the CSR.

2) 
`k logs -n openshift-kube-apiserver kube-apiserver-ocp201-mmb9l-master-03`

```
E0913 16:38:02.549776      18 cacher.go:420] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.openshift-operators.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate signed by unknown authority; reinitializing...
E0913 16:38:03.560729      18 cacher.go:420] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.openshift-operators.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate signed by unknown authority; reinitializing...
```

This service doesn't trust the CA of the operator-tls certificate (kubelet serving). Not sure how to fix this, also I am not aware of what this service is supposed to do. 

The errors probably do not directly impact the functioning of Minio, but they totally pollute the operator log, as an entry is generated every second.

**Comment by enrico2828** [comment]
It seems that this issue https://github.com/minio/operator/pull/1248 fixes it, it is available in operator 4.5.0 release. Unfortunately, we only get offered 4.4.28 so I cannot test right now.

**Comment by dvaldivia** [comment]
We are going to update the OpenShift Operators listing soon

**Comment by justinmarygopal** [comment]
Do we have any workaround for now?

**Comment by kaovilai** [comment]
Using 4.5.0 release. Still seeing this issue.

**Comment by kaovilai** [comment]
*on OpenShift.

**Comment by kaovilai** [comment]
I do see the annotation in the mentioned PR in my minio-operator-rhmp.v4.5.0's operator service.

**Comment by kaovilai** [comment]
In addition. 4.5.0 docs are missing OpenShift sections. https://github.com/minio/docs/issues/576

**Comment by enrico2828** [comment]
Still seeing the issue on OpenShift 4.10 with operator 4.5.1. Same errors as before, there is a domain missing in the certificate which makes the kube-api server not accept the minio certificate.
![CleanShot 2022-10-05 at 16 45 14](https://user-images.githubusercontent.com/14042813/194089911-058ccf92-95be-4ff4-a16f-0929f7e76311.png)

**Comment by chris93111** [comment]
Hi same issue here https://github.com/minio/operator/issues/1331

```
kubectl describe csr operator-minio-operator-csr
Name:               operator-minio-operator-csr
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Mon, 31 Oct 2022 13:10:12 +0100
Requesting User:    system:serviceaccount:minio-operator:minio-operator
Signer:             kubernetes.io/kubelet-serving
Status:             Approved,Issued
Subject:
  Common Name:    system:node:operator.minio-operator.svc
  Serial Number:  
  Organization:   system:nodes
Subject Alternative Names:
         DNS Names:  operator
                     operator.minio-operator.svc
                     operator.minio-operator.svc.cluster.local
```

Nov 01 14:02:45 cfg01-master-awx k3s[129356]: E1101 14:02:45.920161 129356 cacher.go:424] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.minio-operator.svc, operator.minio-operator.svc.cluster.local, not minio-operator-service.minio-operator.svc; reinitializing...
Nov 01 14:02:46 cfg01-master-awx k3s[129356]: W1101 14:02:46.925225 129356 reflector.go:324] storage/cacher.go:/minio.min.io/tenants: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.minio-operator.svc, operator.minio-operator.svc.cluster.local, not minio-operator-service.minio-operator.svc
Nov 01 14:02:46 cfg01-master-awx k3s[129356]: E1101 14:02:46.925251 129356 cacher.go:424] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.minio-operator.svc, operator.minio-operator.svc.cluster.local, not minio-operator-service.minio-operator.svc; reinitializing...

**Comment by kaovilai** [comment]
This issue may duplicates https://github.com/minio/operator/issues/1234

**Comment by justinmarygopal** [comment]
Do we have any workaround for this issue?

**Comment by xrafhue** [comment]
@justinmarygopal in my case i use K3D/K3S, my workaround is [here](https://github.com/minio/operator/issues/1331#issuecomment-1317016782)

**Comment by justinmarygopal** [comment]
Could you please let me know what are the changes you have done? We are trying the minio version: 4.4.10 and K8 version: 1.20

**Comment by xrafhue** [comment]
@justinmarygopal take a look in my comment in the other issue i explain what i did.

**Comment by cniackz** [comment]
Please try with latest k8s version, at least 1.24 and the latest operator version 5.0.10 and let us know!.
