### ISSUE TITLE
Add "accessModes" configuration to tenant helm chart.

### ISSUE THREAD

**Issue by ScionOfDesign** [minio/operator#1246]
**Is your feature request related to a problem? Please describe.**
We use an external pod attached to the same PVC for managing backups/restoring our applications. This requires the PVC to have a "ReadWriteMany" access mode.
In order to change the access mode on the chart, we have to modify the chart locally.

**Describe the solution you'd like**
Simply add the ability to configure the access mode in the values.yaml of the tenant chart.

**Describe alternatives you've considered**
Just modifying the chart ourselves.

**Comment by harshavardhana** [comment]
> We use an external pod attached to the same PVC for managing backups/restoring our applications. This requires the PVC to have a "ReadWriteMany" access mode.

This will not work with MinIO unfortunately @ScionOfDesign - this can lead to corruption of backend disks and MinIO needs exclusive access to your PVCs to ensure that data that is being written does not get corrupted. 

Using some external tools to modify PVCs on the backend is not expected and will not be supported by MinIO Operator. 

You want to backup MinIO using something like Commvault-like tools to backup your MinIO buckets, or you can set up Site Replication to keep copies of all data on a DR cluster.
