### ISSUE TITLE
MinIO site-to-site replication not working properly with MinIO operator

### ISSUE THREAD

**Issue by amrragab95** [minio/operator#1266]
## Expected Behavior
<img width="355" alt="image" src="https://user-images.githubusercontent.com/93654678/187453896-af65cd1f-3d0e-4179-a85c-f543fb4b15cf.png">
- adding two sites for replication should work fine as i'm using root username and pass and `mc admin info rep1` works as expected
<img width="633" alt="image" src="https://user-images.githubusercontent.com/93654678/187454271-96e70f63-4084-458b-b489-540f9fc0e23c.png">

## Current Behavior
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/93654678/187454357-8e3a4515-bb8f-4927-8a6b-9517d26e4df5.png">

## Possible Solution
It should work directly 
## Steps to Reproduce (for bugs)

1. run minio-operator helm chart latest version
2. create tenants using latest version too
3. add site to mc
4. do replication

## Context
I want to achieve site-to-site replication

## Your Environment

* Version used (`minio-operator`): latest
* Environment name and version (e.g. kubernetes v1.17.2):kubernetes v1.20

**Comment by klauspost** [comment]
A quick guess is that your mc is configured with localhost and not a remote IP. Guessing this since it is trying to connect to 127.0.0.1

**Comment by klauspost** [comment]
@amrragab95 If mc doesn't know the host name and/or ip of the destination cluster it cannot configure replication. 

Use host names/ips that are visible to the clusters for configuring.
