### ISSUE TITLE
Include full container securityContext in the helm chart

### ISSUE THREAD

**Issue by LeadingMoominExpert** [minio/operator#1267]
**Is your feature request related to a problem? Please describe.**
The current helm chart implementation doesn't allow setting full securityContext to the containers when deploying the operator, operator-console or tenant as described in the kubernetes api documentation https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#securitycontext-v1-core. 

**Describe the solution you'd like**
I would like to be able to include the container securityContext in the helm chart values to be able to configure the containers in a required way.

**Describe alternatives you've considered**
Patch files to be applied after installing the operator, console and tenants with helm.

**Comment by allanrogerr** [comment]
Fixed in https://github.com/minio/operator/pull/1372. Please see for comments.

**Comment by BrettCharrier** [comment]
@allanrogerr 

So `sidecar container`: https://github.com/minio/operator/blob/v5.0.4/pkg/resources/statefulsets/minio-statefulset.go#L898 does not expose/set a securityContext

and `validate-arguments container`: https://github.com/minio/operator/blob/v5.0.4/pkg/resources/statefulsets/minio-statefulset.go#L873 also doesn't expose/set securityContext.

Should a new issue be opened?
