### ISSUE TITLE
Unable to use pre-created credential secret with minio tenant helm chart 

### ISSUE THREAD

**Issue by KnjazS** [minio/operator#1269]
Changes in file [helm/tenant/templates/tenant.yaml](https://github.com/minio/operator/commit/bb8a74a21fd9ee0819b7159a6f845c79d3c83e69#diff-2c1f4d50e1ed47a18c1a1c116e73faf2d12e6d90c2f5010487000bd471e4ff9b)  in #1009 lead to inability to pre-create secret with credentials for minio root user

## Expected Behavior
Previously using such values.yaml in helm release created a Tenant CRD with reference to secret my-secret-with-config-env
```
secrets: false
tenant:
  ...
  configuration: my-secret-with-config-env
```

## Current Behavior
The same values.yaml causes an error:
`Helm install failed: template: tenant/templates/tenant.yaml:30:13: executing "tenant/templates/tenant.yaml" at <dig "secrets" "name" "" ($.Values | merge (dict))>: error calling dig: interface conversion: interface {} is bool, not map[string]interface {}`

If try to change values.yaml to:
```
secrets:
  name: my-secret-with-config-env
tenant:
  ...
```
Helm release try to create secret my-secret-with-config-env with default credentials and replace created one

## Environment
* minio-operator: v4.4.28 commit: [bb8a74a](https://github.com/minio/operator/tree/bb8a74a21fd9ee0819b7159a6f845c79d3c83e69/helm)
* Kubernetes v1.24.4
* sealed-secret v0.18.2 (or another secrets operator)

**Comment by dnskr** [comment]
Right. It looks like PR https://github.com/minio/operator/pull/1232 changes were accidentally overwritten by PR https://github.com/minio/operator/pull/1009 during the conflicts resolution.
So it's needed again to replace in `helm/tenant/templates/tenant.yaml`
```
  configuration:
    name: {{ dig "secrets" "name" "" ($.Values | merge (dict)) }}
```
with
```
  configuration:
    name: {{ .configuration.name }}
```
