### ISSUE TITLE
minio pvc mounting taking time because of securitycontext labeling.

### ISSUE THREAD

**Issue by vjvel** [minio/operator#1270]

**Comment by mshanmu** [comment]
Add the "fsGroupChangePolicy: OnRootMismatch" to the securityContext, that will fix your issue. Btw, in latest operator versions, this is set by default.

**Comment by vjvel** [comment]
@mshanmu is it recommended to disable the securitycontext for the tenant deployment so that it will not take more time to mount the PVC.

**Comment by mshanmu** [comment]
@vjvel , Not recommended to disable security context.
