### ISSUE TITLE
resource quota in tenant namespace is failing because of initcontainer for the log pod

### ISSUE THREAD

**Issue by vjvel** [minio/operator#1287]
We are using latest minio image docker pull minio/minio:RELEASE.2022-09-07T22-25-02Z and latest minio-operator v4.3.7

we have enabled quota for the minio tenant namespace. 

Getting the below error,  Initcontainer for this pod  minio-log is not having resource (limit/request).  in tenant only having option to set resource request limits for the log container not the initcontainer.
```
Warning  FailedCreate      6m50s (x34 over 22m)  statefulset-controller  create Pod prod-minio-log-0 in StatefulSet prod-minio-log failed error: pods "prod-minio-log-0" is forbidden: failed quota: minio-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```

can you please update the resource option for init container or update by default ?

**Comment by dvaldivia** [comment]
What version of kubernetes are you using? where did you specify the quota? did you create it yourself?

**Comment by vjvel** [comment]
> What version of kubernetes are you using? where did you specify the quota? did you create it yourself?
1.21
namespace where the tenant has created.  
if container or init container has no resource request/limit is assigned its not allowed to create it in the namespace. I don't see any option to provide resource for the initcontainer for the log pod..   In tenant I can add resource for the main container only..  If we have this limits or request for this initContainer it will work..

**Comment by allanrogerr** [comment]
In `minio operator version 5.0.13`, containers `minio`, `sidecar` and `validate-arguments` (init) have entries for `resources: {}`. This is resolved.

**Comment by rajasekharbh** [comment]
with the operator helm charts(5.0.13 or 6.0.1) the sidecar and validate-arguments containers are getting resource empty and values.yaml doesn't have the resources set for the init and sidecar.  if we don't set the values validation webhook is not allowing to create the pod.

warning FailedCreate 20s (x17 over 5m49s) statefulset-controller create Pod myminio-tenant-pool-0-0 in StatefulSet myminio-tenant-pool-0-0 failed error: admission webhook "validating-webhook.openpolicyagent.org" denied the request: the pod "myminio-tenant-pool-0-0", in namespace "minio-tenant", did not specify cpu limits resources, the pod: "myminio-tenant-pool-0-0", in namespace "minio-tenant", did not specify cpu requests, the pod:"myminio-tenant-pool-0-0", in namespace: "minio-tenant", did not specify memory limits resources, the pod:"myminio-tenant-pool-0-0", in namespace: "monio-tenant", did not specify memory request resources.


https://github.com/minio/operator/blob/v5.0.13/helm/operator/values.yaml

if we set the resourcequota at namespace level, we are getting below error.

Warning FailedCreate 100s (x17 over 7m8s) statefulset-controller create Pod myminio-tenant-pool-0-0 in StatefulSet myminio-pool-0 failed error: pod "myminio-tenant-pool-0-0" is forbidden: failed quots: minio-quota: must specify limits.cpu for : sidecar,validate-arguments; limits,memory for : sidecar,validat-arguments; requests,cpu for sidecar,validate-arguments; requestss,memory for: sidecar,validat-arguments

can you please check this error.

**Comment by rajasekharbh** [comment]
@triage
