### ISSUE TITLE
"NoSchedule": effect must be 'NoExecute' when `tolerationSeconds` is set

### ISSUE THREAD

**Issue by VPelmeSHko** [minio/operator#1298]
Got **Pools.0.tolerations.0.tolerationSeconds.seconds in body is required.** when trying to specify NoSchedule without seconds in PodPlacement -> Tolerations screen.
Specifying seconds to 0 this will cause **invalid: spec.tolerations[0].effect** issue on statefulset

kubectl minio version
v4.5.0

kubectl -n test describe statefulset test-pool-0
~~~
Events:
  Type     Reason            Age                  From                    Message
  ----     ------            ----                 ----                    -------
  Warning  FailedCreate      2m6s (x69 over 37m)  statefulset-controller  create Pod test-pool-0-3 in StatefulSet test-pool-0 failed error: Pod "test-pool-0-3" is invalid: spec.tolerations[0].effect: Invalid value: "NoSchedule": effect must be 'NoExecute' when `tolerationSeconds` is set
~~~

kubectl -n test get  statefulset test-pool-0 -o yaml
~~~
tolerations:                          
      - effect: NoSchedule                                                                                            
        key: nvidia.com/gpu                            
        operator: Equal              
        tolerationSeconds: 0
        value: "true"
~~~

**Comment by cesnietor** [comment]
we'll try to reproduce, it might be just UI.

**Comment by allanrogerr** [comment]
FYI @adriangitvitz 
Two confirmed bugs here:

1. UI should not allow `.tolerations.NoSchedule` with `tolerationSeconds` 
2. UI should return the error currently hidden in the PUT response to request on `/api/v1/namespaces/<tenant-ns>/tenants/<tenant-name>/pools`:

```
{
    "code": 500,
    "detailedMessage": "Invalid value: \"NoSchedule\": effect must be 'NoExecute' when tolerationSeconds is set",
    "message": "an error occurred, please try again"
}
```
