### ISSUE TITLE
Operator Bundle <4.5.0 unavailable on stable channel.

### ISSUE THREAD

**Issue by kaovilai** [minio/operator#1299]
Please read https://olm.operatorframework.io/docs/best-practices/channel-naming/#recommended-upgrade-path.

CSV is not properly setting replaces/skipRanges.

Specifically _to ensure the **older Operator bundle does not get pruned** from the index catalog via the OLM resolver_

> **Note** If you would like to ensure that the users of your Operator are still able to install the Operator bundle version `3.6.29` by using the option `startingCSV` added manually in the subscription then, you will need to also use the `replaces: 3.6.29` to ensure the older Operator bundle does not get pruned from the index catalog via the OLM resolver.

**Comment by enrico2828** [comment]
I second that, we also experienced that we couldn't install an older version of the operator, which was especially urgent when v4.5.0 turned out to be defect. It effectively rendered our (test) environment unusable until a fix with 4.5.1 was available!

**Comment by kaovilai** [comment]
unstale :D

**Comment by dvaldivia** [comment]
I think we had a problem on this that @pjuarezd solved, regarding not using the same channel to release new versions so upgrade was not possible.

**Comment by kaovilai** [comment]
as long as allowed version ranges are set correctly, it should be possible to have different channels selected and still upgrade.

**Comment by cniackz** [comment]
The issue has been resolved in the latest version of Operator. Presently, we utilize replaces. If you require older versions of Operator, remember that CSV is not the sole method for installing Operator. For debugging or other purposes, please consider using kustomize as an alternative method.
