### ISSUE TITLE
Allow multiple tenant in the same namespace

### ISSUE THREAD

**Issue by jvizier** [minio/operator#1302]
## Expected Behavior

Allow operator to create multiple tenant in same namespace, explan why it's not possible.

## Current Behavior
In our k8s cluster, our namespaces are protected, i can only install one tenant in the same namespace as operator, it's ok for the first tenant but not others. It's hardcoded in the code operator/pkg/controller/cluster/main-controller.go

## Possible Solution
If not possible i can install multiple minio in distributed mode in the same namespace.

## Steps to Reproduce (for bugs)
kubectl minio tenant create tenant2 --servers 4 --volumes 4 --capacity 1Gi --namespace minio

## Context
Not able to create multiple tenant with Operator in one namespace

## Regression
No

## Your Environment

* Version used (`minio-operator`): operator-4.5.0	v4.5.0
* Environment name and version : v1.22.9+vmware.1

**Comment by harshavardhana** [comment]
@jvizier this is something out of scope in our design at the moment.

If you have a strict requirement here please send a PR, but we won't be working on this for foreseeable future.
