### ISSUE TITLE
Minio  redirect at different port 

### ISSUE THREAD

**Issue by pankaj9782** [minio/operator#1306]
I have configured minio with distributed mode and port forwards randomly 9000 to 33569
ip 103.27.232.243:9000  (test this)
 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
Yes that port is where you have Console UI running if you want a static port use `--console-address`

**Comment by pankaj9782** [comment]
pls check this
https://prnt.sc/R11H_MIG2Efv
https://prnt.sc/ee4iRQLFpqiV

**Comment by pankaj9782** [comment]
I  have used this  {Console UI running if you want a static port use --console-address}
