### ISSUE TITLE
Minio redirect at different port #1306

### ISSUE THREAD

**Issue by pankaj9782** [minio/operator#1307]
i have configured by official document I used a static port
 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
@pankaj9782 Please have some valid reports, writing a single line in a GitHub issue doesn't tell us what is it that you want help with. 

Please be clear in your issue reporting we cannot imagine your setup. You need to help us to help you.

**Comment by pankaj9782** [comment]
what can i do ??

**Comment by pankaj9782** [comment]
https://prnt.sc/TJaTta2GUV4v
