### ISSUE TITLE
Minio Operator on OpenShift does not provide upgrade option

### ISSUE THREAD

**Issue by enrico2828** [minio/operator#1309]
We run OpenShift 4.9 and 4.10 and install Minio through the OpenShift OperatorHub. When there is a new version, we don't see the option to upgrade to the latest version. We cannot upgrade

## Expected Behavior
For the RedHat Operators, for manual upgrade approvals, an upgrade button will appear so that the operator can be upgraded.

## Current Behavior
No upgrade button appears. If the update approval is set to automatic, no update will be applied. The operator stays on the old version, even though the channel provides a newer version.

## Possible Solution
As a workaround, we uninstall tenants and Minio operator. Then reinstall the operator, which will install with the latest version. Then reinstall the tenant. 
This works, but is not desirable as it leads to downtime of the Minio service. Also, it deletes some secrets like the log search api secret, which will be recreated. But since some tokens are stored within the applications (postgres, minio), the tokens don't match anymore and the logs cannot be pushed to the log api anymore.

## Steps to Reproduce (for bugs)

1. Install Minio operator on OpenShift 
2. Install a Minio tenant
3. Wait for a new version of the Minio operator to be published.
4. See that the new operator version is not installed (automatic installation) or that no upgrade button is available (manual approval)

## Context
This is poses serious production impact since new versions of the Operator cannot be installed without uninstalling Minio.

## Regression
Unsure, it hasn't been working since we started using Minio on OpenShift in March this year.

## Your Environment

* Version used (`minio-operator`): 4.4.24 - 4..5.1
* Environment name and version (e.g. kubernetes v1.17.2): OpenShift 4.9 and 4.10
* Server type and version: Bare Metal
* Operating System and version (`uname -a`): Core OS
* Link to your deployment file:

![CleanShot 2022-10-05 at 14 07 23](https://user-images.githubusercontent.com/14042813/194085740-f2993347-1df6-4219-9d27-0f76c8a1eaf9.png)

**Comment by dvaldivia** [comment]
Perhaps we need some annotation to support upgrades

**Comment by cniackz** [comment]
This was resolved when we used to have `olm.skipRange: '>=4.4.16 <5.0.3'` annotation back in v5.0.3 of our operator but that got removed. Will consult with @pjuarezd on this.

**Comment by cniackz** [comment]
Ok just confirmed with @pjuarezd we are going to be using `replaces: minio-operator-rhmp.v5.0.5` instead of `skipRange` for the upgrade process as that is the method that work better for us:

https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/blob/main/operators/minio-operator-rhmp/5.0.6/manifests/minio-operator-rhmp.clusterserviceversion.yaml#L629

**Comment by cniackz** [comment]
Please wait for our next release and test again and let us know if you still face this issue.

**Comment by cniackz** [comment]
The issue has already been addressed; presently, we are utilizing the replace option. You can find more details here: [replaces](https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/blob/main/operators/minio-operator-rhmp/5.0.6/manifests/minio-operator-rhmp.clusterserviceversion.yaml#L629).
