### ISSUE TITLE
Tenant support for container level securityContext

### ISSUE THREAD

**Issue by mjnagel** [minio/operator#1310]
**Is your feature request related to a problem? Please describe.**

Currently we are unable to set `securityContext` at the container level for Tenants (the CRD does not provide values for this). In high security environments end users may require setting fields at this level, for example to drop all linux capabilities.

**Describe the solution you'd like**

Add to the Tenant CRD spec to allow specifying a container level securityContext for pools. This would then be used by the operator [here](https://github.com/minio/operator/blob/v4.5.2/pkg/resources/statefulsets/minio-statefulset.go#L347) during creation of the container.

**Describe alternatives you've considered**

Currently the only alternative is to have some sort of mutating webhook modify the containers during creation. This is not ideal since it requires external application to manage/back this webhook.

**Additional context**

This would be a pre-requisite to adding support in the helm chart for https://github.com/minio/operator/issues/1267. It seems like there is other interest in the community for this support based on other issues/PRs like that one.

**Comment by LeadingMoominExpert** [comment]
I'd be interested to work on this as I really have a need for this. @mjnagel you pointed where the operator would use the container level securityContext, and [here](https://github.com/minio/operator/blob/v4.5.2/pkg/apis/minio.min.io/v2/types.go#L103) is the spec for the tenant CRD, if I'm not mistaken. Any pointers by the maintainers where this addition would affect would be extremely helpful

**Comment by allanrogerr** [comment]
Fixed in https://github.com/minio/operator/pull/1372. Please see for comments.
