### ISSUE TITLE
Error connecting to db: pq: SSL is not enabled on the server

### ISSUE THREAD

**Issue by qyk1995** [minio/operator#1314]
## Current Behavior

docker run --rm -it -e "POSTGRES_PASSWORD=example" -p 5432:5432 postgres:13-alpine -c "log_statement=all" 
[root@test-minio02 ~]# ./logsearchapi 
2022/10/12 11:39:25 Error connecting to db: pq: SSL is not enabled on the server

## Steps to Reproduce (for bugs)

1. docker run --rm -it -e "POSTGRES_PASSWORD=example" -p 5432:5432 postgres:13-alpine -c "log_statement=all" 
2. go build 
3.  ./logsearchapi
4.

## Your Environment

* Version used (`minio-operator`): 
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
@qyk1995 you are not supposed to run logsearchapi outside of operator please use a k8s deployment for this.
