### ISSUE TITLE
Unable to Override MINIO_SERVER_URL in minio-operator deployed via helm charts 

### ISSUE THREAD

**Issue by shabbiervempalli-yti** [minio/operator#1318]
With Reference to this   https://github.com/minio/operator/issues/1317
when I tried to override the environment variable of minio-operator deployed via helm charts
from MINIO_URL = [http://minio.minio-staging-tenant.svc.cluster.local:80](http://minio.minio-staging-tenant.svc.cluster.local/) to other public URL
it's creating a new entry of MINIO_SERVER_URL
![image (13)](https://user-images.githubusercontent.com/83750373/196594765-29c66dba-c75c-4ded-a0a2-fe0003d36ccc.png)
seems its a bug 
and we are using 4.2.7 Minio-operator

**Comment by cowjen01** [comment]
Hello @shabbiervempalli-yti, could you please provide me with the chart's `values.yaml`? I'm wondering how did you pass root user's credentials into the pods using environment variables without having to specify them in the configuration secret with `config.env` key?

**Comment by shabbiervempalli-yti** [comment]
![image (14)](https://user-images.githubusercontent.com/83750373/196635087-30808b20-377a-4a4a-8771-2bf866526702.png)
`operator:
  ## DEPRECATED: Please use the "CLUSTER_DOMAIN" or "WATCHED_NAMESPACE" env variable
  ## instead of clusterDomain and nsToWatch.
  # clusterDomain: "cluster.local"
  # nsToWatch: ""
  ## Setup environment variables for the Operator
  # env:
  #   - name: MINIO_OPERATOR_TLS_ENABLE
  #     value: "off"
  #   - name: CLUSTER_DOMAIN
  #     value: "cluster.domain"
  #   - name: WATCHED_NAMESPACE
  #     value: ""
  image:
    repository: minio/operator
    tag: v4.2.6
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  initcontainers: []
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  nodeSelector: {}
  affinity: {}
  tolerations: []
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi
console:
  image:
    repository: minio/console
    tag: v0.9.6
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  initcontainers: []
  replicaCount: 1
  nodeSelector: {}
  affinity: {}
  tolerations: []
  resources: {}
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  ingress:
    enabled: false
    labels: {}
    annotations: {}
    tls: []
    host: console.local
    path: /
## MinIO Tenant Definition
tenants:
  # Tenant name
  - name: minio1
    ## Registry location and Tag to download MinIO Server image
    image:
      repository: minio/minio
      tag: RELEASE.2021-09-03T03-56-13Z
      pullPolicy: IfNotPresent
      env:
        MINIO_SERVER_URL: [https:hello564646.com](https://app.slack.com/client/T014W9HBA7R/hello564646.com)
    ## Customize namespace for tenant deployment
    namespace: default
    ## Customize any private registry image pull secret.
    ## currently only one secret registry is supported
    imagePullSecret: {}
    ## If a scheduler is specified here, Tenant pods will be dispatched by specified scheduler.
    ## If not specified, the Tenant pods will be dispatched by default scheduler.
    scheduler: {}
    ## Specification for MinIO Pool(s) in this Tenant.
    pools:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
      - servers: 4
        ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
        volumesPerServer: 4
        ## size specifies the capacity per volume
        size: 10Gi
        ## storageClass specifies the storage class name to be used for this pool
        storageClassName: standard
        ## Used to specify a toleration for a pod
        tolerations: {}
        ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
        ## eligible to run on a node, the node must have each of the
        ## indicated key-value pairs as labels.
        ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
        nodeSelector: {}
        ## Affinity settings for MinIO pods. Read more about affinity
        ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
        affinity: {}
        ## Configure resource requests and limits for MinIO containers
        resources: {}
        ## Configure security context
        securityContext: {}
    ## Mount path where PV will be mounted inside container(s).
    mountPath: /export
    ## Sub path inside Mount path where MinIO stores data.
    subPath: /data
    # pool secrets
    secrets:
      # create a kubernetes secret object with the accessKey and secretKey as defined here.
      enabled: true
      name: minio1-secret
      accessKey: minio
      secretKey: minio123
    # pool metrics to be read by Prometheus
    metrics:
      enabled: false
      port: 9000
    certificate:
      ## Use this field to provide one or more external CA certificates. This is used by MinIO
      ## to verify TLS connections with other applications:
      ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
      externalCaCertSecret: {}
      ## Use this field to provide a list of Secrets with external certificates. This can be used to to configure
      ## TLS for MinIO Tenant pods. Create secrets as explained here:
      ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
      externalCertSecret: {}
      ## Enable automatic Kubernetes based certificate generation and signing as explained in
      ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
      requestAutoCert: true
      ## This field is used only when "requestAutoCert" is set to true. Use this field to set CommonName
      ## for the auto-generated certificate. Internal DNS name for the pod will be used if CommonName is
      ## not provided. DNS name format is *.minio.default.svc.cluster.local
      certConfig: {}
    ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
    ## accessible as DNS entries of form `<bucketname>.minio.default.svc.cluster.local`
    s3:
      ## This feature is turned off by default
      bucketDNS: false
    ## PodManagement policy for MinIO Tenant Pods. Can be "OrderedReady" or "Parallel"
    ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
    ## for details.
    podManagementPolicy: Parallel
    ## serviceMetadata allows passing additional labels and annotations to MinIO and Console specific
    ## services created by the operator.
    serviceMetadata: {}
    ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
    env: {}
    ## PriorityClassName indicates the Pod priority and hence importance of a Pod relative to other Pods.
    ## This is applied to MinIO pods only.
    ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
    priorityClassName: ""`

**Comment by shabbiervempalli-yti** [comment]
operator:
  ## DEPRECATED: Please use the "CLUSTER_DOMAIN" or "WATCHED_NAMESPACE" env variable
  ## instead of clusterDomain and nsToWatch.
  # clusterDomain: "cluster.local"
  # nsToWatch: ""
  ## Setup environment variables for the Operator
  # env:
  #   - name: MINIO_OPERATOR_TLS_ENABLE
  #     value: "off"
  #   - name: CLUSTER_DOMAIN
  #     value: "cluster.domain"
  #   - name: WATCHED_NAMESPACE
  #     value: ""
  image:
    repository: minio/operator
    tag: v4.2.6
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  initcontainers: []
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  nodeSelector: {}
  affinity: {}
  tolerations: []
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi
console:
  image:
    repository: minio/console
    tag: v0.9.6
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  initcontainers: []
  replicaCount: 1
  nodeSelector: {}
  affinity: {}
  tolerations: []
  resources: {}
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  ingress:
    enabled: false
    labels: {}
    annotations: {}
    tls: []
    host: console.local
    path: /
## MinIO Tenant Definition
tenants:
  # Tenant name
  - name: minio1
    ## Registry location and Tag to download MinIO Server image
    image:
      repository: minio/minio
      tag: RELEASE.2021-09-03T03-56-13Z
      pullPolicy: IfNotPresent
      env:
        MINIO_SERVER_URL: [https:hello564646.com](https://app.slack.com/client/T014W9HBA7R/hello564646.com)
    ## Customize namespace for tenant deployment
    namespace: default
    ## Customize any private registry image pull secret.
    ## currently only one secret registry is supported
    imagePullSecret: {}
    ## If a scheduler is specified here, Tenant pods will be dispatched by specified scheduler.
    ## If not specified, the Tenant pods will be dispatched by default scheduler.
    scheduler: {}
    ## Specification for MinIO Pool(s) in this Tenant.
    pools:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
      - servers: 4
        ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
        volumesPerServer: 4
        ## size specifies the capacity per volume
        size: 10Gi
        ## storageClass specifies the storage class name to be used for this pool
        storageClassName: standard
        ## Used to specify a toleration for a pod
        tolerations: {}
        ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
        ## eligible to run on a node, the node must have each of the
        ## indicated key-value pairs as labels.
        ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
        nodeSelector: {}
        ## Affinity settings for MinIO pods. Read more about affinity
        ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
        affinity: {}
        ## Configure resource requests and limits for MinIO containers
        resources: {}
        ## Configure security context
        securityContext: {}
    ## Mount path where PV will be mounted inside container(s).
    mountPath: /export
    ## Sub path inside Mount path where MinIO stores data.
    subPath: /data
    # pool secrets
    secrets:
      # create a kubernetes secret object with the accessKey and secretKey as defined here.
      enabled: true
      name: minio1-secret
      accessKey: minio
      secretKey: minio123
    # pool metrics to be read by Prometheus
    metrics:
      enabled: false
      port: 9000
    certificate:
      ## Use this field to provide one or more external CA certificates. This is used by MinIO
      ## to verify TLS connections with other applications:
      ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
      externalCaCertSecret: {}
      ## Use this field to provide a list of Secrets with external certificates. This can be used to to configure
      ## TLS for MinIO Tenant pods. Create secrets as explained here:
      ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
      externalCertSecret: {}
      ## Enable automatic Kubernetes based certificate generation and signing as explained in
      ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
      requestAutoCert: true
      ## This field is used only when "requestAutoCert" is set to true. Use this field to set CommonName
      ## for the auto-generated certificate. Internal DNS name for the pod will be used if CommonName is
      ## not provided. DNS name format is *.minio.default.svc.cluster.local
      certConfig: {}
    ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
    ## accessible as DNS entries of form `<bucketname>.minio.default.svc.cluster.local`
    s3:
      ## This feature is turned off by default
      bucketDNS: false
    ## PodManagement policy for MinIO Tenant Pods. Can be "OrderedReady" or "Parallel"
    ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
    ## for details.
    podManagementPolicy: Parallel
    ## serviceMetadata allows passing additional labels and annotations to MinIO and Console specific
    ## services created by the operator.
    serviceMetadata: {}
    ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
    env: {}
    ## PriorityClassName indicates the Pod priority and hence importance of a Pod relative to other Pods.
    ## This is applied to MinIO pods only.
    ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
    priorityClassName: ""

**Comment by shabbiervempalli-yti** [comment]
by using this reference https://github.com/minio/operator/issues/790  tried to override the MNIO_SERVER_URL
but unable to login to minio console
![image](https://user-images.githubusercontent.com/83750373/197701724-38630b31-fb1e-4826-843e-ad20fc0a57bf.png)
![image](https://user-images.githubusercontent.com/83750373/197701814-ea871343-03c5-4f70-8992-2776da83ebc6.png)
![image](https://user-images.githubusercontent.com/83750373/197701902-ed86878e-38da-4f23-a87b-8b108e29ba3a.png)
does this feature really supports in minio operator exposing objects using public endpoint instead local kubernetes service

**Comment by dvaldivia** [comment]
`MINIO_URL` is now passed by MinIO to it's UI, so in turn, this must be passed to MinIO, inside the tenant we have a section for specifying domains for both, the MinIO service and the Console.

```yaml
spec:
  features:
    ## Specify a list of domains used to access MinIO and Console
    domains:
      minio:
        - domain1.minio
        - domain2.minio
      console: console.minio
```

**Comment by cesnietor** [comment]
closing due to innactivity
