### ISSUE TITLE
Add Anti-CSRF Token

### ISSUE THREAD

**Issue by Rezkmike** [minio/operator#1323]
**Is your feature request related to a problem? Please describe.**
Minio keep giving me Absence of Anti-CSRF Token issue on vulnerability scan result

**Describe the expected solution you'd like**
It would be the best if you can implement the Anti-CSRF token on all post requests or on critical stuffs like reset password in the application

**Comment by cesnietor** [comment]
we'll investigate

**Comment by cesnietor** [comment]
We can implement something similar as we did for console, passing the env variables from minio https://github.com/minio/minio/pull/18631.

**Comment by cesnietor** [comment]
closing this since operator ui has been deprecated, see https://github.com/minio/operator/blob/master/docs/notes/v6.0.0.md#whats-new for more.
