### ISSUE TITLE
v4.5.3 can not  install， state always is -  

### ISSUE THREAD

**Issue by robertluoxu** [minio/operator#1330]
![image](https://user-images.githubusercontent.com/52069259/198820184-d92a3f50-301b-4c22-ad4c-032263d925f1.png)
hi !
Use minio operator + directPV to create a cluster, and use the command:"kubectl minio tenant create minio-tenant-1  --servers    4     --volumes 16     --capacity  1T      --storage-class  directpv-min-io --namespace    minio-ns"   or use minio ui to create a tenant can not be successfully created

version: v4.5.3
kubenetes: v1.24.4

**Comment by robertluoxu** [comment]
E1030 00:14:22.936709       1 operator.go:235] Unexpected error during the creation of the csr/operator-minio-operator-csr: timeout during certificate fetching of csr/operator-minio-operator-csr
I1030 00:14:22.936748       1 operator.go:96] Waiting for the operator certificates to be issued timeout during certificate fetching of csr/operator-minio-operator-csr
I1030 00:14:32.949137       1 operator.go:94] operator TLS secret not found: secrets "operator-tls" not found
I1030 00:14:32.970820       1 operator.go:94] operator TLS secret not found: secrets "operator-tls" not found
I1030 00:14:32.984335       1 csr.go:183] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s
E1030 00:34:32.996723       1 operator.go:235] Unexpected error during the creation of the csr/operator-minio-operator-csr: timeout during certificate fetching of csr/operator-minio-operator-csr
I1030 00:34:32.996781       1 operator.go:96] Waiting for the operator certificates to be issued timeout during certificate fetching of csr/operator-minio-operator-csr
I1030 00:34:43.008389       1 operator.go:94] operator TLS secret not found: secrets "operator-tls" not found
I1030 00:34:43.033735       1 operator.go:94] operator TLS secret not found: secrets "operator-tls" not found
I1030 00:34:43.056808       1 csr.go:183] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s
E1030 00:54:43.081155       1 operator.go:235] Unexpected error during the creation of the csr/operator-minio-operator-csr: timeout during certificate fetching of csr/operator-minio-operator-csr
I1030 00:54:43.081201       1 operator.go:96] Waiting for the operator certificates to be issued timeout during certificate fetching of csr/operator-minio-operator-csr
I1030 00:54:53.095931       1 operator.go:94] operator TLS secret not found: secrets "operator-tls" not found
I1030 00:54:53.118317       1 operator.go:94] operator TLS secret not found: secrets "operator-tls" not found
I1030 00:54:53.141763       1 csr.go:183] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s

**Comment by cesnietor** [comment]
please try with latest operator 5.0.10+ and reopen if the issue persists.
