### ISSUE TITLE
MinIO Operator "remote error: tls: bad certificate"

### ISSUE THREAD

**Issue by chris93111** [minio/operator#1331]
Hello my operator minio loop with error "remote error: tls: bad certificate"
in logs of master Post "https://minio-operator-service.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.minio-operator.svc, operator.minio-operator.svc.cluster.local, not minio-operator-service.minio-operator.svc; reinitializing...

## Steps to Reproduce (for bugs)
deploy minio operator 4.5.1 with olm on k3s
deploy one tenant
get the logs

## Your Environment
k3s 1.24.7
minio operator 4.5.1
Rhel7.9
install via olm with groups operator 

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: minio-operator
  labels:
    operators.coreos.com/minio-operator.minio-operator: ''
spec:
  channel: stable
  installPlanApproval: Manual
  name: minio-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: minio-operator.v4.5.1
```

**Comment by dvaldivia** [comment]
what is looping the Tenant? that sounds like the MinIO Operator didn't got setup properly if the `minio-operator` service is missing.

you mentioned `4.3.1` in your environment, but the logs mention `4.5.1`.

Can you share the list of services for the `minio-operator` namespace? or wherever the MinIO Operator installed

**Comment by chris93111** [comment]
@dvaldivia  The service is present but the csr not contain the minio-operator-svc

kubectl describe csr operator-minio-operator-csr
Name:               operator-minio-operator-csr
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Mon, 31 Oct 2022 13:10:12 +0100
Requesting User:    system:serviceaccount:minio-operator:minio-operator
Signer:             kubernetes.io/kubelet-serving
Status:             Approved,Issued
Subject:
  Common Name:    system:node:operator.minio-operator.svc
  Serial Number:  
  Organization:   system:nodes
Subject Alternative Names:
         DNS Names:  operator
                     operator.minio-operator.svc
                     operator.minio-operator.svc.cluster.local

**Comment by dvaldivia** [comment]
the CSR resource gets cleared up automatically after some time, yours seems to be issued, so I don't think that is the problem, what are the logs for the Operator Pod that is acting as the leader?

**Comment by chris93111** [comment]
I do not thinks so, the operator-tls is gen with csr, so i used with target minio-operator-service.minio-operator.svc but is not in DNS Name of cert 

2022/11/01 13:02:12 http: TLS handshake error from 10.42.14.0:53952: remote error: tls: bad certificate
2022/11/01 13:02:12 http: TLS handshake error from 10.42.0.0:46840: remote error: tls: bad certificate
2022/11/01 13:02:13 http: TLS handshake error from 10.42.14.0:53958: remote error: tls: bad certificate
2022/11/01 13:02:13 http: TLS handshake error from 10.42.0.0:46842: remote error: tls: bad certificate
2022/11/01 13:02:14 http: TLS handshake error from 10.42.14.0:53960: remote error: tls: bad certificate
2022/11/01 13:02:14 http: TLS handshake error from 10.42.0.0:46844: remote error: tls: bad certificate
2022/11/01 13:02:15 http: TLS handshake error from 10.42.14.0:53962: remote error: tls: bad certificate
2022/11/01 13:02:15 http: TLS handshake error from 10.42.0.0:46846: remote error: tls: bad certificate
2022/11/01 13:02:16 http: TLS handshake error from 10.42.14.0:53964: remote error: tls: bad certificate
2022/11/01 13:02:16 http: TLS handshake error from 10.42.0.0:46852: remote error: tls: bad certificate
2022/11/01 13:02:17 http: TLS handshake error from 10.42.14.0:53972: remote error: tls: bad certificate
2022/11/01 13:02:17 http: TLS handshake error from 10.42.0.0:46854: remote error: tls: bad certificate
2022/11/01 13:02:18 http: TLS handshake error from 10.42.14.0:53976: remote error: tls: bad certificate
2022/11/01 13:02:18 http: TLS handshake error from 10.42.0.0:46856: remote error: tls: bad certificate
2022/11/01 13:02:19 http: TLS handshake error from 10.42.14.0:53978: remote error: tls: bad certificate
2022/11/01 13:02:19 http: TLS handshake error from 10.42.0.0:46858: remote error: tls: bad certificate
2022/11/01 13:02:20 http: TLS handshake error from 10.42.14.0:53980: remote error: tls: bad certificate
2022/11/01 13:02:20 http: TLS handshake error from 10.42.0.0:46868: remote error: tls: bad certificate
2022/11/01 13:02:21 http: TLS handshake error from 10.42.14.0:53986: remote error: tls: bad certificate
2022/11/01 13:02:21 http: TLS handshake error from 10.42.0.0:46874: remote error: tls: bad certificate
```

```
Nov 01 14:02:45 cfg01-master-awx k3s[129356]: E1101 14:02:45.920161  129356 cacher.go:424] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.minio-operator.svc, operator.minio-operator.svc.cluster.local, not minio-operator-service.minio-operator.svc; reinitializing...
Nov 01 14:02:46 cfg01-master-awx k3s[129356]: W1101 14:02:46.925225  129356 reflector.go:324] storage/cacher.go:/minio.min.io/tenants: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.minio-operator.svc, operator.minio-operator.svc.cluster.local, not minio-operator-service.minio-operator.svc
Nov 01 14:02:46 cfg01-master-awx k3s[129356]: E1101 14:02:46.925251  129356 cacher.go:424] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.minio-operator.svc, operator.minio-operator.svc.cluster.local, not minio-operator-service.minio-operator.svc; reinitializing...
```

```
[chris@~ ] $ kubectl get svc -n minio-operator
NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
console                  ClusterIP   10.43.99.161   <none>        9090/TCP,9443/TCP   4d1h
minio-operator-service   ClusterIP   10.43.9.121    <none>        4222/TCP            4m13s
operator                 ClusterIP   10.43.149.54   <none>        4222/TCP,4221/TCP   4d1h
[chris@~ ] $
```

**Comment by little-guy-lxr** [comment]
the same problem

W1111 07:31:50.195896       1 reflector.go:324] storage/cacher.go:/minio.min.io/tenants: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.operators.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.operators.svc, operator.operators.svc.cluster.local, not minio-operator-service.operators.svc
E1111 07:31:50.195934       1 cacher.go:424] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.operators.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.operators.svc, operator.operators.svc.cluster.local, not minio-operator-service.operators.svc; reinitializing..

operator version:  4.4.28

**Comment by xrafhue** [comment]
Same issue here using k3d 
k3S : rancher/k3s:v1.21.12-k3s1 or rancher/k3s:v1.21.14-k3s1
Minio Operator : v4.4.11

When i apply the workaround  of @aceeric's comment (thanks to him!) ---> [#860](https://github.com/minio/operator/issues/860#issuecomment-937898193)

**It's work for me !**
```
apiVersion: k3d.io/v1alpha4
kind: Simple
[...]
options:
  k3s:
    extraArgs:
      - arg: --kube-controller-manager-arg=cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt
        nodeFilters:
          - server:*
      - arg: --kube-controller-manager-arg=cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key
        nodeFilters:
          - server:*
```
In the K3S release v1.21.14's code source, the client CA is used instead of the server CA:
[server.go#L118](https://github.com/k3s-io/k3s/blob/982252d747f7e50701da7052383d9fd788d2b20e/pkg/daemons/control/server.go#L118
```
		"cluster-signing-legacy-unknown-cert-file":        runtime.ClientCA,
		"cluster-signing-legacy-unknown-key-file":         runtime.ClientCAKey,
```



)

**Comment by chris93111** [comment]
My k3s is 1.24.6 and the problem is present , the probleme is not the ca but service declared in csr

**Comment by xrafhue** [comment]
@chris93111 , in few week will upgrade our k3s version what do you mean about the service please ?

**Comment by chris93111** [comment]
@xrafhue the operator webhook is contacted with https://minio-operator-service.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s but in csr they are operator.minio-operator.svc.cluster.local 
so response is x509: certificate is valid for operator, operator.minio-operator.svc, operator.minio-operator.svc.cluster.local, not minio-operator-service.minio-operator.svc

**Comment by chris93111** [comment]
work correctly with new update https://github.com/minio/operator/pull/1383 

thanks
