### ISSUE TITLE
[bug] ensure non-empty $HOME in deployments

### ISSUE THREAD

**Issue by Privatecoder** [minio/operator#1337]
## Expected Behavior
Always ensure non-empty `$HOME` in deployments

## Current Behavior
- `$HOME` in `minio-operator` and `console`-pods is empty when using `crun` as `containerd`-runtime, i.e. `echo $HOME` => empty.
- The `operator` called pod with the `minio/console`-image therefore gets stuck in crash-loop after installing with an error-msg `console: <ERROR> Unable to get mcConfigDir. exit status 2.`.
- All tenant-pods created successively crash as well due to the same issue.
- Other containers, `nginx` for example, have env-vars set correctly, i.e. not empty `echo $HOME` => `/root`.

## Possible Solution
Ensure `$HOME` is not empyty

## Steps to Reproduce (for bugs)
Deploy minio-operator through krew or helm on a K8s v1.24.7 cluster with containerd 1.6.9 / crun 1.6

## Your Environment
* minio-operator (tested) 4.4.28, 4.5.1, 4.5.2, 4.5.3, 4.5.4
* kubernetes v1.24.7
* containerd 1.6.9 with crun 1.6

**Comment by Privatecoder** [comment]
I deployed sample pods, pods through deployments and even a test hello-world helm-chart to check if the required `HOME` env was set and this **has been the case** in **all** test-scenarios.

**Comment by Privatecoder** [comment]
This might be an issue with [crun](https://github.com/containers/crun/issues/108) which was closed in 2019 however it still seems to be an issue as I also found [this](https://github.com/cilium/cilium/issues/14301).

**Comment by Privatecoder** [comment]
With `runc` as  as `containerd` runtime `$HOME` is present so this indeed is an issue with `crun` however minio should still ensure its presence.

I created a new `runc` `RuntimeClass` and modified the operators and consoles helm-chart to enable passing `runtimeClassName` and _work around_ the issue.

**Comment by Privatecoder** [comment]
This does not set the `runtimeClassName` of a tenants `minio/minio` container however so it only works for the `operator` and `console` deployments deployed by the chart.

**Comment by dvaldivia** [comment]
will making `runtimeClassName` configurable on Tenant fix this problem?

**Comment by allanrogerr** [comment]
@Privatecoder Please confirm @dvaldivia 's proposal above

**Comment by Privatecoder** [comment]
@allanrogerr @dvaldivia

this will probably work however it would still be a workaround as changing the runtime class for a specific deployment is not always an option.

A fix would require to ensure a non-empty `$HOME env`

**Comment by allanrogerr** [comment]
I'm not sure that I'm following. The helm charts for tenant already contain runtimeClassName. 

1. Using ```runtimeClassName: runc``` allows the tenant nodes to come online successfully.
2. Switching to ```runtimeClassName: crun``` causes the tenant pods the throw the error ```<ERROR> Unable to get mcConfigDir. exit status 2```.

This looks like a crun issue still. The ```$HOME``` environment variable was consistently populated when doing this test - it never became empty during the above test. I'm investigating a bit further.

Could you clarify if you prefer if minio pods don't start up if there is no ```$HOME``` environment variable set? Ideally all users have ```$HOME``` set.

Also based on the conversation up to now we have these below options. I'm also looking into these now

- The helm charts for operator/console do not yet contain runtimeClassName. This can be added.
- We can also add the ability to set the runtimeClassName of a tenant in the UI.

**Comment by Privatecoder** [comment]
Following my post [here](https://github.com/minio/operator/issues/1337#issuecomment-1304219129) I found, that the issue was fixed for podman like [this](https://github.com/containers/podman/pull/9399/files).

So _This looks like a crun issue still._ is obviously the case we should still make sure that `$HOME` is never empty anyway.

Adding a configurable `runtimeClassName` for the Operator and in the UI for the tenants will allow users to _workaround_ the issue however I'd prefer a solid fix if this would be a _chose any of the two options_.

**Comment by dvaldivia** [comment]
@Privatecoder isn't this missing `$HOME` variable something that can be set on the `minio-operator` and `console` deployment on a per-need basis?

**Comment by Privatecoder** [comment]
@dvaldivia I came across this issue when I tried to deploy MinIO to a new cluster which was using `crun` as `containerd-runtime` and therefore crashed with the mentioned error-message.

As I could not figure out what the issue was initially I was glad to solve this eventually with some help.

Digging into this I found other threads such as the – also mentioned – podman-issue-thread.

After fixing the operator and console by making the `runtimeClassName` configurable I ended up with non-working tenants for the very same reason..(of course one could go ahead and fix this manually all the time).

However & to sum it up:

Imho one would expect to be able to deploy a chart without manually fixing env-vars (other deployments have `$HOME` set in `crun` environments) or changing the `runtimeClass`.

I also think that since this might be an easy fix, MinIO should incorporate something similar to the fix [here](https://github.com/containers/podman/pull/9399/files) (or others).

**Comment by dvaldivia** [comment]
we were able to replicate the issue, @allanrogerr will send a fix for tenants in the particular case of `crun` runtime, but as for the deployments for `minio-operator` and `console` on the `minio-operator` namespace I'm wondering if it's worth adding HOME to the deployments themselves or if this is something the administrators can fix when they are installing the Operator

**Comment by Privatecoder** [comment]
Like I wrote: If the `minio-operator` and  `console` rely on it than we should at least name it in the docs however I would suggest fixing it like for the tenants.

**Comment by dvaldivia** [comment]
sure, let's document this @allanrogerr

**Comment by cniackz** [comment]
It will be fixed in https://github.com/minio/operator/pull/1381

**Comment by allanrogerr** [comment]
Added to UI in https://github.com/minio/console/pull/2626
All outstanding requests addressed.

**Comment by pitwegner** [comment]
Don't want to resurrect old issues, but this is still an issue for crun execution. I don't have an alternative runtime class available in my cluster. Setting the HOME env var manually does not work, as in the tenant I cannot add env vars to all init containers. Also, building my own image, added just with an `ENV HOME=/root`, does not work, as again there is no field in the tenant to replace the operator image for init containers.
