### ISSUE TITLE
kubeconfig flag not working

### ISSUE THREAD

**Issue by astingengo** [minio/operator#1361]
version that I'm using is 4.5.4

If running `kubectl-minio_4.5.4_linux_amd64 --kubeconfig <file> init` it will ignore my --kubeconfig file and it will say
`The connection to the server localhost:8080 was refused - did you specify the right host or port?`

**Comment by pjuarezd** [comment]
this sounds like your local kubernetes API is not available, make sure it is running in localhost:8080 and that is correctly configured in the `server` field of your ~.kube/config file

**Comment by astingengo** [comment]
I already tried that hopping it will do the trick but the result was same

**Comment by astingengo** [comment]
I think it is ignored on tenant commands as well
