### ISSUE TITLE
error: no kind "Tenant" is registered for version "minio.min.io/v2" in scheme "pkg/scheme/scheme.go:28"

### ISSUE THREAD

**Issue by 631068264** [minio/operator#1365]
## Current Behavior

 
Get error
```
kubectl logs -f tenant.minio.min.io/storage  -n minio-tenant
error: no kind "Tenant" is registered for version "minio.min.io/v2" in scheme "pkg/scheme/scheme.go:28"
```
## Steps to Reproduce (for bugs)

```
helm install minio-operator  minio-operator-4.3.7.tgz -n minio-operator --create-namespace
```
After install minio operator，then deploy Tenant  use [example](https://github.com/minio/operator/blob/master/examples/kustomization/tenant-lite/tenant.yaml)

But get crd
```
kubectl get crd |grep minio
tenants.minio.min.io                                  2022-12-09T02:03:30Z
```

## Your Environment

* Version used (`minio-operator`): v4.3.7 
* Environment name and version (e.g. kubernetes v1.17.2): v1.19.6
* Server type and version:  Centos7
* Operating System and version (`uname -a`):  Linux server-44904695-b3bc-4721-8bad-725d6497a69a 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:

**Comment by dvaldivia** [comment]
hi @631068264 that version of the operator is slightly outdated, could you try with `v4.5.5` which is the latest?

Tenant v2 was introduced in operator `v4` so it should be available unless you are upgrading

**Comment by dvaldivia** [comment]
@631068264 yesh, we moved from the single chart and introduced two separate charts `minio/operator` and `minio/tenant` beginning with `v4.4.0` I believe
