### ISSUE TITLE
 error copying from remote stream to local connection: readfrom tcp4 192.168.229.131:9090->192.168.229.1:55993: write tcp4 192.168.229.131:9090->192.168.229.1:55993: write: broken pipe

### ISSUE THREAD

**Issue by 13567436138** [minio/operator#1400]
## Current Behavior

```
Forwarding from 0.0.0.0:9090 -> 9090
Handling connection for 9090
Handling connection for 9090
Handling connection for 9090
Handling connection for 9090
Handling connection for 9090
E0115 18:36:58.229201  892890 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 192.168.229.131:9090->192.168.229.1:55993: write tcp4 192.168.229.131:9090->192.168.229.1:55993: write: broken pipe
Handling connection for 9090
Handling connection for 9090
E0115 18:37:28.230056  892890 portforward.go:340] error creating error stream for port 9090 -> 9090: Timeout occurred
Handling connection for 9090
E0115 18:37:47.966518  892890 portforward.go:340] error creating error stream for port 9090 -> 9090: Timeout occurred
E0115 18:37:58.235252  892890 portforward.go:340] error creating error stream for port 9090 -> 9090: Timeout occurred
Handling connection for 9090
Handling connection for 9090
E0115 18:38:33.302007  892890 portforward.go:340] error creating error stream for port 9090 -> 9090: Timeout occurred
Handling connection for 9090
E0115 18:38:43.172043  892890 portforward.go:340] error creating error stream for port 9090 -> 9090: Timeout occurred
Handling connection for 9090
E0115 18:39:03.305219  892890 portforward.go:340] error creating error stream for port 9090 -> 9090: Timeout occurred
Handling connection for 9090
E0115 18:39:18.685441  892890 portforward.go:340] error creating error stream for port 9090 -> 9090: Timeout occurred
```
## Steps to Reproduce (for bugs)

1.kubectl minio proxy -n minio-operator 
2.brower http://192.168.229.131:9090/login
3.
4.

## Your Environment

* Version used (`minio-operator`):v4.5.7
* Environment name and version (e.g. kubernetes v1.17.2):v1.21.0
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
This is not our problem, looks like a kubectl proxy issue.

**Comment by mkubenka** [comment]
I'm getting exact same error on OpenShift cluster (4.10.47), interestingly it works fine with `minio-operator` version 4.5.5

**Comment by fawzy-ibrhim** [comment]
I'm getting the same error with local Kubernetes cluster: 

- Version used (minio-operator): **v4.5.7** and **v4.5.5**
- Environment name and version: **v1.25.5**
- Server type and version: **3 VM running on KVM**
- Operating System and version (uname -a): **Ubuntu Server 22.04 with kernel version 5.15.0-58-generic**

`$ kubectl --namespace minio-operator logs deployments.apps/console 
Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system
Serving operator at http://[::]:9090`

**Comment by m3talstorm** [comment]
Same here

**Comment by fawzy-ibrhim** [comment]
@harshavardhana you may be right: https://github.com/kubernetes/kubernetes/issues/74551

I used the below work around to access the console by creating nodePort as:

```
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  namespace: minio-operator 
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    nodePort: 32090
  selector:
    app: console
  type: NodePort
```

But when I upload a file to a tenant, the browser keeps rounding and not displaying any uploaded object but when I check with `mc` client, the file is there.

**Comment by bebosudo** [comment]
"Solved" by defining an ingress in front of the `console` service (had to edit the service first to change it into become a NodePort since we're on AWS, and ingresses only work with NodePorts)
