### ISSUE TITLE
Crashloop updating to version 4.5.8

### ISSUE THREAD

**Issue by jaynakus** [minio/operator#1408]
After upgrading to new version 4.5.8 my tenant is in crashloop. In logs I can see this error
invalid arguments specified cmd/prepare-storage.go:291:cmd.waitForFormatErasure()

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by pjuarezd** [comment]
Please share us details on your environment section
how did you did the install?, krew plugin, kubectl apply?, helm chart?
Which container is showing that error message: operator, console, minio, log search api, mc?
