### ISSUE TITLE
kubectl-minio_linux_amd64.zip renamed to kubectl-minio_linux_amd64_v1.zip in v4.5.8 release

### ISSUE THREAD

**Issue by datosh** [minio/operator#1410]
## Expected Behavior

```sh
wget -q https://github.com/minio/operator/releases/latest/download/kubectl-minio_linux_amd64.zip
```

## Current Behavior

Download fails, since file was renamed to `kubectl-minio_linux_amd64_v1.zip` in v4.5.8.

## Possible Solution

Rename (or duplicate) file in v4.5.8 release to match naming convention.

## Steps to Reproduce (for bugs)

1. `wget -q https://github.com/minio/operator/releases/latest/download/kubectl-minio_linux_amd64.zip`
2. => HTTP 404

**Comment by harshavardhana** [comment]
why are you manually downloading this manually? @datosh you need to use `kubectl krew upgrade` https://github.com/kubernetes-sigs/krew-index/pull/2879/files
