### ISSUE TITLE
postgres log pod does not start under restricted pod security standards

### ISSUE THREAD

**Issue by stymp** [minio/operator#1416]
When creating a tenant in a namespace enforcing restricted pod security standards, the tenant does not reach initialized state. This is due to log db pods not starting. The log db statefulset is attempting to run the postgres-init-chown-data init container as root which is blocked by the Pod Security Admission controller. 

## Expected Behavior
Log db pod starts, completing initialization of the tenant. 

## Current Behavior
Log db pod does not start. 

## Steps to Reproduce (for bugs)
1. Run on k8s 1.22+. I am running on k8s 1.25.
2. Enforce restricted pod security standards on a namespace. 
3. Deploy tenant into the namespace with restricted pod security standards. 

## Your Environment

* Version used (`minio-operator`): 4.5.8
* Environment name and version (e.g. kubernetes v1.17.2): 1.25.5

**Comment by allanrogerr** [comment]
To avoid this sort of issue due to additional deployments, Log Search was removed from the CRD from v5.0.0 See https://github.com/minio/operator/blob/v5.0.0/UPGRADE.md.

Please maintain a standalone deployment and upgrade to >v5.0.0. This was the minio tenant is not blocked from starting up.

**Comment by allanrogerr** [comment]
@stymp Were you able to progress with the above suggestion?

**Comment by allanrogerr** [comment]
Closing due to lack of input from user for over 1 week.
