### ISSUE TITLE
unable to create certs CA directory in console logs

### ISSUE THREAD

**Issue by marccampbell** [minio/operator#1430]
When the console pod starts, it logs:

```
E: 2023/02/02 14:37:52 Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system
Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system
```

I don't know if this is the cause, but it prevents the console from loading. The login page shows a spinner.
I suspect this error should not be present, but not sure how to resolve it.

## Expected Behavior
Not erroring about a read only filesystem when following the normal "happy path" instructions.

## Steps to Reproduce (for bugs)
1. `kubectl minio init` (no extra flags or anything, this is a new cluster)
2. View the logs

## Your Environment
`kubectl minio version`: v4.5.8
Kubernetes version v1.26.0
K8s installed via: kubeadm (bare metal cluster)
Running on CentOS 8 stream
uname -a: `Linux worker-02 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pjuarezd** [comment]
this error only indicates that the secret `console-sa-secret` do not exists.

This secret containis a tls secret and key for the console to use in TLS, when no present cosole starts anyways in the http 9090 port.

```
E: 2023/02/02 22:13:05 Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system
Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system

Serving operator at http://[::]:9090
```

If you see that message `Serving operator at http://[::]:9090` in the log, the console pod started properly.

This is probably the cause of console login "spinner" https://github.com/minio/operator/issues/1400

**Comment by pjuarezd** [comment]
Looking for ways to make it more clear if Operator console has https enabled or not

**Comment by harshavardhana** [comment]
This is fixed in MinIO @pjuarezd in RELEASE.2023-03-09T23-16-13Z 

```
commit 72e521284290e7658257ce9134d947f0bf3b23d8
Author: Harshavardhana <harsha@minio.io>
Date:   Mon Mar 6 08:56:29 2023 -0800

    fix: handle syscall.EROFS also for osIsPermission() (#16765)
```

**Comment by houshym** [comment]
I have the same issue and I could not figure it out
