### ISSUE TITLE
Add way to specify PVC labels

### ISSUE THREAD

**Issue by pschichtel** [minio/operator#1444]
**Is your feature request related to a problem? Please describe.**
The chart currently severely restricts what can be configured in the volumeClaimTemplate. In particular I'm interested in the PVC labels in order to exclude minio's data volumes from velero's volume backups, which it uploads into that very same minio tenant.

**Describe the solution you'd like**
Allow configuring the PVC labels in this chart

**Describe alternatives you've considered**
I'm able to manually patch the PVC for the time being

**Comment by pschichtel** [comment]
It is still not possible to configure PVC labels as far as I am aware

**Comment by cesnietor** [comment]
we'll discuss internally if we need to support this.

**Comment by pschichtel** [comment]
@jiuker has this always been there? I don't currently have a test setup where I could quickly test this and it doesn't seem to get applied to existing PVCs, but if you can say this would be applied to a new PVC then I would be perfectly fine with closing this issue.

**Comment by jiuker** [comment]
> @jiuker has this always been there? I don't currently have a test setup where I could quickly test this and it doesn't seem to get applied to existing PVCs, but if you can say this would be applied to a new PVC then I would be perfectly fine with closing this issue.

I had test it. That's fine to label them. @pschichtel
