### ISSUE TITLE
When number of tenant pods exceeds 24, it causes crashloopback in minio pods during startup

### ISSUE THREAD

**Issue by mshanmu** [minio/operator#1459]
When the number of tenant pods increases beyond 24, the [GetenvHandler](https://github.com/minio/operator/blob/v4.5.8/pkg/controller/cluster/http_handlers.go#L133)  - GET /webhook/v1/getenv/{namespace}/{name}?key={env}, starts failing with "net/http: timeout awaiting response headers", because it takes more than 3 seconds to respond.

This causes the minio pods to go into crashloopback during startup and takes anywhere from 10 - 20 minutes to stabilize, requiring manual intervention, especially with the exponential backoffs.

I saw this behavior in two different scenarios,
1. MinIO image upgrade
2. Adding a new server pool 

## Expected Behavior

No crashloopback in MinIO pods

## Current Behavior

During startup, MinIO pods go into crashloopback for 10 - 20 minutes.

## Possible Solution

Either of the below solutions,

1. Increase the response timeout from 3 seconds to higher number may be 30 seconds. Also, the cancellation context time from 3.5 to 30 seconds as well.
2. Fix GetenvHandler() handler to respond within 3 seconds by caching the results, since for a tenant it is going to be same answer.

## Steps to Reproduce (for bugs)

Real scenario,
1. Create 3 server pools (4 pod, 4 pod, 8 pod)
3. Expand with 16 server pods
4. Notice the 8 out of 16 server pods are in crashloopback for some time with the below error,
5. "Get https://<url>:4222/webhook/v1/getenv/<namespace>/<namespace>?keys=MINIO_ARGS: net/http: timeout awaiting response headers"

## Context

After expanding to 32 pods, took long time to initialize and another problem I saw was cluster state was not properly synced with all server pools, thereby, "NoSuchKey" errors were thrown. Doing a "mc admin service restart" fixed it.

## Regression

No idea

## Your Environment

* Version used (`minio-operator`): v4.5.5 (the latest version v4.5.8 has the same code)
* Environment name and version (e.g. kubernetes v1.17.2): k8s v1.24
* Server type and version: Linux
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by mshanmu** [comment]
I have a easy repro using the code from https://github.com/minio/pkg/blob/main/env/web_env.go#L73,

1. Compile the attached golang code 
2. Copy the binary into minio pod (cat <binary> | k -n minio-tenant-1 exec -i minio-tenant-1-ss-1-0 -- tee /tmp/jwt-sign > /dev/null
3. Run the binary, like below,
4. bash-4.4$ ./jwt-sign 32 <username> <password> <envurl>
``
Start test
SUCCESS Response, Routine: 11 response time:29.11219ms
SUCCESS Response, Routine: 13 response time:29.123135ms
SUCCESS Response, Routine: 6 response time:30.829137ms
SUCCESS Response, Routine: 24 response time:32.666726ms
SUCCESS Response, Routine: 22 response time:29.751816ms
SUCCESS Response, Routine: 26 response time:30.800492ms
SUCCESS Response, Routine: 9 response time:32.776521ms
SUCCESS Response, Routine: 16 response time:34.599598ms
SUCCESS Response, Routine: 12 response time:34.638116ms
SUCCESS Response, Routine: 2 response time:34.926317ms
SUCCESS Response, Routine: 28 response time:226.701653ms
SUCCESS Response, Routine: 15 response time:427.193584ms
SUCCESS Response, Routine: 4 response time:629.773898ms
SUCCESS Response, Routine: 5 response time:830.591031ms
SUCCESS Response, Routine: 10 response time:1.025543396s
SUCCESS Response, Routine: 20 response time:1.226065703s
SUCCESS Response, Routine: 8 response time:1.428548736s
SUCCESS Response, Routine: 14 response time:1.627454515s
SUCCESS Response, Routine: 31 response time:1.828381195s
SUCCESS Response, Routine: 29 response time:2.031401485s
SUCCESS Response, Routine: 23 response time:2.231188868s
SUCCESS Response, Routine: 17 response time:2.426465346s
SUCCESS Response, Routine: 3 response time:2.632242473s
SUCCESS Response, Routine: 0 response time:2.831680136s
FAILED Response, Routine: 19 response time: 3.020831986s err: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-tenant-1/minio-tenant-1?key=MINIO_ARGS": net/http: timeout awaiting response headers
FAILED Response, Routine: 18 response time: 3.021367215s err: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-tenant-1/minio-tenant-1?key=MINIO_ARGS": net/http: timeout awaiting response headers
FAILED Response, Routine: 30 response time: 3.021148618s err: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-tenant-1/minio-tenant-1?key=MINIO_ARGS": net/http: timeout awaiting response headers
FAILED Response, Routine: 27 response time: 3.021773777s err: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-tenant-1/minio-tenant-1?key=MINIO_ARGS": net/http: timeout awaiting response headers
FAILED Response, Routine: 21 response time: 3.025445975s err: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-tenant-1/minio-tenant-1?key=MINIO_ARGS": net/http: timeout awaiting response headers
FAILED Response, Routine: 1 response time: 3.025291646s err: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-tenant-1/minio-tenant-1?key=MINIO_ARGS": net/http: timeout awaiting response headers
FAILED Response, Routine: 7 response time: 3.024802848s err: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-tenant-1/minio-tenant-1?key=MINIO_ARGS": net/http: timeout awaiting response headers
FAILED Response, Routine: 25 response time: 3.021809708s err: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-tenant-1/minio-tenant-1?key=MINIO_ARGS": net/http: timeout awaiting response headers
Done
bash-4.4$ 
``

**Comment by mshanmu** [comment]
source code
```
ackage main
import (
    "fmt"
    "time"
    "context"
    "net"
    "net/http"
    "crypto/x509"
    "io/ioutil"
    "crypto/tls"
    "os"
    "strconv"
    "sync"
    "path/filepath"
    "github.com/lestrrat-go/jwx/jwa"
    "github.com/lestrrat-go/jwx/jwk"
    "github.com/lestrrat-go/jwx/jwt"
)

var (
    rootCAs *x509.CertPool
    wg sync.WaitGroup
    username string
    password string
    envKey = "MINIO_ARGS"
    envURL string
)

func requestMO(routine int) {
    ctx, cancel := context.WithTimeout(context.Background(), 6500*time.Millisecond)
    defer cancel()

    defer wg.Done()


    req, err := http.NewRequestWithContext(ctx, http.MethodGet, envURL+"?key="+envKey, nil)
    if err != nil {
        fmt.Printf("http.NewRequestWithContext() err:%v\n", err)
        return
    }

    skey, err := jwk.New([]byte(password))
    if err != nil {
        fmt.Printf("jwk.New() err:%v\n", err)
        return
    }

    skey.Set(jwk.AlgorithmKey, jwa.HS512)
    skey.Set(jwk.KeyIDKey, "minio")

    token := jwt.New()
    t := time.Now().Add(15 * time.Minute)
    if err = token.Set(jwt.IssuerKey, username); err != nil {
        fmt.Printf("token.Set(jwt.Issuerkey) err:%v\n", err)
        return
    }

    if err = token.Set(jwt.SubjectKey, envKey); err != nil {
        fmt.Printf("token.Set(jwt.Subjectkey) err:%v\n", err)
        return
    }

    if err = token.Set(jwt.ExpirationKey, t.Unix()); err != nil {
        fmt.Printf("token.Set(jwt.ExpirationKey) err:%v\n", err)
        return
    }

    signed, err := jwt.Sign(token, jwa.HS512, skey)
    if err != nil {
        fmt.Printf("jwt.Sign err:%v\n", err)
        return
    }

    //fmt.Printf("Authorization: Bearer %s\n",string(signed))

    req.Header.Set("Authorization", "Bearer "+string(signed))

    clnt := &http.Client{
        Transport: &http.Transport{
            Proxy: http.ProxyFromEnvironment,
            DialContext: (&net.Dialer{
                Timeout:   3 * time.Second,
                KeepAlive: 5 * time.Second,
            }).DialContext,
            ResponseHeaderTimeout: 3 * time.Second,
            TLSHandshakeTimeout:   3 * time.Second,
            ExpectContinueTimeout: 3 * time.Second,
            TLSClientConfig: &tls.Config{
                RootCAs: rootCAs,
            },
            // Go net/http automatically unzip if content-type is
            // gzip disable this feature, as we are always interested
            // in raw stream.
            DisableCompression: true,
                                                                                                                                                                            },
    }

    startTime := time.Now()
    resp, err := clnt.Do(req)
    endTime := time.Now()
    elapsed := endTime.Sub(startTime)
    if err != nil {
        fmt.Printf("FAILED Response, Routine: %d response time: %v err: %v\n", routine, elapsed, err)
        return
    }

    _, err = ioutil.ReadAll(resp.Body)
    if err != nil {
        fmt.Printf("ioutil.ReadAll() err:%v\n", err)
        return
    }

    fmt.Printf("SUCCESS Response, Routine: %d response time:%v\n", routine, elapsed)
}

func main() {
    fmt.Println("Start test")
    numRoutines := 16
    if len(os.Args) > 1 {
        var err error
        numRoutines, err = strconv.Atoi(os.Args[1])
        if err != nil {
            fmt.Printf("Invalid numRoutines(%s) err:%v\n", os.Args[1], err)
            return
        }
    }

    username = ""
    password = ""
    envURL = ""

    if len(os.Args) > 2 {
        username = os.Args[2]
    }

    if len(os.Args) > 3 {
        password = os.Args[3]
    }

    if len(os.Args) > 4 {
        envURL = os.Args[4]
    }

    if username == "" || password == "" || envURL == "" {
        fmt.Printf("Missing required parameters: Usage: %s <num concurrent requests> <username> <password> <env URL>\n", os.Args[0])
        return
    }

    rootCAs = x509.NewCertPool()

    f, err := os.Open("/tmp/certs/CAs")
    if err != nil {
        fmt.Printf("Cannot open cert directory, err:%v\n", err)
        return
    }

    defer f.Close()

    _, err = f.Stat()
    if err != nil {
        fmt.Printf("Cannot stat cert directory, err:%v\n", err)
        return
    }

    files, err := f.Readdirnames(0)
    if err != nil {
        fmt.Printf("Read directories, err:%v\n", err)
        return
    }
   for _, file := range files {
        bytes, err := ioutil.ReadFile(filepath.Join("/tmp/certs/CAs", file))
        if err == nil { // ignore files which are not readable.
            rootCAs.AppendCertsFromPEM(bytes)
        }
    }

    wg.Add(numRoutines)
    for i := 0; i <numRoutines; i++ {
        go requestMO(i)
    }

    wg.Wait()

    fmt.Println("Done")
}

```

**Comment by cniackz** [comment]
`MINIO_ARGS` is no longer directly provided by the Operator. As of version 5.x.x, a sidecar container now handles this functionality. Please attempt this operation again using the newer version of the Operator.
