### ISSUE TITLE
Publishing events to kafka

### ISSUE THREAD

**Issue by ivanovpavel1983** [minio/operator#1502]
Hello.
Is it possible to enable event publishing to kafka(https://min.io/docs/minio/linux/administration/monitoring/publish-events-to-kafka.html) in minio-tenant?
Is it possible to use SCRAM-SHA-512 authorization? 
How to mount kafka certificate to statefulset?

**Comment by dvaldivia** [comment]
> Is it possible to enable event publishing to kafka(https://min.io/docs/minio/linux/administration/monitoring/publish-events-to-kafka.html) in minio-tenant?
You would have to configure in that in the tenant itself once it comes online.

> Is it possible to use SCRAM-SHA-512 authorization?
I'm not sure MinIO supports that, it'd be better to raise the question at the https://github.com/minio/minio repo

> How to mount kafka certificate to statefulset?
In the UI you can use the `Security` tab to attach additional certificates, alternatively you can create a secret with your certificates, and pass it to the tenant in the way we document it here https://github.com/minio/operator/blob/master/docs/operator-tls.md
