### ISSUE TITLE
Authenticate Tenant with KES using MINIO_KMS_KES_API_KEY env variable

### ISSUE THREAD

**Issue by pjuarezd** [minio/operator#1517]
## Current state
Operator uses a certificate to authenticate himself as a client with KES, 2 things about this certificate:

* Is Issued by k8s  certificate API, or a custom certificate provided in a secret and set in the tenant `spec.externalClientCertSecret ` field
* Is mounted in the tenant Pods

## Desired state

Instead of mount this certificate in the Tenant pods, Operator could set the env variable `MINIO_KMS_KES_API_KEY` and provide an Identity key.

**Describe the solution you'd like**
1 Import [kes-go](https://github.com/minio/kes-go) in Operator
2 [Create a Identity key](https://pkg.go.dev/github.com/minio/kes-go#GenerateAPIKey)
3 Once generated the key, and the corresponding identity,  use the identity in the kes config yaml file
4 Set the key in tenant statefulset with the env variable `MINIO_KMS_KES_API_KEY`

## Resources

[Kes CLI access](https://github.com/minio/kes/wiki/Getting-Started#kes-cli-access)
[kes-go SDK](https://github.com/minio/kes-go)
[Create a Identity key](https://pkg.go.dev/github.com/minio/kes-go#GenerateAPIKey)

Code Snippets provided by @aead 
```go
apiKey, err := kes.GenerateAPIKey(nil)
if err != nil { // todo error handling }

fmt.Println(apiKey.Identity()) // This has to go into the KES config yaml
fmt.Println(apiKey.String())   // This has to go to the application - e.g. MinIO
```
Client 
```go
apiKey, err := kes.ParseAPIKey("...")
if err != nil { // TODO: error handling }

cert, err := kes.GenerateCertificate(apiKey)
if err != nil { // TODO: error handling }

client := kes.NewClient("https://kes.local/", cert)
```

**Comment by allanrogerr** [comment]
This is confirmed possible by setting the variable `MINIO_KMS_KES_API_KEY` and unsetting (setting to "") `MINIO_KMS_KES_CERT_FILE` and `MINIO_KMS_KES_KEY_FILE`.
e.g.
```
MINIO_KMS_KES_API_KEY="kes:v1:ALKGFquybtbl4nCykQJrTLaOZxWS3n7Xv7tdwM3U6V9T"
MINIO_KMS_KES_CERT_FILE=""
MINIO_KMS_KES_KEY_FILE=""
```

Automation will be addressed in a future PR.
