### ISSUE TITLE
minio console from helm operator Post "http://localhost:9000/": dial tcp [::1]:9000: connect: connection refused

### ISSUE THREAD

**Issue by stepanovdg** [minio/operator#1526]
https://github.com/minio/console/issues/2733

Just do helm install minio-operator
Everything is deployed -> trying to login to operator console with admin/
Results in red banner with
```
Post "http://localhost:9000/": dial tcp [::1]:9000: connect: connection refused
in logs
Serving console at http://[::]:9090 ErrorWithContext:Post "http://localhost:9000/": dial tcp [::1]:9000: connect: connection refused %!(EXTRA *errors.errorString=invalid Login)
```

attached to the pod and looks like "/console server" is running but listens only on ipv6 localhost :9090.
```
bash-4.4$ cat /proc/1/net/tcp6 sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode 0: 00000000000000000000000000000000:2382 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000  1000        0 2375640 1 0000000000000000 100 0 0 10 0 bash-4.4$ cat /proc/1/net/tcp  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode                                                      
bash-4.4$ 
```

Tried to change CONSOLE_MINIO_SERVER to http://0.0.0.0:9090/ (to connect to open port) -> got exception S3 API Requests must be made to API port.

running console server in pod result in nothing
```
bash-4.4$ time ./console server

real 0m0.869s
user 0m0.655s
sys 0m0.088s
bash-4.4$ 
```

Is any way to debug why server is not listening on 9000?

## Expected Behavior
Successfully auth to operator console

## Current Behavior
Looks like in  CONSOLE_OPERATOR_MODE : on  console still trying to connect to localhost console server

## Possible Solution
Have no idea.

## Regression
no

## Your Environment
k3s on amd64 nodes

* Version used (`minio-operator`):
OS: linux (amd64)
OS Image: Ubuntu 22.04.2 LTS
Kernel version: 5.15.0-67-generic
Container runtime: containerd://1.6.15-k3s1
Kubelet version: v1.25.6+k3s1

**Comment by dvaldivia** [comment]
Looks like the console is not properly deployed, can you share the deployment yaml?
```bash
kubectl -n minio-operator get deployment console -o yaml
```

**Comment by stepanovdg** [comment]
Hi Daniel,

Please find 
`apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    meta.helm.sh/release-name: minio-operator
    meta.helm.sh/release-namespace: storage
  creationTimestamp: "2023-03-22T05:09:34Z"
  generation: 8
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v4.5.8
    helm.sh/chart: operator-4.5.8
  name: console
  namespace: storage
  resourceVersion: "8392230"
  uid: 6496f125-db9a-49b0-9023-62505117027f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: minio-operator-console
      app.kubernetes.io/name: operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: minio-operator-console
        app.kubernetes.io/name: operator
    spec:
      containers:
      - args:
        - server
        env:
        - name: CONSOLE_OPERATOR_MODE
          value: "on"
        image: minio/console:latest
        imagePullPolicy: IfNotPresent
        name: operator
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 9443
          name: https
          protocol: TCP
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: console-sa
      serviceAccountName: console-sa
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-22T05:09:35Z"
    lastUpdateTime: "2023-03-23T07:27:16Z"
    message: ReplicaSet "console-57d9d99b64" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-27T23:31:24Z"
    lastUpdateTime: "2023-03-27T23:31:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
`

**Comment by dvaldivia** [comment]
@stepanovdg the problem is that you are using `minio/console:latest` which no longer contains the `operator ui` you need to stick to `minio/console:v0.22.5` if you are using MinIO Operator `v4.5.8` or older or upgrade altogether to `v5.0.0` and switch to `minio/operator:latest` image
