### ISSUE TITLE
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value minio operator console

### ISSUE THREAD

**Issue by GenLN** [minio/operator#1534]
## Expected Behavior

Minio Operator Console logging using JWT token should pass login screen and give Console UI.

## Current Behavior

Just loading the page after entered JWT token from "console-sa-secret" and logging this in console pod
"Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value minio operator console"

## Steps to Reproduce (for bugs)

1. helm install minio operator/tenant v5.0.1
2. port-forward 9090 console service
3. enter JWT from console-sa-secret secret file (decoded base64)
4. check logs from pod console

## Your Environment

* Version used (`minio-operator`): v5.0.1
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.24.9
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by dvaldivia** [comment]
@GenLN we are aware of this problem, it's caused by `kubectl port-forward` itself, we already reported this to the kubernetes team

**Comment by dvaldivia** [comment]
I introduced a fix in `v5.0.2` for this, please upgrade and re-open if you are still getting this problem
