### ISSUE TITLE
Tenant while created in operator console generate <tenant>-console and minio services with type LoadBalancer

### ISSUE THREAD

**Issue by stepanovdg** [minio/operator#1536]
## Expected Behavior
Service types created for tenant should be to be configurable - maybe in ui, maybe through operator values.yaml

## Current Behavior
Use operator console to create tenant <tenant-name>
which will generate 
- <tenant-name>-console service
- minio service 
With type Load Balancer which will not work for some bare-metal k8s clusters 

## Possible Solution
- Ability to configure either through UI
- Use service type the same as configured for Operator
- Use separate configuration section for tenants in operator values file

## Steps to Reproduce (for bugs)
helm install minio-operator
create tenant through operator-console 

## Context
Such services are pending - need to be in ClusterIp + Ingress for my case

## Regression
Have no idea (( Just start using minio

## Your Environment
Version used (minio-operator): 5.0.1
OS: linux (amd64)
OS Image: Ubuntu 22.04.2 LTS
Kernel version: 5.15.0-67-generic
Container runtime: containerd://1.6.15-k3s1
Kubelet version: v1.25.6+k3s1

**Comment by dvaldivia** [comment]
@stepanovdg ingress is a particular area where we have decided to stay away from, since everyone does ingress different, it would be extremely challenging to support ingress properly, however for `clusterIP` type of services, we do have support in `.spec.exposeServices.minio` and `.spec.exposeServices.console` just set these to true, which is supported by the UI and the CLI as well

**Comment by stepanovdg** [comment]
@dvaldivia 
i have this properties to true
  exposeServices:
    console: true
    minio: true
    
What I am saying that services created with type LoadBalancer not clusterIp. Is it possible to change type?
`status:
  loadBalancer: {}
spec:
  ports:
    - name: https-minio
      protocol: TCP
      port: 443
      targetPort: 9000
      nodePort: 30184
  selector:
    v1.min.io/tenant: default
  clusterIP: 10.43.97.93
  clusterIPs:
    - 10.43.97.93
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
`
