### ISSUE TITLE
KES cannot longer be configured via UI anymore

### ISSUE THREAD

**Issue by cniackz** [minio/operator#1538]
In Operator Version 4.5.8, KES was deployed when configured via UI but in Operator version 5.0.1 is not longer working. This is because the configuration is outdated and we should be using new configuration as observed in kes repo: https://github.com/minio/kes/blob/master/server-config.yaml

Current issue after deploying kes via UI is:
```
Error: failed to read config file: yaml: unmarshal errors:
  line 22: cannot unmarshal !!map into []struct { Name keserv.Env[string] "yaml:\"name,omitempty\"" }
```

Above is because we are using old `server-config.yaml` in the secret.

## Expected Behavior

UI can configure KES and it should work.

## Current Behavior

```
Error: failed to read config file: yaml: unmarshal errors:
  line 22: cannot unmarshal !!map into []struct { Name keserv.Env[string] "yaml:\"name,omitempty\"" }
```

Due to old server-config.yaml in the secret.

## Possible Solution

1. To update Operator Code to get latest server-config.yaml for newer KES version
2. The WA is to just change/update secret from old config:

```
address: 0.0.0.0:7373
root: disabled
tls:
  key: /tmp/kes/server.key
  cert: /tmp/kes/server.crt
policy:
  default-policy:
    paths:
    - /v1/key/create/my-minio-key
    - /v1/key/generate/my-minio-key
    - /v1/key/decrypt/my-minio-key
    identities:
    - ${MINIO_KES_IDENTITY}
cache:
  expiry:
    any: 5m0s
    unused: 20s
log:
  error: "on"
  audit: "off"
keys:
  vault:
    endpoint: http://vault.default.svc.cluster.local:8200
    prefix: my-minio
    approle:
      id: 9bf1dc92-8ea5-d560-7cc4-29c51f66078c
      secret: 4442d775-a2ea-fd52-a141-8cc953797f59
    status: {}
```

to new config

```
version: v1
address: 0.0.0.0:7373
admin:
  identity: ${MINIO_KES_IDENTITY}
tls:
  key: /tmp/kes/server.key
  cert: /tmp/kes/server.crt
cache:
  expiry:
    any: 5m0s
    unused: 20s
log:
  error: "on"
  audit: "off"
keystore:
  vault:
    endpoint: http://vault.default.svc.cluster.local:8200
    prefix: my-minio
    approle:
      id: 9bf1dc92-8ea5-d560-7cc4-29c51f66078c
      secret: 4442d775-a2ea-fd52-a141-8cc953797f59
    status: {}
```

## Steps to Reproduce (for bugs)

1. Create cluster or have one ready, kind is ok to reproduce
2. Install Operator and Vault
3. Install Tenant with KES

You can follow steps from: https://github.com/cniackz/public/wiki/How-to-deploy-kes-tenant-via-UI

## Context

This is mainly to a new server-config.yaml required for newer KES versions.

## Regression

Yes, I test this manually and not sure why Operator Test is not catching this UI issue, maybe we need a UI test for this too.

## Your Environment

* Version used (`minio-operator`): 5.0.1
* Environment name and version (e.g. kubernetes v1.17.2): 

```
$ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:38:29Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```

* Server type and version: kind with containers

* Operating System and version (`uname -a`): 

```
$ uname -a
Darwin Cesars-MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
Cesars-MacBook-Pro:bash-config cniackz$
```

* Link to your deployment file:

No idea what this mean...

**Comment by kingsabru** [comment]
I am facing the same problem with configuring SSE for a Tenant from the Operator console. I'm using AWS Secret Manager as my root KMS (following this [doc](https://min.io/docs/minio/kubernetes/eks/operations/server-side-encryption/configure-minio-kes-aws.html)). The `kes` pod fails with the message:
```
Error: failed to read config file: yaml: unmarshal errors:
  line 22: cannot unmarshal !!map into []struct { Name edge.env[string] "yaml:\"name\"" }
```

# Environment Details
Minio Operator version: 5.0.4
Kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.13-dispatcher", GitCommit:"144103b3ddd7dcabfd3de8793c1e010c23913da1", GitTreeState:"clean", BuildDate:"2023-04-18T03:29:20Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.13-eks-0a21954", GitCommit:"6305d65c340554ad8b4d7a5f21391c9fa34932cb", GitTreeState:"clean", BuildDate:"2023-04-15T00:33:45Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
```
OS version (Mac OS Ventura 13.3.1):
```
$ uname -a
Darwin Kingsleys-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112 arm64
```
---

I wondered whether there was a way to configure SSE for a Tenant using the Minio Kubernetes Plugin (using the `kubectl minio tenant create` command) instead of from the Operator Console. The [plugin doc](https://min.io/docs/minio/kubernetes/eks/reference/kubectl-minio-plugin/kubectl-minio-tenant-create.html) does not provide enough detail for this, nor can I find other resources.

**Comment by cniackz** [comment]
Many things has changed since then and we need to re-test and confirm this is still an issue. In the meantime, closing this one until proven needed.
