### ISSUE TITLE
Operatorhub Outdated

### ISSUE THREAD

**Issue by julianseeger** [minio/operator#154]
https://operatorhub.io/operator/minio-operator points to version 1.0.3 and this Repository has Tags above v2.0.0.  

## Expected Behavior
Operatorhub stable channel should point to a somewhat recent version (2.x.x).

## Current Behavior
It points to v1.0.3 which does not work with the examples of v2.0.0 (different apiVersion for MinIOInstance for example).

## Possible Solution
Push new version to operatorhub.

## Steps to Reproduce (for bugs)
go to https://operatorhub.io/operator/minio-operator

## Context
In https://github.com/minio/minio-operator/issues/108 it seems like there have been efforts to update the operatorhub but it looks like that did not work. If there is an ongoing issue at the operatorhub, this issue could be used to track that upstream effort. Otherwise it should be fixed as an outdated version at operatorhub is IMO worse than no version at operatorhub.

## Regression
No

## Your Environment
Browser: Chrome 83 ;)
Doesn't matter

**Comment by harshavardhana** [comment]
Operator hub is deprecated, we have no intention of maintaining it. We are moving towards kubectl plugin model.

**Comment by javajon** [comment]
> Operator hub is deprecated.

I think you meant to say that your support of Operator Hub is deprecated. 

To not confuse those that are learning about your project and unaware of these nuances shouldn't the tile be updated to say "deprecated" or better removed from Operator Hub and Artifact Hub?
