### ISSUE TITLE
Cannot set resources on init and sidecar containers

### ISSUE THREAD

**Issue by artur-reaboi** [minio/operator#1543]
When using quotas on namespaces, a MinIO tenant cannot be created, as resources for the default init and sidecar are not specified.

The reported event reads like the following:
`create Pod dev-minio-pool-0-3 in StatefulSet dev-minio-pool-0 failed error: pods "dev-minio-pool-0-3" is forbidden: failed quota: default-rnh8b: must specify limits.cpu for: sidecar,validate-arguments; limits.memory for: sidecar,validate-arguments`

## Expected Behavior
Successfully create tenant pods in a namespace with CPU and/or Memory quotas

## Possible Solution
Allow specifying resources for init and sidecar containers or provide some hardcoded defaults (as a temporary solution).

## Your Environment
* Version used (`minio-operator`): 5.0.2
* Environment name and version (e.g. kubernetes): 1.24.10

**Comment by RyanRConaway** [comment]
Running into the same issue on version 5.0.3. Unable to migrate from Minio operator 4.5.8 on an openshift cluster. Please add the ability to configure resources on init container and sidecars.

**Comment by artur-reaboi** [comment]
Related to #1287

**Comment by cniackz** [comment]
Thank you guys for this issue, I am working to fix it. I will try to get a PR soon for this!

**Comment by cniackz** [comment]
Let's start by reproducing the issue, requested cpu and requested memory at tenant level:

```
      resources:
        requests:
          cpu: "4"
          memory: 11Gi
```

They get propagated to MinIO container but not to the other two containers, sidecar and init containers.
In `~/operator/pkg/resources/statefulsets/minio-statefulset.go` is where the fix should goes, thanks @dvaldivia for explaining this to me. I am working now to get the fix!.

**Comment by RyanRConaway** [comment]
Awesome! Glad this is being worked on. Quick comment about the expected behavior - The sidecar and init containers should not necessarily match the existing resources provided for the tenant/minio-pool. Likely the init/sidecar will have substantially lowered values, so they would need to be specified separately in the chat.

**Comment by patrickdet** [comment]
I agree with @RyanRConaway the sidecar and init containers have very different resource requirements and should be specified separately. #1734 does not cover this yet

**Comment by jiuker** [comment]
@cniackz @RyanRConaway @patrickdet PATL https://github.com/minio/operator/pull/1754

**Comment by oluwafemiayo** [comment]
After deploying the minio operator succesccfully, tenant is stuck in pending state and checking the logs, i got this output:

kubectl -n minio-tenant1 logs minio-tenant1-ss-0-0
Defaulted container "minio" out of: minio, sidecar, validate-arguments (init)
