### ISSUE TITLE
MinIO-Operator dangerous behavior

### ISSUE THREAD

**Issue by D1StrX** [minio/operator#1557]
## Expected Behavior

- When the MinIO-Operator is deleted, it must not delete all tenants.

## Current Behavior

When the MinIO-Operator is deleted, it deletes all tenants managed by that operator. 
Helm upgrade <release_name> doesn't add the tenants to a newly installed operator. Nor does it triggers to install the pods again. Pods in this context are the minio-pools-x-x

## Possible Solution

Don't delete the tenants.

## Steps to Reproduce (for bugs)

1. Have tenants deployed and managed by the operator
2. Helm uninstall -n <namespace> <release_name>

## Context

Environment depending on MinIO has an outage.

## Regression

No

## Your Environment

Version used (minio-operator): 4.5.8
Environment name and version (e.g. kubernetes v1.17.2): Kubernetes 1.26.3
Server type and version: On-prem
Operating System and version (uname -a): Ubuntu 22.04
Link to your deployment file: .

**Comment by D1StrX** [comment]
That doesn't make sense to me. Nginx-operator doesn't have such behavior.
I understand that the CRD's are deleted by uninstallation of the MinIO-Operator?
In that case I would suggest it shouldn't delete the CRDs, but rather do it when a parameter is set to do so.

**Comment by jiuker** [comment]
https://github.com/minio/operator/issues/1553#issuecomment-1650661259
