### ISSUE TITLE
Handle custom CA certificates for MCS/Minio connection

### ISSUE THREAD

**Issue by vmwiz** [minio/operator#156]
**Is your feature request related to a problem? Please describe.**
When deploying Minio operator on a cluster with a private CA, MCS cannot connect to Minio pods because the certifcate is not trusted. The following error message appears in the MCS pod logs: `error obtaining MinIO region: Get https://minio-internal-service.storage.svc.cluster.local:9000/minio/admin/v3/help-config-kv?key=&subSys=region: x509: certificate signed by unknown authority`

The Minio TLS certificate is generated using cert-manager as a subordinate CA from my company root CA, Minio is configured with:
```
externalCertSecret:
    name: minio-tls
    type: cert-manager.io/v1alpha2
```
Works like a charm for Minio, accessing the GUI with https://myminio.mydomain.lan through an ingress configured with SSL passthrough shows trusted certificates.

Using the CLI mc also recognize the certificate as trusted.

**Describe the solution you'd like**
Being able to inject the `externalCertSecret` in the MCS pod and use it as a trusted certificate to access the Minio cluster or give the possibility to inject CA public key as a trusted issuer in MCS pod.

At worst, allows setting environment variables in the MCS pod to enable `MCS_MINIO_SERVER_TLS_SKIP_VERIFICATION=on` as a dirty quick fix

**Describe alternatives you've considered**
Deploying MCS outside of the operator with TLS verification turned off

**Additional context**
Why not splitting MCS/KCS into their own CRDs for more granular configuration without complexifying MinioInstance itself?

**Comment by kerneltime** [comment]
Thank you @vmwiz will look into.
Are you on our slack? I would like to learn more about how you are using the operator.

**Comment by Alevsk** [comment]
@vmwiz Hi, if you are using the latest code of MCS `MCS_MINIO_SERVER_TLS_SKIP_VERIFICATION ` has been deprecated in favor of `MCS_MINIO_SERVER_TLS_ROOT_CAS`, you can provide there the certificate file names separated by comma, we will update the documentation.

**Comment by harshavardhana** [comment]
> @vmwiz Hi, if you are using the latest code of MCS `MCS_MINIO_SERVER_TLS_SKIP_VERIFICATION ` has been deprecated in favor of `MCS_MINIO_SERVER_TLS_ROOT_CAS`, you can provide there the certificate file names separated by comma, we will update the documentation.

It would be worth if we take a directory and load all certs from that common path.

**Comment by vmwiz** [comment]
Looks nice but how am I supposed to make use of it with the operator? The MinioInstance CRD does not allow passing environment variables to the MCS container.

**Comment by Alevsk** [comment]
@vmwiz we will discuss internally about this, in the meantime, as a workaround you can edit the YAML definition of an existing minio statefulset and add there the required environment variables and secrets

**Comment by rajinator** [comment]
@Alevsk will the operator not override customizations set in YAML definition? I am trying to a similar thing on an OKD cluster

**Comment by Alevsk** [comment]
@rajinator you can change the statefulset yaml definition once its created by the operator, there should not be any issues with that

**Comment by dvaldivia** [comment]
@Alevsk @rajinator those changes may get be discarded if there's changes to the Tenant (in case of operator v3) or MinioInstance

**Comment by croeck** [comment]
So now the tenant does allow us to specify env variables for the console, such as `MCS_MINIO_SERVER_TLS_ROOT_CAS`.
However, the variable expects filenames only and we can't mount any files to the deployment produced by the operator. So still stuck here.

**Comment by immanuelfodor** [comment]
Bumped into the same issue with Console and self-signed cert-manager certs:

```
kubectl logs pod/minio-console-66876d8b6-tmsp7

2020/08/02 09:12:41 Serving console at http://[::]:9090
2020/08/02 09:14:56 Redirecting /minio/login to index.html.
2020/08/02 09:17:14 error obtaining MinIO region: Get https://minio.minio.svc.cluster.local:9000/minio/admin/v3/help-config-kv?key=&subSys=region: x509: certificate signed by unknown authority
2020/08/02 09:17:56 error obtaining MinIO region: Get https://minio.minio.svc.cluster.local:9000/minio/admin/v3/help-config-kv?key=&subSys=region: x509: certificate signed by unknown authority
2020/08/02 09:18:04 error obtaining MinIO region: Get https://minio.minio.svc.cluster.local:9000/minio/admin/v3/help-config-kv?key=&subSys=region: x509: certificate signed by unknown authority
2020/08/02 09:18:17 error obtaining MinIO region: Get https://minio.minio.svc.cluster.local:9000/minio/admin/v3/help-config-kv?key=&subSys=region: x509: certificate signed by unknown authority
2020/08/02 09:18:24 error obtaining MinIO region: Get https://minio.minio.svc.cluster.local:9000/minio/admin/v3/help-config-kv?key=&subSys=region: x509: certificate signed by unknown authority
```

A new error line is added upon clicking the Console login button. Any way to trust the certs or skip the cert verification for Console like the above env variable for MCS?

**Comment by immanuelfodor** [comment]
Well, the deployment/pod contain these envs, interesting:

```
    Environment:
      CONSOLE_MINIO_SERVER:                        https://minio.minio.svc.cluster.local:9000
      CONSOLE_MINIO_SERVER_TLS_SKIP_VERIFICATION:  on
```

**Comment by immanuelfodor** [comment]
According to https://github.com/minio/console#connect-console-to-a-minio-using-tls-and-a-self-signed-certificate and https://github.com/minio/console/issues/189#issuecomment-661039941 , I could also define the `CONSOLE_MINIO_SERVER_TLS_ROOT_CAS` variable for Console in the `console-secret` (https://github.com/minio/operator/blob/master/examples/tenant-console.yaml#L15) but there is no way to make it work as the Tenant CRD's `console` section doesn't provide a way to define mounts for the cert-manager certificate object: https://github.com/minio/operator/blob/master/operator-kustomize/crds/minio.min.io_tenants.yaml#L66

**Comment by immanuelfodor** [comment]
With the release of 3.0.7, the `externalCertSecret` can be added to the Console, so now it works fine with Minio. Thank you for the quick fix!

**Comment by dvaldivia** [comment]
@immanuelfodor no problem, thanks for the patience, this week specially we've been cranking releases, but Operator is overall way much more stable thanks to that, please let us know if you find any other issues, we also welcome PRs.

**Comment by arLevi** [comment]
This is great for k8s, but what about commandline `mc` binary ?
```
$ mc ls my-remote/bucket/file.img

mc: <ERROR> Unable to list folder. Get "https://<server>:<port>/<bucket>/?location=": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

**Comment by ringerc** [comment]
@arLevi Workaround is to set `SSL_CERT_FILE` e.g.

```
SSL_CERT_FILE: /root/.minio/certs/public.crt mc ....
```

Unfortunately this must be in `mc`'s environment so it won't be per-alias.
