### ISSUE TITLE
Newer Helm chart versions not being published to `operator.min.io`

### ISSUE THREAD

**Issue by 9numbernine9** [minio/operator#1560]
Hello! :wave: Now that Operator `5.0.2` and `5.0.3` have been released, we're trying to upgrade to a newer version. We deploy the Operator via the Helm chart but it seems like there's no versions of the Helm chart that correspond to these latest releases of the Operator. 

```
❯ helm search repo minio-operator --versions | grep v5
minio-operator/operator      	5.0.1        	v5.0.1     	A Helm chart for MinIO Operator
minio-operator/operator      	5.0.0        	v5.0.0     	A Helm chart for MinIO Operator
minio-operator/tenant        	5.0.1        	v5.0.1     	A Helm chart for MinIO Operator
minio-operator/tenant        	5.0.0        	v5.0.0     	A Helm chart for MinIO Operator
```

## Expected Behavior
- Helm charts for versions `5.0.2` and `5.0.3` should be available.

## Current Behavior
- Latest version of the Helm chart that appears to be available is `5.0.1`.

## Possible Solution
- Publish newer versions. :smile: 

## Steps to Reproduce (for bugs)
1. Add the Helm chart repo.
2. Search for all versions of the `operator` chart - note that `5.0.2` and `5.0.3` are not present.

## Context
- Trying to upgrade to the latest Operator release via the Helm chart but cannot.

## Regression
- Yes. (Previous Operator releases have a corresponding Helm chart release.)

**Comment by pjuarezd** [comment]
Did you tried update the helm repos?

```
helm repo update
```

I am able to list and install v5.0.3


```
> helm repo add minio-operator https://operator.min.io 
"minio-operator" has been added to your repositories

> helm search repo minio-operator                     
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION                    
minio-operator/minio-operator	4.3.7        	v4.3.7     	A Helm chart for MinIO Operator
minio-operator/operator      	5.0.3        	v5.0.3     	A Helm chart for MinIO Operator
minio-operator/tenant        	5.0.3        	v5.0.3     	A Helm chart for MinIO Operator

> helm install operator --namespace minio-operator --create-namespace minio-operator/operator 
NAME: operator
LAST DEPLOYED: Wed Apr 12 10:10:50 2023
NAMESPACE: minio-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the JWT for logging in to the console:
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
EOF
kubectl -n minio-operator  get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode

2. Get the Operator Console URL by running these commands:
  kubectl --namespace minio-operator port-forward svc/console 9090:9090
  echo "Visit the Operator Console at http://127.0.0.1:9090"
```

**Comment by 9numbernine9** [comment]
Thanks for the response @pjuarezd - it appears to be working now. I was testing this behind a corporate proxy that appears to have aggressively cached the list of previous releases.
