### ISSUE TITLE
Define service port

### ISSUE THREAD

**Issue by febarbosa182** [minio/operator#1562]
On old installations or with helm based model we can define a service port for minio service, defaults to 9000. Using the tenant install it is set only to 443 or 80 make it difficult to evolve without cause impact on applications that are already running.

A feature to set witch port it should use would make the transition easier, this is how this happen on minio chart: https://github.com/minio/minio/blob/master/helm/minio/values.yaml#L173

If this is not possible a capability to set additional ports would work as well.

**Comment by shtripat** [comment]
I feel `kubectl` plugins are meant for more canned deployments and `helm` or `kustomize` provide flexibility to tweak parameters. @harshavardhana @dvaldivia suggestions?

**Comment by cniackz** [comment]
Hello @febarbosa182 

When you say `tenant install`, do you refer to [kubectl minio tenant create](https://min.io/docs/minio/kubernetes/upstream/reference/kubectl-minio-plugin/kubectl-minio-tenant-create.html#kubectl-minio-tenant-create)?. As I don't see any `install` command for it.

**Comment by cniackz** [comment]
Also @febarbosa182 I think there is a confusion here as https://github.com/minio/minio/blob/master/helm/minio/values.yaml#L173 comes from minio repo and we don't use or support this one for k8s deployments, it is more for testing. So sorry about that confusion. If you want to proceed with MinIO Installation, we suggest using our Operator. Hence the helm chart can be obtained from: https://github.com/minio/operator/tree/master/helm-releases where there is one for the operator and one for the tenant.

**Comment by cniackz** [comment]
Lastly, you can change the port if you want, there is no issue with that. I just did by changing the minio service to a new port, for example, look into our wiki:  https://github.com/minio/wiki/wiki/How-to-change-the-minio-port-in-k8s

**Comment by cesnietor** [comment]
closing due to innactivity
