### ISSUE TITLE
Can't build bucket on minio operator website because 404

### ISSUE THREAD

**Issue by DesireWithin** [minio/operator#1597]
## Steps to Reproduce (for bugs)
* I deploy the  minio operator `v5.0.3`, by kubectl minio plugin.
* And then I deploy a tenant named `bryan-test` from the Operator Dashboard. Whether I'm exposed them by  load balancer or not, and no matter if I `Edit Tenant Domains` on Operator Dashboard or not, it always get 404.

* I click management console to manage this tenant,
![图片](https://user-images.githubusercontent.com/23254001/236169877-1bb75c8d-ca75-4c82-b53f-466c81722197.png)

* I want to create a bucket, get 404 error.(GET and POST)
![图片](https://user-images.githubusercontent.com/23254001/236171356-ee31fd2d-7e92-402b-a21c-58211d47ed4b.png)
* The bucket and policyes buttons have the same problem
![图片](https://user-images.githubusercontent.com/23254001/236172115-84309108-673b-4a16-b2bf-a9442eac9966.png)

I notice there is a similar issue https://github.com/minio/operator/issues/1377.

## Workaround

I give tenant a new domain(both tenant console and MinIO Tenant ), new dns name resolution and new nginx reverse proxy and nginx ingress.
I can manage bucket and upload file success.

## Your Environment
* Version used (`minio-operator`): `v5.0.3`
* Environment name and version (e.g. kubernetes v1.17.2):  `kubernetes v1.26.2` on `Ubuntu 22.04` 
* Server type and version: `kvm`
* Operating System and version (`uname -a`): `Linux app-infra-k8s-master01 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by cesnietor** [comment]
Could you please try updating to latest release 5.0.6 and let us know if this got solved? we did some changes in 5.0.5 for webso ckets.

**Comment by cesnietor** [comment]
closing but let us know if you are still facing any issues. Thanks.
