### ISSUE TITLE
Add chart option to disable console deployment

### ISSUE THREAD

**Issue by drivebyer** [minio/operator#1598]
**Is your feature request related to a problem? Please describe.**
In my environment, I do not need console to deployment minio, but just use raw yaml to do it. In this case, I want a option to disable  the console deployment when helm install minio-operator.

**Comment by cesnietor** [comment]
@drivebyer  are you refering to the UI container for the Operator right? cause tenant one now is embedded in the minio binary.

**Comment by drivebyer** [comment]
> @drivebyer are you refering to the UI container for the Operator right? cause tenant one now is embedded in the minio binary.

Yes. Are we still creating two deployments after embedding the UI into the Minio binary?
