### ISSUE TITLE
Add ability to pull images by digest in Helm chart

### ISSUE THREAD

**Issue by Boojapho** [minio/operator#1599]
**Is your feature request related to a problem? Please describe.**
I'd like to pull images based on their digest rather than a tag, since tags can change.  

**Describe the solution you'd like**
The Helm chart only supports pulling by tag: `image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"`.  I'd like it to also support pulling by the digest (SHA)

**Describe alternatives you've considered**

**Additional context**
We use porter to bundle several images together into an OCI image for deployment.  The only way to reference the image is through a digest.

**Comment by cesnietor** [comment]
We'll investigate

**Comment by pjuarezd** [comment]
Digest format
```
minio/operator@sha256:28c80b379c75242c6fe793dfbf212f43c602140a0de5ebe3d9c2a3a7b9f9f983
```

Tag format
```
minio/operator:5.0.6

```

**Comment by cniackz** [comment]
To be added: https://github.com/minio/operator/pull/1706
