### ISSUE TITLE
Init containers and sidecar containers are missing container security context

### ISSUE THREAD

**Issue by xhejtman** [minio/operator#1606]
As of the latest git (5.0.4 and later), tenant initcontainer (validate-arguments) and sidecar container (sidecar) are missing container security context from tenant pool (security context is empty).

This is problem for running in kubernetes 1.25+ that have PSA, minio is unable to run in a restricted namespace as the restricted namespace requires to set at least:
```
allowPrivilegeEscalation: false
capabilities:
  drop:
   - ALL
```

Patch for this is quite simple.

**Comment by hampusehh** [comment]
I am having the same issue. 
Currently running in a privileged namespace, but will not work long term. 
I need a fix.
