### ISSUE TITLE
Unable to ingress to Operator Console via a SubPath

### ISSUE THREAD

**Issue by rkesters** [minio/operator#1607]
## Expected Behavior
Using k3s and networking.k8s.io/v1 Ingress , I create an http rule for the operator console that maps /minio-console/  to the "console" services in the minio-operator namespace. In the helm chart values that installs the operator ,  I include `OPERATOR_SUBPATH` set to `/minio-operator/` .  I can the access the the operator console via `http://localhost:3000/minio-console` .

## Current Behavior
I get 2 console errors when accessing `http://localhost:3000/minio-console.`

1. Uncaught SyntaxError: Unexpected token '<' (at main.567ad562.js1:1
2. Manifest: Line: 1, column: 1 , syntax error.

 

## Possible Solution
There does appear to be code that reads the OPERATOR_SUBPATH env, so I'm not sure. 

## Steps to Reproduce (for bugs)
1. Setup a k3s cluster  (assume localhost access to cluster ingress is via http://localhost:3000)
2. kubeclt apply -f example.yaml (see gist linked below)
3. use browser to access `http://localhost:3000/minio-console`

## Context
using subpaths to expose on cluster UI is a standard practice, port forwarding requires access the console from a different url. 

I don't believe I can use MINIO_BROWSER_REDIRECT_URL, as that appears to be used to keycloak integration (which I'll setup after getting this working)

## Regression
not sure

## Your Environment

* Version used (`minio-operator`): 5.0.4
* Environment name and version (e.g. kubernetes v1.17.2): v1.25.5+k3s1
* Server type and version:  Vbox 
* Operating System and version (`uname -a`): Linux local-moc 5.15.0-57-generic # 63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:  https://gist.github.com/rkesters/df3312e0fdc1ec262f3bb82d3dd3a39f

**Comment by cniackz** [comment]
This is very similar to issue: https://github.com/minio/console/issues/2045
And there was a fix in console for it: https://github.com/minio/console/pull/2818
But since we separated the Operator UI and the console UI, I wonder if similar fix should be applied

**Comment by cniackz** [comment]
I think the fix is: https://github.com/minio/operator/pull/1616

**Comment by cniackz** [comment]
Fixed in: https://github.com/minio/operator/pull/1616
