### ISSUE TITLE
is it possible to configure OIDC for minio operator console?

### ISSUE THREAD

**Issue by bbusioc** [minio/operator#1608]
Hello,

I have just started to test MinIO, successfully managed to deploy the operator and a tenant via helm charts.
For the tenant GUI everything went OK to configure an external OIDC and manage permissions based on policies.
However I can't understand from the documentation if OIDC integration is possible also for the Operator Console.
I could get a JWT and login by using this command:
kubectl minio proxy 

But is there a way to configure OIDC?
And if yes, how exactly is the authorization managed?
For the tenant part, it's quite clear that this is done based on policies; but I don't understand how it should work for the Operator GUI.
Can anyone share a documentation URL for this or help me to understand if this is even possible?

Thanks,
Bogdan

**Comment by sathieu** [comment]
You can use the secret to declare environnement variables: https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#openid-identity-management

**Comment by R-Studio** [comment]
@bbusioc do you find a way to configure OIDC with the Helm values?

**Comment by cesnietor** [comment]
Yes it's possible, we'll share the docs @pjuarezd

**Comment by pjuarezd** [comment]
hi @bbusioc it is possible, here is the doc on how to do it https://github.com/minio/operator/tree/master/examples/kustomization/operator-external-idp-oid
