### ISSUE TITLE
Operator UI allows creation of Tenant without required Encryption fields

### ISSUE THREAD

**Issue by cesnietor** [minio/operator#1610]
If I write something on the Encryption fields, the Create button is disabled until all fields are set but if I started setting up some fields and I change between encryption methods, the Create button gets enabled and allows us to create a Tenant. Which then causes an error while trying to initialize it. I think we probably need to refresh the button state every time we change encryption methods.

https://github.com/minio/operator/assets/11819101/9fcf049e-a485-4f23-a038-7264460b4b06

Since it allows the creation of the tenant, it fails while creating the KES pod
![Screenshot 2023-05-22 at 10 20 31 AM](https://github.com/minio/operator/assets/11819101/e4303df5-d474-497d-84d0-a44bde879680)

## Expected Behavior
Created button should be disabled if Encryption is Enabled and not all fields are being set.
Created button state should be refreshed if changing encryption method and fields should also be refreshed to empty values.

## Current Behavior
Encryption fields hold value even after changing encryption method

## Possible Solution
Refresh button state on change of encryption method

## Steps to Reproduce (for bugs)

1. On UI, Click on Create Tenant
2. Fillup initial required fields (name, namespace, etc)
3. Go to Encryption tab and enable it
4. Select Vault and write something on Endpoint
5. Change to AWS method
6. Go back to Vault Method (here the Create button is enabled but not all required fields have been set)

## Your Environment

* Version used (`minio-operator`): v5.0.4
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by jiuker** [comment]
Something Not work as https://github.com/go-openapi/validate/pull/152

**Comment by cesnietor** [comment]
@jiuker  I believe this is also a UI issue, the UI portion of it doesn't seem to be addressed by the PR is that correct? cc @bexsoft

**Comment by jiuker** [comment]
> @jiuker I believe this is also a UI issue, the UI portion of it doesn't seem to be addressed by the PR is that correct? cc @bexsoft

Yes. But the backend is where the data is finally validated. I am not good at frontend by the way. Right now it's not submittable, the backend will return an error but it won't show the error either, if you're good at front-end, you can help with that.

**Comment by cesnietor** [comment]
thanks, I'll reopen the issue then. Thanks @jiuker  for  adding a validation.

**Comment by cesnietor** [comment]
closing this since operator ui has been deprecated, see https://github.com/minio/operator/blob/master/docs/notes/v6.0.0.md#whats-new for more
