### ISSUE TITLE
Minio operator console doesn't shows object and buckets of tenant

### ISSUE THREAD

**Issue by MalKeshar** [minio/operator#1618]
Minio operator console doesn't shows object and buckets of tenant.

## Expected Behavior
Console should show object and buckets of tenant

## Steps to Reproduce (for bugs)
1. Login minio operator console
2. Choose any tenant
3. Choose management console
Object browser and tab Administration->Bucket doesn't show any buckets and objects.  

At the same time command util mc and usual tenant console(not through operator) shows objects without any problem. Logs below

```
[root@minio-client /]# mc ls tenant1
[2023-02-16 14:36:33 UTC]     0B mimir-alertmanager/
[2023-02-16 14:36:33 UTC]     0B mimir-blocks/
[2023-02-16 14:36:33 UTC]     0B mimir-ruler/
[2023-02-17 12:50:47 UTC]     0B tempo-admin/
[2023-02-17 12:50:47 UTC]     0B tempo-traces/
```

minio console logs:
```
Serving operator at http://[::]:9090/
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
ErrorWithContext:not found

ErrorWithContext:not found
```

## Regression
Yes. It worked at least at 4.5.8
## Your Environment
* Version used (`minio-operator`): 5.0.4
* Environment name and version (e.g. kubernetes v1.17.2):  kubernetes 1.26.4
* Server type and version: Debian 10
* Operating System and version (`uname -a`):
```
Linux node1-k8s 5.10.0-0.bpo.3-cloud-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux
```
* Link to your deployment file:
We use operator without custom values, only defaults.

**Comment by jiuker** [comment]
Minio console is another application. Not operator console. They are diffrent. @MalKeshar

**Comment by MalKeshar** [comment]
@jiuker, problem observed only then switching from **operator**. Should I fill bug in minio console?

**Comment by jiuker** [comment]
@MalKeshar I mean you didn't login in minio console. So it's nothing to show.
