### ISSUE TITLE
Operator UI Console white screen "You need to enable JavaScript to run this app."

### ISSUE THREAD

**Issue by TCGOGOGO** [minio/operator#1620]
Minio Version:
![image](https://github.com/minio/console/assets/10043464/576f2176-0ef4-4927-8d16-7350472bf400)
Minio cluster is provisioned by minio operator in k8s
![16855911053335](https://github.com/minio/console/assets/10043464/d3d49f74-2cf3-408a-9919-2e734454c6af)
click whatever button in console portal result in a white screen
![16855915399254](https://github.com/minio/console/assets/10043464/7742940f-5c20-4845-a5ba-c634571f76e6)
![image](https://github.com/minio/console/assets/10043464/ebf980eb-f217-48f7-85ad-2faad1f6dd7e)
![image](https://github.com/minio/console/assets/10043464/bd730fcc-cd82-490b-a6a0-6f1dc6132375)

**Comment by TCGOGOGO** [comment]
Sorry, this is a console issue, posted in a wrong place ...

**Comment by cesnietor** [comment]
This is an Operator issue so reopening this one, we'll try to reproduce and triage it.

**Comment by TCGOGOGO** [comment]
> This is an Operator issue so reopening this one, we'll try to reproduce and triage it.

Hi @cesnietor, any progress?

**Comment by cesnietor** [comment]
this should be fixed in https://github.com/minio/console/pull/2818, please reopen if not fixed.

**Comment by TCGOGOGO** [comment]
> this should be fixed in #1616, please reopen if not fixed.

Seems fixed in the latest version, much thanks!
