### ISSUE TITLE
Allow to set image repo for tenant init containers and sidecars

### ISSUE THREAD

**Issue by pitwegner** [minio/operator#1632]
**Is your feature request related to a problem? Please describe.**
I want to extend the minio operator image and build my own version. However, I there is no option to replace the image repo and tag for the tenant `sidecar` and `validate-arguments` containers.

**Describe the solution you'd like**
I would like a section in the yaml to override the image for all containers in a tenant. Maybe this could also be set at the operator level as a "global" setting for all tenants.

**Describe alternatives you've considered**
The alternative would be to fork the operator repo and make the change myself, since I am building my own image anyways...

**Comment by cniackz** [comment]
I don't think this is a good idea to implement, we should not allow different or custom images for each container.
It is better to keep them all in synch and you can change the image if you change the Operator Image, so no need for this I think.
