### ISSUE TITLE
Add support for specifying pod priorityClassName

### ISSUE THREAD

**Issue by cameronbraid** [minio/operator#164]
Stateful set pods for minio instances should support a user defined priorityClassName

https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

This way the user can schedule minio pods at a higher priority than their services that use them.  And can prevent minio pods from being evicted until after other less critical pods are evicted.

**Comment by kerneltime** [comment]
Thank you @cameronbraid, will try to include this in up coming releases.
We would love to learn more about how you use the operator and minio. Feel free to use the public slack to chat more about it.
