### ISSUE TITLE
Recomendations on resource requests for `console` in operator helm chart

### ISSUE THREAD

**Issue by jcpunk** [minio/operator#1652]
**Is your feature request related to a problem? Please describe.**
When deploying the `console` pod from the helm chart, no limits are set or suggested.

**Describe the solution you'd like**
Like the `operator` pod, some limits are available for review

**Describe alternatives you've considered**
Random try and see if I'm lucky

**Additional context**
The `operator` pod has a `resource.requests` set.

**Comment by jiuker** [comment]
@jcpunk you can send a pr, Here
