### ISSUE TITLE
No error is seen if tenant yaml file is incorrect

### ISSUE THREAD

**Issue by bexsoft** [minio/operator#1655]
No errors are displayed in edit tenant yaml page after hitting save if the yaml is incorrect

## Expected Behavior
Errors must be seen in case they ocurr

## Current Behavior
<img width="1550" alt="Screenshot 2023-06-20 at 17 59 55" src="https://github.com/minio/operator/assets/33497058/14af8c2c-e874-47a3-b1c4-7a38571cb7eb">

## Possible Solution
Seems like this is related to swagger-api migration. need to convert the error message or create a dispatch to display this.

## Steps to Reproduce (for bugs)
1. Go into tenant details page
2. Click on the pencil on the top right (Edit YAML)
3. write something wrong and hit save

**Comment by si458** [comment]
i see the same thing after testing, a pop up would be nice
