### ISSUE TITLE
add operator Helm Chart to artifacthub

### ISSUE THREAD

**Issue by si458** [minio/operator#1660]
**Is your feature request related to a problem? Please describe.**
currently the is only a community repo listed in artifacthub (https://artifacthub.io/packages/olm/community-operators/minio-operator)
but the operator helm chart isnt listed

**Describe the solution you'd like**
to add the operator helm chart to artifacthub

**Describe alternatives you've considered**
having to manually go to the helm folder on github and read values, defaults etc
https://github.com/minio/operator/tree/master/helm/operator

**Additional context**

**Comment by cniackz** [comment]
@aj-jester will start discussion internally to determine if this is something we are going to do in the near future.

**Comment by aj-jester** [comment]
I've started a discussion internally and will keep folks posted as we make progress.

**Comment by cniackz** [comment]
We have decided not to support artifacthub.
