### ISSUE TITLE
Missing operator 5.0.6 image

### ISSUE THREAD

**Issue by PurpleBooth** [minio/operator#1667]
## Expected Behavior

To be able to pull the operator image in the Helm chart

## Current Behavior

```
docker pull quay.io/minio/operator:v5.0.6
```
```
Error response from daemon: failed to resolve reference "quay.io/minio/operator:v5.0.6": quay.io/minio/operator:v5.0.6: not found
```

## Possible Solution

Rolling the helm chart back to 5.0.5 works, however it would be better to push the image for 5.0.6

## Steps to Reproduce (for bugs)

A helm install

``` kustomisation
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: minio-tenant
    name: tenant
    repo: https://operator.min.io/
    releaseName: tenant
    version: "v5.0.6"
helmGlobals:
  chartHome: .charts
```

```
kustomize build  --enable-helm . | kubectl apply -f-
```

## Regression

Yes - 5.0.6 (Helm chart)

## Your Environment

* Version used (`minio-operator`): 5.0.6
* Environment name and version (e.g. kubernetes v1.17.2):

Kubernetes v1.27.1

* Server type and version:

Linux node-cpx41-6zj68 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
Its not yet released @PurpleBooth

**Comment by PurpleBooth** [comment]
It might not be released on the list of GitHub Releases, but the release is already on the helm repository

```
helm repo add minio https://operator.min.io/
```
```
NAME                	CHART VERSION	APP VERSION	DESCRIPTION                    
minio/minio-operator	4.3.7        	v4.3.7     	A Helm chart for MinIO Operator
minio/operator      	5.0.6        	v5.0.6     	A Helm chart for MinIO Operator
minio/tenant        	5.0.6        	v5.0.6     	A Helm chart for MinIO Operator
```

```
helm search repo minio operator 
```
```
NAME                	CHART VERSION	APP VERSION	DESCRIPTION                    
minio/minio-operator	4.3.7        	v4.3.7     	A Helm chart for MinIO Operator
minio/operator      	5.0.6        	v5.0.6     	A Helm chart for MinIO Operator
minio/tenant        	5.0.6        	v5.0.6     	A Helm chart for MinIO Operator
```

**Comment by harshavardhana** [comment]
That is a mistake, helm must not have been updated.

**Comment by harshavardhana** [comment]
Its released

**Comment by HWiese1980** [comment]
Has this mistake been repeated? I'm getting the same error with v5.0.14.
