### ISSUE TITLE
Minio operator support OCP 4.13

### ISSUE THREAD

**Issue by xinredhat** [minio/operator#1670]
**Is your feature request related to a problem? Please describe.**
Currently the latest version is marked as [supporting OpenShift versions up to 4.12](https://github.com/redhat-openshift-ecosystem/certified-operators/blob/main/operators/minio-operator/5.0.6/metadata/annotations.yaml#L9). I want to know when it  will support Openshift 4.13?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pjuarezd** [comment]
We are evaluating compatibility and yes, support it's onwards

**Comment by Roming22** [comment]
Is there an ETA for OCP 4.13 support?

**Comment by pjuarezd** [comment]
Annotation to support 4.13 is already there https://github.com/minio/operator/pull/1674
Will be available in marketplace on next operator release, Operator releases take no longer than weeks @Roming22.
If you have a different timespan need, please reach out to support@min.io

**Comment by pjuarezd** [comment]
Will be available in next Operator release
