### ISSUE TITLE
Allow non-interactive way to delete the operator using kubectl plugin

### ISSUE THREAD

**Issue by thomasjm** [minio/operator#1683]
**Is your feature request related to a problem? Please describe.**

This is the same as #710, but for the operator itself instead of tenants.

Currently `kubectl minio delete` asks for confirmation; implement a flag `--force` to avoid interactive behavior.

**Describe the solution you'd like**

`kubectl minio delete --force`

**Describe alternatives you've considered**
Skip deleting my operator in tests and just let it be destroyed when the cluster is removed.

**Additional context**
For scripts, tests, or other non-interactive use.

**Comment by cniackz** [comment]
I was reviewing this change to explain or help Abdul with this task and found that the solution can be found here:
https://github.com/minio/operator/pull/711/files

**Comment by cniackz** [comment]
Similar code will apply not just for the tenant but for the Operator as well:

<img width="1840" alt="Screenshot 2023-07-14 at 8 46 08 AM" src="https://github.com/minio/operator/assets/6667358/6276ba81-9ff3-469a-ae26-34fef8b96f90">

**Comment by cniackz** [comment]
Now to test the code change, we can look at Pedro's notes at: https://github.com/minio/operator/pull/1612
