### ISSUE TITLE
Be able to fetch credentials from kubectl plugin

### ISSUE THREAD

**Issue by thomasjm** [minio/operator#1686]
**Is your feature request related to a problem? Please describe.**

Once you create an operator and a tenant, I'd like to be able to retrieve credentials for working with it non-interactively. In interactive mode `kubectl minio proxy` is nice, but doesn't work well for tests and scripts.

At minimum it would be nice to fetch the `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` for a given tenant.

**Describe the solution you'd like**

I'd imagine something like

```shell
kubectl minio tenant [tenant-name] get-credentials
```

which would be able to output them in machine-readable format (JSON etc.).

**Describe alternatives you've considered**

At the moment I get this information programmatically by retrieving the secret `[tenant name]-env-configuration`, which has a key `config.env` which has data like this:

```yaml
config.env: |
  export MINIO_ROOT_PASSWORD="KptUCO56xLYIAQQGHQYBrwarJZVCcFJywC7Sne7K"
  export MINIO_ROOT_USER="54Y1MIV5R5A076LM7QB6"
```

Then I parse this using regexes, which is not ideal.

Another change that might improve the situation would be to change this secret so it's not shell code but instead contains the username and password as separate keys, so it's easier to work with.

**Comment by jiuker** [comment]
`kubectl get tenant tenantName -n namesspace -o=jsonpath="{.spec.configuration.name}" | xargs -I {} kubectl get secret {} -n
namesspace -o=jsonpath="{.data.config\\.env}" | base64 -d` @thomasjm for now.

**Comment by thomasjm** [comment]
Thanks @jiuker !

One question from looking at the new feature -- does this support outputting the data in a machine-readable way? A flag like `-o json` or similar would be ideal.

**Comment by shtripat** [comment]
> Thanks @jiuker !
> 
> One question from looking at the new feature -- does this support outputting the data in a machine-readable way? A flag like `-o json` or similar would be ideal.

I feel, programatically, its better to use kubectl command mentioned at https://github.com/minio/operator/issues/1686#issuecomment-1636796889

**Comment by thomasjm** [comment]
Well that would be a bit of a mess, relying on a potentially brittle `jsonpath`, potentially multiple additional API calls, another potentially brittle `jsonpath`, a `base64` call, and the same problem as before of parsing the `export` statements!

**Comment by jiuker** [comment]
I don't think so. You should parse it by yourself. Or that's too easy for others to get you root user by script. @thomasjm

**Comment by thomasjm** [comment]
Of course you're free to refuse the feature request and that's fine, but

> Or that's too easy for others to get you root user by script.

What?! Are you suggesting that making this difficult is a "security feature" because some malicious actor who is able to run scripts on my machine somehow can't exfiltrate the passwords without parsing them? I suppose then `kubectl get secret -o json` is a massive security hole...

**Comment by jiuker** [comment]
> Of course you're free to refuse the feature request and that's fine, but
> 
> > Or that's too easy for others to get you root user by script.
> 
> What?! Are you suggesting that making this difficult is a "security feature" because some malicious actor who is able to run scripts on my machine somehow can't exfiltrate the passwords without parsing them? I suppose then `kubectl get secret -o json` is a massive security hole...

Yeah. No plan for `--json`
