### ISSUE TITLE
Rotate csr-signer certificate in Openshift

### ISSUE THREAD

**Issue by pjuarezd** [minio/operator#1688]
**Is your feature request related to a problem? Please describe.**
In Openshift certificates are signed by a intermediary, we already did included that credential in the Tenants CAs here https://github.com/minio/operator/pull/1461

**Describe the solution you'd like**
This feature is about monitor the certificate expiration and rotate/renew the certificate to the tenants and Operator

**Comment by itmwiw** [comment]
Hello @pjuarezd,
To be as precise as possible,  in issue #1671, the tenants' certificates are renewed and the secrets are generated. Furthermore, a restart of the tenants' pod resolves the issue without requiring a restart of the operator's pods. Once the tenants' pods are restarted, the operator can communicate with the tenants once again.
