### ISSUE TITLE
minio 5.0.7 has not been released as a certified operator in OCP

### ISSUE THREAD

**Issue by Roming22** [minio/operator#1717]
## Expected Behavior
minio 5.0.7 should be available on OCP 4.13.

## Current Behavior
minio 5.0.7 is not available on OCP.

## Possible Solution
A pull requests to certify the latest version of the operator needs to opened to [certified-operators](https://github.com/redhat-openshift-ecosystem/certified-operators/pulls) (example PR for [5.0.6](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2481)).

## Steps to Reproduce (for bugs)
1. Create an OCP 4.13 cluster.
2. Try to deploy the minio operator.

## Context
Upgrading to the latest version of OCP.

## Regression
No.

## Your Environment
* Version used (`minio-operator`): 5.0.7
* Environment name and version (e.g. kubernetes v1.17.2): OCP 4.13

**Comment by Roming22** [comment]
@pjuarezd This is a follow up to #1670

**Comment by pjuarezd** [comment]
Already published

**Comment by Roming22** [comment]
@pjuarezd I see it now. Awesome, thanks.
