### ISSUE TITLE
Handling CRDs with helm packages

### ISSUE THREAD

**Issue by pasztorl** [minio/operator#1729]
**Is your feature request related to a problem? Please describe.**
We usually running operators in namespaces, so if an operator needed in a namespace it installed separately, not one operator watches all namespaces. We would like to do this with minio operator too, but the current helm chart not allowing it.
The first problem is that the tenant crd is not in the crds special dir, so you can't skip it when you are installing.

**Describe the solution you'd like**

I think it is even better to manage the CRDs on a separate helm package, following the best practices.

https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

**Comment by pjuarezd** [comment]
Related to issue https://github.com/minio/operator/issues/1553 and yes, I got the same conclusion, having the CRD on it's own chart seems like right approach for us, we still need to do some discussion but tentatively this will do
cc @dvaldivia @cniackz @harshavardhana
