### ISSUE TITLE
Minio tenants not starting - In pending state for long time

### ISSUE THREAD

**Issue by Anushakallam** [minio/operator#1733]
Minio tenants not starting - In pending state for long time

## Expected Behavior
Minio tenants should be in running state

## Current Behavior
C:\Users\anusha.kallam\.krew\bin>kubectl get all -n minio-tenant-1
NAME                        READY   STATUS    RESTARTS   AGE
pod/minio-tenant-1-ss-0-0   0/2     Pending   0          5h40m
pod/minio-tenant-1-ss-0-1   0/2     Pending   0          5h40m
pod/minio-tenant-1-ss-0-2   0/2     Pending   0          5h40m
pod/minio-tenant-1-ss-0-3   0/2     Pending   0          125m

NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/minio                    ClusterIP   172.20.82.25    <none>        443/TCP    5h41m
service/minio-tenant-1-console   ClusterIP   172.20.55.220   <none>        9443/TCP   5h41m
service/minio-tenant-1-hl        ClusterIP   None            <none>        9000/TCP   5h41m

NAME                                   READY   AGE
statefulset.apps/minio-tenant-1-ss-0   0/4     5h41m

C:\Users\anusha.kallam\.krew\bin>
C:\Users\anusha.kallam\.krew\bin>kubectl describe pod minio-tenant-1-ss-0-0 -n minio-tenant-1
Events:
  Type     Reason            Age                      From               Message
  ----     ------            ----                     ----               -------
  Warning  FailedScheduling  2m18s (x348 over 5h52m)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.

C:\Users\anusha.kallam\.krew\bin>

## Your Environment

* Version used (`minio-operator`): image: minio/operator:v5.0.7
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes version 1.21 [AWS EKS]
* Server type and version: 
8CPU X 32GB , t3.2xlarge Amazon linux Ec2 instance

* Operating System and version (`uname -a`): amazon-eks-node-1.20-v20210826
* Link to your deployment file: I have not used any deployment file 
* Installed krew
* Installed minio using krew kubectl krew install minio
* kubectl minio init
* created namespace: kubectl create ns minio-tenant-1
* Executed the below command : kubectl minio tenant create minio-tenant-1 --servers 4 --volumes 8 --capacity 10G --namespace minio-tenant-1 --storage-class standard
* Minio operator is started , able to do proxy and login
* Minio tenants are not started , even from the console tenant creation is not taking any pods
*

**Comment by jiuker** [comment]
Your pvcs are pendding. Fix it first.

**Comment by Anushakallam** [comment]
PVCs are pending as the pods are not running
Once pod are running , I think the PVCs will create volumes

**Comment by jiuker** [comment]
> PVCs are pending as the pods are not running Once pod are running , I think the PVCs will create volumes

Not really. You should fix this ` default-scheduler 0/3 nodes are available: 3 pod has unbound` first.
