### ISSUE TITLE
K8S Minio Operator, Tenant  Create, Taints NoSchedule can't work, because it generates with seconds field

### ISSUE THREAD

**Issue by morozev** [minio/operator#1735]
## NOTE
Minio Operator (or MinIO Tenant) Helm Chart with mistake. 
Tenant creation generate wrong statefulset yaml for K8S. Minio can't create storage pool (with tolerations for NoSchedule effect  for pod placement).

K8S Minio Operator, Tenant  Create, Taints NoSchedule can't work, because it generates with seconds field. It is wrong K8S manifest.

## Expected Behavior

Expected manifest with lines:
affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: pool
                    operator: In
                    values:
                      - storage
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - minio
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - pool-1
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
      tolerations:
        - key: pool
          operator: Equal
          value: storage
          effect: NoSchedule
  volumeClaimTemplates:
## Current Behavior

affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: pool
                    operator: In
                    values:
                      - storage
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - minio
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - pool-1
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
      tolerations:
        - key: pool
          operator: Equal
          value: storage
          effect: NoSchedule
          **tolerationSeconds: 0 - !!!!!!!!!!!!this is wrong parameter!!!!!!!!!!!!!!! it not allowed by K8S**
  volumeClaimTemplates:
## Possible Solution

Delete row **tolerationSeconds: 0** for effect NoSchedule at CRD of created tenant.
## Steps to Reproduce (for bugs)

1. install helm chart  Minio Operator (operator-5.0.7)
2. Create taints for nodes like this: pool=storage:NoSchedule
3. Create tenant (web interface) with pod placement tolerations:  pool=storage:NoSchedule
4. Tenant in fault state
( Statefulset in tenant namespace generate error: "is invalid: spec.tolerations[0].effect: Invalid value: "NoSchedule": effect must be 'NoExecute' when tolerationSeconds is set" )
## Your Environment

K8s version 1.23

* Version used (`minio --version`): operator-5.0.7
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by jiuker** [comment]
Show the log @morozev

**Comment by morozev** [comment]
Sorry, but Kubernetes event already gone( 
But signal about problem send by stateful of tenant looks like: "is invalid: spec.tolerations[0].effect: Invalid value: "NoSchedule": effect must be 'NoExecute' when `tolerationSeconds` is set"

I resolve problem by edit CRD of tenant by delete `tolerationSeconds` row and Statefulset successful deployed after editing.

**Comment by jiuker** [comment]
Post your wrong tenant please. I will reproduce it. @morozev

**Comment by morozev** [comment]
Hello @jiuker ! It is edited tenant (please, search **!!!seconds field was here!!!**):

```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: "2023-08-22T07:14:18Z"
  generation: 4
  labels:
    k8slens-edit-resource-version: v2   
  name: minio   
  namespace: minio-tenant1
  resourceVersion: "21956133"
  uid: 796c628c-8211-422b-b4d0-ad7bbf3ed733
scheduler:
  name: ""
spec:
  configuration:
    name: minio-env-configuration
  credsSecret:
    name: minio-secret
  exposeServices: 
    console: true
    minio: true
  features: {}
  image: minio/minio:RELEASE.2023-08-16T20-17-30Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: pool
              operator: In
              values:
              - storage
    name: pool-0
    resources:
      requests:
        cpu: "2"
        memory: 8Gi
    runtimeClassName: ""
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: Always
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    servers: 4
    tolerations:
    - effect: NoSchedule
      key: pool
      operator: Equal
      value: storage
      **!!!seconds field was here!!!**
    volumeClaimTemplate:
    
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "53687091200"
        storageClassName: yc-network-ssd
      status: {}
    volumesPerServer: 4   
  requestAutoCert: false
  users:
  - name: minio-user-0
status:   
  availableReplicas: 4
  certificates: 
    autoCertEnabled: true
    customCertificates: {}
  currentState: Initialized
  drivesOnline: 16
  healthStatus: green
  pools:
  - legacySecurityContext: false
    ssName: minio-pool-0
    state: PoolInitialized
  provisionedUsers: true
  revision: 0
  syncVersion: ""
  usage:
    rawCapacity: 858993459200
    rawUsage: 722752786432  
  writeQuorum: 12
```
`
