### ISSUE TITLE
add third party CA certificates  has incorrect configuration

### ISSUE THREAD

**Issue by wangchao732** [minio/operator#1737]
minio version & tenant  info:
![image](https://github.com/minio/operator/assets/19440083/d3c74b14-3179-4102-bf34-41b6127404ce)

error info:

![image](https://github.com/minio/operator/assets/19440083/bab90fcc-e5e5-4029-ab39-697accbd9c69)
![image](https://github.com/minio/operator/assets/19440083/60010c40-ad52-4dd9-9aa3-371fa0d655fc)

I don't know where this error came from, but I hope I can get help.

**Comment by jiuker** [comment]
I think you should learn the documents that the page mention it.
