### ISSUE TITLE
enableFTPS and or enableFTP

### ISSUE THREAD

**Issue by Jeremy-Boyle** [minio/operator#1741]
Add a new boolean field enableFTPS to the tenant spec. When it is set to true, pass the required arguments to minio to enable FTPS support. Also ensure that required port (8021) is opened when FTPS is enabled.

This is similar to:
https://github.com/minio/operator/pull/1685

**Comment by cniackz** [comment]
We cannot enable this in Kubernetes. It is intentionally not enabled because there is no way to apply load balancing techniques to pure FTP.

**Comment by harshavardhana** [comment]
FTP and FTPS are not load-balancer friendly. There is no way to load balance them without having explicitly written load balancers for FTP/FTPS, which are very expensive and proprietary.

SFTP works fine with proxies, is safer to use, and is supported. Please use that. Let's not bikeshed more on legacy things. Use it the way it is presented.

If you cannot use SFTP, consider a bare-metal deployment for MinIO that can enable FTP/FTPS.
