### ISSUE TITLE
Add SFTP by SSH key

### ISSUE THREAD

**Issue by dod-ia** [minio/operator#1752]
**Is your feature request related to a problem? Please describe.**
For security reason, using SFTP by login/password can be too weak to satisfy the Cyber Risk Management Policy. A feature to be able to connect to Minio by SFTP SSH key may be very useful.

**Describe the solution you'd like**
To be connected by SFTP using SSH key and not (only) password

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ventaubain** [comment]
Close, migrate to Minio project, no operator
