### ISSUE TITLE
Add option to set PodDisruptionBudget

### ISSUE THREAD

**Issue by xoxys** [minio/operator#1764]
**Is your feature request related to a problem? Please describe.**

It's not possible to override the default PodDisruptionBudget while the default might not fit for every use case.

**Describe the solution you'd like**

Add an option to set a custom PodDisruptionBudget or disable it.

**Comment by jiuker** [comment]
Under which case you need to disable this?

**Comment by xoxys** [comment]
I'm using a single server multi disk tenant on a small setup. During node drains, I would still like to get the tenant started on another node even if this results in a short downtime, which is an acceptable in my case. You can still keep the default, but is it required to enforce it for everyone?

**Comment by jiuker** [comment]
I think this is acceptable, you can now manually delete this resource because this resource is mandatory for cluster health to create.

**Comment by D1StrX** [comment]
MinIO in a k8s cluster obstructs the draining in 1.27.x as well
`(will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.` 
This is a deployment of 2 pods spread on 2/3 workers. It doesn't delete the pod on the draining node, and draining command logs the above. 

Will the PR also fix the issue for the environment outlined above?

**Comment by jiuker** [comment]
@D1StrX Yes. It will not create for server are 1 or 2.
