### ISSUE TITLE
--version does not return version

### ISSUE THREAD

**Issue by JakobPetersson** [minio/operator#1768]
Since 5.0.0 the --version flag does not return the version of minio-operator.
It only returns:
```
minio-operator version (dev) - (dev)
```

## Expected Behavior

To print out the minio-operator version.

## Current Behavior

Since 5.0.0 the minio-operator executable only outputs (dev)

## Steps to Reproduce (for bugs)

1. `docker run --rm quay.io/minio/operator:v4.5.8 /minio-operator --version` (Works)
2. `docker run --rm quay.io/minio/operator:v5.0.0 --version` (Only outputs dev)
3. `docker run --rm quay.io/minio/operator:v5.0.1 --version` (Only outputs dev)
4. `docker run --rm quay.io/minio/operator:v5.0.2 --version` (Only outputs dev)
5. `docker run --rm quay.io/minio/operator:v5.0.3 --version` (Only outputs dev)
6. `docker run --rm quay.io/minio/operator:v5.0.4 --version` (Only outputs dev)
7. `docker run --rm quay.io/minio/operator:v5.0.5--version` (Only outputs dev)
8. `docker run --rm quay.io/minio/operator:v5.0.6--version` (Only outputs dev)
9. `docker run --rm quay.io/minio/operator:v5.0.7--version` (Only outputs dev)
10. `docker run --rm quay.io/minio/operator:v5.0.8--version` (Only outputs dev)

## Regression

5.0.0

**Comment by JakobPetersson** [comment]
Ok, that is very reasonable.

Another aspect that seems to be connected to this that the`(dev)`-value ends up in env `MINIO_OPERATOR_VERSION` in the tenant.

**Comment by harshavardhana** [comment]
Yeah that is wrong and we should fix that @JakobPetersson

**Comment by harshavardhana** [comment]
This was introced as a regression when operator console moved from console repo https://github.com/minio/operator/pull/1769

**Comment by harshavardhana** [comment]
fixed by #1769
