### ISSUE TITLE
Can't expand a tenant. Pool exists.

### ISSUE THREAD

**Issue by jenqaz** [minio/operator#1785]
I've created a test tenant using MinIO Operator UI. 4 servers, 4 disks per server and EC:4.
I added a few test data buckets and decided to test the expansion and decommission of the tenant. 
I added a new pool via MinIO Operator (Expand tenant button) and check that:

`
│ 1st │ http://dca-pool-0-{0...3}.dca-hl.minio.svc.cluster.local/export{0...3} │ 25 GiB (used) / 120 GiB (total)  │ Active
`
`
│ 2nd │ http://dca-pool-1-{0...3}.dca-hl.minio.svc.cluster.local/export{0...3} │ 2.1 GiB (used) / 240 GiB (total) │ Active
`

After that, I started the decommission process:
 `.\mc.exe admin decommission start dca/ "http://dca-pool-0-{0...3}.dca-hl.minio.svc.cluster.local/export{0...3}"`

The pool-0 was successfully drained:
`
| 1st │ http://dca-pool-0-{0...3}.dca-hl.minio.svc.cluster.local/export{0...3} │ 1.4 GiB (used) / 120 GiB (total) │ Complete
`
`
│ 2nd │ http://dca-pool-1-{0...3}.dca-hl.minio.svc.cluster.local/export{0...3} │ 26 GiB (used) / 240 GiB (total)  │ Active
`

I edited the tenant's YAML to drop pool-0 from statefulset. The pool is gone but I can't expand the tenant once more, because it's trying to create pool-1 which already exists.

## Expected Behavior
The tenant should be expanded by pool-2.
## Current Behavior
/api/v1/namespaces/minio/tenants/dca/pools POST request response with 406 "pool exists".

Payload:
```json
{"name":"pool-1","servers":4,"volumes_per_server":4,"volume_configuration":{"size":10737418240,"storage_class_name":"local-storage","labels":null},"tolerations":[],"securityContext":{"runAsUser":"1000","runAsGroup":"1000","fsGroup":"1000","fsGroupChangePolicy":"Always","runAsNonRoot":true},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"v1.min.io/tenant","operator":"In","values":["dca"]},{"key":"v1.min.io/pool","operator":"In","values":["pool-1"]}]},"topologyKey":"kubernetes.io/hostname"}]}}}
```

## Steps to Reproduce (for bugs)
1. On UI, click "Expand Tenant";
2. Fill up all fields to setup a new pool;
3. Click "Create".

## Context
The tenant can't be expanded;

## Your Environment

* Version used (`minio-operator`): v5.0.9
* Environment name and version (e.g. kubernetes v1.17.2): v1.27.5
* Server type and version: Virtual machines
* Operating System and version (`uname -a`): Linux 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by allanrogerr** [comment]
I am working on a fix for this.
