### ISSUE TITLE
use full available freeCapacity of a drive

### ISSUE THREAD

**Issue by zeph** [minio/operator#1792]
**Is your feature request related to a problem? Please describe.**
you can fast forward skip to the bottom of this ticket for the root of this request https://github.com/minio/directpv/issues/857#issuecomment-1737698499

from the WebUI of the MinIO Operator I was expecting to size the Tenant PVCs to get the maximum available capacity of each drive on my setup... but several things prevent it... 1st of all the assumption that since I had 25 GiB drives I could put that as a value in the Tenant creation wizard... wrong, I always need to be providing a value as close as possible but lower of the freeCapacity of a drive

**Describe the solution you'd like**
...the best would be a simple flag, that magically pre-fills such value with the max allocatable disk size

**Describe alternatives you've considered**
At least to be able to put a value with a digit after a dot... not only 25 GiB for instance but also 24.999 GiB 
(possible on Tenant creation, but not allowed on the Pool editing UI once the Tenant is already created)

**Additional context**
<img width="970" alt="wizard" src="https://github.com/minio/operator/assets/209808/5527923e-a2f2-455a-9082-658ba156aae2">
in the above you can see the trick of adding .999 to the setup

***

<img width="1051" alt="editing" src="https://github.com/minio/operator/assets/209808/98cbaf2a-67bd-4af2-a978-665b0604a7ff">
the above is the pool editing 

***

<img width="997" alt="field_control" src="https://github.com/minio/operator/assets/209808/f76b7bf6-41d1-4226-816f-490f8ee7a30c">
but if I try to mod the decimals... it does not allow me to add em

**Comment by jiuker** [comment]
We can't get the maximum available capacity for K8S didn't support. If you have any thought about this, let's discuss that.

**Comment by zeph** [comment]
@jiuker I'm in the implementation phase of this at a customer, and last week I exactly stumbled on this again... since my way of proceeding was associating a specific label to a set of drives, and since on creation tenant wizard I do specify a storage class name... exactly selecting such, what prevents you from talking for instance with `directpv` and deduct that? (I'm missing the complete picture, obviously... which u have, I assume... does this needs to be as generic as possible even talking to storage providers that are not directpv? I assume it might be the case)

because my way of proceeding at this stage was attempting to take the value in bytes that `directpc discover` gives me in the drives.yaml ...compute approximately a 99.9% of it, dividing then by (1024^3) I get the value I want in Gibibytes (which is what u use, as integer, after the wizard creation, if i got to change the pool if the PVCs are not allocating accordingly or if too much spare space if waster per drive) 

I instead have to take such value, and even if I'm giving you on the UI the topology, I have to compute the total capacity by x host x drives give u the total in the wizard... seems a bit, inconsistent, no? ...why don't you simply ask the topology and compute the value of total capacity from the available drives on the directpv available info yourself?

 1. you ask me the topology (amount of hosts, racks, drives per host to use - hypothesis)
 2. you see the storage class, you can tell me back: you have these amount of drives of this size
 3. i click and confirm
 
 instead I'm spending my time deleting all the PVCs resources, adjust the value on the pool in the WebUI, delete the sts, wait for the new PVCs with the new value to attempt to allocate again (in the hope of having guessed the max value the right way)... repeat as much as ... (not nice)
