### ISSUE TITLE
No support for declarative cleanup of PVCs

### ISSUE THREAD

**Issue by snarlysodboxer** [minio/operator#1803]
## Expected Behavior
When a `Tenant` object is deleted from the Kubernetes API, the operator should cleanup the PVCs according to the Reclaim Policy of their bound Persistent Volumes, like the docs [already indicate for imperative management](https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/delete-minio-tenant.html#procedure-cli) with the krew plugin.

## Current Behavior
PVCs are left behind, forcing us to hack around the operator and wonder about it's value to us.

## Possible Solution
Move the stated cleanup functionality out of the krew plugin into the operator??

## Your Environment
* Version used: `latest`

**Comment by jiuker** [comment]
I don't think it's a flaw. The data is the most important thing, and if you are using it and discarding it, you can use `emptyDir`. @snarlysodboxer

**Comment by snarlysodboxer** [comment]
Yes, the data is important for real environments, but not ephemeral testing environments, that's why many other operators only support data destruction through an opt-in mechanism.

For example with the postgres-operator you can set a specific annotation's value to match the object's name, in which case the operator will fully cleanup including the PVCs via ownerReferences. Without that annotation it will orphan the StatefulSet and therefore PVCs, helping to prevent mistakenly deleting stateful data. - Set that annotation only in your ephemeral CI testing envs, and you're pretty safe.

Surely this need is understandable? We are not the only ones who want to be able to stand up some minio instances, run some tests against things that use them, and then destroy them afterwards, repeatedly.

Another, perhaps simpler opt-in mechanism is choosing a storageClass with a delete `RetentionPolicy`, thus the suggestion above.

**Comment by jiuker** [comment]
> Yes, the data is important for real environments, but not ephemeral testing environments, that's why many other operators only support data destruction through an opt-in mechanism.
> 
> For example with the postgres-operator you can set a specific annotation's value to match the object's name, in which case the operator will fully cleanup including the PVCs via ownerReferences. Without that annotation it will orphan the StatefulSet and therefore PVCs, helping to prevent mistakenly deleting stateful data. - Set that annotation only in your ephemeral CI testing envs, and you're pretty safe.
> 
> Surely this need is understandable? We are not the only ones who want to be able to stand up some minio instances, run some tests against things that use them, and then destroy them afterwards, repeatedly and automatically via applying and deleting Kubernetes configs.
> 
> Another, perhaps simpler opt-in mechanism is choosing a storageClass with a delete `RetentionPolicy`, thus the suggestion above.

We understand this need, so we have added new features. Waiting to be merged
