### ISSUE TITLE
Operator keeps trying to create buckets every 5 seconds

### ISSUE THREAD

**Issue by b-thiswatch** [minio/operator#1829]
I am running Operator 5.0.10 and Tenant Helm Chart deployed via ArgoCD. I have created my own user and some initial buckets. I can login with that user and the buckets do exists after the cluster is provisioned.

But the operator logs "Hit conflict issue, getting latest version of tenant" every 5 seconds and tries to add the buckets (again). During that time the application is also displayed as "Progressing" and not "Healthy" in ArgoCD.

## Expected Behavior
I guess the buckets should be created once and the cluster should be healthy then :)

## Current Behavior
Operator tries bucket creation every 5 seconds

## Context
I am a bit hesitant to use the current cluster in production when it has "problems" every 5 seconds.

## Your Environment
* Version used (`minio-operator`): 5.0.10
* Environment name and version (e.g. kubernetes v1.17.2): RKE 2 1.27.x
* Operating System and version (`uname -a`): Ubuntu 22.04 LTS

**Comment by jiuker** [comment]
@cniackz ^^

**Comment by D1StrX** [comment]
I see the exact same behavior, a lot:
![image](https://github.com/minio/operator/assets/40062371/3d85cf8a-3c1a-498e-997f-4702748b2a44)

**Comment by cniackz** [comment]
Thank you @jiuker, your PR is fixing the issue I introduced:

<img width="1840" alt="Screenshot 2023-10-30 at 10 24 30 AM" src="https://github.com/minio/operator/assets/6667358/fbd37b6e-e745-4750-81ad-22765a21b385">

<img width="1840" alt="Screenshot 2023-10-30 at 10 24 51 AM" src="https://github.com/minio/operator/assets/6667358/398decff-2ec3-4324-a61a-1198a5345e17">

https://github.com/minio/operator/pull/1837/files

**Comment by kamikaze** [comment]
same here

**Comment by kamikaze** [comment]
> @kamikaze @Hukha What's the minio-operator version?
> 

minio/operator:v5.0.10

**Comment by kamikaze** [comment]
![image](https://github.com/minio/operator/assets/52880/32f47e48-3050-47dc-bcf8-c152bad43e36)

**Comment by jiuker** [comment]
> ![image](https://user-images.githubusercontent.com/52880/283716253-32f47e48-3050-47dc-bcf8-c152bad43e36.png)

Yeah. That be fixed in 5.0.11 @kamikaze

**Comment by b-thiswatch** [comment]
@jiuker is there an ETA on when 5.0.11 will be released?

**Comment by allanrogerr** [comment]
5.0.11 is released
