### ISSUE TITLE
After tenant deletion, certificate keep exists in cluster

### ISSUE THREAD

**Issue by david-nano** [minio/operator#1843]
I've deleted a tenant from the operator, the whole resources seem to be deleted fine, but the certificate exists

## Expected Behavior
Once the tenant is deleted, the deletion progress should be removed it.

## Current Behavior
It's kept to be exists:
```
$ kubectl get certificatesigningrequests.certificates.k8s.io 
NAME                  AGE   SIGNERNAME                      REQUESTOR                                             REQUESTEDDURATION   CONDITION
test-minio-test-csr   18m   kubernetes.io/kubelet-serving   system:serviceaccount:minio-operator:minio-operator   <none>              Approved,Issued

```
## Possible Solution
Add deletion to the delete progress.

## Steps to Reproduce (for bugs)
1. Install the minio operator
2. create new tenant
3. delete the tenant

## Context
Not relevant

## Regression
Not relevant

## Your Environment
* Version used (`minio-operator`): minio/operator:v5.0.10
* Environment name and version (e.g. kubernetes v1.17.2):   kubernetes  v1.24.17
* Server type and version: minio-operator using helm chart
* Operating System and version (`uname -a`): not relevant
* Link to your deployment file: internal

**Comment by pjuarezd** [comment]
Why is the CSR not being deleted a problem? Is this a problem being faced or just a nice to have?

K8s will delete CSR's automatically in a matter of hours anyways see docs
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#request-signing-process

Also Operator will not tripple with existing CSR's if an old CSR still exists, Operator already handles this scenario.

**Comment by david-nano** [comment]
@pjuarezd It's not a blocker or a critical problem, but we don't want junk inside the cluster when deleting the tenant.
But in any case, the link says more then I need to be assured. Thank you.
