### ISSUE TITLE
Helm chart version outdated (4.3.7 instead of 5.0.10)

### ISSUE THREAD

**Issue by Hukha** [minio/operator#1846]
The helm chart refers to version 4.3.7 instead of 5.0.x. Looks that refers to the last release that had minio-operator-x.x.x naming instead of the new operator-x.x.x.

## Expected Behavior

Helm install installing latest version.

## Current Behavior

Installs 4.3.7

## Possible Solution

I guess update naming of releases or helm chart.

## Steps to Reproduce (for bugs)

1. Just try to install minio operator version 5.0.10 using helm or installing the default one and see that is not the latest.

## Context

This caused me problems with default tenant creation and repo value files missmatch.

## Your Environment

* Version used (`minio-operator`): 4.3.7 or 5.0.10
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes 1.23.7
* Server type and version:
* Operating System and version (`uname -a`): Debian 5.10
* Link to your deployment file:

**Comment by jiuker** [comment]
have you  update your helm charts repo?

**Comment by Hukha** [comment]
> have you updated your helm charts repo?

Yes, "https://operator.min.io/" points to 4.3.7 version

**Comment by Hukha** [comment]
So, after testing seems that I was using "minio-operator" instead of "operator". One points to 4.3.7 and the other points correctly to 4.3.7-5.0.10.
Even though I was using it "wrong", this makes very confusing the versioning.

My bad, I'll close the issue.
