### ISSUE TITLE
OLM (community-operators) not have new and current release version

### ISSUE THREAD

**Issue by sergey-kudriavtsev** [minio/operator#1849]
@fibbers  @fibbers  @tobiasmcnulty  @cniackz

**Previously, the update was made (@cniackz) from a private fork https://github.com/cniackz/community-operators**

Currently this should be done visibly by a script
[community-operators/update-community-operator.sh ](https://github.com/minio/operator/pull/1179/files/dd2a862a0604276c5ecee13c6573dc82644e5c9c) ( [Pull Request](https://github.com/minio/operator/pull/1179) )

**But I believe the script has never made a Pull requests**  😱😱😱😱😱

#### The OLM public packagemanifest must include the currently available versions of the operator.
Example **mondoo-operator**:
-  [ operatorhub.io ](https://operatorhub.io/operator/mondoo-operator)
![image](https://github.com/minio/operator/assets/13169606/9b977d47-1c73-4e37-93ae-a0476f666675)

- kubectl get packagemanifest mondoo-operator -o yaml
![image](https://github.com/minio/operator/assets/13169606/c0592474-5047-4408-a22a-33803043a168)

- [community-operators](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/mondoo-operator/ci.yaml)
![image](https://github.com/minio/operator/assets/13169606/78f74c41-5b7b-4d6b-9396-23d31522ac22)

- [Pull requests](https://github.com/k8s-operatorhub/community-operators/pulls?q=mondoo-operator)
![image](https://github.com/minio/operator/assets/13169606/fb64e940-fc11-43ba-9a60-fffd4ce43e25)

## Current Behavior
-  [ operatorhub.io ](https://operatorhub.io/operator/minio-operator)
![image](https://github.com/minio/operator/assets/13169606/fdf21448-5c79-4258-8dd6-7ec3cf2b7338)
- kubectl get packagemanifest minio-operator -o yaml
![image](https://github.com/minio/operator/assets/13169606/344639f1-8ec2-4465-ae9c-aa71f1f3a40c)

- [community-operators](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/minio-operator/ci.yaml)
![image](https://github.com/minio/operator/assets/13169606/23cfd101-eec0-464e-ac91-55c5fa19531b)

- [Pull requests](https://github.com/k8s-operatorhub/community-operators/pulls?q=minio)
![image](https://github.com/minio/operator/assets/13169606/f16e66da-6c3a-4702-a497-735b2803d7c5)

## Possible Solution
Please, add the latest versions  via Pull requests!
1. [Manually Pull requests](https://github.com/k8s-operatorhub/community-operators/pulls?q=minio)
2. Improve the script (@community-operators/update-community-operator.sh)
3.  Perhaps you need to have your own fork of Community-operators, update it via script, and then run a Pull Request command through the script into the original repository (alternatively look at automation from other operators)?

## Steps to Reproduce (for bugs)
-  [ operatorhub.io ](https://operatorhub.io/operator/minio-operator)
-  [community-operators](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/minio-operator/ci.yaml)
-  [Pull requests](https://github.com/k8s-operatorhub/community-operators/pulls?q=minio)
-  kubectl
```sh
kubectl get packagemanifest minio-operator -o yaml
```

## Context
GitHub Actions or kubectl

## Your Environment

* Version used (`minio-operator`): minio-operator v5.0.3
* Environment name and version (e.g. kubernetes v1.17.2): v1.26.9
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by sergey-kudriavtsev** [comment]
I think the current method of integration is described here
https://redhat-openshift-ecosystem.github.io/community-operators-prod/operator-release-process/

_I hope that your repository will be available not only for RedHat_

**Comment by cesnietor** [comment]
we'll discuss internally which ones we'll support / maintain. cc @cniackz

**Comment by pjuarezd** [comment]
We came to a point where maitining a copy on many repositories become a burden, we had to handpick the repositories authorized to be maintained and operatorhub.io is not one of these.

Please consider using [kustomization](https://github.com/minio/operator?tab=readme-ov-file#1-install-the-minio-operator-via-kustomization) instead since is our prefefered install method.
