### ISSUE TITLE
Openshift community operators respository

### ISSUE THREAD

**Issue by ianb-mp** [minio/operator#1929]
**Is your feature request related to a problem? Please describe.**

Minio operator is available via Redhat Marketplace, and so visible when searching OperatorHub from Openshift. However it is not published to the [Openshift community operators repo](https://github.com/redhat-openshift-ecosystem/community-operators-prod), and so not visible in OperatorHub when using [OKD](https://okd.io).

**Describe the solution you'd like**
Please publish Minio operator to the Openshift community operators repo  - see instructions here: https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/docs/packaging-operator.md

**Comment by cniackz** [comment]
I need to discuss this internally to determine if we really want to be present in more catalogs than we currently are.

**Comment by ianb-mp** [comment]
On second thoughts, I see Minio operator is published to [operatorhub.io](https://operatorhub.io/operator/minio-operator) which can be added to OKD clusters, so perhaps that is sufficient.

**Comment by cniackz** [comment]
Okay, thank you, @ianb-mp, for confirming that. We will close this, as we currently have limited bandwidth to support additional catalogs.
