### ISSUE TITLE
minio tenant is stuck in pending state

### ISSUE THREAD

**Issue by oluwafemiayo** [minio/operator#1943]
logs: Defaulted container "minio" out of: minio, sidecar, validate-arguments (init)

**Comment by jiuker** [comment]
Please check the pvc status.

**Comment by Nexusfm** [comment]
Hi.
I have the same problem:

-Configuration:
#kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

#kubectl minio version
Kubectl-Plugin Version: v5.0.11

#kubectl directpv --version
directpv version v4.0.10

- Namespaces
#kubectl get ns
NAME                   STATUS   AGE
directpv               Active   19d
ecetenant              Active   21m
minio-operator         Active   5d2h

- Tenant creation - Pod
#kubectl get pods -n ecetenant -o wide
NAME                  READY   STATUS    RESTARTS   AGE     IP       NODE     NOMINATED NODE   READINESS GATES
ece-tenant-pool-0-0   0/2     Pending   0          6m53s   <none>   <none>   <none>           <none>


-Tenant creation event
ece-tenant
Namespace: ecetenant / Capacity: 512.0 TiB
Events
Type	Reason	Age	Message	
Normal	CSRCreated			18 minutes 	MinIO CSR Created	
Normal	SvcCreated			18 minutes 	MinIO Service Created	
Normal	SvcCreated			18 minutes 	Console Service Created	
Normal	SvcCreated			18 minutes 	Headless Service created	
Normal	SACreated			18 minutes 	Service Account Created	
Normal	RoleCreated			18 minutes 	Role Created	
Normal	BindingCreated		18 minutes 	Role Binding Created	
Normal	PoolCreated			18 minutes 	Tenant pool pool-0 created	
**_Warning	UsersCreatedFailed	3 minutes 	Users creation failed: Put "ht...	
Users creation failed: Put "https://minio.ecetenant.svc.cluster.local/minio/admin/v3/add-user?accessKey=xxxxxxxxxxxxx": dial tcp 10.101.75.68:443: connect: connection refused_**


- Logs 
#kubectl logs -n ecetenant ece-tenant-pool-0-0   (All pods the same message)
Defaulted container "minio" out of: minio, sidecar, validate-arguments (init)

#kubectl logs -n minio-operator console-75dc7dc944-qphgw
I0131 10:48:09.855239       1 event.go:298] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"ecetenant", Name:"ece-tenant", UID:"b9cb6f66-fa82-4b0d-bc2a-abdf43b3bcea", APIVersion:"minio.min.io/v2", ResourceVersion:"16728813", FieldPath:""}): type: 'Warning' reason: 'UsersCreatedFailed' Users creation failed: Put "https://minio.ecetenant.svc.cluster.local/minio/admin/v3/add-user?accessKey=xxxxxxxxxxxxx": dial tcp 10.101.75.68:443: connect: connection refused

#kubectl logs -n minio-operator minio-operator-5c58f669b-lz95n
W0131 10:43:43.013558       1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp"
running PreBind plugin "VolumeBinding": binding volumes: provisioning failed for PVC "data0-ece-tenant-pool-0-0"

**Comment by jiuker** [comment]
> Hi. I have the same problem:
> 
> -Configuration: #kubectl version Client Version: v1.28.3 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.28.3
> 
> #kubectl minio version Kubectl-Plugin Version: v5.0.11
> 
> #kubectl directpv --version directpv version v4.0.10
> 
> * Namespaces
>   #kubectl get ns
>   NAME                   STATUS   AGE
>   directpv               Active   19d
>   ecetenant              Active   21m
>   minio-operator         Active   5d2h
> * Tenant creation - Pod
>   #kubectl get pods -n ecetenant -o wide
>   NAME                  READY   STATUS    RESTARTS   AGE     IP       NODE     NOMINATED NODE   READINESS GATES
>   ece-tenant-pool-0-0   0/2     Pending   0          6m53s
> 
> -Tenant creation event ece-tenant Namespace: ecetenant / Capacity: 512.0 TiB Events Type Reason Age Message Normal CSRCreated 18 minutes MinIO CSR Created Normal SvcCreated 18 minutes MinIO Service Created Normal SvcCreated 18 minutes Console Service Created Normal SvcCreated 18 minutes Headless Service created Normal SACreated 18 minutes Service Account Created Normal RoleCreated 18 minutes Role Created Normal BindingCreated 18 minutes Role Binding Created Normal PoolCreated 18 minutes Tenant pool pool-0 created **_Warning UsersCreatedFailed 3 minutes Users creation failed: Put "ht... Users creation failed: Put "https://minio.ecetenant.svc.cluster.local/minio/admin/v3/add-user?accessKey=xxxxxxxxxxxxx": dial tcp 10.101.75.68:443: connect: connection refused_**
> 
> * Logs
>   #kubectl logs -n ecetenant ece-tenant-pool-0-0   (All pods the same message)
>   Defaulted container "minio" out of: minio, sidecar, validate-arguments (init)
> 
> #kubectl logs -n minio-operator console-75dc7dc944-qphgw I0131 10:48:09.855239 1 event.go:298] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"ecetenant", Name:"ece-tenant", UID:"b9cb6f66-fa82-4b0d-bc2a-abdf43b3bcea", APIVersion:"minio.min.io/v2", ResourceVersion:"16728813", FieldPath:""}): type: 'Warning' reason: 'UsersCreatedFailed' Users creation failed: Put "https://minio.ecetenant.svc.cluster.local/minio/admin/v3/add-user?accessKey=xxxxxxxxxxxxx": dial tcp 10.101.75.68:443: connect: connection refused
> 
> #kubectl logs -n minio-operator minio-operator-5c58f669b-lz95n W0131 10:43:43.013558 1 warnings.go:70] unknown field "spec.pools[0].volumeClaimTemplate.metadata.creationTimestamp" running PreBind plugin "VolumeBinding": binding volumes: provisioning failed for PVC "data0-ece-tenant-pool-0-0"

Please check pvc status.

**Comment by jiuker** [comment]
kubectl get pvc -n yournamespace
kubectl get events -n yournamespace

**Comment by NosIreland** [comment]
> Hi.
> 
> I have solved the problem. I was assigning the wrong disk size when creating the tenant
> 
> Thanks

Hi,
Can you provide more details how you solved this. I have brand new setup with same issue and not sure what I am missing.
Thanks
