### ISSUE TITLE
Allow using of latest `cpuv1` image for tenant

### ISSUE THREAD

**Issue by zdzichu** [minio/operator#1961]
**Is your feature request related to a problem? Please describe.**
Some servers (like my k8s nodes) require a `-cpuv1` container image; see https://github.com/minio/minio/issues/18365
Operator's tenant console allows specifying the image. At the same time, the description hints *If blank, then latest build will be used.* 
There's no way to get *latest* and `cpuv1` at the same time. To get `cpuv1` image, I need to provide exact RELEASE-x.y image.

**Describe the solution you'd like**
I would like to have *latest* **and** `cpuv1` at the same time. I.e. I would like to be able to leave *Image* empty, to get the latest image, but at the same time I would like to specify that I need a `cpuv1` image.
A checkbox would be enough, I think.

**Describe alternatives you've considered**
I don't see any alternatives.

**Additional context**
![image](https://github.com/minio/operator/assets/496236/46109875-80fd-4d3a-822a-70225c322235)

**Comment by harshavardhana** [comment]
Operator is not meant to be used on legacy hardware. Unfortunately we may not be able to support it.
