### ISSUE TITLE
"oc minio proxy" using the wrong port (redirect broken)

### ISSUE THREAD

**Issue by McMac** [minio/operator#1964]
I am using the OpenShift local cluster (4.14) and installed MinIO (5.0.11) via the operator provided in the OperatorHub.

On https://min.io/docs/minio/kubernetes/openshift/operations/installation.html :

__5) Access the Operator Console__

```sh
❯ oc minio proxy
Starting port forward of the Console UI.

To connect open a browser and go to http://localhost:9090

Current JWT to login: eyJh...
```

however: 

`curl http://localhost:9090
<a href="https://localhost:9090/">Moved Permanently</a>.`

This will never work. 

One can use as a workaround:
`k port-forward service/console 9090 9443 -n minio-operator`

and then get the token via:
`kubectl -n minio-operator  get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode`

**Fix required:** _--> change `oc minio proxy` to forward either 9090 *and* 9443 or just forward 9443._
(couldn't figure out how to make this change myself)

--edit:

```sh
❯ kubectl get svc/console -n minio-operator -o json | jq -r '.spec.ports'
[
  {
    "name": "http",
    "port": 9090,
    "protocol": "TCP",
    "targetPort": 9090
  },
  {
    "name": "https",
    "port": 9443,
    "protocol": "TCP",
    "targetPort": 9443
  }
]
```

**Comment by cesnietor** [comment]
we deprecated the `kubectl minio` command which is being used for oc minio proxy, so this won't work anymore.
Please refer to https://min.io/docs/minio/kubernetes/openshift/operations/installation.html#access-the-operator-console
