### ISSUE TITLE
Allow deployment of multiple operators per cluster in Helm chart

### ISSUE THREAD

**Issue by interone-ms** [minio/operator#1972]
**Is your feature request related to a problem? Please describe.**

We operate one beefy AWS EKS cluster for a multitude of internal projects for cost efficiency reasons. Now, when we have multiple projects (or multiple branches) that need MinIO, we can't deploy multiple completely separate sets of operators and tenants (which we would like to do to be able to test version upgrades without having to pay for an extra EKS cluster).

The root cause is that while the CRDs are scoped to the operator's namespace (which by the way does not work in Helm at the moment, see https://github.com/helm/helm/issues/12779), the ClusterRole/ClusterRoleBinding names are hardcoded in the chart (https://github.com/minio/operator/blob/master/helm/operator/templates/operator-clusterrole.yaml) and so there can only be one operator per cluster.

**Describe the solution you'd like**

The operator and console role/rolebinding specs should carry a prefix/suffix, e.g. `{{ .Release.Namespace }}`, and it should be investigated if the working of the operator actually supports the usecase.

**Comment by pjuarezd** [comment]
@interone-ms MinIO Operator is designed as a Cluster level Operator, only one per Cluster, we cannot change it to make it namespace level.

Please conscider running a smaller EKS testing cluster, this is a better pattern for testing, specially when checking compatibillity with new k8s API versions.
