### ISSUE TITLE
Just trying to install via Helm: release 5.0.12 does not exists on quay.io/minio/operator

### ISSUE THREAD

**Issue by urbaman** [minio/operator#1976]
## Expected Behavior

The pods should easily pull the images

## Current Behavior

The 5.0.12 image refered in the chart does not exists

## Possible Solution

Publish the image before updating the chart?

## Steps to Reproduce (for bugs)

Just install the operator chart vanilla.

## Context

Installation fails

## Your Environment

Not relevant

**Comment by xoxys** [comment]
IMO the release process is still broken from a user perspective, see https://github.com/minio/operator/issues/1871#issuecomment-1816468040

**Comment by urbaman** [comment]
Yes, it seems so. Let's see if they can do something about it or if we always have to stumble over it.

I mean, I'm not even managing a CI/CD upgrade pipeline, I'm just trying to install it...

**Comment by pjuarezd** [comment]
Release 5.0.12 container images have been published

**Comment by dakr0013** [comment]
The same problem occurs with 5.0.13, too. We use renovate and renovate says there is a new version 5.0.13. But there is no Release in Github and no Image in quay. In my opinion this is not solved.

**Comment by pschichtel** [comment]
I'm wondering why this keeps happening recently. Apparently the helm chart deployment is triggered by the release commit, but the image build is triggered at a later point. I personally have my argocd auto-updating the operator helm chart on patch releases and have a job that checks if I'm pulling latest versions, which makes this pretty annoying :D (either the uptodate check fails or the deployment fails).

@pjuarezd can't these processes happen together?

**Comment by xoxys** [comment]
Almost every other provider that offers helm charts can do releases correctly. So technically it _is_ possible, but after 3 issues on this topic and already 13 thumbs up on this particular issue, the Minio team just doesn't want to listen to feedback or doesn't care. Instead, issues are closed as quickly as possible without any real solution.

In the end, people can still create their own diagrams or customizations if the problem really bothers them. Is that useful in an open source project, probably not :shrug:
