### ISSUE TITLE
MINIO_OPERATOR_CSR_SIGNER_NAME env variable is ignored if detected platform is EKS

### ISSUE THREAD

**Issue by jplewes** [minio/operator#1985]
MINIO_OPERATOR_CSR_SIGNER_NAME env variable is discarded if detected platform is EKS

## Expected Behavior
MINIO_OPERATOR_CSR_SIGNER_NAME should override the CSR Signer Name when present.

## Current Behavior
If the underlying platform is detected as an EKS variant, the MINIO_OPERATOR_CSR_SIGNER_NAME env variable is never used.   This is the case for EKS Anywhere which does not run in AWS.

## Possible Solution
File:  operator/pkg/controller/certificates/csr.go
Function:   func GetCSRSignerName(clientSet kubernetes.Interface) string { ... }
Add logic to bypass EKS detection if the env variable was populated with a custom value.

## Steps to Reproduce (for bugs)
1.  Install an EKS Anywhere kubernetes cluster on bare metal/vsphere/nutanix etc..
2.  Provide the following in a values.yaml file for the helm chart:
```
operator:
  env:
    - name: MINIO_OPERATOR_CSR_SIGNER_NAME
      value: "kubernetes.io/kubelet-serving"
```
4.  Install the chart.
6.  Observe that the CSR generated has a CSR Signer Name of "beta.eks.amazonaws.com/app-serving" instead of "kubernetes.io/kubelet-serving"

## Context
EKS Anywhere will not issue the CSR

## Regression
No

## Your Environment
* Version used (`minio-operator`): Helm Chart: 5.0.12
* Environment name and version (e.g. kubernetes v1.17.2):  EKS Anywhere v0.18.6, Kubernetes 1.27
* Server type and version: vSphere Hypervisor
* Operating System and version (`uname -a`): BottleRocket
* Link to your deployment file:

**Comment by romanvilu** [comment]
Same here, but with the usual EKS cluster.

**Comment by pjuarezd** [comment]
You can Make Operator change the CSR name to `beta.eks.amazonaws.com/app-serving` using the `MINIO_OPERATOR_RUNTIME=EKS ` env variable. @jplewes

**Comment by pjuarezd** [comment]
Also you could use `MINIO_OPERATOR_RUNTIME=K8S` to make Operator use the `kubernetes.io/kubelet-serving`, but I see we are overwriting this and the `MINIO_OPERATOR_CSR_SIGNER_NAME` env when the detected runtime is EKS, we'll fix that!
