### ISSUE TITLE
couldn't pull docker pull the "minio/k8s-operator:v3.0.2" image

### ISSUE THREAD

**Issue by amgads** [minio/operator#200]
I'm trying to try installing minio:
======================
Trying to get pull the latest minio docker image, but getting timeout

docker pull minio/k8s-operator:v3.0.2
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

## Regression
 No
 v3.0.2

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.17.2
* Server type and version:
* Operating System and version (`uname -a`): linux CentOS 7.8
* Link to your deployment file:

**Comment by harshavardhana** [comment]
> Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Looks like a network error please fix your local network

```
docker pull minio/k8s-operator:v3.0.2
v3.0.2: Pulling from minio/k8s-operator
544a831e0675: Pull complete
e51bc1a06705: Pull complete
Digest: sha256:43a3476717512e78a08f3bab9bc03e2a2222703ca75a82f793af192918d01ea3
Status: Downloaded newer image for minio/k8s-operator:v3.0.2
```

**Comment by amgads** [comment]
Thanks Harshavardhana -- found IPtables setup
