### ISSUE TITLE
Setting sidecar and initcontainer images independently

### ISSUE THREAD

**Issue by olelink** [minio/operator#2009]
**Is your feature request related to a problem? Please describe.**
This was requested before elsewhere but I do not think the topic was well described:

- There needs to be a method to override the images for the sidecar and initcontainers in the helm charts.  I know when this was originally discussed there was an argument that people should not use custom images, however, this problem is larger than that:

1. There are environments that both have no internet access, and cannot have internet access.  These environments need to specify a local registry to pull the image from.  Since this cannot be done, the deployment will fail, trying to reach docker.io via the internet
2. You have environments where people are using porter bundles and the associated registry to build a package and deploy minio.  These environments will pull the main image from porter, but reach out to the internet/docker.io for the sidecar and initcontainers.  The tagging in porter is different than the charts allow for
3. You need to be able to specify a registry when working in specialized or unique environments as noted [here](https://github.com/minio/operator/issues/1632#issuecomment-1949198009)

**Describe the solution you'd like**

- I'd like to have an option in the values to specify both the image and tag of initcontainers and sidecars

**Describe alternatives you've considered**
- some type of mapping?

**Additional context**
Here is someone's [original request](https://github.com/minio/operator/issues/1632).  This was not my request but where I saw the response to a similar request.  I do not know that individual's use case, but there are tons of use cases where this is important

**Comment by dwoldo** [comment]
+1 I have dozens of clusters deployed that each environment maintains a security boundary which includes the image registry. We've historically duplicated the images we use from public registry to the clusters unique image registry. Without the ability to override as described, this blocks/limits our ability to use the MinIO operator.

**Comment by cesnietor** [comment]
hi @olelink  we'll add some steps on how to configure the spec to use the private registry. We won't allow custom images as noted in the issue you posted.

**Comment by cniackz** [comment]
When encountering this issue, the solution involves configuring the private registry in the tenant spec as follows:

```yaml
spec:
  certConfig: {}
  configuration:
    name: storage-configuration
  features:
    domains: {}
  image: internal-registry/minio:RELEASE.2023-01-12T02-06-16Z
  imagePullSecret:
  - name: registry-creds
```

Additionally, ensure that the Operator image is also stored in your private registry. When retrieved, both the Operator image for the Operator itself and the init and sidecar containers will originate from this internal registry. Thus, there is no necessity for custom images for these containers, as mentioned earlier.

**Comment by jrolachea3** [comment]
From what I've been able to test, this works for changing the repo for the main image, but the initcontainers and sidecar will still pull from docker.io.  (the operator images).  We do have the operator image in the registry but it still automatically pulls from docker.io

**Comment by cniackz** [comment]
Moreover, this option is also available in the Operator's Deployment. Since the Operator's deployment offers the same image option, the image source for the tenant will be identical. Could you please provide your Operator's deployment for reference?

**Comment by cniackz** [comment]
In other words, Operator's deployment image and Tenant's images should come from same private registry to avoid this problem.

**Comment by jrolachea3** [comment]
This ended up being a me problem.  Istio proxy was delaying the start of minio operator and it was preventing the operator from correctly pointing the minio tenant to the correct repo

**Comment by ravindk89** [comment]
Hey folks - I just confirmed during a troubleshooting setup that setting `MINIO_OPERATOR_IMAGE=myrepo.com/minio/operator:<TAG>` as part of the `deployments.app/minio-operator` envvar list does work for overriding the sidecar images.

**Comment by cniackz** [comment]
Thank you @ravindk89 for confirming the finding!
