### ISSUE TITLE
Need to detect changes in `resources` per zone on Tenant and apply the change to the statefulset

### ISSUE THREAD

**Issue by dvaldivia** [minio/operator#202]

**Comment by harshavardhana** [comment]
https://github.com/minio/operator/issues/170 we shouldn't apply any change to existing statefulset, since any change i.e 

- increase in the number of servers
- increase in the number of drives

Won't work unless its a zone expansion - if an existing zone is being meddled with, should be rejected.

**Comment by harshavardhana** [comment]
if the change is just in the change in memory, cpu then we can proceed to deploy.

**Comment by dvaldivia** [comment]
Fixed by #209
