### ISSUE TITLE
helm chart issue: minio operator image 5.0.14 does not exist in quay.io

### ISSUE THREAD

**Issue by manju-rn** [minio/operator#2037]
The updated helm chart is incorrect as it points to operator image 5.0.14 which does not exist in quay.io
output of `helm search repo minio-operator`
```
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
minio-operator/minio-operator   4.3.7           v4.3.7          A Helm chart for MinIO Operator
minio-operator/operator         5.0.14          v5.0.14         A Helm chart for MinIO Operator
minio-operator/tenant           5.0.14          v5.0.14         A Helm chart for MinIO Operator
```
The pod fails with ImageBackPullOff since it cannot find image 5.0.14 version in quay.io.  The latest version there in 5.0.13. Here is the snapshot from the site https://quay.io/repository/minio/operator?tab=tags

![image](https://github.com/minio/operator/assets/26291847/404868ca-662b-4351-92ed-b05c7da690b9)

**Comment by harshavardhana** [comment]
We didn't publish the release yet, thanks for letting us know. We will be making a release soon.

**Comment by manju-rn** [comment]
okay I see the v5.0.14 now
![image](https://github.com/minio/operator/assets/26291847/ea1cffa6-13b6-42c6-ad22-a6cbd7045760)
