### ISSUE TITLE
Register to MinIO Subscription Network via Operator is not working

### ISSUE THREAD

**Issue by cniackz** [minio/operator#2042]
Cannot register to Subnet via Operator as the transaction is pending and then after some time it becomes 500 and registration is not possible at my end:

<img width="1728" alt="Screenshot 2024-03-22 at 1 07 59 PM" src="https://github.com/minio/operator/assets/6667358/7a5e3cad-50e3-49b1-ae98-86c279776f39">

<img width="1728" alt="Screenshot 2024-03-22 at 1 09 07 PM" src="https://github.com/minio/operator/assets/6667358/5e765985-79f0-42cd-8a79-b6154d8cd89e">

```
{
    "code": 500,
    "detailedMessage": "Server not initialized, please try again.",
    "message": "an error occurred, please try again"
}
```

## Expected Behavior

Operator can register cluster

## Current Behavior

Operator cannot register cluster

## Possible Solution

Workaround is to register the tenant one by one: `mc license register --license ./minio.license ALIAS --airgap`

## Steps to Reproduce (for bugs)

1. Login into Operator
2. Go to register section
3. Provide your email and password to get the license
4. Try to click on register button, it wont be possible

## Context

It would be nice to be able to register all my tenants at once.

## Regression

I assume yes

## Your Environment

* Version used (`minio-operator`):

5.0.12

* Environment name and version (e.g. kubernetes v1.17.2):

1.25

* Server type and version:

kind local testing

* Operating System and version (`uname -a`):

$ uname -a
Darwin Cesars-MacBook-Pro.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64

* Link to your deployment file:

https://github.com/cniackz/bash-config/blob/main/common.sh

**Comment by jiuker** [comment]
https://github.com/minio/operator/blob/6a99fbf2cb890f7eae7e579b3a7421c6cb47be95/api/operator_subnet.go#L182-L185

**Comment by cesnietor** [comment]
closing
