### ISSUE TITLE
tenantns failed to get storage info: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by wangchao732** [minio/operator#2046]
minio/operator:v5.0.7

all filestore-pool is ready.

![1711509226980](https://github.com/minio/minio/assets/19440083/f554ad46-3cd8-43db-bdc4-99fd30aa7a58)

**Comment by jiuker** [comment]
Could you show the tenant's status?

**Comment by allanrogerr** [comment]
@wangchao732 Is this still an issue?

**Comment by pjuarezd** [comment]
Closing this ticket for lack of response @wangchao732 , if you are still facing the issue, please make sure to use latest Operator version
