### ISSUE TITLE
OpenShift/OCP 4.15 support

### ISSUE THREAD

**Issue by corstuur** [minio/operator#2050]
**Is your feature request related to a problem? Please describe.**
The minio operator is currently not available for OCP 4.15

**Describe the solution you'd like**
I would like to have support for 4.15 of OCP.

**Describe alternatives you've considered**
None

**Additional context**
The operator is available for 4.14 but not available in the 4.15 index.

**Comment by osca-mwongera** [comment]
I have the same experience, the operator catalogue source using the image registry.redhat.io/redhat/certified-operator-index:v4.15 does not list the MINIO operator. This is common for both the OKD releases and OCP.

**Comment by ramondeklein** [comment]
The catalog also shows only v4.11, 4.12, 4.13 and 4.14 as the supported versions. It should be made available for 4.15 too.

**Comment by pjuarezd** [comment]
Operator 5.0.14 have been published with support for OCP 4.15
