### ISSUE TITLE
Tenant provisioning incorrectly auto-detect cluster config #OKD

### ISSUE THREAD

**Issue by parseltongued** [minio/operator#2092]
## Current Behavior
I have a disconnected / air-gap 3-node OKD 4.15 production cluster currently installed with a 1-drive direct-pv installed per node (intending to upgrade 2 drive per node).

However in `resource allocation`, it shows 

-- | --
-- | --
Number of Servers | 4
Drives per Server | 4
Drive Capacity | 64.0 GiB
Total Volumes | 16

![image](https://github.com/minio/operator/assets/120156491/76a0d844-0168-4cea-ae96-bdc0e16f54e0)

Installation of all minio-operator components seems installed correctly.
![image](https://github.com/minio/operator/assets/120156491/eebc4ca1-09bd-4527-a8d7-602e2a004c30)

## Issues
1. These values are incorrect, I suspect it's detecting the number of filesystems in the control-pane (but also incorrect).
![image](https://github.com/minio/operator/assets/120156491/96a3fa94-f557-413c-a817-e77cdcb0aeeb)

2. `Number of servers`, `Drives per server`, `Total size` fields are grey-out, not configurable.

3. Understand Min.io Kubenetes variant uses PVC via direct-pv, shouldn't `drives per server` be transparent using PVC? (just trying to understand why is this field still needed)

## Expected Behavior
`Resource allocation` should show 3, 1, 1Tb as of current configuration
`Number of servers`, `Drives per server`, `Total size` fields are configurable.

## Deployment information:
oc minio version: Kubectl-Plugin Version: v5.0.14
Installed DirectPV version: directpv version v4.0.10
OKD Cluster Version: 4.15.0-0.okd-2024-03-10-010116
Kernel version: v1.28.2-3598+6e2789bbd58938-dirty

 Thank you.

**Comment by jiuker** [comment]
We will not detect the true capacity of PV or PVC again. Some storage is virtual, and we cannot implement this feature. These displayed values are all configured by you.
