### ISSUE TITLE
Fips Support

### ISSUE THREAD

**Issue by L1ghtman2k** [minio/operator#2093]
**Is your feature request related to a problem? Please describe.**
Most of the minio components are fips compliant, but operator seems to be build using standard crypto library.

**Describe the solution you'd like**
Build operator using `GOEXPERIMENT=boringcrypto`, similarly to https://github.com/minio/minio/blob/e7aa26dc2984c85ff8526178235f296918c92ea8/.github/workflows/go-fips.yml#L43

**Comment by harshavardhana** [comment]
https://dl.minio.io/server/minio/release/linux-amd64/minio.RELEASE.2024-04-18T19-09-19Z.fips

**Comment by L1ghtman2k** [comment]
@harshavardhana, this issue is specifically for minio operator, not minio server

**Comment by harshavardhana** [comment]
Right now there are no plans to support fips with operator.

You have a production requirement please reach out to us via https://min.io/pricing 

For now this issue remains closed, thank you.
