### ISSUE TITLE
Minio-tenant: Provisioning initial users, Users creation failed: context deadline exceeded #OKD

### ISSUE THREAD

**Issue by parseltongued** [minio/operator#2094]
## Current Behavior
I have a disconnected / air-gap 3-node OKD 4.15 production cluster currently installed with 2 drives on each node, 3x2=6 drives.

i've added service account: minio-tenant-sa in oc scc already. 

Encountered this error when creating a tenant via cli:
![image](https://github.com/minio/operator/assets/120156491/d2047adf-0b6c-4050-9e69-56ded350a55f)

## Expected Behavior
minio-tenant successfully created.

## Your Environment
oc minio version: Kubectl-Plugin Version: v5.0.14
Installed DirectPV version: directpv version v4.0.10
OKD Cluster Version: 4.15.0-0.okd-2024-03-10-010116
Kernel version: v1.28.2-3598+6e2789bbd58938-dirty

**Comment by jiuker** [comment]
Show pod list plz.

**Comment by parseltongued** [comment]
> Show pod list plz.

@jiuker Thanks for the prompt reply.
![image](https://github.com/minio/operator/assets/120156491/28e5e1ef-8900-4ceb-a99e-4e2aa1b91eaf)

This is the error stack thrown in one of the pods:
![image](https://github.com/minio/operator/assets/120156491/54d3765d-ecec-435d-9e5c-008a49092c41)

Not sure how to add dns mapping to the oc internal dns.

**Comment by jiuker** [comment]
Check your DNS pod logs.

**Comment by parseltongued** [comment]
> Check your DNS pod logs.

 I got an output like this:
 ![image](https://github.com/minio/operator/assets/120156491/936f900a-4011-40fb-9205-c2dcc6d113ab)

is there any guide on what to look out for?

Thanks!

**Comment by jiuker** [comment]
We will not solve the DNS issue of K8S. The log points to DNS issues, which are not within the scope of operators.
