### ISSUE TITLE
k8s event: Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "controller": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by sober-wang** [minio/operator#2106]
deploy minio cluster ,when I used helm chart package.

k8s version:  1.24.6
helm version: v3.13.1
minio chart: 
- chart operator-5.0.14 
- app-version: v5.0.14

![image](https://github.com/minio/operator/assets/35804630/54bf942b-4199-4437-a05c-c49e1055feef)

**Comment by ramondeklein** [comment]
Could you post the output of `helm ls -n minio`? If you actually used Helm image v5.0.14, then you should also have image `quay.io/minio/operator:v5.0.14` instead of `minio/operator:v4.3.7`.

**Comment by mshanmu** [comment]
I had a similar issue and the answer it is user error.

This happens because of using _docker image import_ instead of using **docker image load**.

When you transfer a docker image between sites, always use **docker image save** and **docker image load**.
