### ISSUE TITLE
Missing assets from 5.0.15 release

### ISSUE THREAD

**Issue by harshitsinghvi22** [minio/operator#2118]
the following link does not contain kubectl-minio assets which is breaking our builds
https://github.com/minio/operator/releases/tag/v5.0.15

All the past releases had around 20+ assets however this release does not have the kubectl-minio packages

**Comment by juvivas** [comment]
What are the steps to follow to carry out the migration from krew plugin to helm or kustomization?

**Comment by pjuarezd** [comment]
Using kubectl like this should be enough

```
kubectl apply -k "github.com/minio/operator?ref=v5.0.15"
```

Here is the installation guide https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-operator-kustomize.html
