### ISSUE TITLE
Which version will the return name not be fixed with 'minio'? 

### ISSUE THREAD

**Issue by iamjackhu** [minio/operator#2125]
https://github.com/minio/operator/blob/7ae65b2d74d1f6a63419c524433205799e73b400/pkg/apis/minio.min.io/v2/names.go#L61

**Comment by iamjackhu** [comment]
At least return a fixed name related with instance's id or namespace? It's better than a fixed constant string 'minio'.

**Comment by ramondeklein** [comment]
Having a fixed name makes it easier to search for it. There will be only one `minio` service per namespace, so there should be no problem.

**Comment by harshavardhana** [comment]
We wanted to keep it that way on purpose, so you are not allowed to run more than one tenant per namespace.

You are free to use your own stateful set and achieve what you want.

An operator is meant for sensible deployment patterns that we recommend. We are not interested in turning this into a complex configuration.

This project would suffer, it is out of the scope at this moment.

**Comment by harshavardhana** [comment]
> global of entire cluster.

it is namespace specific already, the SVC name DNS is scoped via namespace

**Comment by iamjackhu** [comment]
Okey. Thank for reply.
