### ISSUE TITLE
Console UI Problem it's showing wrong information of usage info

### ISSUE THREAD

**Issue by darvik-ai** [minio/operator#2130]
I have install minio-operator 5.0.15 in k8s and create a cluster when I see the usage details it's wrong showing on UI
![Screenshot from 2024-05-23 16-41-20](https://github.com/minio/operator/assets/159222738/bff34317-7a3f-46d1-b6d5-3f2e327b5e62)

Inside minio instance usage 
![Screenshot from 2024-05-23 16-43-51](https://github.com/minio/operator/assets/159222738/c2fb3d9c-e7f1-4648-bf7a-2f58ed515a26)

**Comment by cesnietor** [comment]
We'll try to replicate and investigate.

**Comment by cesnietor** [comment]
closing this since operator ui has been deprecated, see https://github.com/minio/operator/blob/master/docs/notes/v6.0.0.md#whats-new for more.
