### ISSUE TITLE
Upgrade package ip

### ISSUE THREAD

**Issue by ramondeklein** [minio/operator#2147]
NPM package auditing resulted in the following message:
```
└─ ip
   ├─ ID: 1097346
   ├─ Issue: ip SSRF improper categorization in isPublic
   ├─ URL: https://github.com/advisories/GHSA-2p57-rm9w-gvfp
   ├─ Severity: high
   ├─ Vulnerable Versions: <=2.0.1
   │ 
   ├─ Tree Versions
   │  └─ 2.0.1
   │ 
   └─ Dependents
      └─ web-app@workspace:.
```
The [ip NPM package](https://www.npmjs.com/package/ip) has a known security issue and needs to be upgraded. Once the package is upgraded then the line `--ignore '1097346'` can be removed from the `ui.yaml` workflow.

**Comment by ramondeklein** [comment]
There is no updated version available yet.

**Comment by cesnietor** [comment]
context: https://github.com/indutny/node-ip/issues/150

**Comment by msummers42** [comment]
Came across this as a consumer of this package and a user of minio. It appears the upstream has archived the repo. We are considering moving to this fork https://github.com/eggjs/node-ip as we evaluate usage. It's tricky due to the sheer number of dependent projects.

**Comment by ramondeklein** [comment]
@msummers42 Thanks for mentioning that https://github.com/indutny/node-ip is now archived. It looks like our repo isn't affected by the security issue, but relying on an archived package is never a good idea.

@cesnietor I think we should check what exactly depends on this package and how to fix that.

**Comment by pjuarezd** [comment]
now that Operatoe console is deprecated we no longer need to upgrade the `ip` package
