### ISSUE TITLE
Release 5.0.15 is not include MinIO Kubernetes plugin make installation doesn't work

### ISSUE THREAD

**Issue by tyohan** [minio/operator#2149]
The installation instruction from  the official doc [here](https://min.io/docs/minio/kubernetes/upstream/operations/installation.html#install-the-minio-kubernetes-plugin) using the manual Linux installation will instruct specifically to run this command for plugin installation

```
curl https://github.com/minio/operator/releases/download/v5.0.15/kubectl-minio_5.0.15_linux_amd64 -o kubectl-minio
chmod +x kubectl-minio
mv kubectl-minio /usr/local/bin/
```

But running this command `curl https://github.com/minio/operator/releases/download/v5.0.15/kubectl-minio_5.0.15_linux_amd64` will return Not Found response because the plugin is not included in the release 5.0.15. This make the instruction in the documentation won't be work except using the previous release 5.0.14.

**Comment by dvaldivia** [comment]
Hi @tyohan we deprecated the `kubectl-minio` plugin, we are working on updating the documentation.

What I recommend is using kustomize via kubectl to install operator and create tenants

# Install Operator

```shell
kubectl apply -k github.com/minio/operator/\?ref\=v5.0.15
```

# Create a tenant

You can use the examples we provide and customize to your need

```shell
kubectl apply -k github.com/minio/operator/examples/kustomization/base
```

you can look at how the other example overlays modify the base tenant.

This is the better approach as it keeps things declarative


cc @ravindk89
