### ISSUE TITLE
Enhance the status display for tenant creation.

### ISSUE THREAD

**Issue by cniackz** [minio/operator#2170]
**Is your feature request related to a problem? Please describe.**
Yes, it is related to https://github.com/minio/operator/issues/2165

**Describe the solution you'd like**
When there is an issue during tenant creation, such as a persistent volume (PV) issue preventing the tenant from being created, I suggest providing a clear message explaining the problem instead of continuously displaying 'Provisioning initial users.'

**Describe alternatives you've considered**
* count events to determine when there is an error, already tried
* current one is to wait until minio is healthy to actually engage on the creation of a user, seems to be the right approach as of now

**Additional context**
Originated from https://github.com/minio/operator/issues/2165

**Comment by pjuarezd** [comment]
Already fixed on https://github.com/minio/operator/pull/2172
