### ISSUE TITLE
Failed to pull image minio/console

### ISSUE THREAD

**Issue by ptisma** [minio/operator#2197]
I am installing the MiniIO operator by following the official docs, I am installing it via Helm:
https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-operator-helm.html#
```
helm repo add minio-operator https://operator.min.io
helm install my-minio-operator minio-operator/minio-operator --version 4.3.7
```

I am getting the error from one of the console pods:
`Failed to pull image "minio/console:v0.12.3": Error response from daemon: pull access denied for minio/console, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

it seems that this image is deleted from the Dockerhub, is this behaviour bug or intended one, and why has not the official docs been updated?

**Comment by harshavardhana** [comment]
Latest release of operator is v5.0.16 - we do not provide community support for older releases.
