### ISSUE TITLE
Source code archive from the release of v5.0.16 uses v5.0.15 image

### ISSUE THREAD

**Issue by pddg** [minio/operator#2210]
When I get source code tagged with v5.0.16, v5.0.15 is used as the image tag in the manifest.

## Expected Behavior
Source codes that tagged v5.0.16 are using v5.0.16 images.

## Current Behavior
They use v5.0.15 as follows:

```sh
wget https://github.com/minio/operator/archive/refs/tags/v5.0.16.tar.gz
tar xf v5.0.16.tar.gz
kustomize build operator-5.0.16/ | grep 'image: minio'
        image: minio/operator:v5.0.15
        image: minio/operator:v5.0.15
```

## Possible Solution

This repository also seems to have `v5.0.16` **branch**. And this branch seems to be correct.

https://github.com/minio/operator/blob/2e51bd380de2d45d877292e12bf8c3cab5cdfe6e/resources/base/deployment.yaml#L26
https://github.com/minio/operator/blob/2e51bd380de2d45d877292e12bf8c3cab5cdfe6e/resources/base/console-ui.yaml#L292

I can't see the code for the v5.0.16 tag on GitHub because it seems that if there is a tag and a branch with the same name, the branch always takes precedence.

Downloading the contents of this branch instead will probably yield the correct one.

```sh
$ wget https://github.com/minio/operator/archive/refs/heads/v5.0.16.tar.gz
$ tar xf v5.0.16.tar.gz
$ kustomize build operator-5.0.16/ | grep 'image: minio'
        image: minio/operator:v5.0.16
        image: minio/operator:v5.0.16
```

However, this is an inconsistent approach since there is no branch with a version name other than v5.0.16.

## Context
The [document](https://min.io/docs/minio/kubernetes/upstream/operations/installation.html) recommended customizing the manifest on this repository as a template. I obtained the source code from the latest release, and when I tried to work on the customization, I noticed that the tag names did not match the image names.

## Regression

At least in 5.0.15 and 5.0.14, the image and Git tags matched.

```
$ kustomize build operator-5.0.15/ | grep 'image: minio'
        image: minio/operator:v5.0.15
        image: minio/operator:v5.0.15
$ kustomize build operator-5.0.14/ | grep 'image: minio'
        image: minio/operator:v5.0.14
        image: minio/operator:v5.0.14
```

## Your Environment

- macOS 14.5
- kustomize v5.4.2

**Comment by cesnietor** [comment]
please pull the image again, this should be already fixed. thanks for reporting.

**Comment by pddg** [comment]
@cesnietor 
The GitHub Release and corresponding Git Tag appear to have been removed, but the v5.0.16 image is already available on the registry.
https://hub.docker.com/layers/minio/operator/v5.0.16/images/sha256-18ac1eea8bf390ae953503d5c1cd474963b3b4844948f1b58ed11cd0a80d68ae?context=explore

Will these images be updated again when v5.0.16 is released?

**Comment by harshavardhana** [comment]
no they won't be - there were done for internal purposes, for all practical purposes v5.0.15 is fine v5.0.16 is just a rebuild of v5.0.15
