### ISSUE TITLE
Support for OCP 4.16

### ISSUE THREAD

**Issue by Roming22** [minio/operator#2226]
**Is your feature request related to a problem? Please describe.**
The operator is not available on OCP 4.16.

**Describe the solution you'd like**
Update the manifests and submit the new release to OCP 4.16.

**Describe alternatives you've considered**
None

**Additional context**
* It might be that the latest release needs to be registered to https://github.com/redhat-openshift-ecosystem/certified-operators
* It would be great if an ETA could be communicated.

**Comment by cesnietor** [comment]
Propietary releases will be only available on downstream releases. For that you'll need a valid MinIO  Enterprise License. Please [reach out to us](https://min.io/pricing) if you have any doubts :) .

**Comment by Roming22** [comment]
Is that a new policy? We used to be able the operator on OCP without a licence, and still can on 4.15 and lower versions.

**Comment by cesnietor** [comment]
yes, starting from version 6.0.0 please take a look at https://github.com/minio/operator/blob/master/docs/notes/v6.0.0.md#whats-new
