### ISSUE TITLE
Console SVC not created by operator

### ISSUE THREAD

**Issue by Ronan-WeScale** [minio/operator#2228]
In the new release the console svc isn't created

## Expected Behavior
%tenant-name%-console service is created by operator

## Current Behavior
%tenant-name%-console service isn't created by operator

## Possible Solution
rollback to 5.0.15

## Steps to Reproduce (for bugs)
Deploy operator with helm chart 6.0.0
Deploy tenant with helm chart 6.0.0

## Regression
Yes console svc not created

## Your Environment
* Version used (`minio-operator`): minio-operator 6.0.0
* Environment name and version (e.g. kubernetes v1.17.2): v1.27.11

**Comment by Ronan-WeScale** [comment]
That's doesn't create console pod too.

**Comment by harshavardhana** [comment]
Console POD is history https://github.com/minio/operator/blob/master/docs/notes/v6.0.0.md#whats-new

**Comment by Ronan-WeScale** [comment]
@harshavardhana Ok for the pod, but the service wasn't created so the ingress created by the helm chart not working.

**Comment by Ronan-WeScale** [comment]
@harshavardhana please re-open the issue

**Comment by pjuarezd** [comment]
Operator V6 deprecated console, please refer to https://github.com/minio/operator/blob/master/docs/notes/v6.0.0.md#whats-new.

not pods, or service for console will be created  anymore @Ronan-WeScale.

**Comment by dvaldivia** [comment]
Re-openning as the issue seems to be the console service for the tenant is not being created, in this case, a tenant called `my-tenant`  is expected to have a `my-tenant-console` service created for that tenant's embedded console

**Comment by Ronan-WeScale** [comment]
thx @dvaldivia I didn't have the time to propose a PR, but you do the job faster. Maybe I can check for enhance your e2e test to avoid this sort of problem next time ?
