### ISSUE TITLE
certificate signed by unknown authority with operator >= 6 and cert-manager

### ISSUE THREAD

**Issue by sebhoss** [minio/operator#2238]
## Expected Behavior

minio-operator should read/use the provided CA data while talking to a tenant as documented in https://github.com/minio/operator/blob/master/docs/cert-manager.md#minio-tenant-tls-certificates-with-cert-manager.

## Current Behavior

Starting with version 6 of the operator, we always see `certificate signed by unknown authority` in the log output of the operator. The operator seems to detect the secret containing the CA data but does not use it(?):

```
I0723 10:45:48.743418       1 main-controller.go:1459] Secret 'minio-operator/operator-ca-tls-minio-tenant-loki' changed                                                                                                                                                           12:54:41 [65/14601]
I0723 10:45:48.743627       1 main-controller.go:1468] No new certificate was added from secret 'operator-ca-tls-minio-tenant-loki/operator-ca-tls-minio-tenant-loki'
```

Version 5 of the operator logs something differently:

```
I0723 10:54:46.572065       1 operator.go:184] External secret found: operator-ca-tls-minio-tenant-loki
I0723 10:54:46.972865       1 operator.go:188] Appending cert from operator-ca-tls-minio-tenant-loki secret
I0723 10:54:46.995475       1 tenants.go:118] external certificate successfully renewed for the tenant
```

After this, connections seem to be possible with version 5. Version 6 never is able to talk to a tenant.

## Possible Solution

Downgrade to the latest version 5 solved this for us.

## Steps to Reproduce (for bugs)

1. Deploy operator
2. Deploy tenant
3. Follow steps from https://github.com/minio/operator/blob/master/docs/cert-manager.md#minio-tenant-tls-certificates-with-cert-manager
4. See logs of operator

## Context

We are using the operator to provision/manage tenants. If the operator cannot talk to tenants, this won't work.

## Regression

Yes - starting with 6.0.0 and 6.0.1

## Your Environment

* Version used (`minio-operator`): 6.0.1
* Environment name and version (e.g. kubernetes v1.17.2): 1.29.7
* Server type and version: 
* Operating System and version (`uname -a`):
* Link to your deployment file: using the official helm chart for the operator

**Comment by sebhoss** [comment]
Mabye I've spoken too soon? We just updated the operator from v5 to v6 in another environment and got exactly the same error as initially described. We have another (non-operator) service talking to that minio tenant just fine so I'm guessing that this is purely a problem of the operator itself. Therefore, can we re-open this?

@cesnietor do you want me to delete the statefulset but leave the pods running? Otherwise this would cause a service disruption which we really don't want to happen

**Comment by cesnietor** [comment]
@cniackz  could you please take a look on this one?

**Comment by sebhoss** [comment]
Ok I think I figured this out and it was a problem on our end. Changes in our automation wrote the extracted CA data to something like `/tmp/minio-tenant-123-ca.crt` and `kubectl create secret` will use that file name as the field name in the created secret. However, the operator looks for a field which is exactly named `ca.crt` and thus this did not work for us anymore.
