### ISSUE TITLE
Cannot overwrite default sidecar image

### ISSUE THREAD

**Issue by alice-vsk** [minio/operator#2245]
In our company we have to use offline images from our repository by security reasons.
So in version 5.0.11 we have downloaded all necessary minio images and set variable MINIO_OPERATOR_IMAGE just as described [here](https://github.com/minio/operator/issues/2009#issuecomment-2035428734). 

Now in version 6.0.1 it seems it's kind of broken because after setting this variable pod in tenant namespace keeps trying to download init and sidecar images from quay.io/minio/operator-sidecar:v6.0.0.

## Expected Behavior
We set MINIO_OPERATOR_IMAGE environment variable with our repository and init and sidecar images downloading from there.

## Current Behavior
We set MINIO_OPERATOR_IMAGE environment variable with our repository and init and sidecar images still downloading from the default repository.

## Steps to Reproduce (for bugs)
1. Install minio-operator and minio-tenant with helm using non-default images in values.yaml

## Our Environment
* Version used (`minio-operator`): v6.0.1
* Environment name and version: kubernetes v1.28.6
* Server type and version: CentOS Linux release 7.9.2009 
* Operating System and version (`uname -a`): 5.4.278-1.el7.elrepo.x86_64

**Comment by ramondeklein** [comment]
Not sure if you're using Helm to install the operator, but then you could use the `image.repository` and `sidecarImage.repository` values. If you prefer to use environment variables, then please set `OPERATOR_SIDECAR_IMAGE` to the sidecar image.

**Comment by alice-vsk** [comment]
Yes, we're using helm.
It seems adding `sidecarImage.repository` has helped.

Thank you!
