### ISSUE TITLE
Minio 6.0.1: can't set MINIO_OPERATOR_IMAGE env variable which sets the sidecar image

### ISSUE THREAD

**Issue by fouadsemaan** [minio/operator#2258]
Minio version < 6.0.0 allowed us to set the MINIO_OPERATOR_IMAGE variable which set the tenant sidecar image. 

## Expected Behavior
When setting the MINIO_OPERATOR_IMAGE env in the operator, it should set the appropriate sidecar.

## Current Behavior
Currently env variable MINIO_OPERATOR_IMAGE is not respected and sidecar image is hardcoded.

## Possible Solution
The code which sets the env variable was removed [here](https://github.com/minio/operator/commit/9d45aba5ecc5c8c08f047db4bd2a411bd06b37e2#diff-52732d3ec39ef3de250ba276b2f85c749aef6e8f9e34cd6066abaa5f165bdd1aL70).

## Your Environment

* Version used (`minio-operator`): 6.0.1
* Environment name and version (e.g. kubernetes v1.17.2): v1.28.9

**Comment by ramondeklein** [comment]
The sidecar now has its own image in v6 and you can set the `OPERATOR_SIDECAR_IMAGE` variable ([source](https://github.com/minio/operator/blob/ccade59dbe074c10855bc4125226954e1d8229ab/pkg/resources/statefulsets/minio-sidecar.go#L37)).

**Comment by fouadsemaan** [comment]
Appreciate the quick response! I think it might be worth updating the [docs](https://min.io/docs/minio/kubernetes/upstream/reference/operator-environment-variables.html#envvar.MINIO_OPERATOR_IMAGE).

**Comment by ramondeklein** [comment]
@fouadsemaan You're right. I'll forward this to the docs team.
