### ISSUE TITLE
configSecret.existingSecret disappeared from 6.0.2 to 6.0.3 making it impossible to use an existing config secret

### ISSUE THREAD

**Issue by fibbs** [minio/operator#2298]
I am on the bumpy road to upgrade from 5.0.16 to 6.0.3. After having understood by reading some of the issues and discussions here how to use the `existingSecret` setting and how to migrate from `.secrets.name` to using `.configSecret` correctly, I found that in version 6.0.3 of the Helm Chart there is no possibility to use an existing secret anymore. A `grep -R existing` in the `templates` directory of the chart does output nothing at all.

## Expected Behavior
with the values.yaml setting `.configSecret.existingSecret=true` one can provide an environment secret containing a key `config.env` which then contains `export` statements to set `MINIO_ROOT_USER`, `MINIO_ROOT_PASSWORD` and others such as prometheus related vars, compression settings etc.

## Current Behavior
`.configSecret.name` is being tried to create anyways, even if already existing. Worse than that, the helm chart tries to OVERWRITE it and thus tries to delete the settings I might have set there for a reason.

## Possible Solution
With commit https://github.com/minio/operator/commit/1792dfdaccee94b3f44d41aa9a8f3d3b8fbdb57c this has been introduced, but with https://github.com/minio/operator/commit/3a8695bde3a272b80bcbeb22a79b0f763cb47b11 it was (accidently?) removed again. Revert or rework the ladder of the commits?

## Steps to Reproduce (for bugs)
Try to set up a MinIO tenant with an existing env variable secret and set both `.configSecret.name` and `.configSecret.existingSecret: True` and find out that you run into an ugly error message that the resource can not be imported into the current release....

## Regression
Is this issue a regression? I believe yes
If Yes, optionally please include minio-operator version caused the regression: 6.0.3

## Your Environment

* Version used (`minio-operator`): 6.0.3
* Environment name and version (e.g. kubernetes v1.17.2): K8S (RKE2) v1.28.8
* Server type and version: RHEL 8
* Operating System and version (`uname -a`): irrelevant
* Link to your deployment file: irrelevant

**Comment by ramondeklein** [comment]
It looks you're right and @ClemaX also mentioned this in https://github.com/minio/operator/pull/2265/files#r1734684401. We need to introduce `.tenant.configSecret.existingSecret`. When set, we shouldn't create the secret.
