### ISSUE TITLE
Possible incorrect tag

### ISSUE THREAD

**Issue by aqeelat** [minio/operator#2303]
PR #2289 replaced the tag of PolicyBinding with an older operator version. I don't know if this is correct or not (or if it matters)

https://github.com/minio/operator/pull/2289/files#diff-5ac2648c9913f8b0abe4bac1e4dd33003a0895a8c1429e3caae269600ad35632
Raising here because it is unlikely that people look at comments of merged PRs.

**Comment by aqeelat** [comment]
cc @harshavardhana @pjuarezd @jiuker

**Comment by cesnietor** [comment]
this is fixed in #2304
