### ISSUE TITLE
MinIO Operator not available anymore on Openshift

### ISSUE THREAD

**Issue by stanbog** [minio/operator#2359]
## Expected Behavior
We've noticed that on our Openshift clusters that were recently updated to version 4.16, we cannot find anymore the MinIO operator in the OperatorHUB list. We can find this however on lower Openshift versions, like 4.15.
We extensively use the MinIO service as part of our Loki logging solution on our Openshift clusters.

Can you let us know if something changed ? And how can we get the operator back ?

Thank you.

## Your Environment

* Version used (`minio-operator`): latest
* Environment name and version: Openshift 4.16 (kubernetes 1.29.8)

**Comment by jonmosco** [comment]
I had to enable the Marketplace in the OperatorHub:
```
Administration | Cluster Settings | Global Configuration | OperatorHub
```

I changed the configuration to enable the Marketplace, waited for the catalog to update, and then it was available again. I am not sure if this will help your particular situation, but I had a similar situation with the operator being unavailable.

**Comment by Woytek-Polnik** [comment]
Does this mean that there will be no "free option for minio" in OCP?
or it is just about operator and maybe we should switch to operator via helm chart instead of the hub? 
Or you are going to totally abandon minio in favor of aistore?

**Comment by ravindk89** [comment]
The RedHat OpenShift Container Platform is itself enterprise software intended for commercial/enterprise deployments. It follows that products deployed to OCP should also be enterprise software, and for that we have AIStor.

The MinIO Server (minio/minio), CLI tool (minio/mc), and Operator (minio/operator) remain Free and Open Source Software licensed under AGPL3.0 and readily available to support other FOSS stacks in use by the Open Source community. They are the very definition of "free" as in "freedom" as intended by the FSF in their [first bulletin](https://www.gnu.org/bulletins/bull1.txt). Anyone can reuse, remix, and redistribute that code in compliance with the license. 

You are also welcome to review our commit tree insofar as claims of MinIO being abandoned.
