### ISSUE TITLE
Support Certificates Without CA

### ISSUE THREAD

**Issue by sstubbs** [minio/operator#248]
**Is your feature request related to a problem? Please describe.**
I've created a tenant using:
```
externalCertSecret:
    name: letsencrypt-cert
    type: cert-manager.io/v1alpha2
```
This is a letsencrypt secret created by certmanager. When the statefulset is created the pod has an error as `ca.crt` isn't present. If I delete this it seems to work but I'm wondering if this could be done by the operator.

**Describe the solution you'd like**
Perhaps a type could be added without the ca.crt mount.

**Describe alternatives you've considered**
Deleting the mount manually from the statefulset isn't a problem and that is what I'm doing now.

**Comment by sstubbs** [comment]
I've noticed `externalClientCertSecret` doesn't have this problem as it links the ca.crt to the certificate. Perhaps the non client certificate could work in the same way.

**Comment by Alevsk** [comment]
@sstubbs `cert-manager.io/v1alpha2` requires for your secret to have the `ca.crt` field, to support a secret without CA field you can use the type `kubernetes.io/tls` instead in your `externalCertSecret `

**Comment by sstubbs** [comment]
Thank you very much. This solved my issue.
