### ISSUE TITLE
Specify Custom URLs KES and Console

### ISSUE THREAD

**Issue by sstubbs** [minio/operator#249]
**Is your feature request related to a problem? Please describe.**
I'm using https://github.com/minio/operator/blob/master/docs/kes.md with vault backend using approle. It works well when `requestAutoCert: true` however when I set it to false and use my own letsencrypt certificates. the kes job that starts to create the key gives me this error. `too many identities: more than one certificate is present` I think this might be because it's targeting the internal url with a certificate for my public domain. I've looked through the logs of both vault and kes but don't see why this is happening.

I have a similar issue in the console which is easily fixed by altering:
```
          env:
            - name: CONSOLE_MINIO_SERVER
              value: 'https://production-0.minio.svc.cluster.local:9000'
```
in the deployment.

**Describe the solution you'd like**
It would be great if there could be two values in the custom resource:
- to set the minio server url for the console
- to set the kes url

**Describe alternatives you've considered**
I don't know how to fix the kes job but I can manually fix the console deployment.

**Additional context**

**Comment by sstubbs** [comment]
I've tried adding a self signed certificate for kes and am still getting the same error so perhaps it isn't related to the issue with console.

**Comment by sstubbs** [comment]
After some help with this on slack I've realised that kes doesn't work well with letsencrypt certificates. So if you want a public accessible minio with kes make sure to set the `kes.externalCertSecret` and `externalClientCertSecret` to self signed certificate. `externalCertSecret` and `console.externalCertSecret` can use letsencrypt certificate.

**Comment by dvaldivia** [comment]
@sstubbs `KES` is intended for encryption of the objects, it sits in between `MinIO` and a `KMS` service (Key Management Service), for internet facing TLS (or SSL) requirements such as Let's Encrypt certificates, you only need to provide those to `MinIO` and `Console` via external certificate secret as you mentioned.

If you use `autoCert:true` on the `Tenant` the operator will attempt to generate certificates and have them signed by kubernetes.

**Comment by sstubbs** [comment]
Understood. I am happier with KES not being publicly accessible but wasn't sure exactly how it all tied together. It's working well for me now with this.

**Comment by nitisht** [comment]
Based on comments doesn't look like anything to be done here. closing. Feel free to reopen if there is anything else @sstubbs
