### ISSUE TITLE
[faq] More documentation and clarification

### ISSUE THREAD

**Issue by rerime** [minio/operator#250]
Hi!
Would be great, if you add more clarification, how to expand or shrink minio cluster. How to calculate disk and server numbers, what can I change after creation? What do you mean by zones, is it like redundancy zones in AWS (a,b,c) or different datacenters?
Thanks in advance!

**Comment by nitisht** [comment]
> how to expand or shrink minio cluster.

Expansion is done by adding zones https://github.com/minio/operator/blob/master/docs/adding-zones.md. Shrinking is not supported as of now. We may be support later. 

> How to calculate disk and server numbers,

It is upto you to decide disk and server based on your capacity requirements. MinIO needs 2x raw capacity by default. It can be configured as per https://github.com/minio/minio/tree/master/docs/erasure/storage-class

> what can I change after creation

**Comment by rerime** [comment]
@nitisht So in general I need minimum 4 nodes in k8s and setup like this?
```
  zones:
    - servers: 4
      volumesPerServer: 1
```
And more `volumesPerServer` if I have more independent hard drives per k8s node, am I correct?

**Comment by nitisht** [comment]
> And more volumesPerServer if I have more independent hard drives per k8s node, am I correct?

Yes, `volumesPerServer` is number of volumes you have available per Pod
