### ISSUE TITLE
Tenants report Ready even when pods are not still ready

### ISSUE THREAD

**Issue by cesnietor** [minio/operator#262]
When a tenant is created and the pods are being created, the Tenant's status is set to `Ready` but pods are still initializing which can take some seconds, hence, server is not ready.

## Expected Behavior
Status should give a more detailed information of the Tenant's status

## Current Behavior
Tenant's status is set to Ready when the pods are created

## Possible Solution
We can possibly  call /cluster/health 
## Steps to Reproduce (for bugs)
1.Create  a Tenant
2.Check Status when pods are being created

**Comment by harshavardhana** [comment]
@cesnietor are you planning to send a fix here?

**Comment by cesnietor** [comment]
No, I tested it with 3.0.13 and was showing the status correctly so no issue anymore.
