### ISSUE TITLE
KES does not seem to mount ca when externalCertSecret set to cert-manager.io/v1alpha2

### ISSUE THREAD

**Issue by sstubbs** [minio/operator#263]
I've got the operator running with letsencrypt certificates for external and a selfsigned certificate for internal. The only issue is and perhaps I'm not understanding something but I have to patch the kes statefulset to add the ca mount. I thought this was because I was using `type: kubernetes.io/tls` under kes but I've now tried `cert-manager.io/v1alpha2` and have the same issue.

## Expected Behavior
ca.crt to be mounted in kes so it can validate the ca when I add the ca path to kes-config.

## Current Behavior
ca is not mounted

## Possible Solution
Currently I just run `kubectl edit statefulset -n minio cluster-1-kes` and add the mount. Then the kes-config does work properly and reads it correctly.

## Context
It isn't a big a problem for me as patching it is easy but it's one of those issues that has to be remembered for every new installation so I would rather not have to do this.

## Your Environment
kubernetes 1.18.8
operator 3.0.13

**Comment by Alevsk** [comment]
duplicated: https://github.com/minio/operator/issues/348
