### ISSUE TITLE
OSX Plugin?

### ISSUE THREAD

**Issue by stobias123** [minio/operator#274]
**Is your feature request related to a problem? Please describe.**
I following docs on readme, I have to use minio kubectl plugin for installation. 

**Describe the solution you'd like**
Please support osx in goreleaser builds so I can follow instructions

**Comment by harshavardhana** [comment]
OSX/macOS is not really a priority for us @stobias123 we will consider this in the future. 

You may use kustomize as an alternative for now - `kubctl apply -k`

**Comment by stobias123** [comment]
@harshavardhana  - any chance you could keep the old readme in docs folder then? Had to check out last version tag to find out how to deploy with regular manifests.

**Comment by stobias123** [comment]
PS - I built locally by just adding...
```
goos:
  - linux
  - darwin
```

Any reason not to commit this as a fix? I can submit the PR if you' dlike

**Comment by harshavardhana** [comment]
PR in #275

**Comment by harshavardhana** [comment]
Fixed by #275
