### ISSUE TITLE
Error: no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by jneo8** [minio/operator#283]
Hi,

I just create a GKE to testing

but keep getting `Error: no Auth Provider found for name "gcp"` error

## Your Environment
* Version used (`minio-operator`): 3.0.14
* Environment name and version (e.g. kubernetes v1.17.2): 1.16.13-gke.1

**Comment by dvaldivia** [comment]
Is this error inside the operator container logs or where?

**Comment by jneo8** [comment]
After enter `kubectl minio operator create` in CLI

**Comment by stefanhenseler** [comment]
I had the same issue when I tried to start the operator out-of-cluster using the following command:

`
go run . --kubeconfig ~/.kube/config
`

I came across this issue: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/pull/55/commits/33ca97735b3b0bc08f25248cf16fbf34f23852a8#diff-d8a75a1487ffd04d33050588d43df97d 

and adding the import to minio-operator/pkg/controller/cluster/main-controller.go made it work for me. I guess the same would be the case for minio-operator/kubectl-minio/cmd/kubectl-minio.go. I've created a branch containing the change:  https://github.com/synax/minio-operator/tree/client-auth-import-provider

**Comment by harshavardhana** [comment]
> and adding the import to minio-operator/pkg/controller/cluster/main-controller.go made it work for me. I guess the same would be the case for minio-operator/kubectl-minio/cmd/kubectl-minio.go. I've created a branch containing the change: https://github.com/synax/minio-operator/tree/client-auth-import-provider

Please send a PR @stefanhenseler

**Comment by Ares3266** [comment]
Can I bump this issue please. Does anyone have a worvalid workaround?

**Comment by harshavardhana** [comment]
Closed by #300 / 108517d65557b79b41167bca5f053627d9af85e1
