### ISSUE TITLE
Please provide method to uninstall/update operator in minio plugin

### ISSUE THREAD

**Issue by heww** [minio/operator#288]
**Is your feature request related to a problem? Please describe.**
I created an operator through minio plugin but use the wrong `--namespace-to-watch`, I want to reinstall the operator with the correct argument, but I can't do that.

**Describe the solution you'd like**
Want to update command to change the operator

**Describe alternatives you've considered**
If no way to update the operator installed, provide a method to uninstall the operator is ok.

**Additional context**

**Comment by harshavardhana** [comment]
kubectl delete -k github.com/minio/operator
