### ISSUE TITLE
support for deploying Minio Tenant with multiple certificates

### ISSUE THREAD

**Issue by Alevsk** [minio/operator#306]
**Is your feature request related to a problem? Please describe.**
Minio supports multiple certificates via SNI, we need a way for operator to deploy tenants taking advantage of this feature

**Describe the solution you'd like**
Create tenant via CRD should support an array of secrets (KeyPairs) that hold multiple TLS certificates to be served by Minio

**Comment by nitisht** [comment]
Fixed by #318
