### ISSUE TITLE
Support for Volume Expansion

### ISSUE THREAD

**Issue by dvaldivia** [minio/operator#310]
We soon will have the need to support volume expansion, according to the [official documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims) this is supported as long as the storage class has the field `allowVolumeExpansion:true`

If the requirement on the storageclass is met, we should then go on and modify the zone's PVC template's and probably the existing PVCs? I'm not sure what is the proper procedure but we should investigate.

**Comment by harshavardhana** [comment]
if the PVCs allow expansion then MinIO doesn't do anything special @dvaldivia - this expansion is different than Zone expansion in MinIO

**Comment by dvaldivia** [comment]
yes, this is for when they want to  make the volumes larger (1TB volumes to 4TB for example)

**Comment by dvaldivia** [comment]
from the docs
```
To request a larger volume for a PVC, edit the PVC object and specify a larger size. This triggers expansion of the volume that backs the underlying PersistentVolume. A new PersistentVolume is never created to satisfy the claim. Instead, an existing volume is resized.
```
