### ISSUE TITLE
Custom Resources for Bucket, User, Bucket Policy, and Bucket Lifecycle

### ISSUE THREAD

**Issue by tobernguyen** [minio/operator#314]
**Is your feature request related to a problem? Please describe.**
I want to configure MinIO Tenant via discrete CRs for things like Bucket creation/management, User management, Bucket Policy, and Object Lifecycle. The only way to manage all of the aforementioned configurations is via MinIO Client (`mc`). Therefore, I couldn't define them as code to have a complete Infrastructure as Code solution.

**Describe the solution you'd like**
When A CR with kind like `TenantBucket`, the operator is going to create and manage that bucket without the need of developer running `mc` commands. When that CR is deleted, the operator will delete that bucket completely as well.
Similar to that, User, Bucket Policy, and Object Lifecycle can be managed via discrete CRDs as well.

**Describe alternatives you've considered**
I don't have any alternatives at the moment. I have to `kubectl exec` to the pod inside the cluster and run `mc` client from there to create buckets, users, etc.

**Additional context**
- Rook Ceph has a CR for Bucket: https://rook.io/docs/rook/v1.4/ceph-object-bucket-claim.html and Bucket User: https://rook.io/docs/rook/v1.4/ceph-object-store-user-crd.html

**Comment by tobernguyen** [comment]
How do I remove the stale?

**Comment by harshavardhana** [comment]
This is unrelated to operator and will be available as https://github.com/kubernetes-sigs/container-object-storage-interface-controller

Out of scope for operator
