### ISSUE TITLE
kubectl-minio requests huge volumes for some capacity values

### ISSUE THREAD

**Issue by haslersn** [minio/operator#385]
Creating a minio cluster with 3 servers, 12 drives and `21.6Ti` capacity results in volume requests for `643584Ti` per volume.

## Expected Behavior

There should either be an error, if `21.6Ti` is an illegal value, or a sane request, otherwise.

## Steps to Reproduce (for bugs)

```
$ kubectl minio tenant create --name minio-hdd --servers 3 --volumes 12 --capacity 21.6Ti -o
```

## Your Environment

kubectl-minio v3.0.29

**Comment by harshavardhana** [comment]
> There should either be an error, if `21.6Ti` is an illegal value, or a sane request, otherwise.

why is it an illegal value? @harlersn

**Comment by haslersn** [comment]
I did not say so. I also proposed an expected behavior if it "otherwise", i.e. if it's not an illegal value.

**Comment by nitisht** [comment]
I don't really understand the problem here. can you elaborate @haslersn ?

**Comment by nitisht** [comment]
care to elaborate further @haslersn ?

**Comment by haslersn** [comment]
Just as @harshavardhana, I also think that `21.6Ti` is a valid value. My original post contains the steps to reproduce the issue. The minio operator created volumes requests for `643584Ti` rather than `1.8Ti` per volume.
