### ISSUE TITLE
 Tenant console is failing with Incorrect Usage: flag provided but not defined: -certs-dir -minio/k8s-operator:v3.0.29

### ISSUE THREAD

**Issue by mohantnr** [minio/operator#387]
Hi,
k8s Minio version: minio/k8s-operator:v3.0.29

It is successfully creating the MinIO Tenant tenant1 Created

# kubectl minio tenant create --name tenant1 --servers 1 --volumes 4 --capacity 100Gi --storage-class local-storage -n minio-ns

Tenant
Access Key: 05559518-7b76-4dee-9a8c-49bc52bffda1
Secret Key: 5c3005e8-f523-4151-9e46-c34aa2c34b7b
Version: minio/minio:RELEASE.2020-11-19T23-48-16Z
ClusterIP Service: tenant1-internal-service

MinIO Console
Access Key: 2d914f4f-39e4-4368-b889-ff51d58e0264
Secret Key: 4d9f96f9-8f32-44fb-9799-040eeb0b1f67
Version: minio/console:v0.3.14
ClusterIP Service: tenant1-console

tenant-console is failing

# kubectl get all -n minio-ns
NAME                                   READY   STATUS             RESTARTS   AGE
pod/minio-operator-78b4f47796-bbswt    1/1     Running            0          38h
pod/tenant1-console-77f88dc475-67txc   0/1     CrashLoopBackOff   10         31m
pod/tenant1-console-77f88dc475-np7kw   0/1     CrashLoopBackOff   10         31m
pod/tenant1-zone-0-0                   1/1     Running            0          32m

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/minio             ClusterIP   10.100.12.139   <none>        443/TCP             33m
service/tenant1-console   ClusterIP   10.100.53.99    <none>        9090/TCP,9443/TCP   31m
service/tenant1-hl        ClusterIP   None            <none>        9000/TCP            33m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/minio-operator    1/1     1            1           38h
deployment.apps/tenant1-console   0/2     2            0           31m

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/minio-operator-78b4f47796    1         1         1       38h
replicaset.apps/tenant1-console-77f88dc475   2         2         0       31m

NAME                              READY   AGE
statefulset.apps/tenant1-zone-0   1/1     32m

# kubectl logs tenant1-console-77f88dc475-np7kw -n minio-ns
Incorrect Usage: flag provided but not defined: -certs-dir

NAME:
  console server - starts Console server

USAGE:
  console server [command options] [arguments...]

FLAGS:
  --host value             HTTP server hostname (default: "0.0.0.0")
  --port value             HTTP Server port (default: 9090)
  --tls-host value         HTTPS server hostname (default: "0.0.0.0")
  --tls-port value         HTTPS server port (default: 9443)
  --tls-certificate value  filename of public cert
  --tls-key value          filename of private key
  --help, -h               show help

# kubectl describe deployment.apps/tenant1-console -n minio-ns
Name:                   tenant1-console
Namespace:              minio-ns
CreationTimestamp:      Thu, 10 Dec 2020 13:45:44 -0800
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               v1.min.io/console=tenant1-console
Replicas:               2 desired | 2 updated | 2 total | 0 available | 2 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  v1.min.io/console=tenant1-console
  Containers:
   console:
    Image:       minio/console:v0.3.14
    Ports:       9090/TCP, 9443/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      server
      --certs-dir=/tmp/certs
    Environment Variables from:
      tenant1-console-secret  Secret  Optional: false
    Environment:
      CONSOLE_MINIO_SERVER:  https://minio.minio-ns.svc.cluster.local:443
    Mounts:
      /tmp/certs from tenant1-console (rw)
  Volumes:
   tenant1-console:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          tenant1-console-tls
    SecretOptionalName:  <nil>
    SecretName:          tenant1-tls
    SecretOptionalName:  <nil>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      False   MinimumReplicasUnavailable
OldReplicaSets:  <none>
NewReplicaSet:   tenant1-console-77f88dc475 (2/2 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  32m   deployment-controller  Scaled up replica set tenant1-console-77f88dc475 to 2

It was working fien in minio/k8s-operator:v3.0.26. Can you help me to find what is the issue here?

**Comment by dvaldivia** [comment]
`minio/console:v0.3.14` is fairly old, can you  upgrade your console to `minio/console:v0.4.6` that should fix this issue.

**Comment by mohantnr** [comment]
Hi Dvaldivia,

Thank you and it is working after the console upgrade to minio/console:v0.4.6

**Comment by Nilegfx** [comment]
@dvaldivia thanks for the hint/answer. 

I think the documentation for the operator is not well organized and doesn't explain how to create new tenant with an updated console image or you mean to manually update the generated deployment after the operator creates it?

I do think that the minio plugin should always be up-to-date with the latest images or give an option to pass it, or if this option already there, then it has to state the correct flag to pass for this option, right now when I do:

```
kubectl minio tenant create --help
```

that's what I get and no mention for any flag for updating the console image or so.
```
'create' command creates a new MinIO tenant

Usage:
  minio tenant create [flags]

Examples:
  kubectl minio tenant create --name tenant1 --servers 4 --volumes 16 --capacity 16Ti --namespace tenant1-ns

Flags:
      --capacity string        total raw capacity of MinIO tenant in this zone, e.g. 16Ti
  -h, --help                   help for create
      --kes-config string      name of secret with details for enabling encryption, refer example https://github.com/minio/operator/blob/master/examples/kes-secret.yaml
      --name string            name of the MinIO tenant to create
  -n, --namespace string       namespace scope for this request (default "default")
  -o, --output                 dry run this command and generate requisite yaml
      --servers int32          total number of pods in MinIO tenant
  -s, --storage-class string   storage class for this MinIO tenant (default "default")
      --volumes int32          total number of volumes in the MinIO tenant

```
