### ISSUE TITLE
Pools or Zones?

### ISSUE THREAD

**Issue by chadleeshaw** [minio/operator#388]
I'm seeing an issue where the Tenant example is needing spec:zones and throwing an error.

## Expected Behavior
I'd expect spec:pools to work.

## Current Behavior
Using the [tenant.yaml ](https://github.com/minio/operator/blob/master/examples/tenant.yaml)and testing against the latest 3.0.29 operator I get the following error:

> The Tenant "minio" is invalid: spec.zones: Required value

## Steps to Reproduce (for bugs)
1. kubectl create ns minio
2. kubectl minio init --namespace minio
3. kubectl apply -n minio -f tenant.yaml

## Context
Just testing minio-operator

## Your Environment

* Version used (`minio-operator`): 3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): 1.17.4
* Server type and version: VM
* Operating System and version (`uname -a`): CentOS 7 (4.19.113)

**Comment by harshavardhana** [comment]
v3.0.29 is the released version not v4.0.0 - you need to use the released version https://github.com/minio/operator/blob/v3.0.29/examples/tenant.yaml
