### ISSUE TITLE
Any support openshift 3.11?

### ISSUE THREAD

**Issue by iamruhua** [minio/operator#389]
In the readme, it says only support 1.17+ of k8s, but openshift 3.11 was built on k8s 1.11.

Any plan to support that or any clue on why it's not supported?

**Comment by harshavardhana** [comment]
We cannot support openshift 3.11 due to CRDs and certain requirements in terms of kubernetes features.  Unfortunately no.

**Comment by abdennour** [comment]
same question.

**Comment by abdennour** [comment]
@harshavardhana  sealed-secrets operator supports very old versions like Openshift 3.11 (k8s 1.11) , and also latest k8s versions (1.23). 

From the other side, sealed-secret operator uses CRDs ... so on. 
Could you check it and tell us why this operator cannot support old version like 1.11  ?
https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets

If it's in our hands, we would have OCP 4 on prod, but consider that there is shared responsibility in big organization where the team who maintain the cluster, not the same team who provides PaaS on top of the cluster, not the same team who provides SaaS leveraging the PaaSs
