### ISSUE TITLE
Credentials in resources generated by kubectl plugin can not be customized.

### ISSUE THREAD

**Issue by anekdoti** [minio/operator#394]
From my understanding, the kubectl minio plugin has two modes:  in both modes, the resources necessary for the deployment of a Tenant are created from command line arguments and credentials are randomly created. Then, the resources are either directly applied to the cluster, or just outputted (using the -o yaml  switch).

According to the documentation, in the second case it should be possible to customize the resources and then to apply them manually to the Kubernetes cluster. However, it seems that changing the credentials (accesskey and secretkey in minio-creds-secret) from the randomly created ones to something custom is not possible.

My specific kubectl plugin command is
`kubectl minio tenant create --name minio --servers 1 --volumes 4 --capacity 1Gi --namespace my-namespace --storage-class my-storage-class`

When using the resources as created from the plugin, login to the Minio cluster using mc or the web UI on :9000 works.

## Expected Behavior
After changing the accesskey and secretkey to custom base64 encoded credentials in minio-creds-secret and removing and reapplying all resources (including the persistent volume claims), it should be possible to login to the Minio cluster using  these new credentials.

## Current Behavior
After changing the accesskey and secretkey, login is impossible. In the Web UI on :9000 and in mc, the returned error is "The access key ID you provided does not exist in our records". 
I verified in the Minio pods that the new accesskey and secretkey are correctly injected into the env vars MINO_ACCESS_KEY and MINIO_SECRET_KEY. After changing the credentials back to the original ones created by the kubectl plugin, login works again.

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
Described above.

## Context
I apply resources to my cluster using a GitOps approach with FluxCD. In this context, I want to choose custom credentials and want to encrypt them using the Sealed Secrets operator to avoid exposing them in my repository.
But what is most concerning for me that the bug/unexpected behaviour described suggests a dependency between the tenant and the generated credentials that can not be seen in the tenant resource. 

## Regression
I don't know

## Your Environment
* Version used (`minio-operator`): v3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): kubectl v1.18.8, kubernetes v1.18.8+vmware.1
* Server type and version: v1.18.8+vmware.1
* Operating System and version (`uname -a`): Linux {hostname-redacted} 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file: The resources can be directly created from the command above (by choosing a suitable storage class for your system)

**Comment by ravindk89** [comment]
Some additional context (and lots of conversation) in the [Community Slack Channel](https://minio.slack.com/archives/C3NDUB8UA/p1608053023053900). Might be helpful in additional diagnostics/ideas here.

**Comment by nitisht** [comment]
with #456 follow below steps to update the root creds

1. Update the Secret `minio-creds-secret` with new credential values. 
2. Add below env vars in the tenant yaml (remember to use the _actual_ old creds)

```yaml
  env:
  - name: MINIO_ROOT_USER_OLD
    value: "minio"
  - name: MINIO_ROOT_PASSWORD_OLD
    value: "minio123"
```

3. Apply the tenant.yaml file. 
4. You should see the MinIO statefulsets getting updated with new new root credentials.

**Comment by harshavardhana** [comment]
> ```yaml
>   env:
>   - name: MINIO_ROOT_USER_OLD
>     value: "minio"
>   - name: MINIO_ROOT_PASSWORD_OLD
>     value: "minio123"
> ```

Perhaps its better to still mention MINIO_ACCESS_KEY_OLD combination for older releases

**Comment by Mercbot7** [comment]
@nitisht It would be good if the verbiage and guidance you reference here earlier is in the documentation. Right now it is relatively ambiguous and obscure enough that people may think they can enter anything for the old password.
