### ISSUE TITLE
timeout during certificate fetching 

### ISSUE THREAD

**Issue by JannikZed** [minio/operator#395]
When trying to create a fresh Tenant with the operator, the operator fails to fetch the certificate: 
```
1 main-controller.go:964] Deploying zone zone-0
I1219 09:46:23.731031       1 csr.go:73] Generating private key
I1219 09:46:23.746896       1 csr.go:86] Generating CSR with CN=*.minio-hl.common-services.svc.cluster.local
I1219 09:46:23.786537       1 csr.go:217] Start polling for certificate of csr/minio-common-services-csr, every 5s, timeout after 20m0s
E1219 10:06:23.796679       1 csr.go:136] Unexpected error during the creation of the csr/minio-common-services-csr: timeout during certificate fetching of csr/minio-common-services-csr
E1219 10:06:23.796760       1 main-controller.go:784] error syncing 'common-services/minio': timeout during certificate fetching of csr/minio-common-services-csr
I1219 10:06:23.812053       1 main-controller.go:964] Deploying zone zone-0
I1219 10:06:23.888030       1 csr.go:217] Start polling for certificate of csr/minio-console-common-services-csr, every 5s, timeout after 20m0s
E1219 10:26:23.895984       1 console-csr.go:81] Unexpected error during the creation of the csr/minio-console-common-services-csr: timeout during certificate fetching of csr/minio-console-common-services-csr
E1219 10:26:23.896066       1 main-controller.go:784] error syncing 'common-services/minio': timeout during certificate fetching of csr/minio-console-common-services-csr
I1219 10:26:23.917222       1 main-controller.go:964] Deploying zone zone-0
E1219 10:26:26.021896       1 main-controller.go:784] error syncing 'common-services/minio': MinIO is not ready
```
I don't know what to change or to do differently. My tenant description:

```
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio
  namespace: common-services
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: minio-console-secret
    image: minio/console:v0.3.14
    metadata:
      creationTimestamp: null
      name: minio
    replicas: 2
    resources: {}
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: true
  serviceName: minio-internal-service
  zones:
  - resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: hcloud-volumes
      status: {}
    volumesPerServer: 2
status:
  availableReplicas: 0
  currentState: ""
```
Issuing the certificate with cert-manager is not working as well - these certificates do not have a file "public.csr" so this file can't be mounted  :/

## Expected Behavior

The service should start up!
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`): 3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): v1.18
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
> E1219 10:26:23.895984       1 console-csr.go:81] Unexpected error during the creation of the csr/minio-console-common-services-csr: timeout during certificate fetching of csr/minio-console-common-services-csr

The timeout is because your deployment k8s took longer than usual required CSR to be granted.

**Comment by JannikZed** [comment]
thank you for the answer! Do you have an idea, where this is coming from, or how I could debug the root cause? Because 20 minutes sounds pretty long .. I don't think, that my cluster is that slow. I tried it several times, without luck. So I'm guessing there might be some kind of misconfiguration in the cluster.

**Comment by harshavardhana** [comment]
> thank you for the answer! Do you have an idea, where this is coming from, or how I could debug the root cause? Because 20 minutes sounds pretty long .. I don't think, that my cluster is that slow. I tried it several times, without luck. So I'm guessing there might be some kind of misconfiguration in the cluster.

yes you should look at `kubectl get events` on the operator pod and also the kube-system side where the CSR is coming from. 

@Alevsk ^^ do you have any inputs?

**Comment by Alevsk** [comment]
> > thank you for the answer! Do you have an idea, where this is coming from, or how I could debug the root cause? Because 20 minutes sounds pretty long .. I don't think, that my cluster is that slow. I tried it several times, without luck. So I'm guessing there might be some kind of misconfiguration in the cluster.
> 
> yes you should look at `kubectl get events` on the operator pod and also the kube-system side where the CSR is coming from.
> 
> @Alevsk ^^ do you have any inputs?

Yes the issue seems to be during the csr creation

```
1 console-csr.go:81] Unexpected error during the creation of the csr/minio-console-common-services-csr: timeout during certificate fetching of csr/minio-console-common-services-csr
```

`kubectl get events` should tell us more information about what happened.

**Comment by JannikZed** [comment]
so get events did not show me anything - nothing about the CSR.. but it was the right direction. My setup is using rancher and they are missing these settings for the kube controller:
```
services:
  kube-controller: 
    extra_args: 
      cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
      cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"
```
This makes it impossible for kubernetes to generate a certificate from the csr. 

After adding this value, everything works smooth!

**Comment by harshavardhana** [comment]
> so get events did not show me anything - nothing about the CSR.. but it was the right direction. My setup is using rancher and they are missing these settings for the kube controller:
> 
> ```
> services:
>   kube-controller: 
>     extra_args: 
>       cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
>       cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"
> ```
> 
> This makes it impossible for kubernetes to generate a certificate from the csr.
> 
> After adding this value, everything works smooth!

Strange good to know.

**Comment by jgato** [comment]
so @JannikZed, what is the reason of needing that? I would like not to have to modify the default rancher configuration (unless is absolutly need it). Is this because it tries to generate some kind of automatic certificates? because I have my own ones.

**Comment by JannikZed** [comment]
@jgato I did not deep-dive into that issue, as I also never faced the problem before .. this issue is giving some more researching background: https://github.com/cockroachdb/cockroach/issues/28075
and yes, it is used to automatically sign internal certificates. You don't have to change a lot for this setting. You can edit a simple yaml file in the rancher gui, so it wasn't a big deal :) 

Hope that helps a little bit!

**Comment by jgato** [comment]
thanks @JannikZed you are right is pretty easy to solve the issue with Rancher. But I am trying to automatize an platform deployment, so... the most I dont have to do manually, the better :) 
Maybe someone would help me about... how to deploy minio operator without using this automatic process of signing certificates. I want to provide my own ones. I will try in a new post :)

**Comment by devops-internal-app** [comment]
Is there an ETA for a minio fix? I have the same problem and I don't want to manually change rancher

**Comment by StefanSa** [comment]
Any solution to solve this problem?

**Comment by Blackclaws** [comment]
I am wondering whether a dependency on cert manager and using that systems certificate signing and request system wouldn't better fit in tthis case.
