### ISSUE TITLE
 When kubectl don't use default kubeconfig command exec return unknown command 

### ISSUE THREAD

**Issue by sunshineing** [minio/operator#410]
## Expected Behavior
$kubectl minio init
CustomResourceDefinition tenants.minio.min.io: created
ClusterRole minio-operator-role: created
ServiceAccount minio-operator: created
ClusterRoleBinding minio-operator-binding: created
MinIO Operator Deployment minio-operator: created

## Current Behavior
$kubectl --kubeconfig kubeconfig minio init
Error: unknown command "minio" for "kubectl"
Run 'kubectl --help' for usage.

**Comment by nitisht** [comment]
will check and get back @sunshineing

**Comment by nitisht** [comment]
@sunshineing can you pls try with #414 ?
