### ISSUE TITLE
use The MinIO Kubernetes Operator init minio error

### ISSUE THREAD

**Issue by huatan** [minio/operator#413]
when init minio ，the error appear
system centos7.8
kubernetes 1.19.2
 Version used (`minio-operator`):

## Current Behavior
[root@k8s-master1 ~]# kubectl get pod
NAME                             READY   STATUS    RESTARTS   AGE
mariadb-0                        1/1     Running   15         33d
quickstart-es-default-0          1/1     Running   15         33d
quickstart-kb-769769cbf8-nmdtw   1/1     Running   15         33d
[root@k8s-master1 ~]# kubectl minio init
Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

**Comment by nitisht** [comment]
Doesn't look like you configured `kubectl` properly. Please configure `kubectl` to connect to your K8S cluster before using the plugin

**Comment by huatan** [comment]
@nitisht 

but I use `kubectl` deploy elasticsearch operator success,deploy mariadb success

**Comment by nitisht** [comment]
please try providing the `--kubeconfig` flag, once #414 is merged and released.

**Comment by huatan** [comment]
@nitisht I  see #414 Merging is blocked,when released ,I will try. is the minio plugin version will changed?

**Comment by nitisht** [comment]
> is the minio plugin version will changed?

Yes, we'll make a new release soon
