### ISSUE TITLE
Roadmap for 4.X release

### ISSUE THREAD

**Issue by elmariofredo** [minio/operator#417]
Thanks for this operator 👍

Given recent breaking changes https://github.com/minio/operator/pull/371 is there any roadmap when do you plan to release these changes?

**Comment by dvaldivia** [comment]
@elmariofredo I'm working on a PR to support upgrading previous tenants to the new structure

**Comment by dvaldivia** [comment]
when that is ready perhaps we will release 4.0

**Comment by elmariofredo** [comment]
Thanks for the answer! If there is anything I can help with, please do let me know.

**Comment by bahetiamit** [comment]
These breaking changes resolved now? I still see below error when I try to execute functional test https://github.com/minio/operator/blob/master/testing/one-zone.yaml 

[~]# oc apply -f one-zone.yaml
secret/test-minio-creds-secret created
The Tenant "one-pool" is invalid: spec.zones: Required value
