### ISSUE TITLE
tenant console deployment failed

### ISSUE THREAD

**Issue by ZleFox** [minio/operator#418]
when clean install from kubectl minio tenant create the tenant-console deployment is using wrong args
the logs are: 

```
Incorrect Usage: flag provided but not defined: -certs-dir

NAME:
  console server - starts Console server

USAGE:
  console server [command options] [arguments...]

FLAGS:
  --host value             HTTP server hostname (default: "0.0.0.0")
  --port value             HTTP Server port (default: 9090)
  --tls-host value         HTTPS server hostname (default: "0.0.0.0")
  --tls-port value         HTTPS server port (default: 9443)
  --tls-certificate value  filename of public cert
  --tls-key value          filename of private key
  --help, -h               show help
```

## Expected Behavior
console sever should start with correct flags

## Current Behavior
the deployment must be manually configured 

## Your Environment

* Version used (`minio-operator`): minio         v3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): k8s 18.14
* Server type and version: rke installed via rancher
* Operating System and version (`uname -a`): 
* Link to your deployment file:

**Comment by Born2Bake** [comment]
I have got the same issue. How to resolve it?
