### ISSUE TITLE
Create tenant failed with error "timeout during certificate fetching of csr/minio-cluster-default-csr"

### ISSUE THREAD

**Issue by jaggerwang** [minio/operator#420]
The operator logs the following error when create a tenant:

```
I0113 08:05:46.253780       1 main.go:66] Starting MinIO Operator
I0113 08:05:46.255812       1 main-controller.go:236] Setting up event handlers
I0113 08:05:46.255897       1 main-controller.go:698] Starting Tenant controller
I0113 08:05:46.255910       1 main-controller.go:701] Waiting for informer caches to sync
I0113 08:05:46.356065       1 main-controller.go:706] Starting workers
I0113 08:08:27.939881       1 main-controller.go:964] Deploying zone zone-0
I0113 08:08:27.951396       1 csr.go:73] Generating private key
I0113 08:08:27.962002       1 csr.go:86] Generating CSR with CN=*.minio-cluster-hl.default.svc.cluster.local
I0113 08:08:27.972989       1 csr.go:217] Start polling for certificate of csr/minio-cluster-default-csr, every 5s, timeout after 20m0s
E0113 08:28:27.976553       1 csr.go:136] Unexpected error during the creation of the csr/minio-cluster-default-csr: timeout during certificate fetching of csr/minio-cluster-default-csr
E0113 08:28:27.976589       1 main-controller.go:784] error syncing 'default/minio-cluster': timeout during certificate fetching of csr/minio-cluster-default-csr
I0113 08:28:27.982210       1 main-controller.go:964] Deploying zone zone-0
I0113 08:28:28.006371       1 csr.go:217] Start polling for certificate of csr/minio-cluster-console-default-csr, every 5s, timeout after 20m0s
```

## Steps to Reproduce (for bugs)
1. Install minio plugin.
2. Init minio plugin.
3. Create a tenant.

```bash
kubectl krew update
kubectl krew install minio

kubectl minio init

kubectl minio tenant create                \
    --name minio-cluster                   \
    --servers 4                            \
    --volumes 4                            \
    --capacity 12Ti                        \
    --storage-class local-storage
```

StorageClass:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

PersistentVolumes:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-kubenode1-data2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3.7Ti
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-kubenode1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-kubenode2-data2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3.7Ti
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-kubenode2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-kubenode3-data2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3.7Ti
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-kubenode3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-kubenode4-data2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3.7Ti
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-kubenode4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
```

## Your Environment
* Version used (`minio-operator`): v3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): v1.18.14 managed by Rancher
* Server type and version: CentOS Linux release 8.3.2011
* Operating System and version (`uname -a`): Linux dev-kubenode1 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
PTAL 

> * Environment name and version (e.g. kubernetes v1.17.2): v1.18.14 managed by Rancher

https://github.com/minio/operator/issues/395

**Comment by harshavardhana** [comment]
```yaml
services:
  kube-controller: 
    extra_args: 
      cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
      cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"
```

**Comment by luciferhs** [comment]
> ```yaml
> services:
>   kube-controller: 
>     extra_args: 
>       cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
>       cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"
> ```


I have configured it, but the installation still reports the problem of TLS。

The document says
“MinIO Tenants deploy with TLS enabled by default, where the MinIO Operator uses the Kubernetes certificates.k8s.io API to generate the required x.509 certificates. Each certificate is signed using the Kubernetes Certificate Authority (CA) configured during cluster deployment. While Kubernetes mounts this CA on Pods in the cluster, Pods do not trust that CA by default. You must copy the CA to a directory such that the update-ca-certificates utility can find and add it to the system trust store to enable validation of MinIO TLS certificates:

cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
update-ca-certificates”


How to do it？

**Comment by luciferhs** [comment]
> > ```yaml
> > services:
> >   kube-controller: 
> >     extra_args: 
> >       cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
> >       cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"
> > ```
> 
> I have configured it, but the installation still reports the problem of TLS，Pod is always in creating state。
> 
> The document says
> “MinIO Tenants deploy with TLS enabled by default, where the MinIO Operator uses the Kubernetes certificates.k8s.io API to generate the required x.509 certificates. Each certificate is signed using the Kubernetes Certificate Authority (CA) configured during cluster deployment. While Kubernetes mounts this CA on Pods in the cluster, Pods do not trust that CA by default. You must copy the CA to a directory such that the update-ca-certificates utility can find and add it to the system trust store to enable validation of MinIO TLS certificates:
> 
> cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
> update-ca-certificates”
> 
> How to do it？

**Comment by jaggerwang** [comment]
If you use rancher, you can enter into edit cluster page, and then click button "Edit as YAML".

**Comment by Homatp** [comment]
> > ```yaml
> > services:
> >   kube-controller: 
> >     extra_args: 
> >       cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
> >       cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"
> > ```
> 
> I have configured it, but the installation still reports the problem of TLS。
> 
> The document says
> “MinIO Tenants deploy with TLS enabled by default, where the MinIO Operator uses the Kubernetes certificates.k8s.io API to generate the required x.509 certificates. Each certificate is signed using the Kubernetes Certificate Authority (CA) configured during cluster deployment. While Kubernetes mounts this CA on Pods in the cluster, Pods do not trust that CA by default. You must copy the CA to a directory such that the update-ca-certificates utility can find and add it to the system trust store to enable validation of MinIO TLS certificates:
> 
> cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
> update-ca-certificates”
> 
> How to do it？


is there any response for this question??

**Comment by linkafsar** [comment]
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
update-ca-certificates”

i am also stuck on this ? can anybody help us to do ?

**Comment by archenroot** [comment]
same here, I posted to slack, but yet no answer to this topic...
