### ISSUE TITLE
Tenant stuck in "Waiting for Pods to be ready" state; No Console pod visible

### ISSUE THREAD

**Issue by crawdaddy18** [minio/operator#425]
## Expected Behavior
I would assume there should be a console pod in the tenant I created and that the tenant should not be stuck in a "Waiting for Pods to be ready" state for over 11 minutes.

## Current Behavior
While I can pull the console image using docker pull, the console pod is not launching.  

## Possible Solution
I assume this is an issue inside the operator.

## Steps to Reproduce (for bugs)
Follow your steps on your documentation to create a new namespace, and create a tenant.  I used all of the default values with one caveat, I had to add the "--name" flag as the "kubectl minio tenant create" command would not execute without this value. 

## Context
Access the minio console

## Your Environment

* Version used (`minio-operator`):  RELEASE.2020-11-19T23-48-16Z
* Environment name and version (e.g. kubernetes v1.17.2): 1.17.5
* Server type and version:  x86 CentOS7
* Operating System and version (`uname -a`): 3.10.0-1127.8.2.el7.x86_64
* Link to your deployment file:

**Comment by dvaldivia** [comment]
@crawdaddy18 can you share your tenant configuration? Can you also share the logs for at least 1 of the MinIO pods? we can confirm that way if MinIO started successfully

This issue could be caused by the operator not being able to talk to the MinIO pods to check if they are ready and start deploying. Are there any network policy restrictions in your cluster?

**Comment by crawdaddy18** [comment]
![image](https://user-images.githubusercontent.com/10227891/104504246-c5b7f980-55a7-11eb-9e6e-3e350be4fe2c.png)

![image](https://user-images.githubusercontent.com/10227891/104504490-22b3af80-55a8-11eb-8c9e-00a9bd95d423.png)

Does appear to be some sort of networking issue.  I am not aware of any policy restrictions.

**Comment by dvaldivia** [comment]
@crawdaddy18 MinIO is not starting, the error indicates the DNS cannot resolve the name, by any chance do you have a custom cluster domain in your k8s cluster?

**Comment by crawdaddy18** [comment]
Oh no...someone manually changed it to mycluster.local and I have NO IDEA WHY.  Is there a way to specify what cluster domain I want to use?

**Comment by harshavardhana** [comment]
> Oh no...someone manually changed it to mycluster.local and I have NO IDEA WHY. Is there a way to specify what cluster domain I want to use?

CLUSTER_DOMAIN=mycluster.local needs to be set in ENV during the operator deployment

**Comment by crawdaddy18** [comment]
sorry if this is a dumb question, but does the env variable need to be set on the node where I am executing the "kubectl minio init" command or does it need to be on all of the worker nodes?

I set it on the node where I was executing "kubectl minio init" and that did not seem to work

**Comment by dvaldivia** [comment]
no worries, you can do `kubectl minio init --cluster-domain  mycluster.local`

**Comment by crawdaddy18** [comment]
That did it, thank you.  This may be good even if the "getting started" section.  Also, please add the "--name" requirement to your example tenant create.

Thanks again!

**Comment by crawdaddy18** [comment]
Reopening, as the container keeps dying:

![image](https://user-images.githubusercontent.com/10227891/104512870-7d530880-55b4-11eb-871d-ecc9094e52b3.png)

**Comment by harshavardhana** [comment]
> Reopening, as the container keeps dying:

Change the console version to use minio/console:v0.4.6
