### ISSUE TITLE
minio-tenant-console pods are stuck at CrashLoopBackOff with MinIO Operator

### ISSUE THREAD

**Issue by mokpolar** [minio/operator#426]
## Expected Behavior

minio-tenant-console pods should reach the running state

## Current Behavior

minio-tenant-zone pods are running.

2 minio-tenant-console pods are stuck.

logs of minio-tenant-console : 

Incorrect Usage: flag provided but not defined: -certs-dir

## Steps to Reproduce (for bugs)

1. installed and initialized the minio kubectl plugin per: https://github.com/minio/operator/blob/master/README.md
2. created 4 PVs using GCP Compute Engine Disks. storage class : local-storage
3. generate minio operator
      kubectl minio tenant create --name minio-tenant \
      --servers 4                             \
      --volumes 4                            \
      --capacity 800Gi                         \
      --namespace auto-create-34              \
      --storage-class local-storage        \

## Context

Trying to bring up a minio cluster in kubernetes cluster for use with staging and then production applications.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2): GKE 1.17.12
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
> Incorrect Usage: flag provided but not defined: -certs-dir

upgrade your `console` image version to `v0.4.6` @mokpolar

**Comment by mokpolar** [comment]
> > Incorrect Usage: flag provided but not defined: -certs-dir
> 
> upgrade your `console` image version to `v0.4.6` @mokpolar

Thank you for your prompt reply.
How do I upgrade the MinIO console of Kubernetes?

**Comment by nitisht** [comment]
> But is it a normal way to use kubectl edit?

yes, that is fine @mokpolar . Closing this as working now

**Comment by vvavepacket** [comment]
@mokpolar  @nitisht 

Where did you modify / which CRD did you modify to force the image version to v0.4.6 ? I am facing the same issue. I currently have the latest minio release..

Or is there anyway to specify the image version during installation using kubectl krew / minio?

Thanks
