### ISSUE TITLE
operator starts server with unsupported --certs-dir switch

### ISSUE THREAD

**Issue by displague** [minio/operator#437]
I installed the minio operator using the krew plugin, which was also installed yesterday. (I don't know the version numbers, sorry).

The server pod was failing because --certs-dir was not supported. I changed the arguments to --tls-* effectively working around the changes introduced in https://github.com/minio/operator/pull/346.

I've since changed my install to the helm based install, without the operator, and this is working for me.

**Comment by harshavardhana** [comment]
change the console image version to v0.4.6
