### ISSUE TITLE
Install operator in declarative way without krew

### ISSUE THREAD

**Issue by sev3ryn** [minio/operator#439]
**Is your feature request related to a problem? Please describe.**
approach with installing minio-operator using krew acts like blackbox - you don't know/control what elements are installed and where. Also using krew plugin - configuration is imperative which neglects the main beauty of Kubernetes - declarative configuration which can be reviewed and versioned in version control

**Describe the solution you'd like**
I'd like to be able to install Minio operator and add tenants in declarative way by submitting yaml manifests using existing tooling that our company uses (skaffold, helm, etc), the same way as most other operators are done - see prometheus-operator, open policy agent as so on.

**Describe alternatives you've considered**
I considered using official minio helm charts, but as said in readme it is not the main way of installing/managing Minio. Also we are using security policies that doesn't allow to modify root filesystem (only mounted volumes) but minio tries to create /.minio folder which is not possible to mount using existing helm chart.
 
Edit: removed my comment about "inventing the wheel" which may be misleading - sorry if I offended you.

**Comment by nitisht** [comment]
Have you seen the -o flag in kubectl plugin? or the bunch of examples available in examples folder?

**Comment by sev3ryn** [comment]
> Have you seen the -o flag in kubectl plugin? 
```
❯ kubectl minio -o yaml init
Error: this command does not accept arguments
```
I do understand that behind the curtain it is all yaml manifests, but there is no official doc or way of installing Minio operator (doing kubectl minio init) without krew. This is exactly what am I asking for.

**Comment by nitisht** [comment]
> but there is no official doc or way of installing Minio operator (doing kubectl minio init) without krew. 

$ kubectl-minio init --help

'init' command creates MinIO Operator deployment along with all the dependencies.

Usage:
  minio init [flags]

Examples:
  kubectl minio operator init

Flags:
  -d, --cluster-domain string       cluster domain of the Kubernetes cluster (default "cluster.local")
  -h, --help                        help for init
  -i, --image string                operator image (default "minio/k8s-operator:v3.0.29")
      --image-pull-secret string    image pull secret to be used for pulling operator image
  -n, --namespace string            namespace scope for this request (default "default")
      --namespace-to-watch string   namespace where operator looks for MinIO tenants, leave empty for all namespaces
  **-o, --output                      dry run this command and generate requisite yaml**

> ❯ kubectl minio -o yaml init
Error: this command does not accept arguments

kubectl-minio init -o > init.yaml

**Comment by nitisht** [comment]
If you don't want krew, you have `kustomize` manifest available as `kustomize build github.com/minio/operator | kubectl apply -f -`

**Comment by sev3ryn** [comment]
thank you for detailed answer! Especially for kustomize option

**Comment by dvaldivia** [comment]
@sev3ryn you can also install via kustomize option in `kubectl` like this

```
kubectl apply -k github.com/minio/operator/\?ref\=v3.0.29
```
or use operator as a base in your own kustomization.yaml files

**Comment by harshavardhana** [comment]
> @sev3ryn you can also install via kustomize option in `kubectl` like this
> 
> ```
> kubectl apply -k github.com/minio/operator/\?ref\=v3.0.29
> ```
> 
> or use operator as a base in your own kustomization.yaml files

Our recommended style is using `kubectl` plugin  - if you want help beyond that feel free to look at the source @sev3ryn
