### ISSUE TITLE
Error updating to latest operator

### ISSUE THREAD

**Issue by cesnietor** [minio/operator#443]
When updating from `v.3.0.28` to  latest operator from master, kustomize fails updating since CRD is invalid
## Expected Behavior
All resources from kustomization.yaml should be deployed with no errors

## Current Behavior
```
/operator (master) ✗ 
➜ kustomize build . | k apply -f -                                                              
namespace/minio-operator unchanged
error: error validating "STDIN": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[0]): unknown field "deprecationWarning" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion]; if you choose to ignore these errors, turn validation off with --validate=false
```

## Steps to Reproduce (for bugs)

1. Deploy operator `v3.0.28` and create a tenant using console
2. Update to latest operator from master using `kustomize build . | k apply -f -`

## Regression
Yes

## Your Environment

* Version used (`minio-operator`): `v.3.0.28`

**Comment by dvaldivia** [comment]
@cesnietor whats the kubernetes versión for server and client?

**Comment by cesnietor** [comment]
> @cesnietor whats the kubernetes versión for server and client?

```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.2-6+38ac483e736488", GitCommit:"38ac483e736488517dd754156441b89e0b2060e2", GitTreeState:"clean", BuildDate:"2020-07-07T13:51:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
@dvaldivia ^

**Comment by dvaldivia** [comment]
@cesnietor can you update your client to 1.18 as well? the feature was only marked as stable on `1.19` so it means it was not present on `1.16`

**Comment by cesnietor** [comment]
this issue is now solved with https://github.com/minio/operator/pull/447
There is still an issue upgrading to latest operator but I'll open that bug in a different issue.
