### ISSUE TITLE
statefulSet not updated when updating env vars in tenant spec

### ISSUE THREAD

**Issue by ninjaslothx** [minio/operator#449]
While trying to update/add new env vars in the tenant spec, the tenant CRD is updated and the controller detects the update but the statefulset is not updated to reflect the change. 

## Steps to Reproduce (for bugs)
1. Have existing tenant
2. Update tenant CRD to add in some env var to spec: E.g
```
  env:
  - name: MINIO_PROMETHEUS_AUTH_TYPE
    value: public
```
3. Operator log detects update  `main-controller.go:779] Successfully synced 'minio-testing/minio-testing`
3. Statefulset is not updated. 

## Your Environment
Operator
minio/k8s-operator:v3.0.29
Tenant
minio:RELEASE.2020-11-19T23-48-16Z

**Comment by nitisht** [comment]
Thanks for reporting, we'll take a look
