### ISSUE TITLE
Error: unknown command "init" for "minio"

### ISSUE THREAD

**Issue by whitmell** [minio/operator#454]
Receiving unknown command error on fresh install of krew and minio.

## Expected Behavior
kubectl minio init 
Initializes minio operator

## Current Behavior
kubectl minio init
Error: unknown command "init" for "minio"

## Steps to Reproduce (for bugs)
1. Uninstall previous install of krew using uninstall instructions from krew docs (remove ~/.krew folder)
2. Install krew using install instructions from krew docs (currently v0.4.0)
3. Install minio by running "kubectl krew install minio"
4. Run "kubectl minio init"

## Context
Preventing me from installing minio operator & tenant on kubernetes

## Your Environment

* Version used (`minio-operator`): 3.0.29
* Environment name and version (e.g. kubernetes v1.17.2):  v1.20.2
* Server type and version:  v1.19.7+k3s1
* Operating System and version (`uname -a`): Windows WSL2 (Ubuntu 20.04)
* Link to your deployment file: n/a

**Comment by nitisht** [comment]
Can you try `kubectl minio init --help` and post the output?

**Comment by whitmell** [comment]
Same error.

**Comment by nitisht** [comment]
You have an older version of plugin, please try `kubectl minio operator init`

**Comment by wmatthews-fti** [comment]
That doesn't work for me either.  I have 3.0.29 installed, I thought that was the latest?


```
'operator' is the top level command for managing MinIO operator.

Usage:
  minio operator [command]

Available Commands:
  create      Create MinIO Operator deployment

Flags:
  -h, --help   help for operator

Use "minio operator [command] --help" for more information about a command.
```

**Comment by whitmell** [comment]
That doesn't work for me either.  I have 3.0.29 installed, I thought that was the latest?


```
'operator' is the top level command for managing MinIO operator.

Usage:
  minio operator [command]

Available Commands:
  create      Create MinIO Operator deployment

Flags:
  -h, --help   help for operator

Use "minio operator [command] --help" for more information about a command.
```

**Comment by nitisht** [comment]
Can you try `which kubectl-minio`? Looks like you have an older copy somewhere

**Comment by whitmell** [comment]
/usr/local/bin/kubectl-minio

**Comment by harshavardhana** [comment]
> /usr/local/bin/kubectl-minio

rm /usr/local/bin/kubectl-minio

and then 

```
kubectl krew install minio
```

**Comment by whitmell** [comment]
That seems to have done it, thanks!  I will try the install again later this evening, but the help for "kubectl minio" now shows init.

I had to add one extra step: `kubectl krew uninstall minio`

````
kubectl plugin to manage MinIO operator CRDs.

Usage:
  minio [command]

Available Commands:
  delete      Delete MinIO Operator deployment
  help        Help about any command
  init        Initialize MinIO Operator deployment
  tenant      Manage MinIO tenant

Flags:
  -h, --help   help for minio
````

**Comment by harshavardhana** [comment]
> I had to add one extra step: `kubectl krew uninstall minio`

:+1:
