### ISSUE TITLE
minio tenant ssl certificate is not signed by cluster root CA

### ISSUE THREAD

**Issue by celalsahin** [minio/operator#459]
Here: https://github.com/minio/operator/blob/master/README.md#3-connect-to-the-tenant it is mentioned that the "Each certificate is signed using the Kubernetes Certificate Authority (CA) configured during cluster deployment." but that is not the case, at least, with OCP 4.6.13 - also in current kubernetes documentation I can see that it is not the case, at least the description suggests so:
https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/
############
Note: Certificates created using the certificates.k8s.io API are signed by a dedicated CA. It is possible to configure your cluster to use the cluster root CA for this purpose, but you should never rely on this. Do not assume that these certificates will validate against the cluster root CA.
############
## Expected Behavior

minio cluster uses a ssl certificate signed by cluster CA that can be found in /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

## Current Behavior

cluster uses a ssl certificate that is NOT signed by cluster CA that can be found in /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

## Steps to Reproduce (for bugs)

1. Create PVs
2. Create a tenant 
3. observe the minio certificate, see that it is signed with sth like kube-csr-signer_@######
4. observe that cluster root certificate is not "kube-csr-signer_@######" but sth like kube-apiserver-lb-signer

## Context

Trying to setup minio within our OCP cluster & would like other pods of the same OCP cluster to be able to access minio s3 service. 

## Regression

No

## Your Environment

* Version used (`minio-operator`): image: minio/minio:RELEASE.2020-11-19T23-48-16Z
* Environment name and version (e.g. kubernetes v1.17.2): OpenShift 4.6.13
* Server type and version: BareMetal OCP Cluster
* Operating System and version (`uname -a`):
* Link to your deployment file: I do not use a deployment file(I guess it would be a yaml) - just a simple kubectl minio tenant create ....

**Comment by dvaldivia** [comment]
I did saw the certificates being signed by the k8s CA, the way i tested this:

Get a shell
```
kubectl run my-shell  -i --tty --image miniodev/debugger -- bash
```

Copy the root CA to the container certs
```
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /etc/ssl/certs/
```

Talk to my MinIO Tenant over TLS

```
mc config host add myminio https://minio.default.svc.cluster.local minio minio123
mc ls myminio
```

can you confirm these steps fail for you?

**Comment by celalsahin** [comment]
Hi Daniel!

Thanks for the quick reply! I can confirm that those steps fail for me:

[csahin@qp08c ~]$ kubectl run my-shell  -i --tty --image miniodev/debugger -- bash
If you don't see a command prompt, try pressing enter.
root@my-shell:/# cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /etc/ssl/certs/
root@my-shell:/# mc config host add myminio https://minio.minio-test-tenant1.svc.cluster.local 4b6b7e02-3327-453f-8296-8d9199e1bed6 4ea1021d-d1a6-41d9-acac-20865cbee6a4
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "https://minio.minio-test-tenant1.svc.cluster.local/probe-bucket-sign-uwju99nmmxun/?location=": x509: certificate signed by unknown authority.
root@my-shell:/#

I am curious how this works on your cluster, as per definition found in:

https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

"anything that is signed by "certificates.k8s.io" will be signed by a dedicated CA."
That note also adds "It is possible to configure your cluster to use the cluster root CA for this purpose, but you should never rely on this. " - is it possible that you made some configuration on your cluster? Or maybe using another version of kubernetes?

Regards
Celal

**Comment by Alevsk** [comment]
> cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /etc/ssl/certs/

Hi @celalsahin please try copying the `ca.crt` file to MinIO's `certs/CAs` folder

```
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt $HOME/.minio/certs/CAs
```

MinIO will verify everything against all the certificates in that folder

**Comment by celalsahin** [comment]
Hi both,

Thanks for your quick replies.

@Alevsk minio-debugger does not have the necessary folder structure:

**Comment by Alevsk** [comment]
@celalsahin understood, didn't saw you were running `mc` inside a pod the first time, in that case please try this first (if the folder doesn't exists please create it manually):

```
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt $HOME/.mc/certs/CAs
```

Answering your question:

> That being said, for me (& people like me) to work around this issue, does minio operator provide a way of installing/running the service inside the cluster as http? I couldn't find anything related to that in the docu.
> 

It's possible to deploy a tenant with TLS disabled (please look at https://github.com/minio/operator/blob/master/examples/tenant.yaml#L130), you will need to use the YAML 

```
spec
  requestAutoCert: false
  ...
  ..
```

**Comment by harshavardhana** [comment]
> cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt $HOME/.mc/certs/CAs

We should let `mc` also automatically read from this location like MinIO server @Alevsk

**Comment by Alevsk** [comment]
@celalsahin please update to latest version `mc`, mc will automatically load the `ca.crt` file in the ca certificates pool

**Comment by celalsahin** [comment]
Hi both,

Sorry but I still feel I cannot explain myself good enough.
First result of the tests you requested: (from start of creation of the tenant)

```
[csahin@qp08c ~]$ oc new-project minios3

Now using project "minios3" on server "https://api.ocp2.emcode.siemens.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app ruby~https://github.com/sclorg/ruby-ex.git

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node

[csahin@qp08c ~]$ oc project minios3
Already on project "minios3" on server "https://api.ocp2.emcode.siemens.com:6443".
[csahin@qp08c ~]$ kubectl minio tenant create --name minios3 --servers 4 --volumes 16 --capacity 160Gi --namespace minios3 --storage-class local-storage -o > tenant.yaml
[csahin@qp08c ~]$ vim tenant.yaml #I edit the tenant so I replace console version with 0.4.6 otherwise it does not come up - I am using 3.0.29 minio-operator version. - no other edit is done on the yaml.
[csahin@qp08c ~]$ oc create -f tenant.yaml
tenant.minio.min.io/minios3 created
secret/minios3-creds-secret created
secret/minios3-console-secret created
[csahin@qp08c ~]$
```

Then the test you asked:

**Comment by celalsahin** [comment]
Regarding:
||If you want just to get unstuck and continue your work, you can use the --insecure flag in your mc client (but copying the certificate above should work), ie:
--> I am using mc debugger just to provide more information. In my real use case some CI jobs will access s3 storage & "insecure" is not an option 

|| It's possible to deploy a tenant with TLS disabled (please look at https://github.com/minio/operator/blob/master/examples/tenant.yaml#L130), you will need to use the YAML
--> I will test this & come back - if this works this can be a work around for the time being

**Comment by Alevsk** [comment]
@celalsahin thanks for the clarification, now is more clear, we will continue investigating the issue, in the mean time there's an option for you to provide manually generated certificates that works witth your CI Jobs:

```
spec:
  externalCertSecret:
    - name: tls-ssl-minio
       type: kubernetes.io/tls
 ```

If `tls-ssl-minio` it's a generic secret operator will look for the `public.crt` and `private.key` field, if the secret type is `kubernetes.io/tls` then `tls.crt` and `tls.key`

**Comment by celalsahin** [comment]
@Alevsk Thanks for the proposal, I am able to get http working - this is good of a work around for us, for the time being :)

**Comment by memelet** [comment]
I have this exact problem. Was there any resolution before the issue was closed?
