### ISSUE TITLE
[Question] slack channel not publicly accessible

### ISSUE THREAD

**Issue by vvavepacket** [minio/operator#461]
I would like to join the slack channel but it seems its private only. Does someone have a unique link or is it invite only?

My question was how can I install minio operator on a specific namespace?

I'm using `kubectl krew minio init`, but it install to a default namespace.

**Comment by kerneltime** [comment]
You should be able to provide the namespace 
```> kubectl minio init --help

'init' command creates MinIO Operator deployment along with all the dependencies.

Usage:
  minio init [flags]

Examples:
  kubectl minio operator init

Flags:
  -d, --cluster-domain string       cluster domain of the Kubernetes cluster (default "cluster.local")
  -h, --help                        help for init
  -i, --image string                operator image (default "minio/k8s-operator:v3.0.29")
      --image-pull-secret string    image pull secret to be used for pulling operator image
  -n, --namespace string            namespace scope for this request (default "default")
      --namespace-to-watch string   namespace where operator looks for MinIO tenants, leave empty for all namespaces
  -o, --output                      dry run this command and generate requisite yaml
```

**Comment by vvavepacket** [comment]
Thanks Ritesh, do you happen to be a member of minio slack. Are users allowed to join?

**Comment by harshavardhana** [comment]
its self invite https://slack.minio.io @vvavepacket

**Comment by vvavepacket** [comment]
@harshavardhana 
It is not.. It is invite only.. Can you please enable it or add me ?

![image](https://user-images.githubusercontent.com/8295642/107284493-eac74d00-6a2b-11eb-9aaa-0779ad0f7c2d.png)


Only allowed are those with .minio.io domain

**Comment by harshavardhana** [comment]
Looks like invite has expired let me fix it @vvavepacket

**Comment by harshavardhana** [comment]
Refresh the page and try again @vvavepacket

**Comment by vvavepacket** [comment]
@harshavardhana 
For some reason, I still could not join :/ It still says invite only and does not allow someone to self join... Tried signing in with my email but still not seeing the option to join minio

**Comment by harshavardhana** [comment]
> For some reason, I still could not join :/ It still says invite only and does not allow someone to self join... Tried signing in with my email but still not seeing the option to join minio

You should refresh the page @vvavepacket - try incognito mode.

**Comment by harshavardhana** [comment]
![slack](https://user-images.githubusercontent.com/622699/107286098-fb1ffd80-6a14-11eb-9736-cfd0b7ad7d82.png)

This is what you should see

**Comment by vvavepacket** [comment]
Thanks able to join!

**Comment by fireshaper** [comment]
It looks like it's not working again. 
![image](https://user-images.githubusercontent.com/10916477/142262864-6eb5d4f6-ffe2-4a0e-9a5d-d7382d866d55.png)

**Comment by harshavardhana** [comment]
> It looks like it's not working again. ![image](https://user-images.githubusercontent.com/10916477/142262864-6eb5d4f6-ffe2-4a0e-9a5d-d7382d866d55.png)

Refresh - it's fixed.

**Comment by nicolaerosia** [comment]
@harshavardhana can you please fix it again?:)

**Comment by harshavardhana** [comment]
> @harshavardhana can you please fix it again?:)

It is fixed already you just need to go to incognito, it must have cached and older URL.

**Comment by nicolaerosia** [comment]
found the fix, I need to use https://slack.minio.io - otherwise I need an invitation

**Comment by harshavardhana** [comment]
that is the correct link

**Comment by aaronplata123** [comment]
@harshavardhana can you please fix it again?:)
