### ISSUE TITLE
securityContext not respected in console deployments (and therefore pods)

### ISSUE THREAD

**Issue by ConnorJC3** [minio/operator#466]
## Expected Behavior
Setting the security context should apply to all pods created by the operator. Alternatively, there should be a configuration option for separate pods to set the securityContext.

## Current Behavior
Setting the securityContext only applies to the minio StatefulSet, and not the console deployment.

## Possible Solution
Apply the securityContext to other minio components as well.

## Steps to Reproduce (for bugs)
1. Create a minio tenant with a `securityContext` and console
2. Observe it is not propagated to the console deployment/pod

## Context
I am attempting to use the minio operator on a cluster where running containers with the root user is prohibited (both as an official policy and technically via a PodSecurityPolicy). The console pod gets stuck at `CreateContainerConfigError` with the error:

```
Error: container has runAsNonRoot and image will run as root (pod: "example-console-5fcdc814d-2zm7h_namespace(8061bfa4-f11e-433d-9f99-15794e36c45d)", container: console)
```

## Regression
Not a regression.

## Your Environment
N/A (applies to all environments)

**Comment by dvaldivia** [comment]
do you expect the same securityContext for console? I think it'd make sense to have separate securityContext for console pods as well as logging, prometheus and kes pods

**Comment by ConnorJC3** [comment]
In my case, a separate context for console is unneeded, because I just need to make sure the container is running with a non-root user (so as long as the same context works on both types of pods I'm good to go). However, a separate context per type of pod may help others with more diverse needs, and would be equivalently useful for me, so that would be cool too.
