### ISSUE TITLE
kubectl minio plugin doesn't properly cleanup after operator 3.0.29

### ISSUE THREAD

**Issue by jhoblitt** [minio/operator#473]
```
-bash-4.2$ kubectl krew list
PLUGIN  VERSION
krew    v0.4.0
minio   v3.0.29
-bash-4.2$ kubectl minio delete
Are you sure you want to delete ALL the MinIO Tenants and MinIO Operator? [Y/N]: y
Error: serviceaccounts "minio-operator" not found
-bash-4.2$ 
-bash-4.2$ kubectl minio init --image=minio/k8s-operator:v4.0.0
CustomResourceDefinition tenants.minio.min.io: created
ClusterRole minio-operator-role: created
ServiceAccount minio-operator: created
Error: ClusterRoleBinding minio-operator-binding: already present, skipped
```

## Your Environment
* Version used (`minio-operator`): 3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): rke 1.19.7
* Server type and version: dell r740s
* Operating System and version (`uname -a`): `Linux chonchon01.cp.lsst.org 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jhoblitt** [comment]
The help for `delete` claims that the default namespace is default but it still only does a partial cleanup with the `-n` flag. E.g. the operator pod is still running.

```
-bash-4.2$ kubectl minio delete -h

'delete' command delete MinIO Operator deployment along with all the tenants.

Usage:
  minio delete [flags]

Examples:
  kubectl minio delete

Flags:
  -h, --help               help for delete
  -n, --namespace string   namespace scope for this request (default "default")
-bash-4.2$ kubectl minio delete -n minio-operator
Are you sure you want to delete ALL the MinIO Tenants and MinIO Operator? [Y/N]: y
Error: customresourcedefinitions.apiextensions.k8s.io "tenants.minio.min.io" not found
```

**Comment by cesnietor** [comment]
@jhoblitt thanks for reporting the issue, I've sent one pr to fix some issues.  ^

**Comment by jhoblitt** [comment]
I haven't checked all the resources yet but I can confirm that at least the clusterrolebinding for the console is now being cleaned up.  Thank you!
