### ISSUE TITLE
warning in Makefile says to use controller-gen v0.4.6 but links to v0.4.7

### ISSUE THREAD

**Issue by jhoblitt** [minio/operator#477]
When running `make` on current master, this warning is printed:
```
WARNING: for the time being, you need to clone and build github.com/minio/controller-tools/cmd/controller-gen@v0.4.6
```

However, right above the warning in the makefile, v0.4.7 is being fetched:

https://github.com/minio/operator/blob/master/Makefile#L57

v0.4.7 is also specified in `go.mod`:

https://github.com/minio/operator/blob/master/go.mod#L10

There doesn't seem to be any manual attempt in the github workflow to install an alternative version either:

https://github.com/minio/operator/blob/master/.github/workflows/go.yml#L31-L32

So is this warning real? Which version of `controller-gen` should be used?

**Comment by jhoblitt** [comment]
Also, I am getting the same error regenerating the CRD with both `controller-gen` v0.4.6 and v0.4.7: 

```
Error: rawResources failed to read Resources: Load from path ../base failed: '../base' must be a file (got d='/home/jhoblitt/github/operator/resources/base')
```

**Comment by jhoblitt** [comment]
Updating kustomize to `{Version:kustomize/v4.0.1 GitCommit:516ff1fa56040adc0173ff6ece66350eb4ed78a9 BuildDate:2021-02-13T21:21:14Z GoOs:linux GoArch:amd64}` resolved the `rawResources` error.

**Comment by dvaldivia** [comment]
nice catch, I'll update it to the `v0.4.7` on my next PR
