### ISSUE TITLE
Unexpected keys provided at minio tenant installation; no console generated

### ISSUE THREAD

**Issue by Pratyush2703** [minio/operator#487]
Following the steps at [https://github.com/minio/operator/blob/master/README.md](https://github.com/minio/operator/blob/master/README.md), instead of receiving the 

`Tenant 'minio-tenant-1' created in 'minio-tenant-1' Namespace
  Username: admin 
  Password: dbc978c2-bfbe-41bf-9dc6-699c76bafcd0 
+-------------+------------------------+------------------+--------------+-----------------+
| APPLICATION |      SERVICE NAME      |     NAMESPACE    | SERVICE TYPE | SERVICE PORT(S) |
+-------------+------------------------+------------------+--------------+-----------------+
| MinIO       | minio                  | minio-tenant-1   | ClusterIP    | 443             |
| Console     | minio-tenant-1-console | minio-tenant-1   | ClusterIP    | 9090,9443       |
+-------------+------------------------+------------------+--------------+-----------------+`

I get the image as below.

![Screenshot from 2021-02-22 22-53-18](https://user-images.githubusercontent.com/36813309/108741678-8c40b980-7569-11eb-8458-df799b6b4a7a.png)
This is on a locally deployed cluster with 2 nodes.

Furthermore, no minio-console service is generated

**Comment by ravindk89** [comment]
The currently documented output may have been from an earlier patch of master...I will test and validate what the actual output is. In the short term, I'll remove the explicit example, as you are still getting credentials for the Tenant and MinIO Console as expected. 

As far as the service goes - can you provide the output of `kubectl get svc --namespace minio-tenant-1` ?

**Comment by harshavardhana** [comment]
v4.0.0 released, please try again.

**Comment by Pratyush2703** [comment]
Issue was fixed in v4.0.0
