### ISSUE TITLE
securing minio access key and secret key with Hashicorp vault 

### ISSUE THREAD

**Issue by akshayuppal3** [minio/operator#493]
I referred to this link https://gist.github.com/harshavardhana/427f6cffc068418278129f4e65cbf9cc to inject secrets via vault sidecar injection. But instead of using deployment file I am updating the values.yaml and deploying via helm.
So to export access key and secret key as environment variables we need to source the secrets and entrypoint script but for that, we need to issue a bash command similar to https://gist.github.com/harshavardhana/427f6cffc068418278129f4e65cbf9cc#file-vault-secrets-minio-yaml-L48 but can we do the same with values.yaml.
I see we have extraArgs in values yaml but I guess it appends the argument instead of being entry-point script. Can we add command with values yaml?

my code so far
```
values.yaml
 .............. trimming some lines
  podAnnotations:
    vault.hashicorp.com/agent-pre-populate: "false"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-minio-access-key: "kv/data/shared/blob/name"
    vault.hashicorp.com/agent-inject-secret-minio-secret-key: "kv/data/shared/blob/key"
    vault.hashicorp.com/role: "minio-app"
    vault.hashicorp.com/agent-inject-template-minio-access-key: |
      {{`
      {{- with secret "some path" -}}
          export MINIO_ACCESS_KEY="{{ .Data.data.access_key }}"
      {{- end -}}
      `}}
    vault.hashicorp.com/agent-inject-template-minio-secret-key: |
      {{`
      {{- with secret "some path" -}}
          export MINIO_SECRET_KEY="{{ .Data.data.secret_key }}"
      {{- end -}}
      `}}

  # sourcing vault secrets as mentioned here: https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example
  command: [
      "/bin/sh",
      "-ce",
      "source /vault/secrets/minio-secret-key && /vault/secrets/minio-access-key
      && /usr/bin/docker-entrypoint.sh"]
```

**Comment by harshavardhana** [comment]
Did you use operator? - looks like you are copy pasting helm chart configuration here @akshayuppal3 ..

**Comment by akshayuppal3** [comment]
how can we check just to be sure

**Comment by harshavardhana** [comment]
> how can we check just to be sure

Start following the operator docs and first install the operator.. https://docs.min.io/minio/k8s/
