### ISSUE TITLE
Minio-tenant-1-console service is not created

### ISSUE THREAD

**Issue by Pratyush2703** [minio/operator#496]
## Expected Behavior
minio-tenant-1-console service is created 

## Steps to Reproduce (for bugs)
Using the latest version of minio released today (v4.0.0)

Operator init:
![Screenshot from 2021-02-25 11-14-38](https://user-images.githubusercontent.com/36813309/109106116-c2e12480-7761-11eb-9fb5-59b439fa8fee.png)

Tenant creation:
![Screenshot from 2021-02-25 11-15-56](https://user-images.githubusercontent.com/36813309/109106195-e015f300-7761-11eb-9855-3b7288f29b50.png)

However, the minio tenant console isn't created as a service and so cannot be accessed:
![Screenshot from 2021-02-25 12-15-57](https://user-images.githubusercontent.com/36813309/109106861-3df70a80-7763-11eb-8a21-1d4cd4814667.png)

**Comment by nitisht** [comment]
krew plugin has not be updated yet, so you're probably running older plugin. We'll let you know once krew is updated

**Comment by nitisht** [comment]
actually looks like it is released. https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/minio.yaml 

Can you check  the namespace `minio-operator` for the service?

**Comment by Pratyush2703** [comment]
There IS a console service in minio-operator namespace. Accessing it asks for a JWT token instead of login credential.

![Screenshot from 2021-02-25 12-38-58](https://user-images.githubusercontent.com/36813309/109108724-a4c9f300-7766-11eb-925b-4fa04a2f345a.png)

![Screenshot from 2021-02-25 12-42-24](https://user-images.githubusercontent.com/36813309/109108894-f2def680-7766-11eb-8181-d34f5eabe581.png)

**Comment by nitisht** [comment]
That console is operator console, if you're looking for tenant console, look at the namespace `minio-tenant-1`

**Comment by Pratyush2703** [comment]
Yes; in that namespace there is no console service. That is the issue.

Please See: 
![image](https://user-images.githubusercontent.com/36813309/109117661-de095f80-7774-11eb-8841-66ea063e71d3.png)

**Comment by nitisht** [comment]
are console pods running? can you try `kubectl get pods -n minio-tenant-1`

**Comment by Pratyush2703** [comment]
![Screenshot from 2021-02-25 14-46-43](https://user-images.githubusercontent.com/36813309/109120271-558cbe00-7778-11eb-96fb-930560470c36.png)

Dont see them. I did `kubectl describe pods` on the above pod and the message was 

`Warning  FailedMount  6s (x7 over 38s)  kubelet            MountVolume.SetUp failed for volume "minio-tenant-1-tls" : secret "minio-tenant-1-tls" not found`
 
 
![Screenshot from 2021-02-25 14-49-06](https://user-images.githubusercontent.com/36813309/109120562-b3b9a100-7778-11eb-8a48-bf7f437ac351.png)

**Comment by Pratyush2703** [comment]
I assume `minio-tenant-1-tls` should have been created during this process?

**Comment by nitisht** [comment]
yes, let me check and get back on this. What is the k8s distribution here?

**Comment by Pratyush2703** [comment]
Not sure how to find that out; Kubernetes was installed in our inhouse servers 

![Screenshot from 2021-02-25 16-38-27](https://user-images.githubusercontent.com/36813309/109133785-efa83280-7787-11eb-90a8-b29b7957ba8e.png)

The following resource was followed to set it up: https://acloudguru.com/blog/engineering/building-a-three-node-kubernetes-cluster-quick-guide

**Comment by longlnk** [comment]
I same problem with v4.0.0
![image](https://user-images.githubusercontent.com/15074179/109686060-82940300-7bb4-11eb-91e5-8d8482db8128.png)
![image](https://user-images.githubusercontent.com/15074179/109686086-89227a80-7bb4-11eb-8c36-f214f4e07d57.png)
![image](https://user-images.githubusercontent.com/15074179/109686158-97709680-7bb4-11eb-814b-14fccf1aa588.png)

**Comment by nitisht** [comment]
How was your cluster deployed? It is OpenShift?

**Comment by longlnk** [comment]
> How was your cluster deployed? It is OpenShift?

Hi,

I deployed on Rancher (2.4.5) /K8s (1.18.x)

**Comment by titou10titou10** [comment]
Same kind of error as described in the initial post on OpenShift v4.6.18, ie the`minio tenant create`just create 2 services ("minio and minio-tenant-1-hl) , 3 secrets and nothing else

I see those message in the`minio-operator`pod in the`minio-operator` namespace: `"cannot set blockOwnerDeletion"`

    main.go:72] Starting MinIO Operator
    main.go:139] caBundle on CRD updated
    main-controller.go:250] Setting up event handlers
    main-controller.go:634] Starting Tenant controller
    main-controller.go:637] Waiting for informer caches to sync
    main-controller.go:598] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
    warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
    warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
    warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
    csr.go:217] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s
    main-controller.go:642] Starting workers
    warnings.go:70] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
    csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
    operator.go:129] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
    {...}

Versions:

    oc version
    Client Version: 4.6.19
    Server Version: 4.6.18
    Kubernetes Version: v1.19.0+f173eb4

**Comment by matthijsthoolen** [comment]
Any updates on this issue. I have a RKE based kubernetes cluster with minio v4.0.1. Currently having the same issues as described here, no console (only the operator console), and error logs with "Operator-tls" not found.

**Comment by msecker** [comment]
same problem here, no pods were created and console service is missing on RKE...

**Comment by jgato** [comment]
what is the reason for that? I would like not to have to modify the default rancher configuration (unless is absolutly need it). Is this because it tries to generate some kind of automatic certificates? because I have my own ones.

**Comment by travisghansen** [comment]
Hitting the same issue with the secret here as well. Also with `rke`. I'll try the `extra_args` and see how that goes.

**Comment by travisghansen** [comment]
If note, I disabled `tls` so not sure why it's still trying to do this anyway..

**Comment by DanielLopezDiaz** [comment]
+1 @travisghansen.

We are expiring the same issue, with the procedure of disable tls.

**Comment by travisghansen** [comment]
I did add the extra args and things came up. I’m unclear exactly how that secret is used and if it’s use can be disabled or not. For now I’m moving along though.

**Comment by nitisht** [comment]
> operator TLS not found on RKE .- fixed this issue by adding the below extra args under kube-controller in rancher cluster config file .
> 
> ```
>   extra_args:
>     cluster-signing-cert-file: /etc/kubernetes/ssl/kube-ca.pem
>     cluster-signing-key-file: /etc/kubernetes/ssl/kube-ca-key.pem
> ```
> 
> after deploying tenant object everything works fine except console pods are not creating.

Closing as this is the working solution for Rancher.
