### ISSUE TITLE
tenant expand returns "Error: the server could not find the requested resource"

### ISSUE THREAD

**Issue by celalsahin** [minio/operator#497]
I have a tenant created with 3.0.29 - I tried to expand the storage before release of 4.0.0 which failed & I opened a bug(https://github.com/minio/operator/issues/467) & it was resolved - thanks!
Now I update my operator to 4.0.0 & try the expand again, it is failing with Error: the server could not find the requested resource (get tenants.minio.min.io minios3)
But the tenant exists, details will be below.

## Expected Behavior

I would expect tenant expand to work when there is a running tenant with that name

## Current Behavior

tenant expand does not work.

## Steps to Reproduce (for bugs)

1. First follow the steps described in https://github.com/minio/operator/issues/467#issuecomment-778619830 with operator version 3.0.29 - at least this is how this tenant is created.
2. Update the operator to 4.0.0
3. 
```
[csahin@qp08c ~]$ oc get tenant -n minios3
NAME      STATE         AGE
minios3   Initialized   11d
[csahin@qp08c ~]$
```
4. 
```
[csahin@qp08c ~]$ kubectl minio tenant expand minios3 --servers 4 --volumes 4 --capacity 20Gi --namespace minios3
Error: the server could not find the requested resource (get tenants.minio.min.io minios3)
[csahin@qp08c ~]$
```

## Context

I am trying to expand a minio tenant I created. I hope expanding tenants created with earlier operator versions are supported.

## Your Environment

* Version used (`minio-operator`): 4.0.0  (tenant was initially created with operator version 3.0.29)
* Environment name and version (e.g. kubernetes v1.17.2): OCP 4.6.13
* Server type and version: 
* Operating System and version (`uname -a`): 
* Link to your deployment file:

**Comment by Pratyush2703** [comment]
I was able to fix this issue by completely uninstalling and reinstalling minio operator including all of its components, some of which need to be deleted manually. Specifically, delete all the components created during `kubectl minio init`

This is not the correct way to fix your problem but worked out for me

**Comment by celalsahin** [comment]
Thanks for your comment Mishra, can I find the "instructions" to "completely uninstall" the operator somewhere? - I guess this means that I can keep my old tenants (as they are productive currently) & just uninstall/re-install the operator so I can expand.

**Comment by Pratyush2703** [comment]
No, sorry; the tenants were lost during this

**Comment by celalsahin** [comment]
hmm, okay then this is indeed not a solution nor a work around for the problem :)

Thanks for writing to me anyway! :)

**Comment by longlnk** [comment]
I same problem with version v4.0.0

![image](https://user-images.githubusercontent.com/15074179/109685918-55475500-7bb4-11eb-9bd5-1511c0948209.png)
![image](https://user-images.githubusercontent.com/15074179/109685961-609a8080-7bb4-11eb-8ab9-3bd66fa532d3.png)

**Comment by tomoki1337** [comment]
I'm getting what I'm assuming is an RBAC issue after upgrading from v3.0.29 to v4.0.0 using krew
![image](https://user-images.githubusercontent.com/22425997/109790698-f6182d80-7c11-11eb-99b0-d2a9cd4f6433.png)
minio-operator log: 
```
I0303 10:08:56.039648       1 main.go:72] Starting MinIO Operator 
E0303 10:08:56.083499       1 main.go:131] Error getting CRD for adding caBundle: customresourcedefinitions.apiextensions.k8s.io "tenants.minio.min.io" is forbidden: User "system:serviceaccount:minio-operator:minio-operator" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope 
I0303 10:08:56.084622       1 main-controller.go:250] Setting up event handlers 
I0303 10:08:56.084831       1 main-controller.go:634] Starting Tenant controller 
I0303 10:08:56.084860       1 main-controller.go:637] Waiting for informer caches to sync 
E0303 10:08:56.095139       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
I0303 10:08:56.152285       1 main-controller.go:625] Starting api server 
E0303 10:08:57.381919       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
E0303 10:09:00.082739       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
E0303 10:09:03.494726       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
E0303 10:09:10.900957       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
E0303 10:09:24.945446       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
E0303 10:09:58.252399       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
E0303 10:10:43.712771       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
E0303 10:11:38.134853       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
E0303 10:12:14.567097       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) 
E0303 10:12:55.994101       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: the server could not find the requested resource (get tenants.minio.min.io) `

**Comment by celalsahin** [comment]
Just fyi that this issue continues with the latest release 4.0.1

**Comment by celalsahin** [comment]
Issue persists with release 4.0.5
