### ISSUE TITLE
Any plans to provide an OLM (Operator Lifecycle Manager) package?

### ISSUE THREAD

**Issue by titou10titou10** [minio/operator#501]
Are there any plans to provide an integration with OLM for installation, automatic update etc?
Thanks

Operator Lifecycle Manager official site: https://olm.operatorframework.io/

**Comment by harshavardhana** [comment]
Moving to relevant repo

**Comment by davidkarlsen** [comment]
Isn't https://artifacthub.io/packages/olm/community-operators/minio-operator this ?

**Comment by titou10titou10** [comment]
@davidkarlsen I was talking about the current version of the MinIO operator: https://github.com/minio/operator/blob/master/README.md
The operator you point out is years behind the current code (latest version 10/2019..), The CRD defines`"MinIOInstances"`objects where the current version of the MinIO operator manage`"Tenants"`...
IMHO It is so obsolete  that it should be removed from the the OeratorHub OLM catalog

**Comment by davidkarlsen** [comment]
@titou10titou10 it actually points to this repo, but yes, it is ancient (v1.0.3).

**Comment by kfox1111** [comment]
+1 an olm bundle would be really nice.

**Comment by kfox1111** [comment]
olm support for deployment would be great. It would allow the operator to be easily installed per namespace, and different versions of the operator potentially installed in different namespaces with auto / manual approval for upgrades. This really helps with testing upgrades.

**Comment by harshavardhana** [comment]
MinIO is now available as part of the Red Hat's OpenShift operators catalog https://catalog.redhat.com/software/operators/detail/60945b58d3f6d18cdbac26fe

**Comment by kfox1111** [comment]
It doesn't seem to have been updated for Kubernetes, only OpenShift:
https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/minio-operator

**Comment by harshavardhana** [comment]
> It doesn't seem to have been updated for Kubernetes, only OpenShift:
> https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/minio-operator

No plans to add it there @kfox1111 for now.
