### ISSUE TITLE
Error: Storage resources are insufficient for the read operation

### ISSUE THREAD

**Issue by maxclac** [minio/operator#504]
Hi all!

## Expected Behavior
Having a Tenant up and running

## Current Behavior

After creating a tenant like this:
```
kubectl minio tenant create minio-tenant-1 --servers 1 --volumes 4 --capacity 10Mi --namespace minio --storage-class local-storage
```
The tenant is undefinitely waiting for the pods to be ready
```
# kubectl get tenants -n minio
NAME             STATE                          AGE
minio-tenant-1   Waiting for Pods to be ready   16m
```
The logs of the only pod running are telling this:

```
root@k8s-controller:~/minio# kubectl logs minio-tenant-1-ss-0-0 -n minio
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)

API: SYSTEM()
Time: 15:03:53 UTC 03/02/2021
DeploymentID: 5b6400f3-58e1-454f-851f-80d38b82a871
Error: Storage resources are insufficient for the read operation .minio.sys/buckets/.bloomcycle.bin (cmd.InsufficientReadQuorum)
       1: cmd/data-scanner.go:92:cmd.runDataScanner()
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)

```

## Your Environment

* Version used (`minio-operator`): VERSION: v4.0.0
* Environment name and version: kubernetes v1.20.4 
* Operating System: Ubuntu 20.04.2 LTS
* Kernel: Linux 5.4.0-66-generic
* Master node: 2 CPUs, 4 GB RAM, 25 GB Disk
* Worker nodes 1 and 2: 4 CPUs, 8 GB RAM, 25 GB Disk

**Comment by nitisht** [comment]
> --servers 1 --volumes 4 --capacity 10Mi

Please use atleast 8Gi total, i.e. ` --capacity 8Gi`

**Comment by maxclac** [comment]
I did just that, I still have the problem.

**Comment by maxclac** [comment]
I was just thinking: maybe I don't have enough nodes in my cluster? Is there a minimum number of nodes to get the Minio operator working?

**Comment by Pratyush2703** [comment]
I was able to progress with 2 nodes (including tainted master)

**Comment by harshavardhana** [comment]
> root@k8s-controller:~/minio# kubectl logs minio-tenant-1-ss-0-0 -n minio
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> 
> API: SYSTEM()
> Time: 15:03:53 UTC 03/02/2021
> DeploymentID: 5b6400f3-58e1-454f-851f-80d38b82a871
> Error: Storage resources are insufficient for the read operation .minio.sys/buckets/.bloomcycle.bin (cmd.InsufficientReadQuorum)
>        1: cmd/data-scanner.go:92:cmd.runDataScanner()
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
> Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)

This is mainly because you have pods running in different versions - most probably @maxclac

**Comment by maxclac** [comment]
How can that be? Aren't the pods supposed to be created all at once? How can I have a version discrepancy in my pods?

**Comment by dvaldivia** [comment]
@maxclac are you re-creating the tenant with the same name? If so are you deleting the PVCs between attempts?

**Comment by maxclac** [comment]
Yes, I delete everything before recreating a tenant. I will double check to see if I thought about also deleting the pods.

**Comment by maxclac** [comment]
Hi! I still have this problem although I really deleted everything related to the tenant. Anything else I can do?

**Comment by maxclac** [comment]
I now use the same number of servers and volumes as in the instructions. Each of my PVC are 1Gi each.

```
kubectl minio tenant create minio-tenant-1 --servers 4 --volumes 16 --capacity 16Gi --namespace minio --storage-class local-storage
```
Now something new is coming:

```
API: SYSTEM()
Time: 10:55:31 UTC 03/10/2021
Error: lookup minio-tenant-1-ss-0-2.minio-tenant-1-hl.minio.svc.cluster.local on 10.96.0.10:53: read udp 10.244.140.23:47945->10.96.0.10:53: i/o timeout (*net.DNSError)
       host=minio-tenant-1-ss-0-2.minio-tenant-1-hl.minio.svc.cluster.local, elapsedTime=30 seconds elapsed
       5: cmd/endpoint.go:469:cmd.Endpoints.UpdateIsLocal()
       4: cmd/endpoint.go:653:cmd.CreateEndpoints()
       3: cmd/endpoint-ellipses.go:372:cmd.createServerEndpoints()
       2: cmd/server-main.go:142:cmd.serverHandleCmdArgs()
       1: cmd/server-main.go:418:cmd.serverMain()
```
