### ISSUE TITLE
Operator to deploy MinIO NAS gateway and Console 

### ISSUE THREAD

**Issue by lucas-dehandschutter** [minio/operator#524]
**Describe the solution you'd like**

My K8s cluster has a huge NAS storage plugged to it as a NFS PV.
I would like to use Operator to deploy Minio Nas Gateway to it ( with Console and KES if possible ) .
Actually, the documentation of Operator only mention Minio distributed Installation. 
Thx

**Comment by harshavardhana** [comment]
Gateway is not going to be part of the Operator @lucas-dehandschutter - you need to construct your own yaml and deploy.
