### ISSUE TITLE
error syncing 'default/minio': secrets "operator-tls" not found

### ISSUE THREAD

**Issue by samene** [minio/operator#525]
Installed minio-operator following the instructions provided here - https://github.com/minio/operator/tree/master/helm/minio-operator

Then created sample tenant from manifest https://github.com/minio/operator/blob/master/examples/tenant.yaml

## Expected Behavior
Minio installation created successfully

## Current Behavior
Error in Operator logs and nothing created

`E0307 08:30:48.459921       1 main-controller.go:720] error syncing 'default/minio': secrets "operator-tls" not found
E0307 08:30:58.418716       1 main-controller.go:720] error syncing 'default/minio': secrets "operator-tls" not found
E0307 08:31:58.433530       1 main-controller.go:720] error syncing 'default/minio': secrets "operator-tls" not found
`

## Your Environment

* Version used (`minio-operator`): master
* Environment name and version (e.g. kubernetes v1.17.2): 1.18.8

**Comment by toabi** [comment]
I did exactly the same.

Installed the helm chart with default values and then the example tenant.

I wondered why nothing happens and I'm seeing the same error messages.

https://github.com/minio/operator/blob/c1d330746b9e86717921b099911649cd14362944/pkg/controller/cluster/operator.go#L119-L123 looks like it should create the secret itself… but none was created.

**Comment by toabi** [comment]
Solved for my by doing exactly this: https://github.com/minio/operator/issues/395#issuecomment-748657628

**Comment by jgato** [comment]
@toabi is there any way to make the operator to use an existing certificate instead of allowing it to create a new one? I am also using rancher and I guess I have a similar problem. But I have also my own certificate, so I prefer to use the Operator with it. 

There is something no clear for me during the installation. In the default values.yaml there installs the ooperator but also a console, but later, console is also installed when creating tenants, why?

**Comment by balorette** [comment]
Fighting through this one as well, almost to the point of scrapping the Operator. 

The reason there are two console is one is the UI for the Operator, the other is the UI for the tenant. The image is the same but its functionality is driven by Env Vars.

**Comment by balorette** [comment]
> ok, so in the values.yaml the specification of .console is to define the Console for the operator. And the values for .tenant.console is for the usual MINIO GUI, right? This at least could help to detect where is the issue with the automatic certificates generaion.

Yes, the cert generation though looks to be done within the Operator, i.e. coded into it. [https://github.com/minio/operator/blob/master/pkg/controller/cluster/operator.go]

**Comment by balorette** [comment]
A crude work around is to query the CSR:
kubectl get certificatesigningrequest

Describe the signing request for MinIO and get the values, create a cert matching that and put it into a secret named operator-tls

At least gets you passed that.

**Comment by jgato** [comment]
I guess I will give up, and I will just patch the Rancher cluster as it was explained in other threads :(

**Comment by toabi** [comment]
Well, it looks like the Operator trust in this Kubernetes 1.19 feature https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/ which Rancher for some weird reason doesn't properly support in its default configuration.

**Comment by balorette** [comment]
> Well, it looks like the Operator trust in this Kubernetes 1.19 feature https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/ which Rancher for some weird reason doesn't properly support in its default configuration.



> I guess I will give up, and I will just patch the Rancher cluster as it was explained in other threads :(

From the path I've gone down this would probably be the right thing to do, I can see it being a "Proper" configuration. And if I read between the lines, Rancher offers the ability to use Cert Manager for a lot of things, which might be why it is not enabled by default.

**Comment by jgato** [comment]
would it be possible this issue is causing also the NO creation of the tenants? Because I cannot reach the MINIO Consoles.

**Comment by jgato** [comment]
I auto answer myself: yes

**Comment by jgato** [comment]
with the patch running the tenants appears to start, but the issues with tls certificates are there. Now in the pod for the tenant:

```
You are running an older version of MinIO released 1 month ago
Update: Run `mc admin update`


Status: 4 Online, 0 Offline.
Endpoint: https://10.42.0.162:9000 https://127.0.0.1:9000

Browser Access:
https://10.42.0.162:9000 https://127.0.0.1:9000

Object API (Amazon S3 compatible):
Go: https://docs.min.io/docs/golang-client-quickstart-guide
Java: https://docs.min.io/docs/java-client-quickstart-guide
Python: https://docs.min.io/docs/python-client-quickstart-guide
JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
.NET: https://docs.min.io/docs/dotnet-client-quickstart-guide
2021-04-13 14:45:53.034894 I | http: TLS handshake error from 10.42.2.125:45974: certs: no server certificate is supported by peer
2021-04-13 14:46:53.086422 I | http: TLS handshake error from 10.42.2.125:46316: certs: no server certificate is supported by peer
2021-04-13 14:47:53.128555 I | http: TLS handshake error from 10.42.2.125:46654: certs: no server certificate is supported by peer
2021-04-13 14:48:53.173616 I | http: TLS handshake error from 10.42.2.125:46926: certs: no server certificate is supported by peer
```

I had MInio installed with the previous version of the Helm/Chart and it was piece of cake.
