### ISSUE TITLE
Gateway Support

### ISSUE THREAD

**Issue by sharkymcdongles** [minio/operator#527]
Will the operator add gateway support? I read in older tickets it isn't on the roadmap yet, but it seems it should be since the old minio is being deprecated according to the git repo:

https://github.com/minio/charts

NOTE: This helm chart is being deprecated and this project will cease to take new updates from April 2021. All users are advised to migrate to our MinIO operator. MinIO operator supports helm chart.

I think it'd be useful to add it as the old minio gateway only supports single buckets at a time and an operator based one would allow for multiple.

**Comment by harshavardhana** [comment]
Gateway support won't come to operator for now.  We may do it in future if there is a customer interest.

Currently the scope of operator is distributed deployments only.

**Comment by aelbarkani** [comment]
I can't understand then why the helm chart is being deprecated and saying to migrate to operator if the operator won't support gateways...

**Comment by harshavardhana** [comment]
> I can't understand then why the helm chart is being deprecated and saying to migrate to operator if the operator won't support gateways...

Because gateway is not our main product - it is there for legacy reasons to migrate content to MinIO. If you want to perpetually use gateway that is not our intention.
