### ISSUE TITLE
unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed

### ISSUE THREAD

**Issue by narindergupta** [minio/operator#528]
I am deploying minio on kubernetes 1.20.4 using the csi driver of local-device on 4 nodes with 1 drive each.
Following this documentation 
https://github.com/minio/charts
operator and console on minio-operator namespaces are up and running no issue.
But when i apply the tenant.yaml i am seeing an error in kubernetes master

Mar  9 14:09:02 node01 kube-apiserver.daemon[100494]: E0309 14:09:02.072715  100494 cacher.go:419] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://operator.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s": dial tcp 10.1.50.5:4222: connect: connection refused; reinitializing...

## Expected Behavior
I should see pods created with required pvc from storage class.

## Current Behavior
Seeing the error in description and no pods have been created.

## Possible Solution
do not know

## Steps to Reproduce (for bugs)
1. install bare metal kubernetes with worker have two disk one for root and one for minio /dev/sdc
2. install openebs to create a device with openebs-device storage class
 kubectl get pods -A
NAMESPACE                         NAME                                                      READY   STATUS    RESTARTS   AGE
ingress-nginx-kubernetes-worker   default-http-backend-kubernetes-worker-6494cbc7fd-9lcnr   1/1     Running   0          7h4m
ingress-nginx-kubernetes-worker   nginx-ingress-controller-kubernetes-worker-426x5          1/1     Running   0          7h4m
ingress-nginx-kubernetes-worker   nginx-ingress-controller-kubernetes-worker-84npp          1/1     Running   0          7h4m
ingress-nginx-kubernetes-worker   nginx-ingress-controller-kubernetes-worker-bs9vr          1/1     Running   0          7h3m
ingress-nginx-kubernetes-worker   nginx-ingress-controller-kubernetes-worker-nvdwx          1/1     Running   0          7h3m
kube-system                       coredns-7bb4d77796-rth7f                                  1/1     Running   0          7h4m
kube-system                       kube-state-metrics-7f55b9fcd7-dfb9b                       1/1     Running   0          7h4m
kube-system                       metrics-server-v0.3.6-f6cf867b4-2qd2k                     2/2     Running   0          7h1m
kubernetes-dashboard              dashboard-metrics-scraper-74757fb5b7-8xgnp                1/1     Running   0          7h4m
kubernetes-dashboard              kubernetes-dashboard-64f87676d4-b5v2d                     1/1     Running   0          7h4m
minio-operator                    console-7494c75898-hjn69                                  1/1     Running   0          6h37m
minio-operator                    minio-operator-758cfccc86-7nprx                           1/1     Running   0          6h37m
openebs                           maya-apiserver-747fbf7f89-77xbn                           1/1     Running   4          6h47m
openebs                           openebs-admission-server-555b957648-b9c72                 1/1     Running   0          6h47m
openebs                           openebs-localpv-provisioner-7d7c74fbbb-qh4q7              1/1     Running   0          6h47m
openebs                           openebs-ndm-ckbgn                                         1/1     Running   0          6h47m
openebs                           openebs-ndm-cqsm7                                         1/1     Running   0          6h47m
openebs                           openebs-ndm-jpxc9                                         1/1     Running   0          6h47m
openebs                           openebs-ndm-operator-6bd5949967-4rzlh                     1/1     Running   0          6h47m
openebs                           openebs-ndm-tj5jc                                         1/1     Running   0          6h47m
openebs                           openebs-provisioner-cd9474fb8-v2gp7                       1/1     Running   0          6h47m
openebs                           openebs-snapshot-operator-897d78956-4dtt6                 2/2     Running   0          6h47m
ubuntu@OrangeBox24:~/fce-demo$ kubectl get sc
NAME                        PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-device              openebs.io/local                                           Delete          WaitForFirstConsumer   false                  6h45m
openebs-hostpath            openebs.io/local                                           Delete          WaitForFirstConsumer   false                  6h45m
openebs-jiva-default        openebs.io/provisioner-iscsi                               Delete          Immediate              false                  6h45m
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  6h45m
3. kubectl apply -f tenant.yaml # after changing the storage class to openebs-device
4. I should expect pods created under tenant namespaces and no pods created. and seeing error in kube API server.

## Context
Experimenting the minio

## Your Environment

* Version used (`minio --version`): latest 
* Server setup and configuration: 4 baremetal with kubernetes 1.20.4
* Operating System and version (`uname -a`): Ubuntu 20.04.   uname -a
Linux node01 5.4.0-66-generic minio/minio#74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nitisht** [comment]
What is the operator version @narindergupta ?

**Comment by narindergupta** [comment]
operator version i am seeing is


minio/operator:v4.0.0


Thanks and Regards,
Narinder Gupta
Canonical, Ltd.
+1.281.736.5150

Ubuntu- Linux for human beings | www.ubuntu.com | www.canonical.com

**Comment by nitisht** [comment]
looks like incorrect deployment @narindergupta . Please try creating operator using `kubectl apply -k ./resources` in `minio-operator` directory. Then create a tenant with relevant storage class and let us know how it goes. Closing this for now
