### ISSUE TITLE
Operator gives console credentials to Pods

### ISSUE THREAD

**Issue by haslersn** [minio/operator#533]
The operator gives the full content of the console secret to console Pods, including the special variables `CONSOLE_ACCESS_KEY` and `CONSOLE_SECRET_KEY`. This is an unnecessary exposure of the configured `CONSOLE_SECRET_KEY`. Example:

```yaml
$ kubectl get pod -l v1.min.io/console=minio-console -o json | jq '.items[0].spec.containers[0].envFrom[0]'
{
  "secretRef": {
    "name": "minio-console-secret"
  }
}
```

## Expected Behavior

Only the relevant variables (e.g. everything except `CONSOLE_ACCESS_KEY` and `CONSOLE_SECRET_KEY`) should be passed.

## Possible Solution

Preferably use `valueFrom.secretKeyRef`.

## Your Environment

* Version used (`minio-operator`): v4.0.2
* Environment name and version (e.g. kubernetes v1.17.2): v1.19.2

**Comment by Alevsk** [comment]
This issue will be fixed by https://github.com/minio/console/pull/647

**Comment by Alevsk** [comment]
Fix merged
