### ISSUE TITLE
operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)

### ISSUE THREAD

**Issue by wangjunjack** [minio/operator#538]
## Steps to Reproduce (for bugs)

1. when i create Tenant that will be "error syncing 'minio-tenant-1/tenant1': secrets "operator-tls" not found"
2. how i do it?
3.
4.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.18.1
<img width="1311" alt="error" src="https://user-images.githubusercontent.com/30251247/111739428-fffe8980-88bd-11eb-8327-06fb935c9903.png">
):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by dvaldivia** [comment]
@wangjunjack can you restart the Operator pod once and share the logs

**Comment by wangjunjack** [comment]
I0319 08:54:46.314441       1 main.go:72] Starting MinIO Operator

I0319 08:54:47.018108       1 main.go:139] caBundle on CRD updated

I0319 08:54:47.019008       1 main-controller.go:251] Setting up event handlers

I0319 08:54:47.019125       1 main-controller.go:635] Starting Tenant controller

I0319 08:54:47.019143       1 main-controller.go:638] Waiting for informer caches to sync

I0319 08:54:47.049571       1 main-controller.go:599] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)

I0319 08:54:47.096629       1 csr.go:217] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s

I0319 08:54:47.419474       1 main-controller.go:643] Starting workers

**Comment by wangjunjack** [comment]
@dvaldivia

**Comment by wangjunjack** [comment]
@dvaldivia when i Execute “kubectl minio init”,  that will be "operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)"

**Comment by wangjunjack** [comment]
### when i create Minio Tenant , it will be 
`E0319 09:00:25.324901       1 main-controller.go:721] error syncing 'minio-tenant-1/tenant1': secrets "operator-tls" not found

E0319 09:00:35.226868       1 main-controller.go:721] error syncing 'minio-tenant-1/tenant1': secrets "operator-tls" not found`
 
### the command is 
`kubectl minio tenant create tenant1 --namespace minio-tenant-1 --storage-class longhorn --servers 4 --volumes 4 --capacity 480Gi `

**Comment by dvaldivia** [comment]
@wangjunjack are you able to see any CSR in your cluster from operator? if the secret is missing it means the Certificate Signing Request never succeeded and the TLS certificate for operator didn't install

**Comment by wangjunjack** [comment]
@dvaldivia yes, i can see it.

**Comment by wangjunjack** [comment]
@dvaldivia 
<img width="1222" alt="csr" src="https://user-images.githubusercontent.com/30251247/111927102-72ec4800-8aea-11eb-99ee-b8c6ce84ee27.png">

**Comment by dvaldivia** [comment]
@wangjunjack and still the operator is not starting?

**Comment by wangjunjack** [comment]
@dvaldivia the operator is started, but the log of "operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)"

**Comment by dvaldivia** [comment]
@wangjunjack did you by any chance install operator to a custom namespace? What are the logs of the operator after restart? does it says soming like " polling for certificate" ?

**Comment by wangjunjack** [comment]
my step :
1. kubectl minio init
I0322 05:15:10.756044       1 main.go:72] Starting MinIO Operator
2021/3/22 下午1:15:11 I0322 05:15:11.396504       1 main.go:139] caBundle on CRD updated
2021/3/22 下午1:15:11 I0322 05:15:11.397358       1 main-controller.go:251] Setting up event handlers
2021/3/22 下午1:15:11 I0322 05:15:11.397465       1 main-controller.go:635] Starting Tenant controller
2021/3/22 下午1:15:11 I0322 05:15:11.397487       1 main-controller.go:638] Waiting for informer caches to sync
2021/3/22 下午1:15:11 I0322 05:15:11.426485       1 main-controller.go:599] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
2021/3/22 下午1:15:11 I0322 05:15:11.498451       1 main-controller.go:643] Starting workers
2021/3/22 下午1:15:11 I0322 05:15:11.505655       1 csr.go:217] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s

the namepsace is default "minio-operator".
<img width="1237" alt="minio" src="https://user-images.githubusercontent.com/30251247/111944033-b0180080-8b11-11eb-8367-26f48beb8148.png">

The log of "operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)", i don't know where is it, i check secrets there is not find any "operator-tls" secrets

**Comment by wangjunjack** [comment]
@dvaldivia 
the start log 
`[root@ds-n1 ~]# kubectl logs minio-operator-9c79bb668-tlqz4 -n minio-operator
I0322 05:15:10.756044       1 main.go:72] Starting MinIO Operator
I0322 05:15:11.396504       1 main.go:139] caBundle on CRD updated
I0322 05:15:11.397358       1 main-controller.go:251] Setting up event handlers
I0322 05:15:11.397465       1 main-controller.go:635] Starting Tenant controller
I0322 05:15:11.397487       1 main-controller.go:638] Waiting for informer caches to sync
I0322 05:15:11.426485       1 main-controller.go:599] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
I0322 05:15:11.498451       1 main-controller.go:643] Starting workers
I0322 05:15:11.505655       1 csr.go:217] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s`

**Comment by dvaldivia** [comment]
can you delete the CSR (certificate signging request) and reinstall operator this way

```
kubectl apply -k github.com/minio/operator/\?ref\=v4.0.3
```

**Comment by wangjunjack** [comment]
@dvaldivia  i have sloved problem. thank you

**Comment by dvaldivia** [comment]
@wangjunjack how did you solved it? was it the reinstall? or a missing cluster role permission?

**Comment by wangjunjack** [comment]
you need add some config for kubernetes when you init kubernetes cluster. the config is:
`services:
  kube-controller: # 这个选项必须添加，否则会报“Operator-tls not found”
    extra_args:
      cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
      cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"`

**Comment by wangjunjack** [comment]
@dvaldivia thank you for your help

**Comment by ctml91** [comment]
I am facing this same issue with this operator deployed via OLM on OpenShift, the proposed solution doesn't sound applicable.

**Comment by dvaldivia** [comment]
@ctml91 do you see any logs showing an error writing a secret to the tenant namespace? What version of the operator do you have?

**Comment by ctml91** [comment]
> @ctml91 do you see any logs showing an error writing a secret to the tenant namespace? What version of the operator do you have?

Thanks for the lightning quick reply. Updated original comment with specific error, we installed 4.0.9.

**Comment by dvaldivia** [comment]
@ctml91 that's a little bit old, can you try the 4.4.9re elase from oeprator hub? https://operatorhub.io/operator/minio-operator

**Comment by ctml91** [comment]
> @ctml91 that's a little bit old, can you try the 4.4.9re elase from oeprator hub? https://operatorhub.io/operator/minio-operator

This is the latest available from OpenShifts integrated operator hub. Is it possible to publish the updated versions to their repo?

https://github.com/redhat-openshift-ecosystem/certified-operators
