### ISSUE TITLE
Default instructions in the README.md don't work

### ISSUE THREAD

**Issue by harshavardhana** [minio/operator#541]
## Expected Behavior
```
kubectl minio tenant create tenant-1  --servers 7 --volumes 7 --capacity 7Ti --namespace minio-tenant-1 --storage-class direct-csi-min-io

Tenant 'tenant-1' created in 'minio-tenant-1' Namespace

  Username: admin 
  Password: ff99a14a-761b-461b-bbd4-7458469ffaeb 
  Note: Copy the credentials to a secure location. MinIO will not display these again.

+-------------+------------------+----------------+--------------+--------------+
| APPLICATION | SERVICE NAME     | NAMESPACE      | SERVICE TYPE | SERVICE PORT |
+-------------+------------------+----------------+--------------+--------------+
| MinIO       | minio            | minio-tenant-1 | ClusterIP    | 443          |
| Console     | tenant-1-console | minio-tenant-1 | ClusterIP    | 9443         |
+-------------+------------------+----------------+--------------+--------------+

```

## Current Behavior
```
kubectl minio tenant create tenant-1  --servers 7 --volumes 7 --capacity 7Ti --namespace minio-tenant-1 --storage-class direct-csi-min-io
Error: namespaces "minio-tenant-1" not found
```

## Possible Solution
Create the namespace properly.

## Steps to Reproduce (for bugs)
Just follow the readme.md

## Regression
Yes

## Your Environment
```
kubectl version info
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by harshavardhana** [comment]
Tenant delete also doesn't work thinks that tenant-1 name is namespace although `tenant-1-ss` has been created instead.

```
~ kubectl minio tenant delete tenant-1

This will delete the Tenant tenant-1 and ALL its data. Do you want to proceed?: y
This will delete the Tenant tenant-1 and ALL its data. Do you want to proceed?: y
Error: tenants.minio.min.io "tenant-1" not found
```

**Comment by harshavardhana** [comment]
I don't know what it is, but looks like fully broken

**Comment by dvaldivia** [comment]
we should probably validate the namespace exists before attempting to create the tenant, probably we are failing there right now

**Comment by nitisht** [comment]
> Tenant delete also doesn't work thinks that tenant-1 name is namespace although tenant-1-ss has been created instead.

How did you created the tenant?

**Comment by harshavardhana** [comment]
all using our README.md docs I just kept copy-pasting starting with first command it complained about `minio-tenant-1`

**Comment by nitisht** [comment]
> Create the namespace properly.

Plugin used to create the namespace, but since namespace creation is a privileged operation, we removed that capability and expect that namespace is created before using rest of the commands. It is mentioned here: https://github.com/minio/operator#prerequisites. May be we can make it prominent.

**Comment by harshavardhana** [comment]
> Plugin used to create the namespace, but since namespace creation is a privileged operation, we removed that capability and expect that namespace is created before using rest of the commands. It is mentioned here: https://github.com/minio/operator#prerequisites. May be we can make it prominent.

Yeah but its confusing @nitisht it doesn't guide the user error messages are bit cryptic .

**Comment by nitisht** [comment]
> If we can print kubectl create ns minio-tenant-1 is better

Sure, we can do that
