### ISSUE TITLE
Change of Tenant.spec.kes.replicas is not synced

### ISSUE THREAD

**Issue by haslersn** [minio/operator#543]
I think the title is self-explaining. Please ask if it is unclear.

## Your Environment

* Version used: `github.com/minio/operator?ref=v4.0.2`
* API version: `minio.min.io/v2`
* Environment: Kubernetes 1.19.2

**Comment by dvaldivia** [comment]
@Alevsk We don't compare the KES specification from from Tenant.spec.kes to what's deployed, we should add something around it

**Comment by Alevsk** [comment]
This issue will be addressed in the following PR https://github.com/minio/operator/pull/552
