### ISSUE TITLE
kubectl minio doesn't update CRD conversion endpoint if using custom namespace

### ISSUE THREAD

**Issue by dvaldivia** [minio/operator#546]
kubectl minio doesn't update CRD conversion endpoint if using custom namespace

**Comment by travisghansen** [comment]
Yes please! Just hit this myself.

**Comment by dvaldivia** [comment]
@travisghansen do you have the latest kubectl-minio plugin?

**Comment by travisghansen** [comment]
Actually, my problem may be slightly different. I'm using helm and the `crd` should probably have that in the template. I'm deploying with the hard-coded value and then *something* must be updating the crd behind the scenes to the correct value/namespace (a job, or whatever is generating the certs).

In my case, I'm using argocd to deploy so after the modification argo wants to put it back to the hard-coded value..

**Comment by dvaldivia** [comment]
@travisghansen when I opened this bug I was confused, but I saw that the code updates the CRD with the namespace what the operator detects for itself

**Comment by travisghansen** [comment]
Yeah, that's problematic for gitops tools though. They'll regenerate and detect a diff...is it possible to set the value to a templated value in the chart/crd definition?

**Comment by harshavardhana** [comment]
Is this still a problem? @dvaldivia

**Comment by agmimidi** [comment]
Seeing the same issue, using argocd to deploy minio operator as well.
Any one managed to go around this issue?
