### ISSUE TITLE
No option available of persistent volume claim in MinIOInstance in  Minio operator 

### ISSUE THREAD

**Issue by skadian2309** [minio/operator#549]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skadian2309** [comment]
When I create the minio Instance  then I am not able to find persistent volume claim option, here below is the configuration:

apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 4
  credsSecret:
    name: minio-creds-secret
  requestAutoCert: false

**Comment by harshavardhana** [comment]
https://github.com/minio/operator/blob/master/examples/tenant.yaml#L70 ? @skadian2309

**Comment by dvaldivia** [comment]
@skadian2309 thats quite an old CRD you should try the new examples for the latest version of the operator

**Comment by skadian2309** [comment]
Hi @dvaldivia, Actually I installed minio operator through operatorhub.io, there the version is 1.0.3 and I want to install in openshift, Is there any way to install the latest version in openshift.
