### ISSUE TITLE
Operator instructions return error

### ISSUE THREAD

**Issue by christianh814** [minio/operator#550]
Following this: https://github.com/minio/operator/tree/master/helm/minio-operator

Using the `tenant-lite.yaml` returns the following

```shell
$ kubectl apply -f https://github.com/minio/operator/blob/master/examples/tenant-lite.yaml
error: error parsing https://github.com/minio/operator/blob/master/examples/tenant-lite.yaml: error converting YAML to JSON: yaml: line 91: mapping values are not allowed in this context
```

## Expected Behavior
It should apply the manifest

## Current Behavior
Returns error

## Steps to Reproduce (for bugs)

1. Add the repo `helm repo add minio https://operator.min.io/`
2.  Update your definitions `helm repo update`
3. Install the operator `helm install --namespace minio-operator --create-namespace --generate-name minio/minio-operator`
4. Run `kubectl apply -f https://github.com/minio/operator/blob/master/examples/tenant-lite.yaml`

## Context
This also happens when I download the YAML

```shell
 kubectl apply -f tenant-lite.yaml 
error: error parsing tenant-lite.yaml: error converting YAML to JSON: yaml: line 91: mapping values are not allowed in this context
```

## Your Environment
Kube v1.20

**Comment by RafalSkolasinski** [comment]
Same on Kind 1.18:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:22:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-22T22:45:59Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by echarles** [comment]
Same error here on minikube.

**Comment by echarles** [comment]
When I download the files, it works

```
kubectl apply -f ./specs/tenant.yml 
secret/minio-creds-secret created
secret/console-secret created
tenant.minio.min.io/minio created
```

**Comment by marcelmaatkamp** [comment]
The url is wrong and points to the webpage, use the "display raw" link on github:

`$ kubectl apply -f  https://raw.githubusercontent.com/minio/operator/master/examples/tenant-lite.yaml`

**Comment by harshavardhana** [comment]
> ```shell
> $ kubectl apply -f https://github.com/minio/operator/blob/master/examples/tenant-lite.yaml
> ```

You should use RAW yaml mentioned here - https://github.com/minio/operator/tree/master/helm/minio-operator#creating-a-tenant - not sure where you are copying this from - the doc seems to point to RAW link properly. 

@christianh814 @echarles 
@RafalSkolasinski
