### ISSUE TITLE
kubectl apply --prune deletes minio-ss-0 statefulset

### ISSUE THREAD

**Issue by mattlqx** [minio/operator#554]
## Expected Behavior
`apply --prune` should not affect the running minio-ss pod/statefulset.

## Current Behavior
When an `apply --prune` is run with all of the cluster configuration (including other things besides the minio-operator and tenants), the minio-ss stateful set is pruned. The minio-console deployment/pod is unaffected as are other statefulsets created by other operators (e.g. elasticsearch). The minio-operator recreates the deleted statefulset, but this takes a few minutes to fully reconverge.

Relevant output for minio shows:
```
              customresourcedefinition.apiextensions.k8s.io/tenants.minio.min.io configured
              clusterrole.rbac.authorization.k8s.io/minio-operator-role unchanged
              clusterrolebinding.rbac.authorization.k8s.io/minio-operator-binding unchanged
              serviceaccount/minio-operator unchanged
              deployment.apps/minio-operator unchanged
              secret/minio-creds-secret unchanged
              secret/minio-console-secret unchanged
              tenant.minio.min.io/minio unchanged
              pod/minio-ss-0-0 pruned
              statefulset.apps/minio-ss-0 pruned
```

## Steps to Reproduce (for bugs)

1. Apply your CRD, operator and tenant configuration.
2. Wait for successful deployment of minio.
3. Run apply with `--prune`.
4. The apply operation will prune the minio-ss statefulset.

## Context
As part of our GitOps methodology, Kubernetes configs are committed to a repository and then during each configuration cycle (done on an 15m interval), the manifests are concatenated together and applied via `kubectl apply --prune --cascade`.

## Regression
I recently started to use the operator with version 4.0.0.

## Your Environment

* Version used (`minio-operator`): 4.0.3
* Environment name and version (e.g. kubernetes v1.17.2): 1.19.7
* Server type and version: EC2
* Operating System and version (`uname -a`): Ubuntu 20.04
* Link to your deployment file: https://gist.github.com/mattlqx/6db93d45cca8ef472f8eec5db1993e70

**Comment by mattlqx** [comment]
Other operators that use stateful sets don't get pruned. Seems like something specific to how the minio-operator is setting it up. 🤷🏻‍♂️

**Comment by nitisht** [comment]
can you help us with `kubectl get sts <sts-that-doesnt-get-prune> -o yaml`

**Comment by mattlqx** [comment]
Sure, https://gist.github.com/mattlqx/47a7272e3233da681b00c73da39d6fe5 is the Elasticsearch statefulset by their operator.

**Comment by nitisht** [comment]
And what is the command you're using to install the operator - I mean specific commands used in each step to repro the issue.
