### ISSUE TITLE
Support credential rotation?

### ISSUE THREAD

**Issue by arianvp** [minio/operator#564]
**Is your feature request related to a problem? Please describe.**

https://docs.min.io/docs/minio-server-configuration-guide.html  says that in order to change the `MINI_ACCESSS_KEY` and `MINIO_SECRET_KEY` after the fact, a roll-over needs to be done using the `MINIO_ACCESS_KEY_OLD` and `MINIO_SECRET_KEY_OLD` env vars.

I expected the operator to do this when you change the kubernetes secret storing the minio credentials but this doesn't seem implemented currently.

**Describe the solution you'd like**
minio should restart with these credentials set; and the old credentials set as `*_OLD` so that the credentials are rotated properly

**Describe alternatives you've considered**
none

**Additional context**

**Comment by nitisht** [comment]
you can simply add `*_OLD` creds in the `env` section of tenant.yaml file (under examples) and use the new creds in the `minio-creds-secret` secret. Operator takes up the relevant fields and rotates the creds.
