### ISSUE TITLE
minio v4.0.4 -- when we create new tenant , statefulset.apps/tenant1-log PV are getting created in default storage class, instead of creating in local-storage class, which I have created

### ISSUE THREAD

**Issue by mohantnr** [minio/operator#568]
minio v4.0.4 -- when we create new tenant , statefulset.apps/tenant1-log PV are getting created in default storage class, instead of creating in local-storage class, which I have created
## Steps to Reproduce (for bugs)

1. install minio using krew
2. create tenant using UI interface
3.  kubectl get statefulset.apps/tenant1-log -n minio-dev-ns -o yaml | grep storage-class. So no storage class option mentioned in statefulset.  Else it will create PV in default Storage class.
4.

## Your Environment

* Version used (`minio-operator`): v4.0.4 
* Environment name and version (e.g. kubernetes v1.17.2):v1.17.17
* Server type and version:SLES 12 SP5
* Operating System and version (`uname -a`):Linux 4.12.14-122.7-default #1 SMP Thu Dec 5 16:36:10 UTC 2019 (4cf61c0) x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:

**Comment by nitisht** [comment]
Can you please try with latest operator (`minio/operator:v4.0.6`) and latest console (`minio/console:v0.6.6`)

**Comment by mohantnr** [comment]
![image](https://user-images.githubusercontent.com/19817031/114354598-1251a780-9b8c-11eb-9179-bb2d5eece580.png)

**Comment by nitisht** [comment]
Please use CLI for now, we'll add PVC support soon.
