### ISSUE TITLE
use release namespace for helm chart crd conversion webhook namespace

### ISSUE THREAD

**Issue by travisghansen** [minio/operator#574]
## Expected Behavior
The `crd` renders with the appropriate namespace.

## Current Behavior
The `crd` renders with a hard-coded namespace. Then the controller or *something* updates it post install.

## Possible Solution
Not sure if it's possible to use `{{ .Release.Namespace }}` in `crds` or not.

## Steps to Reproduce (for bugs)

1. install using the chart in a non-default namespace
2. observer the crd get updated in the api server to point to the appropriate namespace

## Context
This is problematic for folks trying to use gitops (I'm using argocd) as a diff is detected and the resource is updated (or flagged as having a delta).

## Your Environment

* Version used (`minio-operator`): 4.0.5
* Environment name and version (e.g. kubernetes v1.17.2): k8s 1.19
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by travisghansen** [comment]
Similar to https://github.com/minio/operator/issues/546

**Comment by nitisht** [comment]
@travisghansen not really sure what is the problem here? ` CustomResourceDefinitions themselves are non-namespaced and are available to all namespaces.`  (ref: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/). So what namespace are you talking about?

**Comment by travisghansen** [comment]
@nitisht https://github.com/minio/operator/blob/master/helm/minio-operator/crds/minio.min.io_tenants.yaml#L14

**Comment by nitisht** [comment]
@travisghansen unfortunately CRDs are not templated yet in helm, so it is not possible to add dynamic values in the field that you're looking for. 

> These CRDs are not templated

Ref: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

**Comment by travisghansen** [comment]
Would it make sense to omit that block completely from the crd rather than having a place holder? And let whatever sets it set it behind the scenes? I'm not even certain how that would play out with argo specifically...I *think* it ignores fields that are patched/not present but could be mistaken..

**Comment by nitisht** [comment]
why is argo bothered about another CRD here? shouldn't it be just concerned about the MinIO tenants only?

**Comment by travisghansen** [comment]
I'm deploying the operator itself (many others besides just minio) with `argo-cd`. I have it manage the `crds` as well so I'm alerted when updates are available to them and can react appropriately.

**Comment by nitisht** [comment]
I am not sure what we can do here. May be trying removing the webhook conversion since you're sure you're not going to use tenant v1.

Note that we have not tested this, so looking forward to how it goes for you

**Comment by travisghansen** [comment]
I intend to use tenant, I'm just not deploying a tenant with this specific configuration. I only deploy the operator+crd and then tenants will be managed completely separately.

Do you know what component it is that generates the cert and sets the value after creation? And if I restart it will it re-update it?

**Comment by travisghansen** [comment]
Still looking for a solution/ideas here :)

**Comment by travisghansen** [comment]
Still valid.

**Comment by travisghansen** [comment]
I had to alter the chart :(
