### ISSUE TITLE
Addition of a tenant helm chart

### ISSUE THREAD

**Issue by morremeyer** [minio/operator#578]
**Is your feature request related to a problem? Please describe.**
With the current operator chart, one can already specify a list of tenants. This works fine **unless** the operator is not deployed yet as the CRDs will be missing then.

Therefore, one needs to change the values.yaml (or e.g. the helmfile.yaml when using helmfile), which makes it impossible to use the feature to boostrap the operator with a tenant.

**Describe the solution you'd like**
To enable automated workflows deploying the operator and tenants, I propose to add a tenant helm chart seperately to the operator helm chart (and optionally remove tenant creation from the operator helm chart to reduce maintenance needed).

This would put the need for dependency management on the user/the tool they are using. E.g. with plain helm: first deploy the operator, then the tenant. Or with helmfile, one can specify a dependency to that chart which ensures the correct order.

**Describe alternatives you've considered**
None. I am not aware of possible alternatives using just helm.

**Comment by mnp** [comment]
Another issue is it's not obvious how to override the default tenant that's in the minio-operator helm chart.  One might be tempted to try something like
```
helm install --set 'tenants[0].pools[0].storageClassName=my-storage' ....
```
but of course that doesn't work. So it seems you need to install the operator first with `--set tenants=null` and then template up `examples/tenant.yaml` yourself.  Is that the intention here?

**Comment by oliverbaehler** [comment]
Yes, this should be handled by a helm chart published by minio. Otherwise different charts start abstracting tenants within their charts since they have a dependency to just a minio instance but not the operator as whole. So to me this seems very important.
