### ISSUE TITLE
Error: Unrecognized scope when using external idp

### ISSUE THREAD

**Issue by ssharma2089** [minio/operator#579]
## Expected Behavior
When I am clicking on welcome screen, it should redirect to ldap login page and after successful login it should reditect to console dashboard page.

## Current Behavior
When I am click on welcome button, its stays on the same page. When I tried inspecting it, I could see "unrecognized scope : app_metadata and state_metadata". 
https://console.mwsdev.tri.int/oauth_callback?error=invalid_scope&error_description=Unrecognized+scope%28s%29+%5B%22app_metadata%22+%22user_metadata%22%5D&state=TDBJRURIMElWWEhaTFlITExCTjJPRE4yUDpsT2V0em95bUkzaDVQdUlRVnhlU09Bd1ZuZENkWnpjemNmcDJXaGdMd2wwPQ%3D%3D

## Steps to Reproduce (for bugs)

1. Installed minIO operator in minio-operator namespace by using this link "https://github.com/minio/operator#create-a-minio-instance"
2. Created certificate by using the link " https://github.com/minio/operator/blob/master/docs/tls.md#using-cert-manager ". I am using cert-manager for issuing certificate
3. Deployed minIO console in minio namespace by using the link "https://github.com/minio/operator/blob/master/examples/tenant-with-external-idp.yaml" Changed requestAutoCert from true to false and added externalCertSecret.
4. Login to console ui page

## Context
I am unable to login console dashboard page.

## Your Environment

* Version used (`minio-operator`): v4.0.5 and console: v0.6.3
* Environment name and version (e.g. kubernetes v1.17.2): v1.20.4+k3s1 (using k3s)
* Server type and version:
* Operating System and version (`uname -a`): Linux mwsdev01.tri.int 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Fri Oct 16 13:36:46 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:
[tenant.txt](https://github.com/minio/operator/files/6297592/tenant.txt)

**Comment by ZouhairBear** [comment]
@ssharma2089 Hello, to solve your problem you will need to add 2 scopes(client scopes)  : `app_metadata,user_metadata`  to your openId app

**Comment by ssharma2089** [comment]
@ZouhairBear I am using dexip/dex for authentication. These two scopes are not supported by dex.

**Comment by ZouhairBear** [comment]
@ssharma2089 I think that you should add an env variable to the tenant as shown in the below exmple : 
* `Kubectl edit tenant -n namespace` 
* add the following env var in the `spec.env` :  

```
spec:
  env:
  - name: MINIO_IDENTITY_OPENID_SCOPES
    value: openid,profile,email,app_metadata,user_metadata  
``` 
I have given an exemple for keycloack and I'm surtenly that it will work for you, you should adapt the values withe your scope values

**Comment by ssharma2089** [comment]
@ZouhairBear Getting same error after adding the above scope. I tried to add the scope in console env also but didn't work.

**Comment by ZouhairBear** [comment]
@ssharma2089 these variable are in the minio env var.
If you want to change the console,then you should edit the deployement and add this env var

**Comment by ssharma2089** [comment]
@ZouhairBear I tried it  but it didn't work

**Comment by ssharma2089** [comment]
Like this
spec:
      containers:
      - args:
        - server
        - --certs-dir=/tmp/certs
        env:
        - name: CONSOLE_MINIO_SERVER
          value: https://minio.minio.svc.cluster.local:443
        - name: CONSOLE_IDP_URL
          value: https://login.mwsdev.tri.int/dex
        - name: CONSOLE_IDP_CLIENT_ID
          value: d4795fb0ca5d24e02f4
        - name: CONSOLE_IDP_SECRET
          value: 17fce3a32b4ad7fab65bf3572ec8eb26713b7592
        - name: CONSOLE_IDP_SCOPES
          value: openid,profile,email,app_metadata,user_metadata
        - name: CONSOLE_IDP_CALLBACK
          value: https://console.mwsdev.tri.int/oauth_callback

**Comment by ZouhairBear** [comment]
@ssharma2089 the console does not have a variable for scope, it's the minio who has it.
I have an other question, why do you disable the minio deployment?

**Comment by ssharma2089** [comment]
@ZouhairBear I didn't disable it. I have deployed as per documentation by using below link
https://github.com/minio/operator/blob/master/examples/tenant-with-external-idp.yaml

And I want to use external idp from the console.

**Comment by ZouhairBear** [comment]
@ssharma2089 
I tryed the file and it didn't work for me,
The console does not work,
If you try to get your pods, you will not see the tenant( not the headless ) ...
I created created a minio-tenant using the command line in the officiel documentation of the operator.
I recommand you to create it using the cli or the user interface,then edit the tenant 
Using the command line 
`kubectl edit tenant -n namesapce` 
And add  the variables in the tenant

**Comment by ssharma2089** [comment]
@ZouhairBear I have tried with new  minio release v0.6.8 and scope part is resolved now. But I am facing below token issue

error.go:46: original error: invalid Login
debugging error: Post "https://login.mwsdev.tri.int/dex/token": x509: certificate signed by unknown authority

**Comment by kannappanr** [comment]
@ssharma2089 closing this issue as resolved. Please open a new one for the certificate issue
