### ISSUE TITLE
Add Ingress to helm chart

### ISSUE THREAD

**Issue by dnskr** [minio/operator#585]
**Is your feature request related to a problem? Please describe.**
There is no default way in the helm chart to set up Ingress for operator console, tenant consoles and tenant webservers.

**Describe the solution you'd like**
Add posibility to optionally set Ingress for operator console, tenant consoles and tenant web-servers.

**Additional context**
I can implement and add this feature to helm chart if it is ok.

**Comment by dvaldivia** [comment]
Every ingress controller is different so it's hard to offer a generic solution, some cloud providers don't even offer ingress and have you setup access via a load balancer service with annotations, so this is a feature where I think one size won't fit all

**Comment by dnskr** [comment]
You are right,  but we can add Ingress objects as optional and disabled by default.
For example like in [deprecated](https://github.com/minio/charts) helm chart([values.yaml](https://github.com/minio/charts/blob/master/minio/values.yaml#L178) and [ingress.yaml](https://github.com/minio/charts/blob/master/minio/templates/ingress.yaml)) and others helm charts.

**Comment by travisghansen** [comment]
This is promising. Can we make it possible to *not* expose both the console and the data `services` as type `LoadBalancer`?

I'd rather use ingresses (with the integration with external-dns, cert-manager, etc) while also not burning through LB IPs.

**Comment by sergeyshaykhullin** [comment]
Any plans to support ingress for regular minio ui per tenant?

**Comment by dnskr** [comment]
Still relevant issue for other minio users https://github.com/minio/operator/issues/742

**Comment by sergeyshaykhullin** [comment]
Not stale

**Comment by dnskr** [comment]
Not stale but might depend on the issue [#981](https://github.com/minio/operator/issues/981)

**Comment by dnskr** [comment]
I'm very happy to close the ticket finally!

**Comment by harshavardhana** [comment]
> I'm very happy to close the ticket finally! #595 #1153

Thank you for all the work on helm charts 🍰 @dnskr
