### ISSUE TITLE
Add the ability to optionally set affinity and tolerances for operator and console pods

### ISSUE THREAD

**Issue by zjheyvc** [minio/operator#586]
**Is your feature request related to a problem? Please describe.**
This configuration would be appropriate because in many contexts these pods must run on specific resources

**Describe the solution you'd like**
Add the ability to optionally set affinity and tolerances for operator and console pods.. In Helm charts:
- Update the [console-deployment](https://github.com/minio/operator/blob/master/helm/minio-operator/templates/console-deployment.yaml)
- Also [operator-deployment](https://github.com/minio/operator/blob/master/helm/minio-operator/templates/operator-deployment.yaml)
- So, in [values.yaml](https://github.com/minio/operator/blob/master/helm/minio-operator/values.yaml) we can put this parameters.

**Additional context**
I can contribute by adding this feature to the helm charts

**Comment by dvaldivia** [comment]
We do have support for pod affinity, the field is exposed on a per-pool basis

**Comment by zjheyvc** [comment]
> We do have support for pod affinity, the field is exposed on a per-pool basis

yes, but what about console pod or minio-operator pod

**Comment by dvaldivia** [comment]
Ahhh, I thought you meant on the tenant, those could be achieved with an overlay for the kustomize base, or do you mean also in helm and the kubectl plug-in?

**Comment by zjheyvc** [comment]
> Ahhh, I thought you meant on the tenant, those could be achieved with an overlay for the kustomize base, or do you mean also in helm and the kubectl plug-in?

Sorry for not detailing previously, I updated the issue but in a nutshell it should be change on [the minio-operator helm chart ](https://github.com/minio/operator/tree/master/helm/minio-operator)
