### ISSUE TITLE
Server image doesn't exists in release 4.0.7

### ISSUE THREAD

**Issue by lainosantos** [minio/operator#588]
Hello,

The command execution `kubectl minio init --namespace minio-operator --image minio/operator:v4.0.7` creates operator at version 4.0.7, then `kubectl minio tenant create minio-tenant-1 --servers 4 --volumes 4 --capacity 1Ti --storage-class default --namespace s3` creates a minio tenant, however the tenant is not starting because the minio server image minio/minio:RELEASE.2021-04-06T21-25-49Z not exists in public registry.

**Comment by harshavardhana** [comment]
This is fixed with 4.0.8
