### ISSUE TITLE
Console Deployment SecurityContext 

### ISSUE THREAD

**Issue by Fabyao** [minio/operator#590]
To comply with the Center for Internet Security (CIS), we have the following Pod Security Policy (PSP) in place:
``` 
runAsUser:
    rule: "MustRunAsNonRoot" # CIS - 5.2.6
````

Pods must provide a `securityContext` to meet the PSP above in order the run. The deployment file `helm/minio-operator/templates/console-deployment.yaml` does not have a `securityContext` and so is prevented from running in our cluster.

## Expected Behavior
Minio Console should successfully deploy in restricted PSP clusters

## Current Behavior
Minio Console deployment fails with "Must run as non root"

## Possible Solution
To overcome this I have manually patched the deployment file `helm/minio-operator/templates/console-deployment.yaml` to include the following:
``` 
securityContext:
  runAsUser: 1000
  runAsGroup: 2000
  runAsNonRoot: true
```

Assuming that 1000 and 2000 are correct values.

**Comment by bhargavamakwana** [comment]
> To comply with the Center for Internet Security (CIS), we have the following Pod Security Policy (PSP) in place:
> 
> ```
> runAsUser:
>     rule: "MustRunAsNonRoot" # CIS - 5.2.6
> ```
> 
> Pods must provide a `securityContext` to meet the PSP above in order the run. The deployment file `helm/minio-operator/templates/console-deployment.yaml` does not have a `securityContext` and so is prevented from running in our cluster.
> 
> ## Expected Behavior
> Minio Console should successfully deploy in restricted PSP clusters
> 
> ## Current Behavior
> Minio Console deployment fails with "Must run as non root"
> 
> ## Possible Solution
> To overcome this I have manually patched the deployment file `helm/minio-operator/templates/console-deployment.yaml` to include the following:
> 
> ```
> securityContext:
>   runAsUser: 1000
>   runAsGroup: 2000
>   runAsNonRoot: true
> ```
> 
> Assuming that 1000 and 2000 are correct values.

Running this patch on OpenShift 4 gives following error:

**pods "minio-operator-6768bb95c8-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000780000, 1000789999]]**
