### ISSUE TITLE
Chart 4.0.7-1 should have a version that is after 4.0.7

### ISSUE THREAD

**Issue by dsharp-pivotal** [minio/operator#594]
## Expected Behavior

`helm install --namespace minio-operator --create-namespace --generate-name minio/minio-operator` should install the latest version of the operator including the fix from #584

## Current Behavior

`helm install --namespace minio-operator --create-namespace --generate-name minio/minio-operator` installs version 4.0.7, which is broken.

## Possible Solution

Name the latest version 4.0.8 instead of 4.0.7-1

## Context

In semver, a `-` introduces a "pre-release" version segment. That is "4.0.7-1" is the "1st" release **before** (leading up to) "4.0.7". This is evidenced in `helm search` output (below). Furthermore, by making the latest release a development version, it is not visible by default without extra flags (`--devel` or `--version`).

```
→ helm search repo minio/minio-operator -l --devel
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
minio/minio-operator	4.0.7        	           	A Helm chart for MinIO Operator
minio/minio-operator	4.0.7-1      	           	A Helm chart for MinIO Operator
minio/minio-operator	4.0.6        	           	A Helm chart for MinIO Operator
minio/minio-operator	4.0.5        	           	A Helm chart for MinIO Operator
minio/minio-operator	4.0.3        	           	A Helm chart for MinIO Operator
minio/minio-operator	4.0.2        	           	A Helm chart for MinIO Operator
minio/minio-operator	4.0.1        	           	A Helm chart for MinIO Operator
minio/minio-operator	4.0.0        	           	A Helm chart for MinIO Operator
```

**Comment by harshavardhana** [comment]
It will be fixed - it was just a stop-gap solution for now - until one more PR gets merged to make 4.0.8
