### ISSUE TITLE
Please document how Helm tenant templating is supposed to be used

### ISSUE THREAD

**Issue by mnp** [minio/operator#601]
**Is your feature request related to a problem? Please describe.**
Granted there are several PR's in flight to cleanup tenants, but there is still confusion about how they are intended to be used as seen in #598, #593, etc. This is a time sink.

**Describe the solution you'd like**
Add instructions to `helm/minio-operator/README.md` saying how to:
1. How to `--set` or `--values` to modify the builtin tenant packaged with the operator. The yaml paths needed are not obvious to newcomers.
2. How to turn off the builtin tenant and use one of `examples/tenant*.yaml` instead. Note, while simply disabling default operator with `--set tentants=null` does work, customizing and applying one of `examples/tenant*yaml` will usually hit one of the known issues and fail. 

**Describe alternatives you've considered**
If #578 is implemented, and there is a second chart for tenants, or even a third wrapping tenants and operator, this whole situation would be simplified actually.

**Additional context**
Thank you for reading.

**Comment by mnp** [comment]
Yes, I am still interested in documentation.  Thank you.

**Comment by ravindk89** [comment]
@harshavardhana just to check, is the plan to use [pulls](https://github.com/minio/minio/pull/12509) to ultimately replace this helm feature? Or will we be keeping the helm-installed Operator route as well?

@mnp right now due to limited resources I can't provide a timeline on when I can address this request. I'm the only dedicated writing resource, and am fully allocated to ongoing migration work + the core MinIO Operator (non-Helm installations to various public cloud K8s infras).

**Comment by harshavardhana** [comment]
> @harshavardhana just to check, is the plan to use [pulls](https://github.com/minio/minio/pull/12509) to ultimately replace this helm feature? Or will we be keeping the helm-installed Operator route as well?
> 

@ravindk89 server side helm is meant for non operator installation, so both will be different.

> @mnp right now due to limited resources I can't provide a timeline on when I can address this request. I'm the only dedicated writing resource, and am fully allocated to ongoing migration work + the core MinIO Operator (non-Helm installations to various public cloud K8s infras).

**Comment by ravindk89** [comment]
For those following along, my last comment still stands - resources are limited right now, so putting a guide together on using the Operator Helm chart is not on the timeline.

The focus for the foreseeable future is the MinIO Operator and Operator Console for Tenant deployments, and guidance on "manual" installation/management via Kustomize as a secondary goal.
