### ISSUE TITLE
Minio operator can't create tenant stuck at TLS message, even when cert option turned on/off

### ISSUE THREAD

**Issue by idealtech-i3dlabs** [minio/operator#605]
Hi,
So I tried couple of times to create a tenant using the minIO operator console but to no avail.
My PVs are all good. Available, Bound to minio after I finalize and click create tenant

Statefulsets are all running:

dev          minio-tenant-1-pool-0-0            1/1     Running   0          25m
dev          minio-tenant-1-pool-0-1            1/1     Running   0          25m
dev          minio-tenant-1-pool-0-2            1/1     Running   0          25m
dev          minio-tenant-1-pool-0-3            1/1     Running   0          25m

Couple of issues I have:

1- Usability feature: I can't seem to add a flag at the console to create a tenant using my own SSL/TLS so I'm forced having to use the operator UI, which, well, doesn't work but even if it did, wouldn't solve "need to automate this at the command line" requirement. I would like to see something like --cert=<path_to_cert> --ca=<bla>.... it's not in your docs so unless it's a hidden flag, let me know?

2- Default: MinIO's internal auto-cert in the UI don't seem to work, stuck on "Waiting for TLS certificate" in the operator UI. I want to provide my own cert in any case but tried it just for kicks and it still failed. There is no proxy, direct access to the internet (which works). When I use Custom SSL option, I browse to the cert, ca, key, all good. But MinIO still gets stuck. 

In the Kubernetes logs I get:

2m48s       Warning   OwnerRefInvalidNamespace   certificatesigningrequest/minio-tenant-1-console-dev-csr   ownerRef [minio.min.io/v2/Tenant, namespace: , name: minio-tenant-1, uid: 514e2e7a-50b1-404b-85cc-8d7b57f4f00c] does not exist in namespace ""
3m48s       Warning   OwnerRefInvalidNamespace   certificatesigningrequest/minio-tenant-1-dev-csr           ownerRef [minio.min.io/v2/Tenant, namespace: , name: minio-tenant-1, uid: 514e2e7a-50b1-404b-85cc-8d7b57f4f00c] does not exist in namespace ""
5m51s       Warning   OwnerRefInvalidNamespace   certificatesigningrequest/operator-minio-operator-csr              ownerRef [minio.min.io/v2/Tenant, namespace: , name: minio-operator, uid: 0374ba8e-bbe2-4e70-8b82-ca9ef16c2e8f] does not exist in namespace ""

Not sure why the namespace string would be empty? Namespace "dev" exists and has other pods running in it.

3- Same problem with my own SSL certificates which work (wildcard) on any other service I'm deploying but MinIO. Exact same waning/error as above.

How do I troubleshoot this ?

## Expected Behavior
- MinIO creates the tenant
- MinIO without SSL option at a minimum doesn't complain about Certificates?

## Current Behavior
MinIO stuck at "Waiting for MinIO TLS certificate" indefinitely.

## Steps to Reproduce (for bugs)
1. Deploy operator, connect to operator UI, create tenant
2. Set everything off (no tls) or with custom cert, same error.

## Context
Trying to have a simple tenant working

## Your Environment

* Version used (`minio-operator`): latest, deployed using kubectl krew as mentioned in your docs
* Environment name and version (e.g. kubernetes v1.17.2): 1.20.2
* Server type and version: Ubuntu 20.04 LTS
* Operating System and version (`uname -a`): Linux k8sbox1 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

NOTE: I am using bare-metal 1.20.2 official from Kubernetes on Ubuntu 20.04. Cluster is working perfectly for everything else I throw at it but MinIO. I saw posts from people using Rancher and having these kinds of problems but I am not on Rancher. Just thought I'd point it out.

**Comment by dvaldivia** [comment]
can you share the tenant that was created with the UI? I see it working where if I disable TLS the `autocert: false` field is placed and TLS certs are not requested for the tenant

**Comment by idealtech-i3dlabs** [comment]
Thanks for your reply. Could you elaborate a bit? Not 100% sure what you need.

When I say "MinIO's internal auto-cert in the UI don't seem to work" I mean minIO's option to "auto" generate a certificate in the UI

But what you mention seems like a good thing to check.

Where can I see the autocert field, in which k8s component?
And how can I validate my own custom certificate is indeed in the config that was created by the UI?

Also, from
https://github.com/minio/operator/blob/master/docs/kes.md

The flag --console-secret and --secret don't seem to work when I try to create a tenant at the command line, I get:
Error: unknown flag: --secret
Error: unknown flag: --console-secret

**Comment by dvaldivia** [comment]
I need the Tenant CR, do `kubectl get tenants --all-namespaces` and then for the tenant in whatever namespace you put it do `kubectl -n NAMESPAce get tenant TENANTNAME -o yaml` and share that

I think all the conflicts you are having are with creating tenants via the krew plugin correct?

**Comment by idealtech-i3dlabs** [comment]
Correct. krew plugin
OK, I'll post the result in a couple of minutes

**Comment by idealtech-i3dlabs** [comment]
So, I wanted to recreate the operator and the tenant in the UI, just in case.
Same as before, SSL on, custom certs.
Now I get something different, not sure if the TLS error should come before or after, but I believe after:

```
$ kubectl get tenants --all-namespaces
NAMESPACE   NAME                      STATE                          AGE
dev     minio-tenant-1   Waiting for Pods to be ready   68s

```

and

```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: "2021-04-24T00:24:01Z"
  generation: 1
  name: minio-tenant-1
  namespace: dev
  resourceVersion: "357818"
  uid: 92ae7f87-362d-413c-b311-671e780baf09
scheduler:
  name: ""
spec:
  console:
    consoleSecret:
      name: minio-tenant-1-console-secret
    image: minio/console:v0.6.3
    replicas: 1
    resources:
      requests:
        memory: 64Mi
  credsSecret:
    name: minio-tenant-1-secret
  env:
  - name: MINIO_STORAGE_CLASS_STANDARD
    value: EC:5
  exposeServices:
    console: true
    minio: true
  externalCaCertSecret:
  - name: ca-certificate-0
    type: Opaque
  externalCertSecret:
  - name: minio-tenant-1-secret-instance-external-certificates-0
    type: kubernetes.io/tls
  image: minio/minio:RELEASE.2021-04-22T15-44-28Z
  imagePullSecret: {}
  log:
    audit:
      diskCapacityGB: 10
    image: minio/logsearch:v4.0.0
    resources: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio-tenant-1
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-0
          topologyKey: kubernetes.io/hostname
    name: pool-0
    resources:
      limits:
        memory: 32Gi
      requests:
        memory: 8Gi
    servers: 4
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "8246337208320"
        storageClassName: local-storage
      status: {}
    volumesPerServer: 8
  prometheus:
    diskCapacityGB: 5
    resources: {}
  requestAutoCert: false
status:
  availableReplicas: 4
  certificates:
    autoCertEnabled: false
  currentState: Waiting for Pods to be ready
  pools:
  - ssName: minio-tenant-1-pool-0
    state: PoolCreated
  revision: 0
  syncVersion: ""

```

I noticed the -hl- statefulset/pod is not there now, but the pods are running.

```
dev          minio-tenant-1-pool-0-0       1/1     Running   0          7m33s
dev          minio-tenant-1-pool-0-1       1/1     Running   0          7m33s
dev          minio-tenant-1-pool-0-2       1/1     Running   0          7m32s
dev          minio-tenant-1-pool-0-3       1/1     Running   0          7m31s
```
Also, PVs and PVCs are all bound.

I think that has to be fixed first. Why would it not recreate the headless pod?

In the logs I get :

```
API: SYSTEM()
Time: 00:36:14 UTC 04/24/2021
Error: lookup minio-tenant-1-pool-0-0.minio-tenant-1-hl.dev.svc.cluster.local on 10.96.0.10:53: no such host (*net.DNSError)
       host=minio-tenant-1-pool-0-0.minio-tenant-1-hl.dev.svc.cluster.local, elapsedTime=11 minutes elapsed
       5: cmd/endpoint.go:469:cmd.Endpoints.UpdateIsLocal()
       4: cmd/endpoint.go:653:cmd.CreateEndpoints()
       3: cmd/endpoint-ellipses.go:372:cmd.createServerEndpoints()
       2: cmd/server-main.go:143:cmd.serverHandleCmdArgs()
       1: cmd/server-main.go:426:cmd.serverMain()

```

Any ideas?
Did I not delete everything properly?

I flushed the namespace, the secrets that were dangling, the pvcs, and the pvs.
There was to my knowledge no trace of minio operator + tenant when I relaunched everything.

:confused:
