### ISSUE TITLE
(NAS) Gateway support

### ISSUE THREAD

**Issue by mdekoster** [minio/operator#606]
On private cloud environments the storage layer is often implemented on a NetApp systems. These systems have RAID configurations that provide data redundancy.

It would be useful to have the operator could create MinIO Tenant pools with NAS Gateway support.

**Comment by harshavardhana** [comment]
Gateway's won't be supported with operator this is a design decision for now.

**Comment by jrefi** [comment]
@harshavardhana  Can we get an explanation as to why this decision was made? 

My use case for this operator is to create dynamic S3 gateways for Azure Storage in our EKS environment. I can use the Helm chart as a workaround, but the operator would be cleaner and more convienent.
