### ISSUE TITLE
Default Buckets

### ISSUE THREAD

**Issue by oliverbaehler** [minio/operator#607]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to have default buckets when creating a minio tenant (at least there seems no option for me looking at the tenant values). Before it was possible to define `defaultBuckets` which then were created via Post Creation Job (https://github.com/minio/charts/blob/master/minio/templates/post-install-create-bucket-job.yaml#L1). Now there's the question if that's done via the oeprator handling the crd or by a seperate Miniop Tenant helm chart.

**Describe the solution you'd like**
That the Minio tenant CRD supports the field `defaultsBuckets` which allows to define defaultbuckets which are created automatically and no manual interaction is required.

**Describe alternatives you've considered**

**Additional context**

**Comment by zarelit** [comment]
Still important to me

**Comment by zamrokk** [comment]
same for me, please do
