### ISSUE TITLE
TenantSpec.credsSecret field is not optional

### ISSUE THREAD

**Issue by dnskr** [minio/operator#614]
Tenant spec [documents](https://github.com/minio/operator/blob/master/docs/crd.adoc#tenantspec) the credsSecret field as _Optional_ but actually it is not.
The MinIO Operator does not autogenerate the secret when credsSecret field is omitted.

## Expected Behavior
Following the documentation
`The MinIO Operator automatically generates the secret along with appropriate values for the access key and secret key if this field is omitted`

## Current Behavior
Tenant stuck with message
```bash
kubectl get tenant --all-namespaces
NAMESPACE   NAME    STATE                                                       AGE
data24      minio   please set credsSecret secret with credentials for Tenant   40m
```

## Steps to Reproduce (for bugs)
Create Tenant without **credsSecret** field

**Comment by ravindk89** [comment]
@dvaldivia did the functionality change at some point, or was this always true and we just missed it in review?

**Comment by dnskr** [comment]
I found one more problem with **credsSecret** field and it might be related to this issue.

If I delete Tenant and create it again but change `accesskey` and/or `secretkey` in the Secret than in the minio pod logs I see
```bash
Verifying if 3 buckets are consistent across drives...
API: SYSTEM()
Time: 11:41:36 UTC 04/30/2021
DeploymentID: 3556e1ae-fcd6-47c9-a680-7e93e34a4a06
Error: Unable to initialize config, some features may be missing Invalid credentials (*fmt.wrapError)
       3: cmd/server-main.go:385:cmd.initAllSubsystems()
       2: cmd/server-main.go:317:cmd.initServer()
       1: cmd/server-main.go:524:cmd.serverMain()
Status:         4 Online, 0 Offline. 
Endpoint: http://172.17.0.15:9000  http://127.0.0.1:9000 
Browser Access:
   http://172.17.0.15:9000  http://127.0.0.1:9000
Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
API: SYSTEM()
Time: 11:41:36 UTC 04/30/2021
DeploymentID: 3556e1ae-fcd6-47c9-a680-7e93e34a4a06
Error: Unable to migrate IAM users and policies to new format: sio: data is not authentic (*fmt.wrapError)
       1: cmd/iam.go:617:cmd.(*IAMSys).Init()
API: SYSTEM()
Time: 11:41:36 UTC 04/30/2021
DeploymentID: 3556e1ae-fcd6-47c9-a680-7e93e34a4a06
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
       1: cmd/iam.go:618:cmd.(*IAMSys).Init()
```

At the same time I don't have this issue if I change `CONSOLE_SECRET_KEY` for `users` secrets or `consoleSecret`

**Comment by dvaldivia** [comment]
@dnskr at the moment the root credentials cannot be rotated, I think we are making changes to the server to actually deprecate the root credentials, however at the moment they are needed, credsSecret was never optional

**Comment by ravindk89** [comment]
I'll push a fix to update the docs before end of day.

**Comment by harshavardhana** [comment]
> @dnskr at the moment the root credentials cannot be rotated, I think we are making changes to the server to actually deprecate the root credentials, however at the moment they are needed, credsSecret was never optional

Root credentials are not used with encryption anymore with v4.0.10 release of operator defaults to latest release of MinIO - which brings this change.  This would allow for root credentials to change anytime you feel like it.

Backend IAM/Config encryption now fully depends on KMS configuration i.e KES deployment. We can consider this issue closed.

**Comment by mehemken** [comment]
The format of that secret is not clear in the documentation. It took me about an hour to figure this out.

Ideally [this page](https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant.html#minio-k8s-deploy-minio-tenant) should make it clear that the secret should have [this format](https://github.com/minio/operator/blob/c3495a77092729708b5fef7ac6e95f9dfc6f57fb/helm/tenant/templates/tenant-configuration.yaml#L9-L17):

```
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER=admin
    export MINIO_ROOT_PASSWORD=password123
```

**Comment by ramondeklein** [comment]
The documentation refers to the example hat has the following [example secret](https://github.com/minio/operator/blob/master/examples/kustomization/base/tenant-config.yaml):
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio-tenant
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
```
