### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext

### ISSUE THREAD

**Issue by wdekou** [minio/operator#621]
When trying to install the operator from the helm chart, I get this error 
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext`

## Expected Behavior

Installation should be done

## Current Behavior

```
$ helm install -n minio-operator --create-namespace minio-operator minio/minio-operator 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext
```

## Steps to Reproduce (for bugs)

```
helm repo add minio https://operator.min.io/
helm install -n minio-operator --create-namespace minio-operator minio/minio-operator
```

## Your Environment

* Version used (`minio-operator`):
`version: 4.0.10`
* Environment name and version (e.g. kubernetes v1.17.2):
`1.18.15`
* Server type and version:
* Operating System and version (`uname -a`):
`Linux 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your deployment file:
I used all the default configuration in 
https://github.com/minio/operator/tree/master/helm/minio-operator

**Comment by an-tex** [comment]
fixed in 4.0.10 https://github.com/minio/operator/issues/617
