### ISSUE TITLE
Provisioning Console Deployment

### ISSUE THREAD

**Issue by rket022** [minio/operator#622]
When running the  kubectl get tenant  command the state stays in Provisioning Console Deployment

## Expected Behavior

I would expect some kind of running or success message

## Current Behavior

kubectl get tenant -n minio-operator
NAME     STATE                             AGE
minio1   Provisioning Console Deployment   3h8m

## Steps to Reproduce (for bugs)

1. Install via helm
2. After a few minutes the message will show up as Tenant State
3.
4.

## Context

I'm new to minio. I'm not sure the overall effects other than it doesn't seem like a good idea to leave a deployment in an unfinished state.

## Your Environment

* Version used (`minio-operator`): 4.0.9
* Environment name and version (e.g. kubernetes v1.17.2): eks 1.18
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file: I used most of the default values in values.yml with the helm repo other than changing the pass phrases and number of tenant servers to 2.

**Comment by rket022** [comment]
Update: Searching the operator pod logs(which was running and looked originally to be deployed successfully) it was complaining about the user cannot have the same name as the access key.  I made the access key names to be unique in the values.yml file. Once I did that everything was working as expected.

**Comment by dvaldivia** [comment]
@rket022 that's a good catch, I'll add an error to the tenant state if that happen
