### ISSUE TITLE
Accessing minio through Istio ingress gives "Client sent an HTTP request to an HTTPS server."

### ISSUE THREAD

**Issue by pavanfhw** [minio/operator#625]
I executed the 3 steps provided to deploy a minio tenant. Also I added an Istio Ingress for accessing the services via browser. Accessing the browser via the ingress host gives the response "Client sent an HTTP request to an HTTPS server.". I am accessing using a url like `https://my-minio.domain`. And the browser shows the valid certificate provided by cert-manager used in the Istio ingress.

If I access minio using a NodePort service it connects with an invalid certificate (I can access the UIs accepting the privacy risk). 

I am not sure what I have to do to successfully use minio with cert-manager + Istio. 

Do I need to run these?
```
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
update-ca-certificates
```
Where and how, if the certificate is in a container that does no provide the `update-ca-certificates` commad?

Or do I need to make minio ignore these self generated certificates and use my owns? 

The operator is showing:
```
TLS handshake error from 10.42.0.1:51514: remote error: tls: bad certificate
```
## Steps to Reproduce (for bugs)

1. Follow steps 1, 2 and 3 to deploy a minio tenant
2. Deploy an Istio Ingress to access the minio UI

## Your Environment

* Environment name and version (e.g. kubernetes v1.17.2):
kubernetes v1.20
* Server type and version:
kubernetes v1.20
* Operating System and version (`uname -a`):
Linux 5.4.0-70-generic

**Comment by harshavardhana** [comment]
Your istio configuration is wrong your server is on TLS and istio configuration talks over http 

Make sure to fix your setup properly.

**Comment by pavanfhw** [comment]
Ok, so how do I disable TLS on minio?
There is no tls flag for the command `kubectl minio tenant create`

**Comment by harshavardhana** [comment]
> There is no tls flag for the command `kubectl minio tenant create`

you need to turn-off autoCert get the output for your tenant definition as -o yaml and then `requestAutoCert: false`
