### ISSUE TITLE
Minio template has an error which makes it uninstallable

### ISSUE THREAD

**Issue by justinmchase** [minio/operator#628]
Installing the chart fails with this error:
> Error: template: minio-operator/templates/tenant.yaml:9:16: executing "minio-operator/templates/tenant.yaml" at <.metrics.enabled>: nil pointer evaluating interface {}.enabled

## Expected Behavior
Chart installs successfully

## Current Behavior
Fails with an error related to templating

## Possible Solution
unknown

## Steps to Reproduce (for bugs)
```sh
helm upgrade \
  --install \
  --namespace example \
  --set tenants[0].pools[0].storageClassName=minio \
  --set tenants[0].pools[0].volumesPerServer=1 \
  minio minio/minio-operator
```

## Context
Unable to install at all

## Regression
unknown

## Your Environment
* Added default repo `helm repo add minio https://operator.min.io/`

**Comment by harshavardhana** [comment]
Fixed in b584cae79be4e520943ec9086b3fbe1b992fc4b5
