### ISSUE TITLE
Can not create tenant with two pools

### ISSUE THREAD

**Issue by haslersn** [minio/operator#637]
I had the problem that I could not create a tenant with 2 pools. I needed to create it with 1 pool and then add the other pool.

Since I'm telling this from memory, I'm not sure what the error was, but I think it was stuck at "Provisioning MinIO Headless Service" when attempting to create a tenant with 2 pools.

## Expected Behavior

Creating a tenant with 2 pools should work fine. It's needed in case on already has data on the PVs.

## Possible Solution

I looked at the code and wondered whether maybe [this line](https://github.com/minio/operator/commit/88b1ec90e9f072e7e1eec4a8d135508b9f03ad67#diff-c615fc33486997d9702804daabe64e0b43bba13d022c538bfd9a924fb2c5c1c5R948) is not correct 

## Your Environment

* Version used: minio-operator v4.0.8
* Environment name and version: K8s v1.19.2
* Operating System and version (`uname -a`): `Linux kube01 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> I had the problem that I could not create a tenant with 2 pools. I needed to create it with 1 pool and then add the other pool.

You are not supposed to create two pools, to begin with - if you are planning to create 2 pools why not create one to start with and expand later? - This is by design.  

Pooling is only for expansion purposes and you shouldn't be doing expansion while deploying for the first time. This doesn't make sense. 

In fact, in another refactor we will be removing support for deploying 2 pools at the same time from the MinIO server command line as well - so the approach taken in operator is similar to the MinIO server's supported behavior.

**Comment by haslersn** [comment]
Use cases:

- I had a MinIO tenant where I needed to recreate the tenant because of issues with a MinIO operator update.
- Also, if somebody has a MinIO with 2 pools and wants to migrate it to MinIO operator, the tenant needs to be created with 2 pools, right?

**Comment by harshavardhana** [comment]
> If you don't allow creating a tenant with 2 pools, that goes against the concept of a declarative API. You take a declarative API (Kubernetes API extension) and make it imperative.

Declarative is like this 

- You deploy single pool - declarative gives you single pool
- You expand - declarative gives you the expansion


> * Also, if somebody has a MinIO with 2 pools and wants to migrate it to MinIO operator, the tenant needs to be created with 2 pools, right?

You can deploy a single-tenant first and then deploy a second pool for expansion. 

> * I had a MinIO tenant where I needed to recreate the tenant because of issues with a MinIO operator update.

That is still a single pool, if you started off with multiple pools then it is wrong setup to begin with.

**Comment by haslersn** [comment]
I did not start off with multiple pools. I started with a single pool and had to add another pool in the past. After that I had to recreate the tenant; see it as a desaster recovery.

What's the recommended way to recreate a tenant with 2 pools without data loss?

**Comment by harshavardhana** [comment]
> Since I'm telling this from memory, I'm not sure what the error was, but I think it was stuck at "Provisioning MinIO Headless Service" when attempting to create a tenant with 2 pools.

You can even today just turn-off of cert generation @haslersn - since autoCert is only enabled for freshSetup() not existing setups with expansion. That should work without issues IMO. 

Your existing setup operator has no idea since we need to create resources out of band becomes tricky for us.

**Comment by haslersn** [comment]
> You can even today just turn-off of cert generation @haslersn - since autoCert is only enabled for freshSetup() not existing setups with expansion. That should work without issues IMO.
>
> Your existing setup operator has no idea since we need to create resources out of band becomes tricky for us.

@harshavardhana Sorry, I don't understand what you mean. Anyway, I thought you said that creating a tenant with 2 pools is simply not supported. So why do you talk about AutoCerts now?

**Comment by harshavardhana** [comment]
> @harshavardhana Sorry, I don't understand what you mean. Anyway, I thought you said that creating a tenant with 2 pools is simply not supported. So why do you talk about AutoCerts now?

What I meant is you shouldn't do it,  the issue of headless service is because you enabled autoCerts: true - this is not allowed if you are not doing a fresh setup.

**Comment by haslersn** [comment]
Okay, understood.

I hope I made clear that there's a use case where one has to recreate a tenant with multiple pools. Namely for desaster recovery. Is there an answer to this—in my opinion important—question?

> What's the recommended way to recreate a tenant with 2 pools without data loss?

**Comment by harshavardhana** [comment]
> I hope I made clear that there's a use case where one has to recreate a tenant with multiple pools. Namely for desaster recovery. Is there an answer to this—in my opinion important—question?
> 
> >

If it's a disaster recovery isn't it a newer setup? what is the disaster here?

**Comment by haslersn** [comment]
The disaster is that the K8s cluster (or just the Tenant API object) is gone, but the MinIO data (e.g. on hard drives) is still there. In particular, I simply have a manually provisioned StorageClass for each pool and a manually provisioned PersistentVolume for each drive. These things (StorageClasses and PersistentVolumes) can be easily recreated after the K8s cluster is gone. But what about the tenant?

In my case I just created the tenant with a single pool (which uses the first StorageClass) and then did an expansion to a second pool (which uses the second StorageClass). However, I don't know whether this is the recommended way. In particular, I wonder:

- Am I allowed to start MinIO with a single pool, if that pool used to be just one pool of a multi-pool MinIO?
- What happens if, before I expand, somebody writes an object that exists on the second pool? Will it fail or will it be written to the first pool? If the latter: What happens when I expand, since now there's an object with the same name on both pools?

**Comment by harshavardhana** [comment]
> The disaster is that the K8s cluster (or just the Tenant API object) is gone, but the MinIO data (e.g. on hard drives) is still there. In particular, I simply have a manually provisioned StorageClass for each pool and a manually provisioned PersistentVolume for each drive. These things (StorageClasses and PersistentVolumes) can be easily recreated after the K8s cluster is gone. They are also declarative. But what about the tenant?
> 
> In my case I just created the tenant with a single pool (which uses the first StorageClass) and then did an expansion to a second pool (which uses the second StorageClass). However, I don't know whether this is the recommended way. In particular, I wonder:
> 
> * Am I allowed to start MinIO with a single pool, if the data of that pool used to be just one pool of a multi-pool MinIO?

Yes it is allowed

> * What happens if, before I expand, somebody writes an object that exists on the second pool? Will it fail or will it be written to the first pool? If the latter: What happens when I expand, since now there's an object with the same name on both pools?

Why would you allow that? turn-off ingress or any service that they might be using - until you expand.

If everything is there in PVC and you had multiple pools - you can provision with autoCert: false should work fine.

**Comment by haslersn** [comment]
Understood. I think it would still be more convenient and better for declarativeness (and GitOps, ArgoCD etc.) to allow creating the tenant with 2 pools. In my opinion, whether you Create or Update an API object, that should not make a difference, if the resulting state is the same.

Could anything I did lead to minio-operator removing the value of `MINIO_KES_IDENTITY` from the KES StatefulSet? This happened to me after a minio-operator update; but not sure if it's related or a completely different issue.

**Comment by harshavardhana** [comment]
> Could anything I did lead to minio-operator removing the value of `MINIO_KES_IDENTITY` from the KES StatefulSet? This happened to me after a minio-operator update; but not sure if it's related or a completely different issue.

This might be a separate issue lets open a new one and this shouldn't happen
