### ISSUE TITLE
The cert issued should include sans for minio.<ns> and minio.<ns>.svc

### ISSUE THREAD

**Issue by travisghansen** [minio/operator#638]
The cert issued should include sans for `minio.<ns>` and `minio.<ns>.svc` 

## Expected Behavior

I can connect to the service using the short-hand service names.

## Current Behavior

I can't connect to the service using the short-hand service names due to ssl failures.

**Comment by harshavardhana** [comment]
> I can't connect to the service using the short-hand service names due to ssl failures.

why do you want to connect with short-hand service names? are you deploying all your containers in the same namespace?

**Comment by travisghansen** [comment]
I deploy minio alongside all my other services and I reference everything using the short-hand `<svc>` generally speaking. Of more particular interest in this case is I'm doing some gitops based deployments and I can't guarantee every cluster will be using the `cluster.local` suffix so I want to always reference the service simply as `minio` no matter what cluster or ns I'm running in.

**Comment by harshavardhana** [comment]
> I deploy minio alongside all my other services and I reference everything using the short-hand `<svc>` generally speaking. Of more particular interest in this case is I'm doing some gitops based deployments and I can't guarantee every cluster will be using the `cluster.local` suffix so I want to always reference the service simply as `minio` no matter what cluster or ns I'm running in.

I can't understand how does short-hand gets routed if you have many MinIO instances in different namespaces? @travisghansen in different namespaces?

Short hand names are routable/pingable only within the same namespace.  Are you deploying all your workload in the same namespace for example `default`?

**Comment by travisghansen** [comment]
All services can be referenced via `<svc name>` if you're in the same namespace, or if you're in a different namespace via `<svc name>.<namespace>`. That is standard kube-dns behavior.

In my case, I deploy several instances of an app and deploy them in isolated namespaces (ie: dedicated ns per app instance). I deploy minio with each instance. I want the config to be the same across all instances as it relates to the the minio host...it should always be simply `minio`.

**Comment by harshavardhana** [comment]
> All services can be referenced via `<svc name>` if you're in the same namespace, or if you're in a different namespace via `<svc name>.<namespace>`. That is standard kube-dns behavior.

I already know that.  This is why I am wondering why do you need short-hands. 

> In my case, I deploy several instances of an app and deploy them in isolated namespaces (ie: dedicated ns per app instance). I deploy minio with each instance. I want the config to be the same across all instances as it relates to the the minio host...it should always be simply `minio`.

I don't think this use-case warrant changes on our end for TLS certs. This is a niche, our current design is to cater to many tenants in different namespaces.  It doesn't make sense to put `minio` as SAN for all certs. 

Will close this we may try to do it in the future if there is a real field requirement - for now just trust the cert and use it with a fully qualified name.

**Comment by travisghansen** [comment]
I wholly disagree with this decision. It's entirely unreasonable to not include SANs by which the service may be addressed. Not only that, the naming syntax that is most commonly used within clusters to reach cluster services within the same ns or from another ns.

**Comment by travisghansen** [comment]
Also make note, `minio.<ns>` is not currently available either which you have mentioned is the current design.

**Comment by harshavardhana** [comment]
> Also make note, `minio.<ns>` is not currently available either which you have mentioned is the current design.

That we should fix - I agree @travisghansen not `minio`

**Comment by travisghansen** [comment]
I disagree with the assessment of `minio` (if for no other reason than it's an addressable host), but `minio.<ns>` will be helpful :)

**Comment by travisghansen** [comment]
You should also add `<minio>.<ns>.svc`...this is generally how the k8s api is referenced by internal clients for example (`https://kubernetes.default.svc`).
