### ISSUE TITLE
MINIO_KES_IDENTITY removed after sync of KES StatefulSet, after operator update to 4.0.10

### ISSUE THREAD

**Issue by haslersn** [minio/operator#639]
After I updated the MinIO operator from v4.0.8 to v4.0.10, it synced my KES StatefulSet and removed the value of `MINIO_KES_IDENTITY`. The variable was still there, but without value:

```
        env:
        - name: MINIO_KES_IDENTITY
        image: minio/kes:v0.13.6
```

## Expected Behavior

The operator must not remove the value of `MINIO_KES_IDENTITY`.

## Current Behavior

The operator removed the value of `MINIO_KES_IDENTITY`.

## Workaround

As a workaround, after this issue appears, we can fix it by re-adding the value. First we need to find out the value we need to re-add. To do so, change KES' `server-config.yaml`:

```diff
-  audit: off
+  audit: on
```

Apply that change. Then

```
$ kubectl rollout restart statefulset/minio-kes
```

Now look at the KES logs in order to find out the identity of MinIO. It gets logged with HTTP 403 errors. The identity is a sha256 hash. If you found it, use

```
$ kubectl edit statefulset minio-kes
```

and add it below `name: MINIO_KES_IDENTITY` as `value: <sha256 hash>`.

## Steps to Reproduce (for bugs)

Not sure, since I it happend on an operator update and I don't want to downgrade it in order to test reproduction.

## Your Environment

* Version used: minio-operator v4.0.8 -> v4.0.10
* Environment name and version: K8s v1.19.2
* Operating System and version (`uname -a`): `Linux kube01 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`

**Comment by Alevsk** [comment]
@haslersn thanks for reporting this, we are working to have a fix very soon
