### ISSUE TITLE
missing minio-tenant-console-tls if console is enabled after initial install

### ISSUE THREAD

**Issue by travisghansen** [minio/operator#642]
I've deployed a tenant without `console` enabled, then subsequently updated the `tenant` to enable the `console`. After enabling the operator picks this up and tries to start the `console` pod(s) but waits indefinitely for the missing `minio-tenant-console-tls` secret.

## Expected Behavior

The csr/secret get created when needed.

## Current Behavior

The csr/secret seem to only be created when console is enabled at the time the tenant is created.

## Steps to Reproduce (for bugs)

1. Deploy a tenant without console enabled
2. Update the tenant to enable the console
3. Console pods will never start

## Regression
 No

## Your Environment

* Version used (`minio-operator`): 4.0.8
* Environment name and version (e.g. kubernetes v1.17.2): 1.19
* Server type and version: vmware
* Operating System and version (`uname -a`): centos7
* Link to your deployment file:

**Comment by dvaldivia** [comment]
oh, I can imagine why this is happening, we'll look into ti

**Comment by dvaldivia** [comment]
@travisghansen as a work around, you could create the CSR manually and then the TLS secret, that would solve the problem temporarely for you

**Comment by travisghansen** [comment]
It’s just a test env so I just deleted the tenant (left the pvcs) and redeployed. No big deal!

**Comment by travisghansen** [comment]
Not stale.

**Comment by travisghansen** [comment]
Not stale.
