### ISSUE TITLE
roll pods when relevant secrets are updated

### ISSUE THREAD

**Issue by travisghansen** [minio/operator#650]
**Is your feature request related to a problem? Please describe.**
When the keys for minio/console etc are updated in the relevant secret(s) I presume the pods need to be restarted to take effect (it seems to use env vars and env vars from secrets are not automatically updated when secret is updated).

**Describe the solution you'd like**
The relevant secrets are 'watched' and pods roll as appropriate.

**Describe alternatives you've considered**
I manually patch the ds/deployment with arbitrary annotations to make things restart.

**Additional context**
Generally helm charts implement a `checksum` on the generated configmap/secret to mitigate this issue. This of course is not possible as it relates to the operator, but perhaps the operator could generate the checksums on it's own and do similar logic. For example it could do a checksum/hash of the accesskey/secret and apply that to the ds(es).

**Comment by dvaldivia** [comment]
Could you elaborate on the sort of configurations you want to load this way? We actually support hit reload and then a rolling update would start a rolling update to minimize downtime but I'd like to know if there's a good reason for restarting often as large deployments (think 16 pods or more) take a long time to restart via rolling restart

**Comment by travisghansen** [comment]
I manage the creds and console secrets (and tenant, etc) as gitops assets. When I update them I'd prefer the appropriate pods roll.

I have very little experience with the operator so far so I could be missing something. Is the reload button something in the tenant console? That's good to know but still not ideal for gitops-y scenarios.

**Comment by harshavardhana** [comment]
Still needed
