### ISSUE TITLE
Tenant Creation Stuck in Provisioning Console Deployment

### ISSUE THREAD

**Issue by avinash-0-singh** [minio/operator#652]
## Expected Behavior

The operator should deploy a tenant with autocert encryption enabled.

## Current Behavior

Tenant Creation Stuck in Provisioning Console Deployment. Could see mino storage PODS running but the deployment is not successful due to the following error.

`Kubectl get pods

NAME                                    READY   STATUS    RESTARTS   AGE
minio-autocert-encryption-ss-0-0        1/1     Running   0          5m5s
minio-autocert-encryption-ss-0-1        1/1     Running   0          5m5s
minio-autocert-encryption-ss-0-2        1/1     Running   0          5m5s
minio-autocert-encryption-ss-0-3        1/1     Running   0          5m5s
`

###  Problem

`kubectl get tenant  

NAME                        STATE                             AGE
minio-autocert-encryption   Provisioning Console Deployment   11m`

### Error LOGS 

'
API: AddUser()
Time: 18:49:31 UTC 05/25/2021
DeploymentID: d475330f-36b5-403a-942f-bab957961ef0
RequestID: 168263D2659ADEE8
RemoteHost: 100.101.180.154
Host: minio-autocert-encryption-ss-0-0.minio-autocert-encryption-hl.default.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1
Error: crypto/aes: invalid key size 0 (aes.KeySizeError)
       5: cmd/api-errors.go:2031:cmd.toAPIErrorCode()
       4: cmd/admin-handlers.go:957:cmd.toAdminAPIErrCode()
       3: cmd/admin-handlers.go:1057:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-users.go:449:cmd.adminAPIHandlers.AddUser()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
       2: cmd/admin-handlers-users.go:449:cmd.adminAPIHandlers.AddUser()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

API: AddUser()
Time: 18:49:24 UTC 05/25/2021
DeploymentID: d475330f-36b5-403a-942f-bab957961ef0
RequestID: 168263D0BD5FF936
RemoteHost: 100.101.180.154
Host: minio-autocert-encryption-ss-0-0.minio-autocert-encryption-hl.default.svc.cluster.local:9000
UserAgent: MinIO (linux; amd64) madmin-go/0.0.1
Error: crypto/aes: invalid key size 0 (aes.KeySizeError)
       5: cmd/api-errors.go:2031:cmd.toAPIErrorCode()
       4: cmd/admin-handlers.go:957:cmd.toAdminAPIErrCode()
       3: cmd/admin-handlers.go:1057:cmd.toAdminAPIErr()
       2: cmd/admin-handlers-users.go:449:cmd.adminAPIHandlers.AddUser()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

API: AddUser()
Time: 18:49:31 UTC 05/25/2021
DeploymentID: d475330f-36b5-403a-942f-bab957961ef0
RequestID: 168263D2659ADEE8
RemoteHost: 100.101.180.154
'

## Steps to Reproduce (for bugs)

1. Deploy the minion operator using the helm package. Ref. here https://github.com/minio/operator/tree/master/helm-releases
2. Install vault from the official helm chart. Ref. https://github.com/hashicorp/vault-helm
3. vault write auth/approle/login role_id=db02de05-fa39-4855-059b-67221c5c2f63 secret_id=6a174c20-f6de-a53c-74d2-6018fcceff64 --token=<YOUR_ROOT_TOKEN_HERE>. | Ref. https://www.vaultproject.io/docs/auth/approle
4. Configure your vault configurations in the file https://github.com/minio/operator/blob/master/examples/tenant-with-autocert-encryption-enabled.yaml
5. Apply  the configuration by kubectl apply -f <YOUR_TENANT_FILE.yaml>

## Your Environment

* Version used (`minio-operator-4.0.11`):
* Environment name and version (e.g. Kubernetes v1.18.15):

**Comment by harshavardhana** [comment]
Please share your actual tenant.yaml @avinash-0-singh from what it looks like you are using a MinIO version that is incompatible with console version.

**Comment by dvaldivia** [comment]
can you also share the logs for the operator pod?

**Comment by avinash-0-singh** [comment]
@harshavardhana  here is the actual tenant.yaml https://gist.github.com/avinash-0-singh/c9aab517eb0c70935ff1a61b7d4bfae5

**Comment by avinash-0-singh** [comment]
> can you also share the logs for the operator pod?

I0525 18:37:58.648415       1 csr.go:73] Generating private key
I0525 18:37:58.648492       1 csr.go:86] Generating CSR with CN=*.minio-autocert-encryption-hl.default.svc.cluster.local
I0525 18:37:58.654985       1 csr.go:217] Start polling for certificate of csr/minio-autocert-encryption-default-csr, every 5s, timeout after 20m0s
I0525 18:38:03.657267       1 csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
E0525 18:38:03.659507       1 main-controller.go:750] error syncing 'default/minio-autocert-encryption': waiting for minio cert
E0525 18:38:26.392469       1 main-controller.go:791] Tenant 'tenant1-ns/tenant1' in work queue no longer exists
I0525 18:38:26.392490       1 main-controller.go:745] Successfully synced 'tenant1-ns/tenant1'
I0525 18:38:58.742116       1 main-controller.go:997] Deploying pool ss-0
I0525 18:38:58.773293       1 csr.go:73] Generating private key
I0525 18:38:58.773393       1 csr.go:86] Generating CSR with CN=*.minio-autocert-encryption-hl.default.svc.cluster.local
I0525 18:38:58.779513       1 csr.go:217] Start polling for certificate of csr/minio-autocert-encryption-client-csr, every 5s, timeout after 20m0s
I0525 18:39:03.782093       1 csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
E0525 18:39:03.784401       1 main-controller.go:750] error syncing 'default/minio-autocert-encryption': waiting for minio client cert
I0525 18:39:58.782220       1 main-controller.go:997] Deploying pool ss-0
I0525 18:39:58.797768       1 csr.go:217] Start polling for certificate of csr/minio-autocert-encryption-kes-default-csr, every 5s, timeout after 20m0s
I0525 18:40:03.799662       1 csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
E0525 18:40:03.801838       1 main-controller.go:750] error syncing 'default/minio-autocert-encryption': waiting for kes cert
I0525 18:40:58.800826       1 main-controller.go:997] Deploying pool ss-0
I0525 18:40:58.817796       1 csr.go:217] Start polling for certificate of csr/minio-autocert-encryption-console-default-csr, every 5s, timeout after 20m0s
I0525 18:41:03.820250       1 csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
E0525 18:41:03.822475       1 main-controller.go:750] error syncing 'default/minio-autocert-encryption': waiting for console cert
I0525 18:41:58.820117       1 main-controller.go:997] Deploying pool ss-0
E0525 18:41:59.880633       1 main-controller.go:750] error syncing 'default/minio-autocert-encryption': MinIO is not ready
E0525 18:43:18.885964       1 main-controller.go:750] error syncing 'default/minio-autocert-encryption': context deadline exceeded
E0525 18:44:18.893960       1 main-controller.go:750] error syncing 'default/minio-autocert-encryption': context deadline exceeded

CC @dvaldivia

**Comment by dvaldivia** [comment]
@avinash-0-singh seems the operator is trying to contact MinIO to create the console user and it's timing out, do you have any network policies that forbid inter-namespace communication? does your cluster use a custom cluster domain?

**Comment by avinash-0-singh** [comment]
No, there are no network policies and the cluster domain is cluster.local only. I tried to downgrade the minion operator to v4.0.10 and it eventually worked as expected.
