### ISSUE TITLE
Tenant's `spec.metadata` in docs but not in Types

### ISSUE THREAD

**Issue by justbert** [minio/operator#663]
There is reference to `spec.metadata` in the [Minio Operator Reference](https://github.com/minio/operator/blob/master/docs/operator-fields.md) documentation, however, I am unable to find this field in the golang structs nor in the CRD definition. Is this still a field in use?

## Expected Behavior
The documentation should reflect the structure of the API.

## Possible Solution
Update the docs or the type depending on expected functionality.

## Steps to Reproduce (for bugs)
N/A

## Regression
N/A

## Your Environment
N/A

**Comment by nitisht** [comment]
It is field in use, and can be used like this https://github.com/minio/operator/blob/master/examples/tenant.yaml#L32

**Comment by justbert** [comment]
@nitisht That's not `spec.metadata` just `metadata`, isn't it?

**Comment by justbert** [comment]
Also, in the Helm chart's Tenant manifest, there's no `spec.metadata`, however, there's a [note that describes](https://github.com/minio/operator/blob/73fddaa05e7aa40387a44efb30b0cd10758d2549/helm/minio-operator/templates/tenant.yaml#L8) that the `metadata.labels` will be passed to the stateful pods.

**Comment by dvaldivia** [comment]
@justbert we'll update the documentation

**Comment by dvaldivia** [comment]
PR https://github.com/minio/operator/pull/664

**Comment by justbert** [comment]
@dvaldivia Yeah! Totally aware of that! 

Usually it's under the `spec` that you can set the metadata for objects that are created from a CRD or a Manifest such as **Deployments** `spec.template.metadata` or **Tenants** `spec.console.annotations` or `spec.console.labels`.

**Comment by dvaldivia** [comment]
@justbert I believe we used to have a `spec.metadata` but we removed as we saw it was redundant with `metadata`, but we did allowed for a `spec.console.metadata` for console alone

**Comment by justbert** [comment]
@dvaldivia `metadata` is just carried to the underlying StatefulSet and the Pods in the pools?

**Comment by dvaldivia** [comment]
@justbert only `Annotations` and `Labels` 

https://github.com/minio/operator/blob/master/pkg/resources/statefulsets/minio-statefulset.go#L164

**Comment by justbert** [comment]
Perfect! Thanks for all of this! :D
