### ISSUE TITLE
Can't install Helm chart like in documentation

### ISSUE THREAD

**Issue by nlamirault** [minio/operator#671]
## Expected Behavior

According to the documentation (https://artifacthub.io/packages/helm/wener/minio-operator) : 

```
Install this chart using:

helm install --namespace minio-operator --create-namespace --generate-name minio/minio-operator
```

## Current Behavior

With template : 

```
❯ helm --debug template --namespace minio-operatoe --create-namespace --generate-name minio/minio-operator
Error: template: minio-operator/templates/tenant.yaml:26:29: executing "minio-operator/templates/tenant.yaml" at <.imagePullSecret.name>: nil pointer evaluating interface {}.name
helm.go:81: [debug] template: minio-operator/templates/tenant.yaml:26:29: executing "minio-operator/templates/tenant.yaml" at <.imagePullSecret.name>: nil pointer evaluating interface {}.name
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
This is fixed in b584cae79be4e520943ec9086b3fbe1b992fc4b5
