### ISSUE TITLE
Intermittent TLS handshake error

### ISSUE THREAD

**Issue by svmundada** [minio/operator#676]
We are observing intermittent TLS handshake error in minio workload pods.

```
2021/06/11 09:27:58 http: TLS handshake error from 172.18.120.88:39384: EOF
2021/06/11 09:32:36 http: TLS handshake error from 172.18.120.88:41398: EOF
2021/06/11 09:43:54 http: TLS handshake error from 172.18.120.88:45814: EOF
```
All of the four minio pods intermittently (or always not sure yet) show this. These IP addresses are from other minio pods i.e `minio-0` pod logs will have tls handshake error from `minio-{1,2,3}` and this happens with all minio pods.

Also, all drives look good.
```
$ mc admin info my
16 drives online, 0 drives offline
```
It doesn't seem to be certificate errors because:
```
$ curl -I https://minio-pool-0-1.minio-hl.minio.svc.cluster.local:9000/minio/health/live --key /tmp/certs/private.key --cert  /tmp/certs/public.crt  --cacert /tmp/certs/CAs/public.crt
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 16877E59AD1096C5
X-Xss-Protection: 1; mode=block
Date: Fri, 11 Jun 2021 09:51:54 GMT
```

## Steps to Reproduce (for bugs)
1. deploy examples/tenant.yaml
2. `requestAutoCert: true`

## Your Environment

* Version used (`minio-operator`): 4.1.1
* Environment name and version (e.g. kubernetes v1.17.2): 1.19.10
* Server type and version: RELEASE.2021-06-07T21-40-51Z
* Operating System and version (`uname -a`): x86_64 GNU/Linux
* Link to your deployment file: examples/tenant.yaml

**Comment by harshavardhana** [comment]
> 2021/06/11 09:27:58 http: TLS handshake error from 172.18.120.88:39384: EOF
> 2021/06/11 09:32:36 http: TLS handshake error from 172.18.120.88:41398: EOF
> 2021/06/11 09:43:54 http: TLS handshake error from 172.18.120.88:45814: EOF

These are normal sort of in any TLS based deployments that we have seen with Go net/http, what is your TLS handshake timeout? and what is the workload here?

**Comment by svmundada** [comment]
> what is your TLS handshake timeout? 

Sorry, I was not aware if TLS handshake timeout can be configured, so it's the default for us at the moment. Can you please point me docs for the same?

> what is the workload here?

Workloads are just minio pods created by minio-operator for the given `Tenant` resource.

**Comment by harshavardhana** [comment]
> > what is your TLS handshake timeout?
> 
> Sorry, I was not aware if TLS handshake timeout can be configured, so it's the default for us at the moment. Can you please point me docs for the same?
> 

I meant on the client side application.

> > what is the workload here?
> 
> Workloads are just minio pods created by minio-operator for the given `Tenant` resource.

So there is no application workload?

**Comment by harshavardhana** [comment]
If there is no application workload and it is just internode traffic then these EOFs are okay they are just generated for idle connection closures etc inside Go net/http library.  We do not have a lot of control over it and they are really harmless and not indicative of any errors AFAICS. 

Closing this issue, let me know if that is not the case.
