### ISSUE TITLE
Standalone mode with single pv

### ISSUE THREAD

**Issue by lromor** [minio/operator#677]
**Is your feature request related to a problem? Please describe.**
For local development, it would be nice to have the possibility to spawn a single PersistentVolume.
Currently, the minio operator does not allow to have less than 4 volumes.

**Describe the solution you'd like**
If in standalone mode, allow to have a single persistent volume.

**Describe alternatives you've considered**
Create another operator or vanilla manifest files to manage the minio installation in a more customized way that supports this feature.

**Comment by nitisht** [comment]
There are no plans to support single node single volume setups in operator, you can use the helm chart https://github.com/minio/charts for now. Soon we'll add a helm chart in MinIO repo that will support single node single volume setups as well.

**Comment by nitisht** [comment]
Closing this as we don't intend to implement this for now.
