### ISSUE TITLE
minio tenent - admin console logs out automatically. - when created via su-console of minio-operator

### ISSUE THREAD

**Issue by ajlawless** [minio/operator#685]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by ajlawless** [comment]
.

**Comment by harshavardhana** [comment]
Please share more detailed information, most of the information seems to left blank.

Closing issue as non-actionable ..
