### ISSUE TITLE
Error message when enabling Prometheus ServiceMonitor on an old tenant.

### ISSUE THREAD

**Issue by kien-truong** [minio/operator#689]
When we try to enable ServiceMonitor on an old tenant, the minio-operator logs is flood with the following message
    
    E0625 10:51:56.013498       1 main-controller.go:754] error syncing '<tenant_namespace>/<tenant_name>': servicemonitors.monitoring.coreos.com "<service_monitor_name>" already exists

## Expected Behavior
No error messages

## Steps to Reproduce (for bugs)

1. Create a new tenant without `prometheusOperator` spec
2. Modify the tenant to add `prometheusOperator` spec

## Your Environment

* Version used (`minio-operator`): 4.1.2
* Environment name and version (e.g. kubernetes v1.17.2): 1.19

**Comment by mymasse** [comment]
I have started a discussion about this a month ago and it didn't go far: https://github.com/minio/minio/discussions/12408#discussioncomment-851815

**Comment by mymasse** [comment]
Seems also that when you enable prometheus on an old tenant the k8s service label doesn't get updated and the service monitor will then find no matching service
