### ISSUE TITLE
ownerRef [minio.min.io/v2/Tenant, namespace: , name: minio-tenant-1, uid: f3d98805-1ce6-4190-9a4f-7440d38c65d6] does not exist in namespace ""

### ISSUE THREAD

**Issue by archenroot** [minio/operator#702]
So I have experimental libvirt based cluster master + 2 worker nodes, I installed as per description on main github page and I got into this:
![image](https://user-images.githubusercontent.com/553512/124294993-a06c7700-db58-11eb-9d68-14ac840ec1db.png)
![image](https://user-images.githubusercontent.com/553512/124296032-d1997700-db59-11eb-8eb3-5e444ac4bfde.png)

minio pods state:
```
minio-operator   console-5f978bcbdf-fd7cz                   1/1     Running   0          37m
minio-operator   minio-operator-ddd777544-vxzdf             1/1     Running   0          37m
minio-tenant-1   minio-tenant-1-ss-0-0                      0/1     Pending   0          35m
minio-tenant-1   minio-tenant-1-ss-0-1                      0/1     Pending   0          35m
```
So there is message on docs to run this:
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
update-ca-certificates

But where to run this command? on centos nodes there are no such folders, will try to recreate cluster with ubuntu based image, but these docs are not well detailed... 

## Current Behavior

I have master +x 2 node dev k8s cluster running on qemu locally
## Steps to Reproduce (for bugs)

1. kubectl krew update
2. kubectl krew install minio
3. kubectl create namespace minio-tenant-1
4. kubectl apply -f minio-storage-class.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: minio-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
5. kubectl minio init
6. kubectl minio tenant create minio-tenant-1 \
   --servers 2                             \
   --volumes 4                           \
   --capacity 1Gi                         \
   --namespace minio-tenant-1              \
   --storage-class minio-local-storage

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
It is explicitly mentioned that you need a minimum version of k8s 1.19 or higher.

Your k8s version is 1.17.2 it's not supported.
