### ISSUE TITLE
ownerRef [minio.min.io/v2/Tenant, namespace: , name: minio-tenant-1, uid: f3d98805-1ce6-4190-9a4f-7440d38c65d6] does not exist in namespace ""

### ISSUE THREAD

**Issue by archenroot** [minio/operator#703]
So I have experimental libvirt based cluster master + 2 worker nodes, I installed as per description on main github page and I got into this:
![image](https://user-images.githubusercontent.com/553512/124294993-a06c7700-db58-11eb-9d68-14ac840ec1db.png)
![image](https://user-images.githubusercontent.com/553512/124296032-d1997700-db59-11eb-8eb3-5e444ac4bfde.png)

minio pods state:
```
minio-operator   console-5f978bcbdf-fd7cz                   1/1     Running   0          37m
minio-operator   minio-operator-ddd777544-vxzdf             1/1     Running   0          37m
minio-tenant-1   minio-tenant-1-ss-0-0                      0/1     Pending   0          35m
minio-tenant-1   minio-tenant-1-ss-0-1                      0/1     Pending   0          35m
```
So there is message on docs to run this:
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates/
update-ca-certificates

But where to run this command? on centos nodes there are no such folders, will try to recreate cluster with ubuntu based image, but these docs are not well detailed...

Expected Behavior
Current Behavior
I have master +x 2 node dev k8s cluster running on qemu locally

Possible Solution
Steps to Reproduce (for bugs)
```
kubectl krew update
kubectl krew install minio
kubectl create namespace minio-tenant-1
kubectl apply -f minio-storage-class.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: minio-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
kubectl minio init
kubectl minio tenant create minio-tenant-1
--servers 2
--volumes 4
--capacity 1Gi
--namespace minio-tenant-1
--storage-class minio-local-storage
```
### Your Environment
Version used (minio-operator): installed via krew
Environment name and version (e.g. kubernetes v1.17.2): 
zangetsu@andromeda ~/proj/private/k8s-vagrant-multi-node $ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

```
Server type and version: master and 2 node workers are based on centos8
Operating System and version (uname -a): I run them via libvirt qemu on Gentoo system
Link to your deployment file: I used public repo and storage class is above and taken from minio standard docs.

**Comment by harshavardhana** [comment]
> Environment name and version (e.g. kubernetes v1.17.2):

We do not support Kubernetes version anything below v1.19

**Comment by archenroot** [comment]
The server version is: Server Version: version.Info{Major:"1", Minor:"21 as you can see in the kubectl version command output....

**Comment by harshavardhana** [comment]
> The server version is: Server Version: version.Info{Major:"1", Minor:"21 as you can see in the kubectl version command output....

Cool thanks for confirming, did you change namespace after deployment?

**Comment by archenroot** [comment]
what namespace do you mean? I executed new namespace creation for minio as provided in docs.

Otherwise here is my namespace list:
```
zangetsu@andromeda ~/proj/private/k8s-vagrant-multi-node $ kubectl get namespaces
NAME              STATUS   AGE
default           Active   31h
kube-node-lease   Active   31h
kube-public       Active   31h
kube-system       Active   31h
minio-operator    Active   30h
minio-tenant-1    Active   30h

```

**Comment by harshavardhana** [comment]
> what namespace do you mean? I executed new namespace creation for minio as provided in docs.
> 
> Otherwise here is my namespace list:
> 
> ```
> zangetsu@andromeda ~/proj/private/k8s-vagrant-multi-node $ kubectl get namespaces
> NAME              STATUS   AGE
> default           Active   31h
> kube-node-lease   Active   31h
> kube-public       Active   31h
> kube-system       Active   31h
> minio-operator    Active   30h
> minio-tenant-1    Active   30h
> ```

You should do `kubectl describe` to see why pod is in pending stage.. most probably you don't have a CSI and neither you have configured perhaps local PVs

**Comment by archenroot** [comment]
Ok, thats right, here is message form pod:
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  30h   default-scheduler  0/3 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 2 node(s) didn't find available persistent volumes to bind.

```

**Comment by archenroot** [comment]
Let me quickly create config....

**Comment by archenroot** [comment]
Ok, so I create storage class:


and 4 local pvs as its minimum for minio operator install each like this:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-{1/2/3/4}
  spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
          - node2
```
Now all nodes are up and running. Thx @harshavardhana for assistance. Next I go to integrate minio with keycloak.

Ladislav

**Comment by archenroot** [comment]
I also add some hints for locally running dev clusters that kubernetes dynamic provisioning provider won't work in local mode, this one work: https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/quickstart.md
