### ISSUE TITLE
Minio tenant won't delete after kubectl minio delete

### ISSUE THREAD

**Issue by archenroot** [minio/operator#705]
So I run kubectl minio command to clean up everything:
![image](https://user-images.githubusercontent.com/553512/124455682-24597580-dd8a-11eb-8981-075af150190b.png)
It removed completely minio-operator namespace components, but minio-tenant-1 remained, I use octant kubernetes console, so maybe the pods which are seen on screen doesn't exist anymore, but linked pvcs so the console somehow is tricky sometimes....
![image](https://user-images.githubusercontent.com/553512/124455802-4521cb00-dd8a-11eb-8dea-4670b28dbc5c.png)
but strange is I see following events 
![image](https://user-images.githubusercontent.com/553512/124455945-71d5e280-dd8a-11eb-9cdb-40e4eb266509.png)

So actually what remained there are pvcs:
![image](https://user-images.githubusercontent.com/553512/124456159-acd81600-dd8a-11eb-8d40-cde0f195c17a.png)

Note that I use openebs dynamic local pv provisioned with following configuration:
---
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: "#hostpath type will create a PV by \n# creating a sub-directory
      under the\n# BASEPATH provided below.\n- name: StorageType\n  value: \"hostpath\"\n#Specify
      the location (directory) where\n# where PV(volume) data will be saved. \n# A
      sub-directory with pv-name will be \n# created. When the volume is deleted,
      \n# the PV sub-directory will be deleted.\n#Default value is /var/openebs/local\n-
      name: BasePath\n  value: \"/var/openebs/local/\"\n"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"cas.openebs.io/config":"#hostpath type will create a PV by \n# creating a sub-directory under the\n# BASEPATH provided below.\n- name: StorageType\n  value: \"hostpath\"\n#Specify the location (directory) where\n# where PV(volume) data will be saved. \n# A sub-directory with pv-name will be \n# created. When the volume is deleted, \n# the PV sub-directory will be deleted.\n#Default value is /var/openebs/local\n- name: BasePath\n  value: \"/var/openebs/local/\"\n","openebs.io/cas-type":"local"},"name":"openebs-hostpath"},"provisioner":"openebs.io/local","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
    openebs.io/cas-type: local
  creationTimestamp: "2021-07-05T08:24:09Z"
  name: openebs-hostpath
  resourceVersion: "1848"
  uid: a277fc69-a07a-4519-ab25-3685fcc34438
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
If I just run additionally:
`kubectl delete ns minio-tenant-1`
it goes all clean

NOTE: I am preparing scripts for minio deploy/undeploy automation.

**Comment by nitisht** [comment]
IIUC only the PVs are not deleted. That is by design - because deleting PVs means losing data. We left it out of plugin's scope, plugin neither creates nor deletes PVs.

**Comment by archenroot** [comment]
aaahh. @nitisht - make sense :-)
