### ISSUE TITLE
Not able to create a Tenant for Minio Operator Version 4.0.9

### ISSUE THREAD

**Issue by esughos** [minio/operator#708]
Hi Team,

We are facing one issue during spawning of a tenant for **Minio Operator 4.0.9 version** and in this case tenant got created but there is no instance or, pod. We have followed the below process for creating a tenant  in Redhat Openshift 4.6 cluster,

1) Install the MinIO Operator
Install using kubectl krew
Run the following command to install the MinIO Operator and Plugin using krew:

   kubectl krew update
   kubectl krew install minio
Run the following command to initialize the Operator:

kubectl minio init

2) Create a New Tenant
The following kubectl minio command creates a MinIO Tenant with 4 nodes, 16 volumes, and a total capacity of 16Ti. This configuration requires at least 16 Persistent Volumes.

   kubectl minio tenant create minio-tenant-1 \
      --servers 4                             \
      --volumes 16                            \
      --capacity 16Ti                         \
      --namespace minio-tenant-1              \
      --storage-class local-storage        \
Once that is done we can see the below thing in the output,

Tenant 'minio-tenant-1' created in 'latest-minio' Namespace

  Username: admin 
  Password: XXXXXXXXX
  Note: Copy the credentials to a secure location. MinIO will not display these again.

+-------------+------------------------+--------------+--------------+--------------+
| APPLICATION | SERVICE NAME           | NAMESPACE    | SERVICE TYPE | SERVICE PORT |
+-------------+------------------------+--------------+--------------+--------------+
| MinIO       | minio                  | latest-minio | ClusterIP    | 443          |
| Console     | minio-tenant-1-console | latest-minio | ClusterIP    | 9443         |
+-------------+------------------------+--------------+--------------+--------------+

But in Minio operator pod logs we can see the below error,

I0706 07:37:55.514960       1 main-controller.go:620] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
I0706 07:37:55.518271       1 main-controller.go:623] Waiting for the operator certificates to be issued certificatesigningrequests.certificates.k8s.io "operator-auto-tls" is forbidden: User "system:serviceaccount:latest-minio:minio-operator" cannot get resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope
E0706 07:38:01.265775       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:latest-minio:minio-operator" cannot list resource "services" in API group "" at the cluster scope
E0706 07:38:02.809014       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2.Tenant: failed to list *v2.Tenant: tenants.minio.min.io is forbidden: User "system:serviceaccount:latest-minio:minio-operator" cannot list resource "tenants" in API group "minio.min.io" at the cluster scope
I0706 07:38:05.628841       1 main-controller.go:620] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
I0706 07:38:05.632861       1 main-controller.go:623] Waiting for the operator certificates to be issued certificatesigningrequests.certificates.k8s.io "operator-auto-tls" is forbidden: User "system:serviceaccount:latest-minio:minio-operator" cannot get resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope
E0706 07:38:12.181636       1 reflector.go:138] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:latest-minio:minio-operator" cannot list resource "statefulsets" in API group "apps" at the cluster scope
I0706 07:38:15.774508       1 main-controller.go:620] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)

Please suggest and help us to resolve the issue at earliest.

Cluster used:- Redhat Openshift 4.6
Minio Operator:- 4.0.9

**Comment by anuj812** [comment]
@ravindk89 Can you help on this. This is blocking us to move forward.

**Comment by ravindk89** [comment]
The operator TLS error typically indicates that something is preventing the MinIO Operator from generating the necessary TLS certificates.

You need to check that your OpenShift configuration can respond to Certificate Signing Requests. 

You can find more information [here](https://docs.min.io/minio/k8s/deployment/deploy-minio-operator.html#kubernetes-tls-certificate-api). It might be that you need to manually approve the CSRs, or that your OpenShift deployment is not configured to respond to CSRs. These are things you'll need to verify and resolve first.

**Comment by a-dawg** [comment]
I have the same issue with minio operator 4.1.2 and openshift 4.7 . 1 CSR is actually issued and after approval still having the same issue. 
````
operator-openshift-operators-csr   14h   kubernetes.io/kubelet-serving   system:serviceaccount:openshift-operators:minio-operator   Approved,Issued
````
````
I0813 07:55:01.198995       1 csr.go:170] Certificate successfully fetched, creating secret with Private key and Certificate
E0813 07:55:01.201966       1 operator.go:147] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
I0813 07:55:01.202026       1 main-controller.go:627] Waiting for the operator certificates to be issued secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
````

Moreover, In openshift modifying the kube-controller arguments does not seem to be officially supported: https://access.redhat.com/solutions/4306811

is there any workaround?

**Comment by ravindk89** [comment]
@a-dawg It might be worth exploring our updated tutorial on [installing via OperatorHub](https://docs.min.io/minio/k8s/openshift/deploy-minio-on-openshift.html). If the underlying OpenShift cluster simply cannot respond to CSRs though, I'm not sure what the best solution there is. I can only comment on MinIO and K8s in general, not the specific steps required for OpenShift. 

It might be best to also open a ticket with RedHat/OpenShift and see if someone on that end has some ideas.

**Comment by srisvk055** [comment]
> I have the same issue with minio operator 4.1.2 and openshift 4.7 . 1 CSR is actually issued and after approval still having the same issue.
> 
> ```
> operator-openshift-operators-csr   14h   kubernetes.io/kubelet-serving   system:serviceaccount:openshift-operators:minio-operator   Approved,Issued
> ```
> 
> ```
> I0813 07:55:01.198995       1 csr.go:170] Certificate successfully fetched, creating secret with Private key and Certificate
> E0813 07:55:01.201966       1 operator.go:147] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
> I0813 07:55:01.202026       1 main-controller.go:627] Waiting for the operator certificates to be issued secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
> ```
> 
> Moreover, In openshift modifying the kube-controller arguments does not seem to be officially supported: https://access.redhat.com/solutions/4306811
> 
> is there any workaround?


@a-dawg have you found any workaround for the same, almost in the same phase of minio deployment...

**Comment by dvaldivia** [comment]
@a-dawg @srisvk055 I'd recommend to install the upstream MinIO Operator `v4.4.15` instead of the `v4.0.9` shipped with OC
