### ISSUE TITLE
Add alternative domain option for MINIO_DOMAIN

### ISSUE THREAD

**Issue by fakemoon** [minio/operator#717]
**Is your feature request related to a problem? Please describe.**

Minio supports multiple domains separated by comma in MINIO_DOMAIN, but currently the operator is only using MinIOBucketBaseDomain which is 
```
fmt.Sprintf("%s.svc.%s", t.Namespace, GetClusterDomain())
```
that uses kubernetes cluster-domain configuration. Could we have a option in tenant where could add alternative domains to this list. It would be useful when exposing minio as a service with ingress and wanting to have virtual host style bucket access.

**Describe the solution you'd like**

Adding a object in tenant object that would append to MINIO_DOMAIN in the statefulset controlled by operator.

**Describe alternatives you've considered**

I have tried to set env in tenant object but it is clearly not overriding what the operator generated.

**Additional context**

None.

**Comment by harshavardhana** [comment]
CLUSTER_DOMAIN and MINIO_DOMAIN are totally different meant for different purposes.

You do not need to enable bucket DNS style in this manner you only need to enable 

`bucketDNS: true` in your tenant.yaml which will create bucket as clusterIP services automatically whenever a new bucket is created.

You can then externally write ingress rules to dynamically route to all the buckets without worrying about making any changes to MinIO configuration.

MINIO_DOMAIN makes sense for baremetal vanilla OS setups not with k8s
