### ISSUE TITLE
operator-tls issue in EKS regardless of the TLS config

### ISSUE THREAD

**Issue by sidvenu** [minio/operator#720]
I tried deploying MinIO in an AWS EKS stack in 3 different ways:
1. With autocert enabled.
1. With autocert disabled but externalCertSecret pointing to a cert that was created by cert-manager.
1. With autocert disabled and externalCertSecret not specified as well.

In all the above scenarios, I get the error:
`1 main-controller.go:754] error syncing 'default/minio-tenant-1': secrets "operator-tls" not found`

## Expected Behavior

Deployment should be successful.

## Current Behavior

Deployment is not successful.

## Steps to Reproduce (for bugs)

1. Setup an AWS EKS cluster.
1. Install MinIO using Helm.
1. Deploy a MinIO tenant on it with `autocert true`.
1. Note that it doesn't work (`operator-tls not found`).
1. Use cert-manager to install an issuer, and issue a certificate from it.
1. Deploy a MinIO tenant with `autocert false`, and `externalCertSecret` pointing to the certificate you just created.
1. Note that it doesn't work either.
1. Deploy a MinIO tenant with `autocert false` and not specifying `externalCertSecret`.
1. Note that it doesn't work either.

## Context

Can't deploy MinIO to production.

## Your Environment

* Environment name and version (e.g. kubernetes v1.17.2): AWS EKS (kube version `1.20`, platform version `eks.1`)
* Link to your deployment file: https://gist.github.com/sidvenu/7486abe19a615470b308758b2f466380 (this describes scenario 2)

**Comment by ArashAmiri** [comment]
We have the same issue.
We also switched of the autocert and get the same error ("operator-tls" not found)

**Comment by nitisht** [comment]
https://github.com/minio/operator/pull/713 allows you to disable Operator TLS. Can you please try this and let us know how it goes?

**Comment by sidvenu** [comment]
@nitisht sorry, I'm new to Kubernetes. Any way of using Helm to test out the PR version of MinIO?

**Comment by nitisht** [comment]
Please use this image for Operator `nitishtiwari/operator:operator-tls-disable` and set the env var `OPERATOR_TLS` to `false` for Operator. That is all required to test this.

**Comment by nhha1602** [comment]
Thank you,

But when I edit deployment minio-operator and set OPERATOR_TLS to false and get invalid deployment.

Please help

**Comment by nitisht** [comment]
> It seems that we dont have OPERATOR_TLS env
How are you deploying this?

**Comment by nhha1602** [comment]
I run: kubectl edit deployment minio-operator -n minio-operator

then i add lines:
- name: OPERATOR_TLS
   value: false

I do as same of: CLUSTER_DOMAIN env syntax.

**Comment by nitisht** [comment]
can you try with `false` in quotes 

```yaml
name: OPERATOR_TLS
value: "false"
```

**Comment by nhha1602** [comment]
Thank you. It worked :)

**Comment by nitisht** [comment]
> Thank you. It worked :)

Do you have tenant's running as expected now?

**Comment by nhha1602** [comment]
Yep, minio is up. But i to issue with minio-dev-log-search-api. it is not up. it requests connect to a postgresql DB.
it is external postgressql ? and it is not deployed with minio-operator ?

**Comment by nitisht** [comment]
Operator creates the Postgres as a part of tenant creation, if logsearch is enabled in tenant spec

**Comment by nitisht** [comment]
fixed by #713

**Comment by sidvenu** [comment]
Sorry if this is unrelated, any idea when this will be packaged into a release?
