### ISSUE TITLE
minio console does not deploy for tenant

### ISSUE THREAD

**Issue by mjschmidt** [minio/operator#722]
Deploying the minio minimal tenant tiny (link below) does not deploy the console
https://github.com/minio/operator/blob/master/examples/tenant-tiny.yaml

## Expected Behavior

The console should deploy so that I can create services accounts etc. Or there should be a way for me to manually deploy the console with correct configs post deployment

## Current Behavior

Tenant tiny deploys, but the console does not

## Possible Solution

I'm not sure this seems like a bug? I am testing on a minicube right now, but even in our prod env we have 3 workers, which means we will need to deploy in stand alone mode unless we could deploy 4 servers without each server being required to deploy to its own node.

## Steps to Reproduce (for bugs)

kubectl create -f tenant-tiny.yaml

## Your Environment

* Version used (`minio-operator`): latest minio operator
* Environment name and version (e.g. kubernetes v1.17.2): k8s 1.20.9 rancher flavor
* Server type and version: N/A
* Operating System and version (`uname -a`): N/A
* Link to your deployment file: offline deployment, but the tenant-tiny.yaml would suffice for testing.

**Comment by mjschmidt** [comment]
The only other noteworthy thing I can think of is that I am connected to a keycloak.

**Comment by dvaldivia** [comment]
@mjschmidt do you see the console deployment? can you share your tenant as it's applied to the API?
```
kubectl -n NAMESPACE get tenant TENANTNAME -o yaml
```

**Comment by dvaldivia** [comment]
@mjschmidt also if there's any message on the Tenant State or logs on the Operator Pod that'd be useful, the Console is only deployed after MinIO is deployed and comes online

**Comment by mjschmidt** [comment]
Sorry I am in offline so I have to manually transcribe but the status of my deployment is:
```
status:
  availableReplicas: 1
  certificates:
    autoCertEnabled: false
    currentState: Waiting for Pods to be Ready
    pools:
    - ssName: minio-ss-0
      state: PoolInitialized
    revision: 0
    syncVersion: ""
```

So it looks like its waiting for pods to be ready but kubectl get pods shows the one pod is in fact ready. I am wondering if it is because minio normally expects a minimum of 4 pods, but the tenant tiny only has one?

**Comment by mjschmidt** [comment]
The minio operator is in fact showing that the minio tenant is not deployed correctly in it's eyes:
```
...
E0714 <time here> 1 main-controller.go:742] error syncing 'minio/minio' : MinIO is not ready
...
```

**Comment by mjschmidt** [comment]
@dvaldivia would it be helpful if I manually transcribed a yaml for you to duplicate or were you able to quickly try the tiny-tenant yaml from the examples section?

Anything else I can look at?

**Comment by Vineeth-varma** [comment]
I am also facing the same issue right now, while deployoing with normal Yaml file it is fine but when I am deploying it with helm the console deployment is not getting created.

**Comment by mjschmidt** [comment]
@Vineeth-varma without seeing more details, I can tell you that this is most likely not the same issue as the minio team does not currently support a helm chart that I am aware of. They have moved to the operator model.
