### ISSUE TITLE
Add minimal setup with only one server and no need for persistent at all

### ISSUE THREAD

**Issue by Tim-Schwalbe** [minio/operator#730]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nitisht** [comment]
Please refer https://github.com/minio/operator/blob/master/examples/tenant-tiny.yaml

**Comment by Tim-Schwalbe** [comment]
Hi, I tried this but there is but you need at least 4 volumes or maybe I miss understand it.

**Comment by nitisht** [comment]
Yes, Operator only supports erasure coded MinIO tenants which require at least 4 volumes.

**Comment by Tim-Schwalbe** [comment]
okay thanks, would be nice if you can provide a smaller version. Thank you for you very quick support.

**Comment by nitisht** [comment]
Unfortunately this is the smallest Operator can go at the moment. Feel free to use MinIO Helm chart https://github.com/minio/minio/pull/12509 for Gateway / Single Node Single Drive style dummy deployments.
