### ISSUE TITLE
Log persistence for Minio

### ISSUE THREAD

**Issue by Vineeth-varma** [minio/operator#731]
Environment: 

- I am using Kubernetes 1.20
- I have deployed minio Operator 
- I have also deployed minio tenant, minio tenant console with the help of operator.
- For minio tenant i was able to see the pod logs as they are printing to standard output.

Expected behaviour:

- I want those logs to get persisted inside pod to one specific folder.
- How can I do this.

**Comment by nitisht** [comment]
MinIO doesn't support writing logs to a folder. hence this is out of scope for operator
