### ISSUE TITLE
Minio Client (mc)  for Minio Operator

### ISSUE THREAD

**Issue by Vineeth-varma** [minio/operator#736]
I am not sure how to deploy minio client for Minio Operator .
Can anyone guide me to install mc for minio operator setup.

**Comment by kannappanr** [comment]
`mc` can simply be a binary that you can use to talk to MinIO. PTAL https://docs.min.io/docs/minio-client-quickstart-guide.html

Feel free to reach out to us with further questions, closing this issue

**Comment by Vineeth-varma** [comment]
I am still facing some issues while trying to talk to minio using minio client

**Comment by dvaldivia** [comment]
hi @Vineeth-varma you need to expose your tenants so they are reachable outside your kubernetes cluster, if you are not sure how to do that, you could temporarely access them using `kubectl port-forward` for example
```
kubectl -n <TENANT_NAMESPACE> port-foward svc/minio 9000
```
now you can use `mc` on your local machine at `https://localhost:9000` make sure to do `--insecure` if your tenant uses TLS
