### ISSUE TITLE
Helm chart tenant secret vs tenant console secret - When to use which?

### ISSUE THREAD

**Issue by alexander-bruun** [minio/operator#740]
When I use the following values.yaml file: https://gist.github.com/alexander-bruun/3598014e81efdca6df472d081964a70b (modified from the default helm chart), and port forward the tenant-console service to access it locally I would like to be able to login with my "tenant-console-secret" resource as defined in the values file, but this doesn't work:
![image](https://user-images.githubusercontent.com/87643857/126892208-97b973f2-eb1a-4fd8-a2b9-38ec5ae41859.png)
But when I use the accessKey & secretKey from "tenant-secret" resource it lets me login...
![image](https://user-images.githubusercontent.com/87643857/126892540-26c29136-bb09-4ec5-b7e2-4810dd8eab69.png)

I would assume since I portforwarded the "tenant-console-xyz" service, it would make me use the tenant console secrets defined under "tenant-console-secret" in my helm chart values...

And when I inspect the tenant console pod's mount, "87654321" secret which works to login is not even there, but "12345678" is there which doesn't work.
![image](https://user-images.githubusercontent.com/87643857/126892369-770aa872-a30c-45dd-83a9-665b11dcb7c0.png)

## Expected Behavior

Use the "tenant-console-secret" secret to login to the "tenant-console" service.

## Current Behavior

I have to use the "tenant-secret" secret to login to the "tenant-console" service, even though this secret is not even mounted to the pod.

## Steps to Reproduce (for bugs)

1. Use the following command: helm install minio --namespace minio-operator --create-namespace minio/minio-operator --values https://gist.githubusercontent.com/alexander-bruun/3598014e81efdca6df472d081964a70b/raw/5b00298816de45252b9ee95677f6a88bd3b87bea/values.yaml
2. This should give you a tenant-console pod that you have to use "87654321" secret instead of the "12345678" secret defined under the tenant-console configuration.

## Context

In my mind it's making the difinition of "tentant-console-secret" secret obsolete since it's making me use the secret defined previously in the helm chart for logging into the tenant console ui.

## Regression
 No

## Your Environment

* Version used (`minio-operator`): latest helm chart
* Environment name and version (e.g. kubernetes v1.17.2): v1.20.6+k3s1
* Server type and version: K3d on WSL2
* Operating System and version (`uname -a`): Linux DESKTOP-K1PNVDO 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file: https://gist.github.com/alexander-bruun/3598014e81efdca6df472d081964a70b

**Comment by limonkufu** [comment]
I am also seeing this issue. In the env it seems it's using the console-secrets instead of tenant-secrets but when you login it only accepts tenant-secrets. I was under the impression that tenant-secrets are just for accessing the actual tenant and the console-secrets are for accessing the console only.

**Comment by sergeyshaykhullin** [comment]
Any updates?

**Comment by alexander-bruun** [comment]
I abandoned minio long ago due to issues like this, closing issue.

**Comment by sergeyshaykhullin** [comment]
@alexander-bruun What are you using today?
