### ISSUE TITLE
Minio Operator v4.1.3 : no matches for kind "Operator" in version "minio.min.io/v2"

### ISSUE THREAD

**Issue by bahetiamit** [minio/operator#746]
## Expected Behavior
Operator should be able to create operator-tls secret and tenant.

## Current Behavior
I0714 09:41:42.127242 1 csr.go:170] Certificate successfully fetched, creating secret with Private key and Certificate
E0714 09:41:42.205461 1 operator.go:147] Unexpected error during the creation of the secret/operator-tls: secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"
I0714 09:41:42.205504 1 main-controller.go:627] Waiting for the operator certificates to be issued secrets "operator-tls" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion minio.min.io/v2 Kind Operator: no matches for kind "Operator" in version "minio.min.io/v2"

## Steps to Reproduce (for bugs)

1. oc minio init
2. Check operator pod logs
3. Create tenant

## Context

I tried with image - nitishtiwari/operator:operator-tls-disable suggested in https://github.com/minio/operator/issues/720 but that seems to be specific to amd64. I am using power system (ppc64le).

Then I built the image locally on power system using commit# 4843d28 and modified the operator deployment to use locally built image along with setting up the environment variable as below

```
name: OPERATOR_TLS
value: "false"
```

I still see the same error in the logs.

**Comment by bahetiamit** [comment]
Am I missing any step here? Even with current master I am still seeing this issue

**Comment by dvaldivia** [comment]
You cannot upgrade by simply changing the container image, you need to apply the tenant CRD since now we have two versions. Reinstall the operator and the problem will be fixed
