### ISSUE TITLE
When trying to install gives the following error

### ISSUE THREAD

**Issue by joaoguariglia** [minio/operator#761]
![image](https://user-images.githubusercontent.com/23190903/129253778-451dd4b6-6ca0-4762-9608-3fe60ea256dd.png)

**Comment by harshavardhana** [comment]
Excellent issue reporting!

**Comment by joaoguariglia** [comment]
ok i'll try to explain i have kubernetes installed from scratch on ubuntu 20.04.
I tried to follow the installation step-by-step to the letter, but I couldn't go up to the WEB management console, so I redid the procedure and got this error:

$ helm repo add minio https://operator.min.io/
$ helm install --namespace minio-operator --create-namespace --generate-name minio/minio-operator
----
$ kubectl get secret $(kubectl get serviceaccount console-sa --minio-operator namespace -o jsonpath="{.secrets[0].name}") --minio-operator namespace -o jsonpath="{.data.token }" | base64 --decode
$ kubectl --namespace minio-operator port-forward svc/console 9090:9090
---
