### ISSUE TITLE
Default Bucket Creation / sideCar

### ISSUE THREAD

**Issue by adi90x** [minio/operator#762]
Hello, 

Trying to setup Minio and I am trying to find a way to create a "default" bucket when creating a new tenant.
Seems it was available in previous Helm chart but not in the new version using operator.
I am looking at sideCar, but starting a sideCar with `minio/mc` to try to run `mc mb xxx` raise an error : `mc: <ERROR> Unable to save new mc config. mkdir /.mc: permission denied.`  Look like more a permission issue on folders.

Do you have any solution to create a bucket if it doesn't exist  ? 

Regards,

**Comment by Choem** [comment]
We also have the same problem and think this can be improved.

What you could do is write a k8s Job.
This job executes after installing your Minio tenant with a Helm hook.
The job includes a script which creates a default bucket via the Minio SDK.
