### ISSUE TITLE
kubectl-minio plugin "Error: Unauthorized" with KUBECONFIG env variable set

### ISSUE THREAD

**Issue by ol88** [minio/operator#766]
I have two Kubernetes cluster with 2 separate kubeconfig files, my KUBECONFIG environment variable is set and contains the path to both kubeconfig files:

```
$ echo $KUBECONFIG
/home/user/.kube/config-kubernetes-dev:/home/user/.kube/config-kubernetes:
```

The `current-context` is set to the correct cluster where minio is successfully deployed via `kubectl minio init`

```
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.example.com:6443
  name: kubernetes
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.example.com:6443
  name: kubernetes-dev
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
- context:
    cluster: kubernetes-dev
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes-dev
current-context: kubernetes-admin@kubernetes-dev
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```
Note: I never have both clusters running at the same time which is why they share the same url in the config. Both are test clusters running on the same hardware.

All `kubectl` generic commands including minio plugin commands `kubectl minio init` and `kubectl minio delete` work perfectly.
However, none of `kubectl minio tenant` or `kubectl minio proxy` commands work, they all result in:

```
$ kubectl minio tenant list
Error: Unauthorized
```

using the --kubeconfig flag also does not work:

```
$ kubectl minio tenant list --kubeconfig /home/user/.kube/config-kubernetes-dev
Error: Unauthorized
```
The only way to make it work is to change the KUBECONFIG environment variable to a single kubeconfig file path.

```
$ export KUBECONFIG=/home/user/.kube/config-kubernetes-dev:
$ kubectl minio tenant list

Tenant 'tenant', Namespace 'minio-tenant', Total capacity 40 MiB

  Current status: Provisioning Console Deployment
  MinIO version: minio/minio:RELEASE.2021-06-17T00-10-46Z
  Console version: minio/console:v0.7.5
```

## Expected Behavior
`kubectl minio tenant` and `kubectl proxy` should succeed when multiple config path are specified in KUBECONFIG environment variable as long as the kubectl `current-context` is correctly set.

## Current Behavior
`kubectl minio tenant` and `kubectl minio proxy` both fail with error `Error: Unauthorized` when multiple config path are specified in KUBECONFIG environment variable and the kubectl `current-context` is correctly set.

## Possible Solution
Not familiar enough with the code sorry.

## Steps to Reproduce (for bugs)

1. Create a single kubernetes cluster
2. Duplicate the cluster config file to make a secondary kubeconfig file for a different fictional cluster as per above.
3. Set KUBECONFIG environment variable to point to both kubeconfig file paths. 
4. Make sure the "current-context" of kubectl config is properly set to the live cluster context created in 1.
5. Initialize minio operator on live cluster with the following command: `kubectl minio init`
6. Try to open the proxy `kubectl minio proxy -n minio-operator`
7. It should fail with `Error: Unauthorized`...

## Context
See above

## Regression
Unknown

## Your Environment

* Version used (`minio-operator`): v4.1.3
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.21.3
* Server type and version: 
* Operating System and version (`uname -a`): Ubuntu 18.04.4 LTS
* Link to your deployment file: kubectl-minio plugin installed using krew

**Comment by ol88** [comment]
After posting this issue it just started working again with both path set in the env variable. Yet I was successfully able to reproduce this bug multiple times before.

I suggest someone tries to reproduce, if it cannot be reproduced in another environment this could be closed.

**Comment by ol88** [comment]
Nope it's back to not working.

**Comment by harshavardhana** [comment]
> * Version used (`minio-operator`): v4.1.3

Please upgrade to kubectl-minio v4.2.8 and let us know if it works.
