### ISSUE TITLE
Support single volume deployments

### ISSUE THREAD

**Issue by Blackclaws** [minio/operator#768]
**Is your feature request related to a problem? Please describe.**
Currently the operator only supports erasure coded multi volume deployments. This was already touched upon in a different issue: #730

The end result there was to use the helm chart in those cases, however that has now been archived and there will no longer be any development going forward as far as I can tell.

We're already running our underlying volumes on redundant systems so there is no requirement for us to have erasure coding enabled in minio. Also for one-off deployments such as during CI runs where minio is launched as a fire and forget service it might be useful to allow the operator to deploy minio instead of having to manually do it.

**Describe the solution you'd like**
An option to disable erasure coding during tenant creation which would allow single volume deployments. 
Alternative or additionally an option to run minio purely on ephemeral storage and not in any sort of persistent form.

**Describe alternatives you've considered**
Launching minio from a simple deployment manifest that is manually adjusted to the situation at hand: Works, but is more handcrafting than might be needed with operator.

Using the Helm Chart: The helm chart is discontinued, so I don't expect that this is an option going forward

**Comment by Blackclaws** [comment]
This is still a relevant issue

**Comment by harshavardhana** [comment]
> Using the Helm Chart: The helm chart is discontinued, so I don't expect that this is an option going forward

This is not something this operator will do @Blackclaws https://github.com/minio/minio/tree/master/helm/minio is the approach for single drive approach.

**Comment by Blackclaws** [comment]
I see. Its then very confusing that this also exists: https://github.com/minio/charts which definitely states that the helm chart is deprecated but doesn't correctly link to the replacement helm chart but just at the operator. You might want to add a link to the main page of the operator that links to this other helm chart for single drive deployments.
