### ISSUE TITLE
Creating a Tenant via the Console requires at least four servers

### ISSUE THREAD

**Issue by Blackclaws** [minio/operator#769]
## Expected Behavior
I can create the same sort of tenants via the web console that I can create using the kubectl plugin. 
I want to create a single server tenant that uses 4 drives per server. Via the kubectl plugin I can do this like so:
```
kubectl minio tenant create cache-server --servers 1 --capacity 20Gi --namespace gitlab-runner-cache --volumes 4 --storage-class local-path
```

## Current Behavior
Trying to enter number of servers as 1 results in the error message:
```
Number of nodes cannot be less than 4
```
which obviously is not true.

## Possible Solution
Reason might be that the web ui is trying to ensure that the total number of volumes is at least 4. However there are other ways to reach this configuration, as seen by the manual tenant string I posted. 

## Steps to Reproduce (for bugs)
1. Create new tenant using web ui
2. Set number of servers to any number lower than 4

## Your Environment

* Version used (`minio-operator`): v4.1.3
* Environment name and version (e.g. kubernetes v1.17.2): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"archive", BuildDate:"2021-07-16T17:16:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dvaldivia** [comment]
@Blackclaws yes, we enforce this restriction mainly to avoid people going to production with a single server, one way to mitigate this issue is by removing the anti-affinity so all 4 pods are placed on the same node, that's a solution, but still exposes you to losing all pods if a single server fails

**Comment by kannappanr** [comment]
@Blackclaws Closing this issue as answered. Please feel free to reach out to us for further questions

**Comment by Blackclaws** [comment]
Yeah it answers the question. It unfortunately means the operator is probably not the correct solution in this case. All 4 pods on one node works somehow but is unnecessary overhead. A general heads up that this simply isn't supported even with overrides would be nice to have.
