### ISSUE TITLE
Unable to use the drive. Pods not Ready

### ISSUE THREAD

**Issue by Ejant** [minio/operator#773]
Hi all, I'm having problems creating tenant in my helm Chart deployment.

## Expected Behavior

4 Pods and 16Disks setup working. Pods are OK but minio is unsuable

## Current Behavior
~$ kubectl -n minio-operator get all
NAME                                                     READY   STATUS    RESTARTS   AGE
pod/minio-cortex-pool-0                                  1/1     Running   0          108s
pod/minio-cortex-pool-1                                  1/1     Running   0          108s
pod/minio-cortex-pool-2                                  1/1     Running   0          108s
pod/minio-cortex-pool-3                                  1/1     Running   0          108s
pod/minio-operator-1629213187-console-54b8965447-jltf5   1/1     Running   0          176m
pod/minio-operator-849669c89f-z9r8w                      1/1     Running   0          176m

NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/console    ClusterIP   10.98.4.249     <none>        9090/TCP,9443/TCP   176m
service/minio      ClusterIP   10.99.252.177   <none>        443/TCP             2m59s
service/minio-hl   ClusterIP   None            <none>        9000/TCP            2m59s
service/operator   ClusterIP   10.100.55.225   <none>        4222/TCP,4233/TCP   176m

NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/minio-operator                      1/1     1            1           176m
deployment.apps/minio-operator-1629213187-console   1/1     1            1           176m

NAME                                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/minio-operator-1629213187-console-54b8965447   1         1         1       176m
replicaset.apps/minio-operator-849669c89f                      1         1         1       176m

NAME                                 READY   AGE
statefulset.apps/minio-cortex-pool   4/4     109s

logs:

$ kubectl -n minio-operator logs minio-cortex-pool-0 --tail 2
{"level":"INFO","errKind":"","time":"2021-08-17T18:10:40.125206133Z","message":"Unable to use the drive https://minio-cortex-pool-0.minio-hl.minio-operator.svc.cluster.local:9000/export3: open /export3/.minio.sys/tmp/.writable-check-1ba7e8fb79503ddd.tmp: no such file or directory"}
{"level":"INFO","errKind":"","time":"2021-08-17T18:10:40.127728829Z","message":"Waiting for all other servers to be online to format the disks."}

tenant:

~$ kubectl -n minio-operator get tenant
NAME    STATE                          AGE
minio   Waiting for Pods to be ready   9m39s

logs:

~$ kubectl -n minio-operator logs minio-cortex-pool-0 --tail 2
{"level":"INFO","errKind":"","time":"2021-08-17T18:16:42.124695184Z","message":"Unable to use the drive https://minio-cortex-pool-0.minio-hl.minio-operator.svc.cluster.local:9000/export3: open /export3/.minio.sys/tmp/.writable-check-314becdb4fcebf36.tmp: no such file or directory"}
{"level":"INFO","errKind":"","time":"2021-08-17T18:16:42.127048535Z","message":"Waiting for all other servers to be online to format the disks."}

$ kubectl -n minio-operator logs minio-operator-849669c89f-z9r8w --tail 35
I0817 18:06:49.467430       1 main-controller.go:977] Deploying pool cortex-pool
I0817 18:06:50.499305       1 main-controller.go:982] Deploying pool failed cortex-pool
E0817 18:06:50.499400       1 main-controller.go:754] error syncing 'minio-operator/minio': MinIO is not ready
I0817 18:06:59.403741       1 minio.go:141] Generating private key
I0817 18:06:59.403853       1 minio.go:154] Generating CSR with CN=*.minio-hl.minio-operator.svc.cluster.local
I0817 18:06:59.413223       1 csr.go:145] Start polling for certificate of csr/minio-minio-operator-csr, every 5s, timeout after 20m0s
I0817 18:07:04.417388       1 csr.go:170] Certificate successfully fetched, creating secret with Private key and Certificate
E0817 18:07:04.420621       1 main-controller.go:754] error syncing 'minio-operator/minio': waiting for minio cert
I0817 18:07:59.417995       1 main-controller.go:977] Deploying pool cortex-pool
I0817 18:07:59.451961       1 csr.go:145] Start polling for certificate of csr/minio-console-minio-operator-csr, every 5s, timeout after 20m0s
I0817 18:08:04.455077       1 csr.go:170] Certificate successfully fetched, creating secret with Private key and Certificate
E0817 18:08:04.458379       1 main-controller.go:754] error syncing 'minio-operator/minio': waiting for console cert
Server not initialized, please try again.
I0817 18:10:41.154295       1 status.go:54] Hit conflict issue, getting latest version of tenant
I0817 18:10:41.166837       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:12:21.609146       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:13:14.711148       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:15:03.130152       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:16:41.468261       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:17:56.962229       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:19:53.200222       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:21:36.555286       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:22:58.276062       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:24:42.634293       1 main-controller.go:749] Successfully synced 'minio-operator/minio'
Server not initialized, please try again.
I0817 18:25:35.648749       1 main-controller.go:749] Successfully synced 'minio-operator/min

## Steps to Reproduce (for bugs)

1. helm install --namespace minio-operator --create-namespace --generate-name minio/minio-operator
2. kubectl -n minio-operator apply tenant.yaml
3.-kubectl -n minio-operator get tenant
NAME    STATE                          AGE
minio   Waiting for Pods to be ready   21m

## Context
Trying to set up a 4xPods and 16Disks minio solution

## Your Environment

* Version used (`minio-operator`): 4.1.13
* Environment name and version (e.g. kubernetes v1.17.2): v 1.20.2
* Server type and version:
* Operating System and version (`uname -a`): 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

* Link to your deployment file: https://dpaste.org/qXji

Pvc info:

 kubectl -n minio-operator get pvc
NAME                              STATUS   VOLUME                            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cortexdata0-minio-cortex-pool-0   Bound    cortexdata1-minio-cortex-pool-2   100Gi      RWO                           3h14m
cortexdata0-minio-cortex-pool-1   Bound    cortexdata0-minio-cortex-pool-3   100Gi      RWO                           3h14m
cortexdata0-minio-cortex-pool-2   Bound    cortexdata3-minio-cortex-pool-1   100Gi      RWO                           3h14m
cortexdata0-minio-cortex-pool-3   Bound    cortexdata3-minio-cortex-pool-0   100Gi      RWO                           3h14m
cortexdata1-minio-cortex-pool-0   Bound    cortexdata2-minio-cortex-pool-0   100Gi      RWO                           3h14m
cortexdata1-minio-cortex-pool-1   Bound    cortexdata1-minio-cortex-pool-0   100Gi      RWO                           3h14m
cortexdata1-minio-cortex-pool-2   Bound    cortexdata2-minio-cortex-pool-3   100Gi      RWO                           3h14m
cortexdata1-minio-cortex-pool-3   Bound    cortexdata0-minio-cortex-pool-1   100Gi      RWO                           3h14m
cortexdata2-minio-cortex-pool-0   Bound    cortexdata3-minio-cortex-pool-2   100Gi      RWO                           3h14m
cortexdata2-minio-cortex-pool-1   Bound    cortexdata1-minio-cortex-pool-1   100Gi      RWO                           3h14m
cortexdata2-minio-cortex-pool-2   Bound    cortexdata0-minio-cortex-pool-2   100Gi      RWO                           3h14m
cortexdata2-minio-cortex-pool-3   Bound    cortexdata0-minio-cortex-pool-0   100Gi      RWO                           3h14m
cortexdata3-minio-cortex-pool-0   Bound    cortexdata2-minio-cortex-pool-2   100Gi      RWO                           3h14m
cortexdata3-minio-cortex-pool-1   Bound    cortexdata1-minio-cortex-pool-3   100Gi      RWO                           3h14m
cortexdata3-minio-cortex-pool-2   Bound    cortexdata2-minio-cortex-pool-1   100Gi      RWO                           3h14m
cortexdata3-minio-cortex-pool-3   Bound    cortexdata3-minio-cortex-pool-3   100Gi      RWO                           3h14m

$ kubectl -n minio-operator describe pvc cortexdata0-minio-cortex-pool-0
Name:          cortexdata0-minio-cortex-pool-0
Namespace:     minio-operator
StorageClass:
Status:        Bound
Volume:        cortexdata1-minio-cortex-pool-2
Labels:        v1.min.io/pool=cortex-pool
               v1.min.io/tenant=minio
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       minio-cortex-pool-0
Events:        <none>

**Comment by harshavardhana** [comment]
is your cortex a posix compliance disk? @Ejant

**Comment by Ejant** [comment]
> is your cortex a posix compliance disk? @Ejant

It's a local volume on each k8s node, I don't know if is posix compliance. The disks are mounted on pods:

$ kubectl -n minio-operator exec -it minio-cortex-pool-0 -- sh
sh-4.4$ mount | grep export
/dev/mapper/VolGroup00-root on /export3 type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/VolGroup00-root on /export2 type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/VolGroup00-root on /export0 type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/VolGroup00-root on /export1 type ext4 (rw,relatime,errors=remount-ro)

Mountpoints on node:

root@GRFMONLBBE001:~# mount | grep export

/dev/mapper/vgexport0-lvexport0 on /export0 type ext4 (rw,relatime)
/dev/mapper/vgexport1-lvexport1 on /export1 type ext4 (rw,relatime)
/dev/mapper/vgexport2-lvexport2 on /export2 type ext4 (rw,relatime)
/dev/mapper/vgexport3-lvexport3 on /export3 type ext4 (rw,relatime)

These are my pv:

$ kubectl get pv
NAME                              CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                            STORAGECLASS   REASON   AGE
cortexdata0-minio-cortex-pool-0   100Gi      RWO            Retain           Bound    minio-operator/cortexdata2-minio-cortex-pool-3                           155m
cortexdata0-minio-cortex-pool-1   100Gi      RWO            Retain           Bound    minio-operator/cortexdata1-minio-cortex-pool-3                           155m
cortexdata0-minio-cortex-pool-2   100Gi      RWO            Retain           Bound    minio-operator/cortexdata2-minio-cortex-pool-2                           155m
cortexdata0-minio-cortex-pool-3   100Gi      RWO            Retain           Bound    minio-operator/cortexdata0-minio-cortex-pool-1                           155m
cortexdata1-minio-cortex-pool-0   100Gi      RWO            Retain           Bound    minio-operator/cortexdata1-minio-cortex-pool-1                           155m
cortexdata1-minio-cortex-pool-1   100Gi      RWO            Retain           Bound    minio-operator/cortexdata2-minio-cortex-pool-1                           155m
cortexdata1-minio-cortex-pool-2   100Gi      RWO            Retain           Bound    minio-operator/cortexdata0-minio-cortex-pool-0                           155m
cortexdata1-minio-cortex-pool-3   100Gi      RWO            Retain           Bound    minio-operator/cortexdata3-minio-cortex-pool-1                           155m
cortexdata2-minio-cortex-pool-0   100Gi      RWO            Retain           Bound    minio-operator/cortexdata1-minio-cortex-pool-0                           155m
cortexdata2-minio-cortex-pool-1   100Gi      RWO            Retain           Bound    minio-operator/cortexdata3-minio-cortex-pool-2                           155m
cortexdata2-minio-cortex-pool-2   100Gi      RWO            Retain           Bound    minio-operator/cortexdata3-minio-cortex-pool-0                           155m
cortexdata2-minio-cortex-pool-3   100Gi      RWO            Retain           Bound    minio-operator/cortexdata1-minio-cortex-pool-2                           155m
cortexdata3-minio-cortex-pool-0   100Gi      RWO            Retain           Bound    minio-operator/cortexdata0-minio-cortex-pool-3                           155m
cortexdata3-minio-cortex-pool-1   100Gi      RWO            Retain           Bound    minio-operator/cortexdata0-minio-cortex-pool-2                           155m
cortexdata3-minio-cortex-pool-2   100Gi      RWO            Retain           Bound    minio-operator/cortexdata2-minio-cortex-pool-0                           155m
cortexdata3-minio-cortex-pool-3   100Gi      RWO            Retain           Bound    minio-operator/cortexdata3-minio-cortex-pool-3                           155m

Maybe should I use a specific StorageClass??

If you need something else just let me know

**Comment by harshavardhana** [comment]
> {"level":"INFO","errKind":"","time":"2021-08-17T18:10:40.125206133Z","message":"Unable to use the drive https://minio-cortex-pool-0.minio-hl.minio-operator.svc.cluster.local:9000/export3: open /export3/.minio.sys/tmp/.writable-check-1ba7e8fb79503ddd.tmp: no such file or directory"}

The error says it's not able to verify your backend drives properly we expect that you use XFS instead of ext4 - ext4 is not a good filesystem for large-scale deployments. 

Either your filesystem is corrupted here or it's not allowing us to verify O_DIRECT support for some reason leading to failure. 

Please use XFS instead we can't trust ext4.

**Comment by Ejant** [comment]
It's working now. Thanks for the support!!!

**Comment by 13567436138** [comment]
how to work
