### ISSUE TITLE
support new design of minio console for the tenant.

### ISSUE THREAD

**Issue by fcomte** [minio/operator#776]
**Is your feature request related to a problem? Please describe.**
I am unable to publish the random port of the minio console (since the new design)

**Describe the solution you'd like**
I would like to be able to access minio tenant console for the last minio releases

**Describe alternatives you've considered**
I publish the service manually for the moment but the port is random so it's very inefficiant.

Is there any plan to support the new minio console design ?

**Comment by dvaldivia** [comment]
@fcomte the next release should address this https://github.com/minio/operator/pull/774

Meanwhile you could pass an environment variable to set a fixed port, but I don't anticipate the next release taking much time

**Comment by fcomte** [comment]
I confirm that this new release fix that
