### ISSUE TITLE
helm releases

### ISSUE THREAD

**Issue by jr0dd** [minio/operator#780]
In your Chart.yaml you have chart version 4.1.8, but your index.yaml is still showing 4.1.7.

**Comment by dnskr** [comment]
Helm shows chart minio-operator:4.1.7 deploy operator:v4.2.0 instead of operator:v4.1.3
```
$ helm repo up
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "minio" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo minio
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
minio/minio-operator    4.1.7           v4.2.0          A Helm chart for MinIO Operator
```

But in helm chart it is still 4.1.3
```
$ helm pull minio/minio-operator

$ ls
minio-operator-4.1.7.tgz  values.yaml

$ tar -xvf minio-operator-4.1.7.tgz

$ cat minio-operator/Chart.yaml
apiVersion: v2
appVersion: v4.1.3
description: A Helm chart for MinIO Operator
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: dev@minio.io
  name: MinIO, Inc
name: minio-operator
sources:
- https://github.com/minio/operator
type: application
version: 4.1.7
```

**Comment by jr0dd** [comment]
> Chart 4.1.8 has not been released yet.
> 
> At the same time I see weird bug:
> Helm shows chart minio-operator:4.1.7 deploy operator:v4.2.0 instead of operator:v4.1.3
> 
> ```
> $ helm repo up
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "minio" chart repository
> Update Complete. ⎈Happy Helming!⎈
> 
> $ helm search repo minio
> NAME                    CHART VERSION   APP VERSION     DESCRIPTION
> minio/minio-operator    4.1.7           v4.2.0          A Helm chart for MinIO Operator
> ```
> 
> But in helm chart it is still 4.1.3
> 
> ```
> $ helm pull minio/minio-operator
> 
> $ ls
> minio-operator-4.1.7.tgz  values.yaml
> 
> $ tar -xvf minio-operator-4.1.7.tgz
> 
> $ cat minio-operator/Chart.yaml
> apiVersion: v2
> appVersion: v4.1.3
> description: A Helm chart for MinIO Operator
> home: https://min.io
> icon: https://min.io/resources/img/logo/MINIO_wordmark.png
> keywords:
> - storage
> - object-storage
> - S3
> maintainers:
> - email: dev@minio.io
>   name: MinIO, Inc
> name: minio-operator
> sources:
> - https://github.com/minio/operator
> type: application
> version: 4.1.7
> ```

This is what I'm referring to. I probably could have given more details. The Chart.yaml in the helm directory has 4.1.8 as the chart version and appVersion 4.2.0, while the helm repo has 4.1.7 and appVersion 4.2.0.
