### ISSUE TITLE
Provisioning MinIO Statefulset failed because Invalid credentials: access key length should be between 3 and 20

### ISSUE THREAD

**Issue by dshuvar** [minio/operator#782]
Getting error when creating new Tennant by default from minio console
"Invalid credentials: access key length should be between 3 and 20"

## Expected Behavior
tenant created with default parameters

## Current Behavior

Capacity: | 64 GiB | Clusters: | 1
Instances: | 4 | Volumes: | 4
MinIO: | minio/minio:RELEASE.2021-08-17T20-53-08Z
State: | Provisioning MinIO Statefulset

Error in logs:
```
ERROR Unable to validate credentials inherited from the shell environment: Invalid credentials
      > Please provide correct credentials
      HINT:
        Access key length should be at least 3, and secret key length at least 8 characters
 ```
 
 Access key created by default like: 
```
{"console":[{"access_key":"IpvwjrBSBCejluKF","secret_key":"jnIp8XNmO1dWRtY2QNqiEHQgG2MJhthE"}]}
```

## Your Environment

kubernetes v1.20.9
images:
  - name: minio/console:v0.9.2
  - name: minio/operator:v4.2.1

**Comment by dvaldivia** [comment]
@dshuvar can you share the `.status` field of your tenant in this ticket? Can you share a list of secrets for that tenant? We don't need to see the contents, but we do need you to confirm `yourtenant-secret` still has the `accesskey` and `secretkey` populated

@Alevsk I suspect this is the new config secret

**Comment by dshuvar** [comment]
I try to use the latest MinIO: | minio/minio:RELEASE.2021-08-31T05-46-54Z

but in step "Provisioning MinIO Statefulset" I still see in statefulset logs:

```
ERROR Unable to validate credentials inherited from the shell environment: Invalid credentials
      > Please provide correct credentials
      HINT:
        Access key length should be at least 3, and secret key length at least 8 characters
```

**Comment by Alevsk** [comment]
This is fixed in the latest operator release, please test and re open if necessary
