### ISSUE TITLE
cannot install operator

### ISSUE THREAD

**Issue by Linsanxian** [minio/operator#792]
cannot install operator through krew

## Expected Behavior

install successd 
## Current Behavior

kubectl krew install minio
Updated the local copy of plugin index.
Installing plugin: minio
W0831 17:58:31.681095   11014 install.go:164] failed to install plugin "minio": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: a21325e51771a7e03519221b2810acf8730158ec19faf97b494442f40c931731, got 646f16e2cc4892af567db38b706c5a9424697605d8137431b35dc59c15fd12ee
F0831 17:58:31.681535   11014 root.go:79] failed to install some plugins: [minio]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: a21325e51771a7e03519221b2810acf8730158ec19faf97b494442f40c931731, got 646f16e2cc4892af567db38b706c5a9424697605d8137431b35dc59c15fd12ee

## Steps to Reproduce (for bugs)

1. Create EKS cluster
2. kubectl krew update
3. kubectl krew install minio

## Your Environment

* Version used (`minio-operator`): v4.2.3
* Environment name and version (e.g. kubernetes v1.17.2):  v1.22.1
* Server type and version: aws eks
* Operating System and version (`uname -a`):
* Link to your deployment file:

kubectl krew info minio
NAME: minio
INDEX: default
URI: https://github.com/minio/operator/releases/download/v4.2.3/kubectl-minio_darwin_amd64.zip
SHA256: a21325e51771a7e03519221b2810acf8730158ec19faf97b494442f40c931731
VERSION: v4.2.3
HOMEPAGE: https://github.com/minio/operator/tree/master/kubectl-minio
DESCRIPTION:
The kubectl-minio plugin wraps the MinIO Operator and provides a simplified
interface to create and manage MinIO tenant clusters.

**Comment by vadmeste** [comment]
@Linsanxian, thanks. I am able to reproduce this. We will fix it shortly.

**Comment by Linsanxian** [comment]
> @Linsanxian, thanks. I am able to reproduce this. We will fix it shortly.

thanks

**Comment by harshavardhana** [comment]
https://github.com/kubernetes-sigs/krew-index/pull/1498 to be fixed here

**Comment by harshavardhana** [comment]
This is fixed with upgrading to v4.2.4 https://github.com/kubernetes-sigs/krew-index/pull/1505
