### ISSUE TITLE
error syncing 'minio/minio': secrets "operator-tls" not found

### ISSUE THREAD

**Issue by Linsanxian** [minio/operator#796]
I tried deploying minio in aws eks , has error secrets "operator-tls" not found
I tried use #713 
But always get this error

## Steps to Reproduce (for bugs)

1. create aws eks cluster
2. install operator release version v4.2.3
3. kubectl minio init --output > ~/works/Minio/operator.yml
4. edit operator.yml and setting  OPERATOR_TLS is false
4. kubectl apply -f ~/works/Minio/operator.yml
5. use operator console ui create tenant disable AutoCert

## Context

I0901 07:29:45.494469       1 main.go:73] Starting MinIO Operator
I0901 07:29:45.953172       1 main.go:140] caBundle on CRD updated
I0901 07:29:45.953564       1 main-controller.go:242] Setting up event handlers
I0901 07:29:45.953627       1 main-controller.go:359] Starting Tenant controller
I0901 07:29:45.953635       1 main-controller.go:362] Waiting for informer caches to sync
I0901 07:29:45.976895       1 operator.go:85] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
I0901 07:29:45.997722       1 csr.go:145] Start polling for certificate of csr/operator-minio-operator-csr, every 5s, timeout after 20m0s
I0901 07:29:46.053818       1 main-controller.go:367] Starting workers

I0901 07:32:11.953824       1 upgrades.go:40] minio has no log secret
E0901 07:32:11.972181       1 upgrades.go:67] Error deleting operator webhook secret, manual deletion is needed: secrets "operator-webhook-secret" not found
I0901 07:32:12.064521       1 status.go:54] Hit conflict issue, getting latest version of tenant
I0901 07:32:12.127440       1 status.go:54] Hit conflict issue, getting latest version of tenant
E0901 07:32:12.203857       1 main-controller.go:461] error syncing 'minio/minio': secrets "operator-tls" not found
E0901 07:32:22.042424       1 main-controller.go:461] error syncing 'minio/minio': secrets "operator-tls" not found
I0901 07:32:46.065578       1 monitoring.go:104] 'minio/minio' no pool is initialized
E0901 07:33:22.070613       1 main-controller.go:461] error syncing 'minio/minio': secrets "operator-tls" not found
E0901 07:34:22.102307       1 main-controller.go:461] error syncing 'minio/minio': secrets "operator-tls" not found
E0901 07:35:22.132636       1 main-controller.go:461] error syncing 'minio/minio': secrets "operator-tls" not found
I0901 07:35:46.066573       1 monitoring.go:104] 'minio/minio' no pool is initialized

## Your Environment

* Version used (`minio-operator`): v4.2.3
* Environment name and version (e.g. kubernetes v1.17.2): 1.2.11
* Server type and version:  aws eks
* Operating System and version (`uname -a`):
* Link to your deployment file:
[operator.yml.zip](https://github.com/minio/operator/files/7089446/operator.yml.zip)

**Comment by Alevsk** [comment]
@Linsanxian operator-tls secret is generated after the operator-tls csr is approved and issued, please check the out of `kubectl get csr -A`, look for `operator-minio-operator-csr` and verify the status is `Approved, Issued`, similar to:

```
operator-minio-operator-csr   14s   kubernetes.io/kubelet-serving   system:serviceaccount:minio-operator:minio-operator   Approved,Issued
```

If you don't see the `Issued` then theres is something wrong with your AWS EKS cluster, most likely a misconfiguration, we observed this problem in the past and its not an operator bug, the reason is probably because of the missing args on the kube-controller-manager

```
│     - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt                                                                                               │
│     - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
```

you can also describe the CSR and see more information there on what is preventing it for being issued
