### ISSUE TITLE
Minio Tenant got struck at "Provisioning Minio TLS certificate" deployment is through Minio Operator.

### ISSUE THREAD

**Issue by Vineeth-varma** [minio/operator#801]
Minio Operator - deployed successfully
Minio Tenant - Struck at provising TLS certificate.
Getting this error **error syncing 'minio/minio-custom-cert-no-encryption-minio': secrets "operator-tls" not found**
I am using Rancher , I thought may be it is not able to provision correct CA, So I have used custom certificate generated by Cert Manager by following this link https://github.com/minio/operator/blob/master/docs/tls.md
Still my issue isnt resolved ...,

I need some help on this.

**Comment by Vineeth-varma** [comment]
Anyone from the Minio team knows about this issue?

**Comment by dvaldivia** [comment]
this seems like the `operator-tls` secret is missing, by default the operator creates it on each tenant namespace so the MinIO pods can communicate with Operator for various tasks, can you share the logs of your operator? there should be a log complaining about the reason for this not working

**Comment by k8s-cmri** [comment]
I had the same problem,
#but I set the environment variable for value.yaml of opeador
env:
    - name: MINIO_OPERATOR_TLS_ENABLE
      value: "off"
# and set requestautocert in tenant.yaml
 requestAutoCert: false

#Generate a self-signed certificate
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = US
ST = VA
L = Somewhere
O = MyOrg
OU = MyOU
CN = MyServerName

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = minio-pool-0-0.minio-hl.default.svc.cluster.local
DNS.2 = minio-pool-0-1.minio-hl.default.svc.cluster.local
DNS.3 = minio-pool-0-2.minio-hl.default.svc.cluster.local
DNS.4 = minio-pool-0-3.minio-hl.default.svc.cluster.local

Finally, the mini tenant is healthy, but it can't
Click Manage Tenant on minio console
How to get to the create bucket page? I'm a beginner. Please help me

**Comment by Vineeth-varma** [comment]
> this seems like the `operator-tls` secret is missing, by default the operator creates it on each tenant namespace so the MinIO pods can communicate with Operator for various tasks, can you share the logs of your operator? there should be a log complaining about the reason for this not working

These are my logs
![image](https://user-images.githubusercontent.com/60296821/131950145-5c4495a0-8fb3-44c2-bd1f-354b396dfb2d.png)
E0903 03:29:28.625796       1 operator.go:137] Unexpected error during the creation of the csr/operator-miop-csr: timeout during certificate fetching of csr/operator-miop-csr
I0903 03:29:28.626203       1 main-controller.go:627] Waiting for the operator certificates to be issued timeout during certificate fetching of csr/operator-miop-csr
I0903 03:29:38.631486       1 main-controller.go:625] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
I0903 03:29:38.644315       1 csr.go:145] Start polling for certificate of csr/operator-miop-csr, every 5s, timeout after 20m0s``


For my other kubernetes On-prem clusters I havent faced any issue.
This deployment I was trying in Rancher, but it is giving me lot of headehes, could you help.

**Comment by k8s-cmri** [comment]
> > this seems like the `operator-tls` secret is missing, by default the operator creates it on each tenant namespace so the MinIO pods can communicate with Operator for various tasks, can you share the logs of your operator? there should be a log complaining about the reason for this not working
> 
> These are my logs
> ![image](https://user-images.githubusercontent.com/60296821/131950145-5c4495a0-8fb3-44c2-bd1f-354b396dfb2d.png)
> 
> For my other kubernetes On-prem clusters I havent faced any issue.
> This deployment I was trying in Rancher, but it is giving me lot of headehes, could you help.


I  use rancher 2.4.5

**Comment by Vineeth-varma** [comment]
> I use rancher 2.4.5
Yes I have checked with the configurations provided above with env set to
env:
- name: MINIO_OPERATOR_TLS_ENABLE
value: "off" 
 Still facing the same "operator-tls" not found issue.

**Comment by ravindk89** [comment]
The operator-tls issue not found is related to missing K8s TLS infrastructure. See docs [here](https://docs.min.io/minio/k8s/deployment/deploy-minio-operator.html#kubernetes-tls-certificate-api). Rancher is particularly well known for having this issue.

@Vineeth-varma you may need to completely uninstall the operator, remove all pending CSR, and then re-install using any such envvars. Also see https://github.com/minio/operator/issues/632#issuecomment-847843669 for other users with issues on Rancher + TLS.
