### ISSUE TITLE
tenant stuck "Provisioning Prometheus service monitor"

### ISSUE THREAD

**Issue by jr0dd** [minio/operator#804]
The tenant is healthy and usable, but the state is stuck on "Provisioning Prometheus service monitor". The servicemonitor exists and is scraping metrics just fine. This is also spamming the operator logs.  

```
E0903 16:31:16.387999       1 main-controller.go:461] error syncing 'minio/tenant0': servicemonitors.monitoring.coreos.com "tenant0-prometheus" already exists
E0903 16:32:16.511160       1 main-controller.go:461] error syncing 'minio/tenant0': servicemonitors.monitoring.coreos.com "tenant0-prometheus" already exists
E0903 16:33:16.553685       1 main-controller.go:461] error syncing 'minio/tenant0': servicemonitors.monitoring.coreos.com "tenant0-prometheus" already exists
E0903 16:34:16.586747       1 main-controller.go:461] error syncing 'minio/tenant0': servicemonitors.monitoring.coreos.com "tenant0-prometheus" already exists
E0903 16:35:16.732785       1 main-controller.go:461] error syncing 'minio/tenant0': servicemonitors.monitoring.coreos.com "tenant0-prometheus" already exists
E0903 16:36:16.766579       1 main-controller.go:461] error syncing 'minio/tenant0': servicemonitors.monitoring.coreos.com "tenant0-prometheus" already exists
E0903 16:37:16.801620       1 main-controller.go:461] error syncing 'minio/tenant0': servicemonitors.monitoring.coreos.com "tenant0-prometheus" already exists
```

<img width="1464" alt="Screen Shot 2021-09-03 at 12 32 46 PM" src="https://user-images.githubusercontent.com/285797/132039582-c46afc5d-b74f-45b2-9fd9-b030004bba6f.png">

**Comment by jr0dd** [comment]
Please don't hate me for my created issues @harshavardhana lol

**Comment by gdznela** [comment]
I have same issue, running latest version of operator helm chart (4.2.10).
@jr0dd were you able to find a workaround?

**Comment by jr0dd** [comment]
> I have same issue, running latest version of operator helm chart (4.2.10).
> 
> @jr0dd were you able to find a workaround?

I just moved back to the regular minio chart. This needs to mature a bit before I revisit. I have wasted countless hours troubleshooting bugs with the operator chart that just get shrugged off and ignored.
