### ISSUE TITLE
helm 4.2.5 is missing

### ISSUE THREAD

**Issue by wenerme** [minio/operator#809]
## Expected Behavior

from https://operator.min.io/index.yaml

https://operator.min.io/helm-releases/minio-operator-4.2.5.tgz  should exists

## Current Behavior

https://operator.min.io/helm-releases/minio-operator-4.2.5.tgz not found

**Comment by dnskr** [comment]
@dvaldivia Could you please have a look into the issue?
I can download https://operator.min.io/helm-releases/minio-operator-4.2.4.tgz but https://operator.min.io/helm-releases/minio-operator-4.2.5.tgz is not found.

**Comment by harshavardhana** [comment]
@dnskr will update it
