### ISSUE TITLE
Unsupported release tag on new image, non-disruptive update not allowed

### ISSUE THREAD

**Issue by olevitt** [minio/operator#812]
Hi,

When changing the image used by the tenant, the operator outputs the following error : 

```
I0906 12:35:19.688986       1 main-controller.go:953] Updating 'minio' MinIO from: 2021-08-31T05:46:54Z, to: 2021-09-03T03-56-13Z
E0906 12:35:19.689075       1 main-controller.go:961] Unsupported release tag on new image, non-disruptive update not allowed %!w(*errors.errorString=&{2021-09-03T03-56-13Z is not a valid release tag})
E0906 12:35:19.689120       1 main-controller.go:469] error syncing 'minio-test/minio': 2021-09-03T03-56-13Z is not a valid release tag
```  

it still works as expected, upgrading the statefulset's image and upgrading just fine.
I tried with various recent tags, all valid releases and they all triggers those messages.

Additionnaly, where can I find more documentation on minIO non-disruptive updates system ? How do I get control over the way the operator handles the upgrades (for example, disabling non-disruptive updates globally whatever the image tag is) ?

Minio operator : `4.2.5`

Thanks :)

**Comment by harshavardhana** [comment]
> I0906 12:35:19.688986       1 main-controller.go:953] Updating 'minio' MinIO from: 2021-08-31T05:46:54Z, to: 2021-09-03T03-56-13Z
> E0906 12:35:19.689075       1 main-controller.go:961] Unsupported release tag on new image, non-disruptive update not allowed %!w(*errors.errorString=&{2021-09-03T03-56-13Z is not a valid release tag})
> E0906 12:35:19.689120       1 main-controller.go:469] error syncing 'minio-test/minio': 2021-09-03T03-56-13Z is not a valid release tag

Looks like the operator is not parsing the tags correctly.

**Comment by harshavardhana** [comment]
Please test with v4.2.7

**Comment by harshavardhana** [comment]
> ```
> E0906 12:35:19.689120       1 main-controller.go:469] error syncing 'minio-test/minio': 2021-09-03T03-56-13Z is not a valid release tag
> ```

Looks like you are passing wrong release tags here,  this only supports `minio/minio:RELEASE.2021-09-03T03-56-13Z` - looks like you have removed `RELEASE.` from the build date prefix. 

Please fix that and try again.

**Comment by jrpedrianes** [comment]
Is this issue already fixed?

I have the same error:

```
I0205 18:18:54.780576       1 main-controller.go:1066] Updating 'minio' MinIO from: 2022-01-28T02:28:16Z, to: 2022-02-01T18-00-14Z
E0205 18:18:54.780665       1 main-controller.go:1074] Unsupported release tag on new image, non-disruptive update not allowed %!w(*errors.errorString=&{2022-02-01T18-00-14Z is not a valid release tag})
E0205 18:18:54.780717       1 main-controller.go:556] error syncing 'minio/minio': 2022-02-01T18-00-14Z is not a valid release tag
```

I'm using minio operator `minio/operator:v4.4.6` and I'm migrating from this `minio/minio:RELEASE.2021-11-09T03-21-45Z` to `quay.io/minio/minio:RELEASE.2022-01-28T02-28-16Z`. As you can see I'm adding the "RELEASE" prefix in the image tag.

Seems that when you are invoking to `adminClnt.ServerUpdate(ctx, updateURL)` here https://github.com/minio/operator/blob/v4.4.6/pkg/controller/cluster/main-controller.go#L1052 the server response the version without the `RELEASE` prefix, and then the process fails because the call to `miniov2.ReleaseTagToReleaseTime` https://github.com/minio/operator/blob/v4.4.6/pkg/controller/cluster/main-controller.go#L1072 required it.

**Comment by harshavardhana** [comment]
@jrpedrianes yes of course this is already fixed - please share your statelfulset yaml file and lets see what you provided on the yaml file while updating the image.

**Comment by harshavardhana** [comment]
I reproduced the issue @jrpedrianes

**Comment by harshavardhana** [comment]
It will still upgrade by rolling the pods @jrpedrianes - looks like there is some parsing issue.

**Comment by harshavardhana** [comment]
Also that error message is wrong in-fact it has already updated the server, will update the error message as well.

**Comment by jrpedrianes** [comment]
Yes at the end the pods are rolling, but the error appears and it’s a bit odd

**Comment by jrpedrianes** [comment]
Yes and the previous message is not totally correct because log that the server will be updated but was updated before. 😂

**Comment by jrpedrianes** [comment]
I just tested it in a local environment and works perfect, thanks a lot.
