### ISSUE TITLE
minio/operator upgrade from version v4.2.4 to version v4.2.5 cant start

### ISSUE THREAD

**Issue by dshuvar** [minio/operator#813]
When I update minio operator from version v4.2.4 to version v4.2.5:
New pod cant start and in logs below error:

```
I0906 13:11:42.287232       1 main.go:74] Starting MinIO Operator
I0906 13:11:42.607270       1 main.go:141] caBundle on CRD updated
I0906 13:11:42.607783       1 main-controller.go:242] Setting up event handlers
I0906 13:11:42.607850       1 main-controller.go:363] Waiting for API to start
panic: tls: private key does not match public key
goroutine 73 [running]:
github.com/minio/operator/pkg/controller/cluster.(*Controller).generateTLSCert(0xc000162900, 0x19, 0x0, 0x0, 0x225c676e69727400)
	github.com/minio/operator/pkg/controller/cluster/operator.go:120 +0x853
github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1(0xc000162900, 0xc0000a2c60)
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:344 +0x86
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start
	github.com/minio/operator/pkg/controller/cluster/main-controller.go:342 +0x6e
```

**Comment by harshavardhana** [comment]
> I0906 13:11:42.607783       1 main-controller.go:242] Setting up event handlers
> I0906 13:11:42.607850       1 main-controller.go:363] Waiting for API to start
> panic: tls: private key does not match public key

Make sure to delete `operator-tls-secret` - let the operator regenerate

**Comment by harshavardhana** [comment]
Please test with v4.2.7

**Comment by dvaldivia** [comment]
in `v4.2.5` we introduced a change that makes it so operator doesn't start if it cannot get it's own certificate (via CSR) a way to fix the error you are getting @dshuvar is to delete any CSR for MinIO (kubectl get csr -A), the operator TLS secret `operator-tls-secret` on the tenant namespace and any namespace with a tenant and then restar the operator.

Please also use `v4.2.7` for this test, we did a fix for CSRs on this release

**Comment by harshavardhana** [comment]
v4.2.8 is also released closing the issue.
