### ISSUE TITLE
flag provided but not defined: -console-address

### ISSUE THREAD

**Issue by RogerParkinson** [minio/operator#818]
Starting a minio tenant pod using the operator the pod fails and gives me an error (from the log):

```
Incorrect Usage: flag provided but not defined: -console-address
```

## Expected Behavior

I expect the pod to start successfully

## Current Behavior
The operator creates the PVs and they look alright. It creates the StatefulSet and sets it to use image: `minio/minio:RELEASE.2021-06-07T21-40-51Z`, but the pod does not start (CrashLoopBackoff) and the log from the pod contains:
```
Incorrect Usage: flag provided but not defined: -console-address
```
I did a kubectl describe for the pod and it looks like this:

```
Name:         minio-autocert-no-encryption-ss-0-0
Namespace:    onepanel
Priority:     0
Node:         e1-bonanza/192.168.50.50
Start Time:   Wed, 08 Sep 2021 18:37:51 +1200
Labels:       app=minio-autocert-no-encryption-minio
              controller-revision-hash=minio-autocert-no-encryption-ss-0-64646ff7
              statefulset.kubernetes.io/pod-name=minio-autocert-no-encryption-ss-0-0
              v1.min.io/console=minio-autocert-no-encryption-console
              v1.min.io/pool=ss-0
              v1.min.io/tenant=minio-autocert-no-encryption
Annotations:  cni.projectcalico.org/podIP: 10.1.249.141/32
              cni.projectcalico.org/podIPs: 10.1.249.141/32
              min.io/revision: 0
              prometheus.io/path: /minio/prometheus/metrics
              prometheus.io/port: 9000
              prometheus.io/scrape: true
Status:       Running
IP:           10.1.249.141
IPs:
  IP:           10.1.249.141
Controlled By:  StatefulSet/minio-autocert-no-encryption-ss-0
Containers:
  minio:
    Container ID:  containerd://814d2099a9960cc03f5b4cf99c8f6cd5e7fbf59545a3772e782112f8a2ad5d3a
    Image:         minio/minio:RELEASE.2021-06-07T21-40-51Z
    Image ID:      docker.io/minio/minio@sha256:37d020e220d66cee2df84e25ea474636668eb91bed1fbf33a72bb1406b224ce3
    Ports:         9000/TCP, 9090/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      server
      --certs-dir
      /tmp/certs
      --console-address
      :9090
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 08 Sep 2021 18:43:40 +1200
      Finished:     Wed, 08 Sep 2021 18:43:40 +1200
    Ready:          False
    Restart Count:  6
    Environment:
      MINIO_UPDATE:                  on
      MINIO_UPDATE_MINISIGN_PUBKEY:  RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
      MINIO_ARGS:                    <set to the key 'MINIO_ARGS' in secret 'operator-webhook-secret'>  Optional: false
      MINIO_ENDPOINTS:               /data{0...3}
      MINIO_OPERATOR_VERSION:        v4.2.5
      MINIO_ROOT_USER:               <set to the key 'accesskey' in secret 'minio-autocert-no-encryption-minio-creds-secret'>  Optional: false
      MINIO_ROOT_PASSWORD:           <set to the key 'secretkey' in secret 'minio-autocert-no-encryption-minio-creds-secret'>  Optional: false
      MINIO_SERVER_URL:              http://minio.onepanel.svc.cluster.local:80
    Mounts:
      /data0 from data0 (rw)
      /data1 from data1 (rw)
      /data2 from data2 (rw)
      /data3 from data3 (rw)
      /tmp/certs from minio-autocert-no-encryption-tls (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-v26h7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data2:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data2-minio-autocert-no-encryption-ss-0-0
    ReadOnly:   false
  data3:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data3-minio-autocert-no-encryption-ss-0-0
    ReadOnly:   false
  data0:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data0-minio-autocert-no-encryption-ss-0-0
    ReadOnly:   false
  data1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data1-minio-autocert-no-encryption-ss-0-0
    ReadOnly:   false
  minio-autocert-no-encryption-tls:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          operator-tls
    SecretOptionalName:  <nil>
  kube-api-access-v26h7:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  10m                 default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  10m                 default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         10m                 default-scheduler  Successfully assigned onepanel/minio-autocert-no-encryption-ss-0-0 to e1-bonanza
  Normal   Pulled            9m8s (x5 over 10m)  kubelet            Container image "minio/minio:RELEASE.2021-06-07T21-40-51Z" already present on machine
  Normal   Created           9m8s (x5 over 10m)  kubelet            Created container minio
  Normal   Started           9m7s (x5 over 10m)  kubelet            Started container minio
  Warning  BackOff           34s (x47 over 10m)  kubelet            Back-off restarting failed container
```
I noticed in there that at Containers.minio.Args the `--console-address` is specified. So it seems the Operator is specifying a flag that is not compatible with the image it is also specifying. 

## Steps to Reproduce (for bugs)

 1 install microk8s
 2 install krew (https://krew.sigs.k8s.io/docs/user-guide/setup/install/)
 3 `microk8s kubectl krew install minio`
 4 `microk8s kubectl minio init`
 5 `microk8s kubectl create namespace onepanel`
 6 `microk8s kubectl apply -f minio-onepanel.yaml --namespace onepanel`

where the `minio-onepanel.yaml` file is taken from [this site](https://docs.onepanel.ai/docs/deployment/configuration/miniotenants/) unchanged (I also attached it). It specifies two secrets and a tenant.

Give the operator and pod time to initialize and you will see the pod has failed to start and has the error message described above.

## Context

I am trying to start an initial Minio, keeping it as simple as possible for now. I expect to make the configuration more complicated once I have it working. The Minio instance will hold one tenant with several buckets mostly used to store my application configuration files.

## Regression

Yes.
I have a second machine with everything set up as described above. But that is running v4.1.2 of the operator. The args field on that shows `server --certs-dir /tmp/certs --json --anonymous` (no sign of any `console-address` there). The machine with the problem is running operator v4.2.5. Both launch a minio pod running container image `minio/minio:RELEASE.2021-06-07T21-40-51Z`

## Your Environment
microk8s kubectl version
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-3+e5758f73ed2a04", GitCommit:"e5758f73ed2a04898a6bba130459e17b95402dcd", GitTreeState:"clean", BuildDate:"2021-08-12T15:05:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-3+e5758f73ed2a04", GitCommit:"e5758f73ed2a04898a6bba130459e17b95402dcd", GitTreeState:"clean", BuildDate:"2021-08-12T15:00:31Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
[minio-onepanel.yaml.txt](https://github.com/minio/operator/files/7127673/minio-onepanel.yaml.txt)

**Comment by vadmeste** [comment]
You need to use an older MinIO operator for this to work, I think https://docs.onepanel.ai/docs/deployment/configuration/miniotenants/ needs to show how to install a specific operator version

**Comment by nlamirault** [comment]
@vadmeste which version works ? I've got the same error using default values from the Helm chart.

**Comment by harshavardhana** [comment]
> @vadmeste which version works ? I've got the same error using default values from the Helm chart.

You need to use v4.2.5 version of operator @nlamirault

**Comment by RogerParkinson** [comment]
@vadmeste that is consistent with my second machine which is using Operator v4.1.2 and deploying MinIO minio/minio:RELEASE.2021-06-07T21-40-51Z, the one that is not working runs Operator v4.2.5 and also deploys MinIO minio/minio:RELEASE.2021-06-07T21-40-51Z

@harshavardhana you recommended v4.2.5 but that is the version that is giving me problems, however you also mention a different MinIO release. Possibly if I can deploy that MinIO release from v4.2.5 I solve the problem? But I thought the Operator determined the MinIO release. Is there a way to specify the MinIO release?

**Comment by RogerParkinson** [comment]
I found the release in my `minio-onepanel.yaml` file, and it is now working. Thanks for the help.
So my real problem was that I had a version mismatch between the operator and the MinIO container image I was specifying.

**Comment by DanielBo** [comment]
I encoutered something liket his.

When trying to run docker run -p 9000:9000 -p 9001:9001 minio/minio:latest server /data --console-address ":9001" i get the same error.
However if i run the same image from the quay.io repo it works just fine:
docker run -p 9000:9000 -p 9001:9001 quay.io/minio/minio:latest server /data --console-address ":9001"

**Comment by harshavardhana** [comment]
> When trying to run docker run -p 9000:9000 -p 9001:9001 minio/minio:latest server /data --console-address ":9001" i get the same error.

This is because you have a previous `minio` container locally available - this is why you should never use `:latest` tag.  If you do make sure to `docker pull` all the time.
