### ISSUE TITLE
TLS should not be required for KES

### ISSUE THREAD

**Issue by valeriano-manassero** [minio/operator#830]
**Is your feature request related to a problem? Please describe.**
When enabling KES for encryption, TLS enabled is required. While this is generally a good solution, there are environments that already encapsulates traffic encrypting it (like ones using specific configuration of Istio). In that case every application is using HTTP since the traffic is encapsulated on another level.

**Describe the solution you'd like**
TLS should be *recommended* but not *required* in case of KES enabled

**Describe alternatives you've considered**
At the moment I can't see any way to enable KES for encryption with HTTP.

**Comment by harshavardhana** [comment]
KES will never support plain-text connections @valeriano-manassero - KES is a KMS and KMS requires security. 

These are the design decisions of Kes, they are not going to change.

**Comment by valeriano-manassero** [comment]
> KES will never support plain-text connections @valeriano-manassero - KES is a KMS and KMS requires security.
> 
> These are the design decisions of Kes, they are not going to change.

First, thank you for fast answer. I fully agree on `KES requires security` but encrypted communications may be reached with other solutions like `Istio transparent TLS encryption`; forcing a TLS also in KES will mean *double* encryption that doesn't bring any benefit but a waste of resources.

If this is not possible by design, it's at least possible to have MiniIO with TLS enabled (so KES can be enabled) to expose *both* http and https endpoints?

Thank you.
