### ISSUE TITLE
Got error in logsearchapi

### ISSUE THREAD

**Issue by mostafa8026** [minio/operator#841]
after upgrading to the latest version of minio, and minio-console, I got the following error in the console logs:

```
logsearch      | 2021/09/19 09:29:23 Error writing to DB: 'ns' suffix not present (500)
```

## Steps to Reproduce (for bugs)
1. update to the: minio/console:v0.10.0, minio/logsearchapi:v4.2.10

## Your Environment

* Version used (`minio-operator`): I'm using docker-compose
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`): Linux local 5.4.0-74-generic 83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:

**Comment by mostafa8026** [comment]
I think this issue is somehow related to the time.

**Comment by Alevsk** [comment]
Can you try this on the latest version of the operator? The problem should be fixed, please re open if you see the issue

**Comment by mostafa8026** [comment]
Sorry, Not now. Our devops code base migrated to the k8s version and we don't have metrics for now, I will test ASAP.
