### ISSUE TITLE
Detailed Documentation on StorageClass Limitation

### ISSUE THREAD

**Issue by ethernoy** [minio/operator#849]
**Is your feature request related to a problem? Please describe.**
Deploying MinIO operator with tenant on a managed Kubernetes cluster may produce issues in storage class. According to the documentation of this repository, MinIO requires a storage class with `volumeBindingMode` = `WaitForFirstConsumer`. In a managed Kubernetes cluster (e.g. VMware Tanzu), this may not be configurable and default to `Immediate`. I deployed MinIO in a said environment, the tenant can be provisioned normally, but I am not sure whether there is any potential risk.

**Describe the solution you'd like**
A more detailed documentation on storage class limitation: e.g. 
- What may happen if `volumeBindingMode` = `Immediate`?
- If the PVC can be provisioned normally, will there be any extra potential risk in the future during MinIO operation?

**Comment by harshavardhana** [comment]
This is already answered neatly be @nirav-chotai
