### ISSUE TITLE
Minio Operator - LDAP 

### ISSUE THREAD

**Issue by Vineeth-varma** [minio/operator#852]
Can someone help me on how to set up LDAP Authentication for Minio Operator.
I didn't find proper info to set Up LDAP for MInio Operator. Are there any sources or manifests ?

Help would be really appreciated.

**Comment by Vineeth-varma** [comment]
Can someone have configured LDAP for Minio Operator ???

**Comment by Vineeth-varma** [comment]
Why no one is responding to this any one have configured or no idea on this??

**Comment by mfbrj** [comment]
I did some configuration. Minio can authenticate user and get groups from AD. But I get this error when I try to login:
```
API: AssumeRoleWithLDAPIdentity()
Time: 19:58:12 UTC 11/10/2021
DeploymentID: 7dd57a49-584b-41ba-8a2d-0d4c72125044
RequestID: 16B647A5CD0E33C7
RemoteHost: 10.42.233.130
Host: teste-pool-0-0.teste-hl.minio.svc.cluster.local:9000
UserAgent: Go-http-client/1.1
Error: expecting a policy to be set for user `CN=My Full Name,OU=MyOU,OU=OtherOU,DC=mydomain,DC=com` or one of their groups: `CN=SomeGroupName,OU=SomeOU,DC=mydomain,DC=com,DC=br`,`CN=OtherGroupName,OU=SomeOU,DC=mydomain,DC=com,DC=br` - rejecting this request (*errors.errorString)
       3: cmd/sts-errors.go:58:cmd.writeSTSErrorResponse()
       2: cmd/sts-handlers.go:602:cmd.(*stsAPIHandlers).AssumeRoleWithLDAPIdentity()
       1: net/http/server.go:2046:http.HandlerFunc.ServeHTTP()

```

**Comment by harshavardhana** [comment]
> Error: expecting a policy to be set for user `CN=My Full Name,OU=MyOU,OU=OtherOU,DC=mydomain,DC=com` or one of their groups: `CN=SomeGroupName,OU=SomeOU,DC=mydomain,DC=com,DC=br`,`CN=OtherGroupName,OU=SomeOU,DC=mydomain,DC=com,DC=br` - rejecting this request (*errors.errorString)

You need to set a policy for either your group or userDN `mc admin policy set alias/ <policyName> group=groupDN`

**Comment by mfbrj** [comment]
How to setup a policy on Minio Operator UI when creating tenant? I tried to fill several combinations of data on UI such as `CN=SomeGroupName,OU=SomeOU,DC=mydomain,DC=com,DC=br,CN=OtherGroupName,OU=SomeOU,DC=mydomain,DC=com,DC=br` , none worked:
![image](https://user-images.githubusercontent.com/835834/151802196-210c09bf-fc48-4a5f-a3cf-40f80a62f3eb.png)

Moreover, is not possible to use `mc` after the tenant is created, since `mc` cannot authenticate.
