### ISSUE TITLE
Minio Operator 4.2.8 / Rancher RKE2 / k8s 1.21.3 - no CA for Minio server cert in cluster

### ISSUE THREAD

**Issue by aceeric** [minio/operator#860]
I believe this is a potential issue with Minio creating CSRs - at least in Rancher/RKE2. I've developed a work-around (please see second comment below this.)

In a Rancher RKE2 cluster, I'm standing up a Minio Tenant and trying to configure a Postgres server to back up to the Minio object store. In order for Postgres to do this - it needs the CA that issued the Minio server cert. Here are some details:

```
$ kubectl get svc
NAME   TYPE       CLUSTER-IP  INTERNAL-IP  PORT(S)
...
minio  ClusterIP  X.X.X.X     <none>       443/TCP
...

$ kubectl port-forward svc/minio 4443:443
Forwarding from 127.0.0.1:4443 -> 9000

$ openssl s_client -connect localhost:4443
CONNECTED(00000003)
...
Certificate chain
 0 s:/O=system:nodes/CN=system:node:*.storage-hl.postgres-minio.svc.cluster.local
   i:/CN=rke2-client-ca@1625272854
...
```
This shows that the issuer of the Minio cert is `rke2-client-ca@1625272854` - but - that cert is not available in cluster. I need that cert to configure Postgresql to negotiate TLS with Minio. I'm relying on Minio to generate it's own certs. Minio is coming up fine - all is good. But - postgres can't access Minio because the signing cert is not available in cluster.

Some more info:
```
$ kubectl describe tenant
...
Spec:
  Cert Config:
  Configuration:
    Name: storage-configuration
  Creds Secret:
    minio-creds
  Image: minio/minio:RELEASE.2021-09-15T04-54-25Z
  Users:
    Name: storage-user
...

$ kubectl -n minio-operator describe deploy | grep Image
    Image: minio-operator:v4.2.8
    Image: minio-console:v0.10.0

$ kubectl describe secret storage-user
Name: storage-user
Data
====
CONSOLE_ACCESS_KEY: 7 bytes
CONSOLE_SECRET_KEY: 40 bytes

$kubectl get secret storage-configuraiton -ojsonpath='{.data.config\.env}' | base64 -d
export MINIO_ROOT_USER=minio
export MINIO_ROOT_PASSWORD=.....
export MINIO_BROWSER=on

$ kubectl describe secret minio-creds
Name: storage-user
Data
====
accesskey: 5 bytes
secretkey: 40 bytes

$ kubectl get nodes
NAME  STATUS  ROLES   VERSION
...
foo   Ready   <none>  v1.21.3+rke2r1
...

$ kubectl describe csr storage-postgres-minio-csr
Name:             storage-postgres-minio-csr
Labels:           v1.min.io/tenant=storage
Annotations:      <none>
Requesting User:  system:serviceaccount:minio-operator:minio-operator
Signer:           kubernetes.io/legacy-unknown
Status:           Approved,Issued
Subject:
 Common Name:   system:node:*.storage-hl.postgres-minio.svc.cluster.local
 Serial Number:
 Organization:  system:nodes
Subject Alternative Names: 
  DNS Names: storage-ss-0-0.storage-hl.postgres-minio.svc.cluster.local
             minio.postgres-minio.svc.cluster.local
             minio.postgres-minio
             minio.postgres-minio.svc
             *.
             *.postgres-minio.svc.cluster.local
```

**Comment by harshavardhana** [comment]
> Developed work-around as follows:
> 
> After additional reading here: https://docs.min.io/minio/k8s/deployment/deploy-minio-operator.html#kubernetes-tls-certificate-api and here: https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/
> 
> ```
> $ kubectl -n kube-system get po/kube-controller-manager-CLUSTERNAME -oyaml | grep 'cluster-signing-legacy-unknown'
>     - --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/rke2/server/tls/client-ca.crt
>     - --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/rke2/server/tls/client-ca.key
> ```
> 
> Notice _client-ca.crt/.key_. Reconfigure RKE2 to use these arg values for `kube-controller-manager`:
> 
> ```
>     - --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/rke2/server/tls/server-ca.crt
>     - --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/rke2/server/tls/server-ca.key
> ```
> 
> And then - wherever a client workload needs to verify a Minio server cert, use the Kubernetes CA Cert that is projected into every namespace in the `kube-root-ca.crt` `ConfigMap` and everything works fine.
> 
> Questions for the Minio team:
> 
> 1. Is the use of `kubernetes.io/legacy-unknown` as the signer planned to be used for the foreseeable future? The Kubernetes docs indicate this is no longer allowed as of v1.
> 2. Your docs in the first link above indicate:
> 
> > The MinIO Operator therefore requires that the Kubernetes kube-controller-manager configuration include the following configuration settings:
> > --cluster-signing-key-file - Specify the PEM-encoded RSA or ECDSA private key used to sign cluster-scoped certificates.
> > --cluster-signing-cert-file - Specify the PEM-encoded x.509 Certificate Authority certificate used to issue cluster-scoped certificates.
> 
> It would appear this is not a _requirement_. Acording to the Kubernetes docs this disallows any more fine-grained signing args for the `kube-controller-manager`. Therefore, if it were required this would seem to remove some configuration flexibility. Maybe the docs should be updated?
> 
> Some clarification would be appreciated. Thanks.

CSR requires that kube-controller-manager have the necessary Master certs to generate new certs. I would say Rancher deployment is not correct here. 

k8s vanilla installation using kubeadm setups do not face this issue.
