### ISSUE TITLE
Unable to validate the session token

### ISSUE THREAD

**Issue by cedricve** [minio/operator#869]
I'm trying to access the dashboard while proxying the console. It works the first time, but now i'm getting token validation errors. Any thoughts?  I'm initiating the `init` command.

    
    kubectl minio init

And this is the output of the console pod

`I: 2021/10/12 07:55:38 Serving operator at http://[::]:9090
E: 2021/10/12 07:55:43 Refreshing subnet license failed: no license present
I: 2021/10/12 07:55:48 Unable to validate the session token AFF6RLsDMmYCEdzRgOijGngt3tHFja4zKq8dw1Jy4+AZ9/aaUQJ+TqnwXcG8YKAut7/wtdRQ06Xe/Ce/4EHTaPIVPZK+I3aXcdPXN3sHT26Vo8/6JGfYomny9KKxJXpRluh/muDcn8NUTJAAdqdI6PxJbTOnQVRKFfFAwzzcpVCsDwIaOqsviUdJdkl1RATR+DxJGs/C+7cFOs9YrhKnGttG1DIZ0dNBMRzj2VhgqmaFVII7QQ8ct5bBM5OSe/1Z98dG2SiN1WwamenZ8lhv0JDUVARHTjwH0TGbrnhbvJzDK7Qhk+FMdGlx3jEciTKSLYzAIqzg5K5RmzHzSeHt/aJFdF80GwHVCCwl3WMu5utnyjcN1SU9aZNy9DaqrP2an/0EDdp+QoxGwP3d7eGIgElo0jy4VX2KpgR0AXuvROsDQ/wxtI27jOLn3IewBf+yYJCop8IP3tHaUjUMtSxz/W4i9oB6SPigZGLjFlbSdBgw1cE2Lqnm37RDvGA6uu5IuY8i0cKpxFyyPI9GJS80q2DUkJUzDpe7BtefdLIkk6qsWGtQba79y2JyDvCSiDX/xRpnVsIcnoICJwGSI+mrq2Vom9WZ/J47ElSYFd8Gh4aVfV/w2WvCUJwiwixmaZlfyODvjG8EqMiwGBMvTqeEIsr4lwM/N8hRBk+Zmw9bEdzP03oALg0wU6UbafG9pkx+V/gaB9dbSYeJR4r2qC3wjreED46kxb8Notu4lsAc/G9IyCM4+dY3IrB91+tYmASeybXo24vKwWCdgrSEvalumb5iWp3Nwo03jMc8VBwMBcfNGdPuQkPie7EZ3a0ajzyMh8dzNjO7SxsSCBxWfY9PeO+hCW0MsX6CGW3JLP54RwUjm4F83SoTJso2Y6MlaJSDttiKr4RJesEOlRu1VXLid4u552lhSG7RLaKDMe6ZRE70lZar3pKtN1g59p+w2+V915PpUro4ssQbTr69oS9zeFd1wTy8QaHs83dxwJuS06n3VGhTybW2qQXHa3cDJmsTyxSdAkl/jW6OxFDUVSpFd4+On7FY4JyfyznPTg/Jjuv3yB+K+qVSEOrCv1BkR/sNJ9/tSrkNJBXNUvVV7i5Uk0cv2UztHvco0beRgs0DeDfDwe/I2VLQILLSzAVWPeH9N8tDmYf9VHsdrHKHM7AZrdB5Nj9DKTKzyUVBbDYaS+fcJ6elVGg2q91fHNxtTdXMHDJP12V2p+vLI/Ea/PKrTWvJ5lQjdYB1kHywU2ar6vrtlXzZ5RQpWanVqwsvP4oPhkSbSlOknFBtsGWDtYr6hl2qL96L3jjFVXGiddsqMHvZ0iOuVg==AHtJBz2nT8MpdVPOyF2PeMEsYSaaNvi0Q+tg2n2TsLJQId8cJd3XQzhOiKsjmiC0kTc3Ljz7xxGglRQypHWFVeNzaqFTv3vR5NmohSBRknfdPb5fbel7Jnm0/JzoeK0KuLQoOOL+NWhIasdAYHUVNGU3LvCzyT7LQMApLgSdbl7o4JE99CvdH4iFowAbH/JGu/U8t/Wvtb2ebvSgDPiCg2phTkRby4UalD+V0H6Fxo+eLoww7yhvaV9oXJlYE0uPJUHWRVn2jcaZ4DfJtLH6C3pcEAinLkOIevDUOUnlgs8R0IqAXwf/ow0SQ28F0NTfSCLdGMIZRa/pSQSU5IYfsnJrPzHfnjASjmtJH1EvANUlUPrkGZkv67PwgCe0o5dslCYzceEWgCwC+KWhMIbBOzGD+beBJtRUccyycLfbRyg8XE/WrasPWKusOZm5XMTcCUa37FsGuRFP5H130KalQEHI7dafDt/mGhL85xJqGf4hNP63nfXw0aw2Xpu0oeqbdPo6QmEEqg/18Mkpj6JxMY1jYeOtaJu2QRuX8zJBtZiHomoqcAJ6/aJeyRG/wxXCv5ItAn3ieDw3J74vnMhcJGw/XFZSc5KSlBw=: session token internal data is malformed
I: 2021/10/12 07:55:55 Unable to validate the session token AK00H9En7bjYszpPlrWpSpJz6nssMustWcKt0X5y/aAUyXAGVHxkH2vLszdG++HKgQ4srrBR6iDxOMuB6Ce+nybrL0mH0+sn9MPcQ4CbV53mCsPiyjJ+SY5fz3ZlSW6EvZbFuvoDGbC8gTa4qcoGulHlGsmjjgin0YXAwyPFAXlbgXVtGSr6+0kgeVHpPL9urPNhds1aYz9tJIq+Zv1hu1OYYUs9SMwj8o+f7X7lsf7ket7gaAm+jC+1vhrdnaAELEXORLdpEcaFWHSfMe7RzUOXtTx2kPScIsYEcoQpiXsLmpO8rPmOX3GREMfhga338aOmP9emtslxeUAm8T5dga2BtI39WrG7I9kTo+vjVTzeKZ/Gepoe0UWvQlxlg6vftta7ILkdWEweadJubMto/WMig5tyXqAeorjoiAPJ1iHaAbF7I8D3C7+hsSWATGSc9Hv1HMsmxF5U9qycsJ0Dcy57jTwD2+MHbekQvZGDSC26sLb533ZBYwIX7MPey7NIpBbrEe8MiLKZcQfCATZPout+uH9aPkbBN9PKJi1NKBI1KsTadWsBsCOzOXKCRTJBto50Dy4B05/V5tC6QBKU51EuVNR/lmADhvvvylIQBcoLQ2+SJnHF68TW6Lbqis5fee6LKWB1yJbEhhGdeSFecTQ1PefXR8B8qNoZNTN/iA8wWL8eyBkTPf0cz4ZRtyCk+ZZgAKeQ71DS89RADLKcfB6Hp23/O0+MhRDTztcoCZgoaLomQi92aOzEKzPUf1LT6f7MaDnZ/vWgSAcg8EYxcMN0LKbeJzx4ui+N+leJTMqPmPHmHkMpeUQgEGOLw6illfh1NZO7oGcXgS/cy/uaWAkiK77NBCsk69Fv6rR84QX5DdF6oK6R7ttFcDRzfy5wI90oRcRXOnhQma8BR1M40ShEd2QBtVTXCe9MAs0H6FuNtBBmG41ch+m5L7FzaLT9IT+FD35kHMNa7n3tBL6vLN602E/zzmz+LOpVzumq/xgNJdC2fvjUS4GHHKa5X9XV+5JJSwHG6TAi/XNrlsjxIDG5l5zIpnLovsihBKixjiAT/7OQmUpHiWPC6v22nZbJP1M+VnksIK2l1T6XkyOO8EvcyelUKA4KjbOdsoLpI0jje14N0wFS4VUcZZ+xCxxiYaPCfaoBot+OcSBg44cRTJaOt87DOHIEV7dOHUofFU5gesIUP0nDJ/rNBz2uo0ricuk9wLVwWOptTi1WBe45c6XZeWvD/xsVHCHSYxUDc+kXdlVO4+00npivucoyld7giL7hvfHwhcHdMcbUThLayNEdS36/EGCrdIhz3Say6mHFwB/3nw==AHtJBz2nT8MpdVPOyF2PeMEsYSaaNvi0Q+tg2n2TsLJQId8cJd3XQzhOiKsjmiC0kTc3Ljz7xxGglRQypHWFVeNzaqFTv3vR5NmohSBRknfdPb5fbel7Jnm0/JzoeK0KuLQoOOL+NWhIasdAYHUVNGU3LvCzyT7LQMApLgSdbl7o4JE99CvdH4iFowAbH/JGu/U8t/Wvtb2ebvSgDPiCg2phTkRby4UalD+V0H6Fxo+eLoww7yhvaV9oXJlYE0uPJUHWRVn2jcaZ4DfJtLH6C3pcEAinLkOIevDUOUnlgs8R0IqAXwf/ow0SQ28F0NTfSCLdGMIZRa/pSQSU5IYfsnJrPzHfnjASjmtJH1EvANUlUPrkGZkv67PwgCe0o5dslCYzceEWgCwC+KWhMIbBOzGD+beBJtRUccyycLfbRyg8XE/WrasPWKusOZm5XMTcCUa37FsGuRFP5H130KalQEHI7dafDt/mGhL85xJqGf4hNP63nfXw0aw2Xpu0oeqbdPo6QmEEqg/18Mkpj6JxMY1jYeOtaJu2QRuX8zJBtZiHomoqcAJ6/aJeyRG/wxXCv5ItAn3ieDw3J74vnMhcJGw/XFZSc5KSlBw=: session token internal data is malformed`

**Comment by dvaldivia** [comment]
I just found this bug as well about 30 minutes ago, I'm working on a fix, I'll keep you posted
