### ISSUE TITLE
Allow custom name for hardcoded operator service

### ISSUE THREAD

**Issue by RixTmobilender** [minio/operator#871]
**Is your feature request related to a problem? Please describe.**
I'm using a (custom) fullnameoverride for every resource in the minio-operator stack but I'm currently blocked on the operator service since [apparently the tenant pods have a hard-dependency on the operator service being named exactly "operator"](https://github.com/minio/operator/blob/31460bbbc4b7bd3f24ed41c73e9e5dfdc73eacf6/resources/base/service.yaml#L4)

Whenever I declare a tenant, the spawned pods immediately start looking for the un-configurable and inexistent "operator" service:
```
 dial tcp: lookup operator.local-prerequisites-head.svc.cluster.local on 1.1.1.1:1: no such host
```

**Describe the solution you'd like**
- Complete freedom on how to name the operator service
- configurable "operatorServiceName" input for tenants, similar to the existing behavior on [hoststemplates](https://github.com/minio/operator/blob/master/docs/custom-name-templates.md)

**Describe alternatives you've considered**
For now hardcoding the service name is no big deal since there's never more than 1 operator per namespace but it breaks convention and seems a bit unnecessary. Plus it blocks any serious development on the helm chart.

**Comment by harshavardhana** [comment]
> * Complete freedom on how to name the operator service

No this won't be allowed.  Thank you.
