### ISSUE TITLE
Error: Read failed. Insufficient number of disks online (*errors.errorString)

### ISSUE THREAD

**Issue by jaytring** [minio/operator#876]
When using MicroK8s (v1.21) on a 4xARM (Raspberry Pis) with 4xprovisioned storage (volumeBindingMode: WaitForFirstConsumer) and MinIO Operator (v4.2.13, v4.2.10 and v4.2.1) the minio cluster is created however all pool POD's log Error: Read failed. Insufficient number of disks online (*errors.errorString) and Unable to read 'format.json' from https://*****.svc.cluster.local:9000/export: file access denied.

## Expected Behavior
Would expect the local-stroage ext4 mount to be available to the minio-pool-0-* POD and the disks to be initialized.

## Current Behavior
It appears the mount is not bound "correctly" to the pod, SSH onto the POD and ls -l /data (which I think is where the mount point should be),  no permissions to create a file "touch: cannot touch 'abc.a': Permission denied". Confirming that the underlying mount point on each node is accessible, the permissions are VERY open (test system):

drwxrwsrwx  3 root                ubuntu 4096 Oct 17 03:41 minio
drwxrwsrwx  3 ubuntu           ubuntu 4096 Oct  4 02:45  miniologs

Sample PV used (x4 for each node, and are bound to the POD succesfully)

apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-minio-pv1
  namespace: storage-minio
spec:
  capacity:
    storage: 256Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/media/ssd/minio"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: local/ssd
          operator: In
          values:
          - "true"

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)

1. Create "storage-minio" namesapce
2. [On Node] wget https://github.com/minio/operator/releases/download/v4.2.10/kubectl-minio_4.2.13_linux_arm64 -O kubectl-minio
3. [On Node] chmod +x kubectl-minio
4. [On Node] mv kubectl-minio /usr/local/bin/
5. [On Node] kubectl minio delete
6. [On Node] kubectl minio init
7. [On Node] kubectl minio proxy -n minio-operator
8. Navigate to http://ip:9090/login pasting JWT token
9. Create new tenant: Name=test, Namespace=storage-minio, class=local-storage (Standard Storage Class with volumeBindingMode: WaitForFirstConsumer defined)
10. Set total size to be 4xstorage capacity of PV (1024)
11. Click Create.
12. The MinIO cluster will create, all pod's will come online and appear to be functioning, however logs on all 4 storage pods will state 

## Regression
 No

## Your Environment

* Version used (`minio-operator`): v4.2.13, v4.2.10 and v4.2.1
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes v1.21.5 (Microk8s)
* Server type and version: Raspberry PI ARM
* Operating System and version (`uname -a`): Ubuntu Core 20.04.3 LTS /  Linux ubuntu 5.4.0-88-generic
* Link to your deployment file:

**Comment by laggage** [comment]
Got the same error too...

**Comment by harshavardhana** [comment]
> ```shell
> ^CExiting on signal: INTERRUPT
> Unable to read 'format.json' from /export1: file access denied
> 
> Unable to read 'format.json' from /export2: file access denied
> 
> Unable to read 'format.json' from /export3: file access denie
> ```

Fix your security context @jaytring

**Comment by dvaldivia** [comment]
This is because the data in the PVC used to be owned by the root user, in v4.2.3 we changed the default behavior but added a migration, this will apply automatically if you upgrade the operator along with its CRD

**Comment by harshavardhana** [comment]
> This is because the data in the PVC used to be owned by the root user, in v4.2.3 we changed the default behavior but added a migration, this will apply automatically if you upgrade the operator along with its CRD

This is non-actionable issue as its expected to have this securityContext change.
