### ISSUE TITLE
Clarification for CSR and operator-used certificate with certificate rotation

### ISSUE THREAD

**Issue by balpert89** [minio/operator#888]
## Expected Behavior

The operator creates a CSR and stores the certificate & private key in a secret named `operator-tls` in the same namespace as the operator is located. When a `tenant` is created, the certificate will be also stored in a secret named `operator-tls` in the target namespace.

The certificate is valid for 30 days. Shortly before expiration the operator should rotate the certificate, update secrets and rolling restart the minIO pods.

## Current Behavior

The certificate expires, the kube-apiserver can no longer use the webhook endpoint and the minIO pods cannot callback to the operator pod.

## Steps to Reproduce (for bugs)

1. deploy minio-operator
2. create a tenant 
3. inspect the public.crt certificate in secret `operator-tls` in the operator namespace
4. wait for the timeframe until its expired
5. carnage

## Context

As mentioned, the certificates created with a CSR only have a limited TTL and there is no rotation for it.

## Proposed solution
Either have a rotation mechanism or provide the possibility for bring your own certificates. Just creating a secret before deploying the operator is no real solution.

## Your Environment

* Version used (`minio-operator`): 4.2.10
* Environment name and version (e.g. kubernetes v1.17.2): k8s 1.21.3, openshift 4.8.13
* Server type and version: ?

**Comment by stobias123** [comment]
I've been troubleshooting why my tenant blew up and this is the reason. seeing errors with webhook from tenant pods.

**Comment by dvaldivia** [comment]
We recently merged a PR to automatically rotate certificates generated by the operator, I think v4.3.2 includes this behavior, can you try with this version of the operator and let me know if it's rotating as expected

**Comment by stobias123** [comment]
@dvaldivia  - thnx for the info. I updated from 4,3,1 to 4.3.2 and this did not fix certificates. I ended up deleting the entire operator and re-installing.

**Comment by balpert89** [comment]
@dvaldivia PR https://github.com/minio/operator/pull/872 has not been included in v4.3.2, will this arrive in the next version? When can this be expected?

**Comment by stobias123** [comment]
any update on this? this seems like a major dealbreaker im shocked it's not getting more attention. my tenants just tip over :(

**Comment by dvaldivia** [comment]
how did you updated @stobias123 ? @anjalshireesh anyway we can corroborate the certificates will get rotated upon upgrade?

**Comment by anjalshireesh** [comment]
@dvaldivia I'm not sure if the cert rotation will be triggered on upgrade. It might be easier to fix the certs first and then upgrade to 4.3.3. After this, subsequent renewal of the certs should happen automatically.

**Comment by dvaldivia** [comment]
@stobias123 try deleting the CSR and TLS secret that the operator generated for the tenant, the operator should re-issue the certificates for the tenant, test this on an empty tenant before disrupting your main tenant

**Comment by mshanmu** [comment]
@dvaldivia / @anjalshireesh , I am confused with the linkage between MINIO_OPERATOR_TLS_ENABLE and tenant.requestAutoCert here.

When MINIO_OPERATOR_TLS_ENABLE is enabled, operator and tenants pods communicate in TLS.

When requestAutoCert is set to true, it acts as CA and makes the tenant ClusterIP service to be TLS enabled. 

With MINIO_OPERATOR_TLS_ENABLE=on and requestAutoCert=false -> enables TLS between operator and tenant pods, creates certificate with 1 year validity and pushes them to operator and tenant secrets. But, it will **not** automatically renew the certificates, is that correct?

If the above the statement is correct, Should not minio operator automatically renew certificates when MINIO_OPERATOR_TLS_ENABLE=on regardless of the requestAutoCert value?

**Comment by anjalshireesh** [comment]
> With MINIO_OPERATOR_TLS_ENABLE=on and requestAutoCert=false -> enables TLS between operator and tenant pods, creates certificate with 1 year validity and pushes them to operator and tenant secrets. But, it will **not** automatically renew the certificates, is that correct?

When `requestAutoCert=false`, operator doesn't create or renew the certificate. Setting `MINIO_OPERATOR_TLS_ENABLE=on` and `requestAutoCert=false` means that you want to take care of certificate creation/renewal on your own and don't want operator do do it automatically. In such cases, the certificate should be configured using the `externalCertSecret` field.

Refer for more details on configuring TLS: https://github.com/minio/operator/blob/master/docs/tls.md

**Comment by mshanmu** [comment]
> > With MINIO_OPERATOR_TLS_ENABLE=on and requestAutoCert=false -> enables TLS between operator and tenant pods, creates certificate with 1 year validity and pushes them to operator and tenant secrets. But, it will **not** automatically renew the certificates, is that correct?
> 
> When `requestAutoCert=false`, operator doesn't create or renew the certificate. Setting `MINIO_OPERATOR_TLS_ENABLE=on` and `requestAutoCert=false` means that you want to take care of certificate creation/renewal on your own and don't want operator do do it automatically. In such cases, the certificate should be configured using the `externalCertSecret` field.
> 
> Refer for more details on configuring TLS: https://github.com/minio/operator/blob/master/docs/tls.md

@anjalshireesh , When `MINIO_OPERATOR_TLS_ENABLE=on` and `requestAutoCert=false`, operator pod does automatically create a `operator-tls` secret in both operator and tenant namespaces with a certificate & key. See below,

`$ k -n <operator namespace> get secret operator-tls -o yaml
apiVersion: v1
data:
  private.key: <key>
  public.crt: <certificate>
$ k -n minio-tenant-1 get secret operator-tls -o yaml
apiVersion: v1
data:
  public.crt: <certificate>
`
This certificate has a validity of 1 year, see below,

`$ k -n <tenant namespace> get secret operator-tls -o jsonpath='{.data.public\.crt}' | base64 -d | openssl x509 -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            dc:ab:b4:09:4a:b6:21:c8:52:9d:1e:dd:59:5c:4b:65
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=kubernetes
        Validity
            Not Before: Dec 28 16:03:12 2021 GMT
            Not After : Dec 28 16:03:12 2022 GMT
        Subject: O=system:nodes, CN=system:node:operator.minio-operator.svc
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:24:52:66:c2:2e:90:12:e3:21:8c:d0:79:1f:87:
                    3c:fc:63:c2:f6:28:f8:ce:4d:b0:e9:9e:4e:b6:11:
                    0e:39:08:3f:ad:6b:d7:bf:55:8d:6b:74:6a:10:4c:
                    95:60:44:5e:60:54:87:0d:12:54:31:fc:c8:2c:f4:
                    4f:98:7c:60:89
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Alternative Name: 
                DNS:operator, DNS:operator.minio-operator.svc, DNS:operator.minio-operator.svc.cluster.local
   $ 
`
So, coming to the questions, 

1. As you can see, even when `requestAutoCert=false`, operator does create the `operator-tls` secret with certificates. So, will the operator handle automatic renewal for the `operator-tls` secret certificate? Most probably not, IIUC, this issue is created specifically to handle this scenario. Is that correct?
2. What is the manual workaround to force a renewal of `operator-tls` secret certificate?

**Comment by Alevsk** [comment]
@mshanmu `MINIO_OPERATOR_TLS_ENABLE=on` control whether the minio-operator pod will run with TLS or not, it doesnt have anything to do with `tenant.spec.requestAutoCert`.

When operator is deployed with TLS enabled an `operator-tls` secret, containing a public and a private key, will get generated in the `minio-operator` namespace and will be used by the operator, additionally, only the public key will be copied to the new tenant namepace (secret name is `operator-tls` as well but contains only the public key), this is used to verify the TLS connection when the minio tenant pods talks to the operator pod.

if you set `tenant.spec.requestAutoCert=true`, a new keypair will be generated for for the tenant, but this is a completely separated set of keys that are not related to operator.

**Comment by mshanmu** [comment]
@Alevsk , Thanks for the explanation !! 

This comment https://github.com/minio/operator/issues/888#issuecomment-955842715 seems to imply, `operator-tls` secret certificates will be automatically renewed by setting `tenant.spec.requestAutoCert = true`.  That was my source of confusion.

Now, it is clear to me that `operator-tls` secret certificates will **not** be automatically renewed. What is the manual procedure to safely force a renewal?

**Comment by Alevsk** [comment]
@mshanmu we are planning to automate this in the future, in the meantime you can:

1. Delete any existing csr
2. Delete the `operator-tls` secret in the `minio-operator` namespace
3. Restart the operator so the certificate gets regenerated
4. Copy only the new public key to the `operator-tls` secret for each existing tenant

**Comment by haslersn** [comment]
This is not fixed, yet.

**Comment by davidkarlsen** [comment]
Com on bot - unmark it.

**Comment by obockows** [comment]
Red Hat's customers experience the problem on OpenShift. 
`ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://$VARIABLE1:[@VARIABLE2t@operator.openshift-operators.svc.cluster.local](mailto:$VARIABLE@operator.openshift-operators.svc.cluster.local):4222/webhook/v1/getenv/kg-dms-prod/minio-dms: Get "https://operator.openshift-operators.svc.cluster.local:4222/webhook/v1/getenv/kg-dms-prod/minio-dms?key=MINIO_ARGS": x509: certificate has expired or is not yet valid: current time 2022-08-26T09:48:47Z is after 2022-08-24T13:10:38Z`
So we have in the error message also  webhook/v1, so it is likely that the operator doesn't have proper logic. It looks like kubeapiserver invokes webhook what means it invokes minio, takes a cert and realizes it is expired. I believe minio should request rotation. 
Another interesting factor is that Pod runs with expired certs untill it is restarted.

**Comment by harshavardhana** [comment]
Fixed as per

```
commit ec4e74c54e22b47255219924e4553b2bf5cc876d
Author: Lenin Alevski <alevsk.8772@gmail.com>
Date:   Wed Aug 24 18:23:30 2022 -0700

    Rotate Operator TLS certificate in-memory (#1251)
    
    - certNeedsRenewal didn't support kubernetes.io/tls,
      cert-manager.io/v1alpha2 or cert-manager.io/v1 secrets
    - Rotate operator certificate if is expired and refresh it in-memory
    
    Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>
```
