### ISSUE TITLE
No metrics are available when the tenant name is too long

### ISSUE THREAD

**Issue by shapirus** [minio/operator#895]
## Expected Behavior
If the tenant name is too long, minio-operator should not allow it and enforce a safe limit on its name. Otherwise, the prometheus statefulset cannot start its pod.

## Current Behavior
And here's why the pod cannot be created, assuming the name of the tenant is `minio-1234567-123456-12345-production`:

```
create Pod minio-1234567-123456-12345-production-prometheus-0 in StatefulSet minio-1234567-123456-12345-production-prometheus failed error: Pod "minio-1234567-123456-12345-production-prometheus-0" is invalid: [spec.volumes[1].name: Invalid value: "minio-1234567-123456-12345-production-prometheus-config-volmount": must be no more than 63 characters,
```

## Possible Solution
Do not allow tenant names longer than `63 - strlen("-prometheus-config-volmount")`

**Comment by shapirus** [comment]
@dvaldivia I'm afraid your fix will not work as it is. We should limit NOT only the tenant name to 63 characters, but the concatenated string of `tenant_name` + `"-prometheus-config-volmount"`, because the pod creation failed on the _volume_ name being too long. If some derived resources can have even longer names, then they should be accounted for, too.

**Comment by shapirus** [comment]
In other words, if this volume's name is the longest name of all child tenant's resources, then the tenant name has to be limited to `63 - strlen("-prometheus-config-volmount")` = 63 - 27 = 36 characters.

**Comment by shapirus** [comment]
mentioning @harshavardhana too.

**Comment by shapirus** [comment]
@dvaldivia please consider reopening this issue. Or is it better to open a new one?

**Comment by harshavardhana** [comment]
> @dvaldivia please consider reopening this issue. Or is it better to open a new one?

@shapirus I don't think it makes sense - we cannot arbitrarily limit the tenant name to 36 characters. whatever we are validating is fine for now. 

There is sufficient enough validation for now.

**Comment by dvaldivia** [comment]
@harshavardhana @shapirus perhaps we can limit the tenant name to 60 characters and use at least 3 characters for child resources, so "tenant_name"+"pcv" would work

**Comment by harshavardhana** [comment]
> @harshavardhana @shapirus perhaps we can limit the tenant name to 60 characters and use at least 3 characters for child resources, so "tenant_name"+"pcv" would work

We can do that @dvaldivia but this restriction is only during `create` - also only our kubectl plugin can do this validation. 

Anyone using `kustomize` will see this error later.

**Comment by shapirus** [comment]
The problem about this is that the error can be quite difficult to debug. I had to describe pods, describe volumes etc., otherwise it wasn't clear why the pod was staying in a Pending state indefinitely.
Reducing the child resources name suffixes is a good idea that will allow to create tenants with longer names, but still minio-operator should take the maximum possible resource name into account.
