### ISSUE TITLE
ERROR Unable to initialize disk caching: mkdir /optane1: permission denied

### ISSUE THREAD

**Issue by hsabbi** [minio/operator#899]
I am having problems with the new version of minio operator 4.3.3.
Kubernetes version 1.21 with TKG.

Expected Behavior:
Updated from the previous version.
Successful update, all pods online. Tenants State: Initialized.

Current Behavior:
The update of one of the tenants with buckets and information failed., pods tenant-1-pool-0-0 CrashLoopBackOff or error.
The other tenant, without buckets and information was updated successful.

API: SYSTEM()
Time: 21:00:11 UTC 11/09/2021
DeploymentID: 1deb9275-5c3b-4605-90de-d9081cd77c74
Error: mkdir /optane1: permission denied (*fs.PathError)
drive=/optane1
5: cmd/format-disk-cache.go:138:cmd.initFormatCache()
4: cmd/format-disk-cache.go:334:cmd.loadAndValidateCacheFormat()
3: cmd/disk-cache.go:570:cmd.newCache()
2: cmd/disk-cache.go:757:cmd.newServerCacheObjects()
1: cmd/server-main.go:589:cmd.serverMain()
ERROR Unable to initialize disk caching: mkdir /optane1: permission denied

Possible Solution:
I have no idea.

Steps to Reproduce (for bugs):
In a TKG cluster with kubernetes 1.21 mount minio-operator, create 2 tenants. One tenant to create a bucket and upload information, the other tenant to leave it by default without buckets created. Then upgrade to version 4.3.3.

Context:
Kubernetes 1.21
vmware TKG 1.4.

What is the solution for this??

## Regression
No

## Your Environment
TKG 1.4 
Kubernetes 1.21

**Comment by harshavardhana** [comment]
@hsabbi make sure your `/optane1` is writable by MinIO i.e it has correct permissions such as securityContext is defined in your tenant yaml. 


> API: SYSTEM()
> Time: 21:00:11 UTC 11/09/2021
> DeploymentID: 1deb9275-5c3b-4605-90de-d9081cd77c74
> Error: mkdir /optane1: permission denied (*fs.PathError)
> drive=/optane1
> 5: cmd/format-disk-cache.go:138:cmd.initFormatCache()
> 4: cmd/format-disk-cache.go:334:cmd.loadAndValidateCacheFormat()
> 3: cmd/disk-cache.go:570:cmd.newCache()
> 2: cmd/disk-cache.go:757:cmd.newServerCacheObjects()
> 1: cmd/server-main.go:589:cmd.serverMain()
> ERROR Unable to initialize disk caching: mkdir /optane1: permission denied

Also using disk caching with distributed setup will not give you any performance benefits, unfortunately.  Disk caching is designed to be used with share nothing NAS gateway or other Cloud gateway's.
