### ISSUE TITLE
Unable to validate passed arguments in MINIO_ARGS

### ISSUE THREAD

**Issue by AdheipSingh** [minio/operator#904]
- getting the following issues while i try to create tenant. I have faced this issue from console as well as manually creating the tenant using the kubectl minio plugin.

## Steps to Reproduce (for bugs)
1. ``` kubectl minio tenant create tenant1 --servers 4 --volumes 4 --capacity 100Gi --namespace t1 --storage-class local-storage```
2.  for a few minutes, describe po shows the following error ``` MountVolume.SetUp failed for volume "tenant1-tls" : secret "tenant1-tls" not found```
3. once pod gets into running state, it keeps on crashing with following error 
```
ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://VPtReOVfLg:uBWUJddy2hkeaVx07M2c51x@operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/t1/tenant1: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/t1/tenant1?key=MINIO_ARGS": context deadline exceeded
```

## Your Environment

* Version used (`minio-operator`): 4.3.5
* Environment name and version (e.g. kubernetes v1.17.2): 1.22.3
* Kubectl minio plugin: 4.3.3
* Operating System and version (`uname -a`): centos 7
* Link to your deployment file:

**Comment by harshavardhana** [comment]
> ```
> ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://VPtReOVfLg:uBWUJddy2hkeaVx07M2c51x@operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/t1/tenant1: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/t1/tenant1?key=MINIO_ARGS": context deadline exceeded
> ```

Looks like your operator webhook service is not online.

**Comment by harshavardhana** [comment]
Make sure your pods don't have network policies that can block network access to operator pods. 

> * Environment name and version (e.g. kubernetes v1.17.2): 1.22.3

Get into a pod on the tenant namespace and perform 

```
~ curl -k https://operator.minio-operator.svc.cluster.local:4222
```

**Comment by AdheipSingh** [comment]
@harshavardhana 

Thanks for your reply.

No network policies are present.

When i curl  i get this response 
```
curl -k https://operator.minio-operator.svc.cluster.local:4222
404 page not found
```

**Comment by owenthereal** [comment]
I got the same error. This is the log for the operator if that helps:

```
E1123 01:23:52.820658       1 upgrades.go:131] Error deleting operator webhook secret, manual deletion is needed: secrets "operator-webhook-secret" not found
I1123 01:23:52.828629       1 upgrades.go:84] Upgrading v4.2.4
I1123 01:23:52.834178       1 status.go:217] Hit conflict issue, getting latest version of tenant to update version
I1123 01:23:52.843323       1 upgrades.go:84] Upgrading v4.2.8
I1123 01:23:52.857411       1 status.go:217] Hit conflict issue, getting latest version of tenant to update version
I1123 01:23:52.869225       1 upgrades.go:84] Upgrading v4.2.9
I1123 01:23:52.874191       1 status.go:217] Hit conflict issue, getting latest version of tenant to update version
I1123 01:23:53.217200       1 upgrades.go:84] Upgrading v4.3.0
I1123 01:23:53.220341       1 upgrades.go:294] minio1 has no log secret
I1123 01:23:53.413368       1 status.go:217] Hit conflict issue, getting latest version of tenant to update version
I1123 01:23:54.014807       1 status.go:155] Hit conflict issue, getting latest version of tenant
I1123 01:23:54.815942       1 status.go:54] Hit conflict issue, getting latest version of tenant
I1123 01:23:55.415546       1 status.go:54] Hit conflict issue, getting latest version of tenant
I1123 01:23:56.416954       1 main-controller.go:848] 'minio-test/minio1': Deploying pool ss-0
I1123 01:23:57.812611       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:23:58.012796       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:23:59.679252       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:23:59.697691       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:24:03.616632       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:24:04.646891       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:24:06.698796       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:24:08.403436       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:24:09.399983       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:24:24.168118       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:24:35.532026       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:24:52.767731       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:24:53.811349       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:25:07.526653       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:25:19.274383       1 main-controller.go:964] 'minio-test/minio1' Error waiting for pool to be ready: Get "http://minio1-ss-0-0.minio1-hl.minio-test.svc.minio.minio-test.svc.cluster.local:9000/minio/admin/v3/info": dial tcp: lookup minio1-ss-0-0.minio1-hl.minio-test.svc.minio.minio-test.svc.cluster.local on 10.96.0.10:53: no such host
E1123 01:25:19.274527       1 main-controller.go:577] error syncing 'minio-test/minio1': Waiting for all pools to initialize
I1123 01:25:19.300165       1 main-controller.go:823] minio-test/minio1 Detected we are adding a new pool
I1123 01:25:39.828262       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:25:40.899663       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
I1123 01:25:55.531050       1 monitoring.go:109] 'minio-test/minio1' no pool is initialized
```

**Comment by AdheipSingh** [comment]
i am able to get running by switching off tls at operator and minio, in the operator deployment and minio tenant CR

**Comment by iyezhou** [comment]
@AdheipSingh how to switch off tls at operator and minio

**Comment by romqn1999** [comment]
> curl -k https://operator.minio-operator.svc.cluster.local:4222

I got the same error. I created a tenant with 4 nodes, and only 1 node is `Running` remain 3 nodes are `CrashLoopBackOff`
```sh
~ kubectl get all --namespace minio-tenant-1                                                                                                                   1 ↵
NAME                          READY   STATUS             RESTARTS        AGE
pod/minio-tenant-1-pool-0-0   0/1     CrashLoopBackOff   7 (3m16s ago)   14m
pod/minio-tenant-1-pool-0-1   1/1     Running            0               14m
pod/minio-tenant-1-pool-0-2   0/1     CrashLoopBackOff   7 (3m3s ago)    14m
pod/minio-tenant-1-pool-0-3   0/1     CrashLoopBackOff   7 (3m1s ago)    14m

NAME                             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/minio                    LoadBalancer   10.108.55.192    <pending>     443:30362/TCP    14m
service/minio-tenant-1-console   LoadBalancer   10.100.195.121   <pending>     9443:31017/TCP   14m
service/minio-tenant-1-hl        ClusterIP      None             <none>        9000/TCP         14m

NAME                                     READY   AGE
statefulset.apps/minio-tenant-1-pool-0   1/4     14m
```
And I can only get into the running pod on the tenant to run curl, I'm unable to run exec on error pods:
```sh
~ kubectl exec -i -t pod/minio-tenant-1-pool-0-1 -n minio-tenant-1 -- curl -k https://operator.minio-operator.svc.cluster.local:4222
404 page not found
```

**Comment by AdheipSingh** [comment]
@iyezhou @romqn1999 

in your deployment of minio-operator add this
```
- env:
        - name: MINIO_OPERATOR_TLS_ENABLE
          value: "off"

```

in your CR ie ```kubectl get tenant -n minio```
turn of 
```
    requestAutoCert: false
```

**Comment by AdheipSingh** [comment]
im pretty sure TLS works for minio, i haven't experimented with different versions though.
the last time i checked was when using the kubectl plugin to spin up cluster it uses an old version of minio image and some compatibility happened b/w operator image and minio image. ( assuming ) :)

**Comment by romqn1999** [comment]
> @iyezhou @romqn1999
> 
> in your deployment of minio-operator add this
> 
> ```
> - env:
>         - name: MINIO_OPERATOR_TLS_ENABLE
>           value: "off"
> ```
> 
> in your CR ie `kubectl get tenant -n minio` turn of
> 
> ```
>     requestAutoCert: false
> ```

I have turn off TLS as you suggest and the error has gone but I got other error:
```
~ kubectl logs -n minio-tenant-1 pod/minio-tenant-1-pool-0-0
...

API: SYSTEM()
Time: 04:28:19 UTC 12/06/2021
Error: Marking http://minio-tenant-1-pool-0-1.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local:9000/minio/storage/export/v42 temporary offline; caused by Post "http://minio-tenant-1-pool-0-1.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local:9000/minio/storage/export/v42/readall?disk-id=&file-path=format.json&volume=.minio.sys": dial tcp 172.17.0.6:9000: connect: no route to host (*fmt.wrapError)
       6: internal/rest/client.go:149:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
Waiting for all other servers to be online to format the disks.
```
Above error is same for 3 pods `pod/minio-tenant-1-pool-0-0`, `pod/minio-tenant-1-pool-0-2`, `pod/minio-tenant-1-pool-0-3`. And the log of `pod/minio-tenant-1-pool-0-1`:
```
~ kubectl logs -n minio-tenant-1 pod/minio-tenant-1-pool-0-1
...
API: SYSTEM()
Time: 04:06:13 UTC 12/06/2021
Error: Marking http://minio-tenant-1-pool-0-3.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local:9000/minio/storage/export/v42 temporary offline; caused by Post "http://minio-tenant-1-pool-0-3.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local:9000/minio/storage/export/v42/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio-tenant-1-pool-0-3.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local on 10.96.0.10:53: no such host (*fmt.wrapError)
6: internal/rest/client.go:149:rest.(*Client).Call()
5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
Waiting for the first server to format the disks.
```
I have used [kubernetes's dnsutils example pod](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#create-a-simple-pod-to-use-as-a-test-environment) to test dns service and it work fine:
```
~ kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
~ kubectl exec -i -t dnsutils -- nslookup minio-tenant-1-pool-0-1.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   minio-tenant-1-pool-0-1.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local
Address: 172.17.0.6

~ kubectl exec -i -t dnsutils -- nslookup minio-tenant-1-pool-0-3.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   minio-tenant-1-pool-0-3.minio-tenant-1-hl.minio-tenant-1.svc.cluster.local
Address: 10.244.2.49

```

**Comment by Alevsk** [comment]
@romqn1999 I have seen issues with `kube-dns` in the past, is so unreliably, please exec into each one of your `minio` pods and run a `ping` or `curl` command to all other peer domains, you need to be able to resolve all other hostnames from inside the pod otherwise the cluster cannot achieve quorum and minio will not start.

**Comment by nicelogic** [comment]
i have the same error
2022-01-02T06:41:46.411231805Z  ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://u1hebaTS4P0ZS04FaHef:5G14l3BgaOkoBCyeVLolW8h6TdyUHGedIKXKKJbr@operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-base/minio-base-tenant-1: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-base/minio-base-tenant-1?key=MINIO_ARGS": context deadline exceeded

minio version: v4.3.8.

**Comment by harshavardhana** [comment]
> ```
> ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://VPtReOVfLg:uBWUJddy2hkeaVx07M2c51x@operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/t1/tenant1: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/t1/tenant1?key=MINIO_ARGS": context deadline exceeded
> ```

We increased the DNS resolution timeout > 6secs from 1secs - this should fix this issue if DNS resolution fails. 

> [ERROR] plugin/errors: 2 dl.min.io. A: read udp 172.16.1.6:56249->183.60.82.98:53: i/o timeout

This is your DNS issue @nicelogic - your local DNS is broken.

**Comment by snehalyeole92** [comment]
Hi @harshavardhana Can you point out where can we change this DNS resolution timeout?
I am also facing the local DNS issue

[ERROR] plugin/errors: 2 minio.minio-tenant.svc.cluster.local.mip.storage.hpecorp.net. AAAA: read udp 10.1.26.228:57164->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 minio.minio-tenant.svc.cluster.local.mip.storage.hpecorp.net. A: read udp 10.1.26.228:51154->8.8.8.8:53: i/o timeout

**Comment by harshavardhana** [comment]
> ERROR] plugin/errors: 2 minio.minio-tenant.svc.cluster.local.mip.storage.hpecorp.net. AAAA: read udp 10.1.26.228:57164->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 minio.minio-tenant.svc.cluster.local.mip.storage.hpecorp.net. A: read udp 10.1.26.228:51154->8.8.8.8:53: i/o timeout

You have to ask your k8s vendor looks like they are HPE @snehalyeole92
