### ISSUE TITLE
Operator errors - Tenant not healthy on EKS

### ISSUE THREAD

**Issue by Bhagi33** [minio/operator#905]
Hi Team,
Deployed Minio operator in EKS.
I am observing errors in Operator logs . Minio Tenant also throwing erros. I am attaching the Logs.

$ kubectl get csr minio-cluster1-minio-csr -n miop
NAME                       AGE    SIGNERNAME                     REQUESTOR                                   CONDITION
minio-minio-csr   100s   kubernetes.io/legacy-unknown   system:serviceaccount:miop:minio-operator   Approved,Issued
$ kubectl get csr minio-cluster1-minio-csr -n minio
NAME                       AGE    SIGNERNAME                     REQUESTOR                                   CONDITION
minio-minio-csr   106s   kubernetes.io/legacy-unknown   system:serviceaccount:miop:minio-operator   Approved,Issued

Tenant logs
###############################
API: SYSTEM()
Time: 05:27:25 UTC 11/23/2021
Error: Marking https://minio1-pool-0-0.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export3/data/v41 temporary offline; caused by Post "https://minio1-pool-0-0.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export3/data/v41/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio1-pool-0-0.minio1-hl.minio.svc.cluster.local on 172.20.0.10:53: no such host (*fmt.wrapError)
       6: internal/rest/client.go:149:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
###########################################
[tenant logs.txt](https://github.com/minio/operator/files/7580538/tenant.logs.txt)
[operator logs.txt](https://github.com/minio/operator/files/7580540/operator.logs.txt)

**Comment by Bhagi33** [comment]
Please respond this

**Comment by harshavardhana** [comment]
> Error: Marking https://minio1-pool-0-0.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export3/data/v41 temporary offline; caused by Post "https://minio1-pool-0-0.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export3/data/v41/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio1-pool-0-0.minio1-hl.minio.svc.cluster.local on 172.20.0.10:53: no such host (*fmt.wrapError)

DNS issue.
