### ISSUE TITLE
Vanilla helm chart

### ISSUE THREAD

**Issue by rbren** [minio/operator#907]
**Is your feature request related to a problem? Please describe.**
I ship an application that needs a Minio instance alongside it to function. Historically we did this by simply adding
the [Minio chart](https://github.com/minio/charts/tree/master/minio) as a dependency - that made it really easy.

Now we'd need to install the entire _operator_ as well as include the CRD in order to ship our application to our users.
That incurs extra expense and complexity.

**Describe the solution you'd like**
I'd love to see the original helm chart supported in addition to the Operator. This is a pattern established by Prometheus,
which supports both an Operator, as well as a [vanilla helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts)

**Describe alternatives you've considered**
* Continue using the deprecated chart, maybe fork it?
* Our customers eat the cost/complexity of having the operator installed

**Comment by harshavardhana** [comment]
> **Describe the solution you'd like**
> I'd love to see the original helm chart supported in addition to the Operator. This is a pattern established by Prometheus,
> which supports both an Operator, as well as a [vanilla helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts)

Vanilla helm chart is available here

```
helm repo add minio https://charts.min.io/
```

https://github.com/minio/minio/tree/master/helm/minio

**Comment by rbren** [comment]
Perfect, thanks!
