### ISSUE TITLE
Cant create tenant

### ISSUE THREAD

**Issue by Tony-The-Developer** [minio/operator#912]
Hello when I try to create a tenant it creates but no PVCs get created only secrets. 
The CSR is approved. Works on my local machine. But not on our RKE cluster. 
![image](https://user-images.githubusercontent.com/68414482/143981156-cb8f80c1-57be-4ba4-8a38-83d04a4f3489.png)

**Comment by dvaldivia** [comment]
no `state` means the Operator is not acting on the Tenant CRD. Are your operator Pods running? can you post the logs

**Comment by Tony-The-Developer** [comment]
There are no pods created nothing. But the operator is running and healthy.

**Comment by dvaldivia** [comment]
can you share the logs of the operator pod please, also the version that you are using

**Comment by Tony-The-Developer** [comment]
![image](https://user-images.githubusercontent.com/68414482/144160099-77efa420-a80d-4a27-922e-ee3829eb0feb.png)
Thousands of this.

**Comment by Tony-The-Developer** [comment]
Hello, are there any updates on this issue?

**Comment by ryanatkinson** [comment]
Is there a solution to this?  Maybe a mis-configuration?  I am seeing exactly the same thing and really would like to get this working.

**Comment by harshavardhana** [comment]
We are supposed to get the correct k8s version from the underlying distribution 

```
var kubeAPIServerVersion *version.Info
var useCertificatesV1API bool

func (c *Controller) getKubeAPIServerVersion() {
        var err error
        kubeAPIServerVersion, err = c.kubeClientSet.Discovery().ServerVersion()
        if err != nil {
                panic(err)
        }
        useCertificatesV1API = versionCompare(kubeAPIServerVersion.String(), "v1.22.0") >= 0
}
```

```
// ServerVersion retrieves and parses the server's version (git version).
func (d *DiscoveryClient) ServerVersion() (*version.Info, error) {
	body, err := d.restClient.Get().AbsPath("/version").Do(context.TODO()).Raw()
	if err != nil {
		return nil, err
	}
	var info version.Info
	err = json.Unmarshal(body, &info)
	if err != nil {
		return nil, fmt.Errorf("unable to parse the server version: %v", err)
	}
	return &info, nil
}
```


If we don't get this based on kubeClient discovery we have no idea which version of k8s it is to invoke the right cert of certificate APIs - Most probably RKE is broken here and not providing us the necessary APIs to ensure we can autodetect this. 

Please install `k8s` using `kubeadm` works without any hassles.
