### ISSUE TITLE
Unable to update to latest Minio, incompatible signature algorithm

### ISSUE THREAD

**Issue by braunsonm** [minio/operator#913]
## Expected Behavior
I should be able to update the Minio version of my tenant to the latest version of Minio.

## Current Behavior

The operator reports errors and the tenant gets stuck in an "updating" state. 

```
[main-controller.go:577] error syncing 'minio/tenant': Tenant 'tenant' MinIO update failed with Incompatible signature algorithm
```

## Steps to Reproduce (for bugs)

1. Create a tenant with version `RELEASE.2021-11-09T03-21-45Z`
2. Upgrade the tenant to version `RELEASE.2021-11-24T23-19-33Z`
3. Notice operator errors: `Tenant 'tenant' MinIO update failed with Incompatible signature algorithm`

## Context
There is no alternate solutions, there is no way to update to the latest Minio using the operator as of now.

## Regression
Yes

## Your Environment
* Version used (`minio-operator`): 4.3.5
* Environment name and version (e.g. kubernetes v1.17.2): 1.21.5

**Comment by harshavardhana** [comment]
I have seen this and reproduced. Looks like a bug in operator

**Comment by harshavardhana** [comment]
You can however manually upgrade the statefulset directly as a workaround.

**Comment by harshavardhana** [comment]
Upstream library broke the signature algorithm support due to some pre-hashing techniques added.

https://github.com/jedisct1/go-minisign/issues/8

We will be making a new MinIO release that would resolve this problem, for existing deployments however you can remove the `MINIO_UPDATE_MINISIGN_PUBKEY` environment variable that would disable signature verification - that will only do `sha256sum` verification (this should be enough for now)

**Comment by mshanmu** [comment]
> Upstream library broke the signature algorithm support due to some pre-hashing techniques added.
> 
> [jedisct1/go-minisign#8](https://github.com/jedisct1/go-minisign/issues/8)
> 
> We will be making a new MinIO release that would resolve this problem, for existing deployments however you can remove the `MINIO_UPDATE_MINISIGN_PUBKEY` environment variable that would disable signature verification - that will only do `sha256sum` verification (this should be enough for now)

Just curious here, I just upgraded the MinIO from  RELEASE.2021-10-13T00-23-17Z to RELEASE.2021-12-10T23-03-39Z, using v4.3.7 operator (upgraded from v4.3.1). I thought the upgrade will fail with the above error, instead it went fine.  So, What am I missing here?

Btw, it did have the MINIO_UPDATE_MINISIGN_PUBKEY environment variable set.

**Comment by harshavardhana** [comment]
> Just curious here, I just upgraded the MinIO from RELEASE.2021-10-13T00-23-17Z to RELEASE.2021-12-10T23-03-39Z, using v4.3.7 operator (upgraded from v4.3.1). I thought the upgrade will fail with the above error, instead it went fine. So, What am I missing here?

Well, it will go fine even if it failed in the operator since - operator decides to apply the statefulset changes by rolling the pods.  @mshanmu 

It is not working for a specific situations where Operator does `in-place` updates.

**Comment by mshanmu** [comment]
@harshavardhana Thanks for the explanation

**Comment by braunsonm** [comment]
@harshavardhana This issue remains on minio version `RELEASE.2021-12-18T04-42-33Z`. Is there an operator update we need first?

**Comment by harshavardhana** [comment]
> @harshavardhana This issue remains on minio version `RELEASE.2021-12-18T04-42-33Z`. Is there an operator update we need first? 

This will only be fixed after you update to this release.

i.e you update to this release first and then you can update the normal way in future.
