### ISSUE TITLE
preferred CNI plugin for minio

### ISSUE THREAD

**Issue by AdheipSingh** [minio/operator#917]
## Current Behavior

- i have a bare metal k8s deployment with calico as CNI plugin. 
- somehow what i see, is internal lookup between minio nodes is not working. 
- as far my internal dns is concerned by setup was correct.

- so i test the same setup in digital ocean which uses cilium
- same configs run perfectly fine.

In both scenarios i had turn off ```MINIO_OPERATOR_TLS_ENABLE``` at operator and minio CR.

any preferred plugin for minio ? any issues seen with calico ? has anyone seen this issue before ? i was using centos 7 for bare metal

## Your Environment

* Version used (`minio-operator`): 4.3.5 ( latest helm )
* Environment name and version (e.g. kubernetes v1.21.2):
* Server type and version:
* Operating System and version (`uname -a`): centos 7 for bare metal
* Link to your deployment file:

**Comment by harshavardhana** [comment]
> any preferred plugin for minio ? any issues seen with calico ? has anyone seen this issue before ? i was using centos 7 for bare metal

Calico is preferred @AdheipSingh default calico setup is not optimal - here is the preferred setup

```
# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.17/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    nodeAddressAutodetectionV4:
      skipInterface: eno*
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: None
      natOutgoing: Enabled
      nodeSelector: all()
```

**Comment by AdheipSingh** [comment]
oh ok, now i get it. 
Thanks @harshavardhana for the spec. 

I'll redo and check. 
Will close this.
