### ISSUE TITLE
DirectCSI distributed setup minio pods placement

### ISSUE THREAD

**Issue by mjosipovic1979** [minio/operator#921]
hi all, 
i want to use minio operator to install minio distributed cluster using local drives on three (3) worker nodes. Every worker has 6 drives (total 18). As distributed setup reqs. (node=4 or more) we are trying to install 6 node (2 per worker) with 3 disks on each (for total 18). we are using directcsi minio as per recommendation, but having problems to schedule pods on right nodes (pod afinity, node selector etc). anyone using similar setup? is 6 nodes in poll with 3 drives ok? 
## Current Behavior

If we deploy tenant using Operator, tenant is stuck in creating pods/pvc.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

can not install minio 6 server cluster and utilize all 18 drives on 3 k8s worker machine

## Your Environment

* Version used (`minio-operator`):
minio/operator:v4.3.6
* Environment name and version (e.g. kubernetes v1.17.2):
vmware workers with k8s v1.21.5
* Server type and version:
vmware VM
* Operating System and version (`uname -a`):
* Ubuntu 20.04, Linux k8s-lab-s2 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:

Direct-CSI version
quay.io/minio/direct-csi:v1.4.6

kubectl-direct_csi drives ls |grep -i ready
 /dev/sdd   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s1  -            Ready
 /dev/sde   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s1  -            Ready
 /dev/sdf   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s1  -            Ready
 /dev/sdg   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s1  -            Ready
 /dev/sdh   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s1  -            Ready
 /dev/sdi   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s1  -            Ready
 /dev/sdd   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s2  -            Ready
 /dev/sde   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s2  -            Ready
 /dev/sdf   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s2  -            Ready
 /dev/sdg   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s2  -            Ready
 /dev/sdh   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s2  -            Ready
 /dev/sdi   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s2  -            Ready
 /dev/sdd   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s3  -            Ready
 /dev/sde   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s3  -            Ready
 /dev/sdf   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s3  -            Ready
 /dev/sdg   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s3  -            Ready
 /dev/sdh   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s3  -            Ready
 /dev/sdi   1.1 TiB   8.4 GiB    xfs         -        k8s-lab-s3  -            Ready

kubectl-direct_csi info

 NODE          CAPACITY  ALLOCATED  VOLUMES  DRIVES
 • k8s-lab-s1  6.5 TiB   0 B        0        6
 • k8s-lab-s2  6.5 TiB   0 B        0        6
 • k8s-lab-s3  6.5 TiB   0 B        0        6

0 B/20 TiB used, 0 volumes, 18 drives

**Comment by harshavardhana** [comment]
> i want to use minio operator to install minio distributed cluster using local drives on three (3) worker nodes. Every worker has 6 drives (total 18). As distributed setup reqs. (node=4 or more) we are trying to install 6 node (2 per worker) with 3 disks on each (for total 18). we are using directcsi minio as per recommendation, but having problems to schedule pods on right nodes (pod afinity, node selector etc). anyone using similar setup? is 6 nodes in poll with 3 drives ok?

You can't over-provision MinIO in this manner this is not recommended for production setup. If it's a single tenant each node should have a single instance of the pod. 

https://github.com/minio/minio/blob/master/docs/distributed/SIZING.md

Check the sizing list, anything less than < 4 servers is considered a toy setup and you can't have proper HA so we do not recommend that you deploy in this manner.

If you need architecture help - you are advised to get professional help here https://min.io/pricing
