### ISSUE TITLE
Tenants in same namespace

### ISSUE THREAD

**Issue by YuriBucci2** [minio/operator#922]
**Is your feature request related to a problem? Please describe.**
Multiple tenants in the same namespace

**Describe the solution you'd like**
Add support to multiple tenants in the same namespace

**Describe alternatives you've considered**

**Additional context**

**Comment by harshavardhana** [comment]
Multiple tenants in the same namespace are not possible @YuriBucci2 - it's our operator design decision.

There are no plans to change it.
