### ISSUE TITLE
Allow disabling + customizing Prometheus/LogSearch Deployments in Operator

### ISSUE THREAD

**Issue by ravindk89** [minio/operator#925]
**Is your feature request related to a problem? Please describe.**

During a training, one of the learners commented they had some concerns on managing the Prometheus/PostgreSQL services deployed as part of tenant support.

At this time there does not appear to be a simple way via the Operator Console UI to customize or disable the Prometheus and PostgreSQL service configs, beyond setting SecurityContext and PVC request size.

**Describe the solution you'd like**

For Prometheus, it seems reasonable to support a toggle (possibly under the Create Tenant -> Configure panel) to override deploying a per-Tenant Prometheus instance and instead point the Tenant at a centralized Prometheus instance. While this requires some work on the part of the user to set up Prometheus to scrape the Tenant, we can cover that in docs guidance.

For LogSearch, I think it's more complicated since the user has to create the appropriate tables/schemas in PostgreSQL to support LogSearch API, among a few other things. I'm not as certain how the guidance here would look. _But_ for users who would prefer (or cannot) deploy databases independent of their org's management structure, there should be a toggle to disable LogSearch entirely. We can include docs warning that this disables the Audit Log search feature in the Tenant Console.

**Describe alternatives you've considered**

One option is to provide guidance on modifying the Tenant deployment YAML to:

A) Customize deployment YAML to point at a central prometheus
B) Customize deployment YAML to remove Prometheus pod + service
C) Customize deployment YAML to remove LogSearch pod + service

This would be faster since it involves editing YAML and letting K8s do the work, but it also requires editing the YAML, which can be problematic for users who are trying to avoid that.

**Comment by harshavardhana** [comment]
> A) Customize deployment YAML to point at a central prometheus

We already support this check ServiceMonitor feature


> B) Customize deployment YAML to remove Prometheus pod + service

You can already do this just not mention it in YAML.


> C) Customize deployment YAML to remove LogSearch pod + service

You can already do this and not mention it in the YAML.

> During a training, one of the learners commented they had some concerns on managing the Prometheus/PostgreSQL services deployed as part of tenant support.

This is a design decision there should be no concern - MinIO is fully supporting such a deployment across various customers.

**Comment by ravindk89** [comment]
@harshavardhana when I was walking through the latest Operator Console UI, I didn't see a way to explicitly disable/configure prometheus/log search deployments in the way described above. I'll double check and see if I've missed something.

> We already support this check ServiceMonitor feature

Will look into this.

> This is a design decision there should be no concern - MinIO is fully supporting such a deployment across various customers.

We do by editing YAML, but I'm curious if we can do this entirely during Tenant creation w/o having to do work on the Tenant post-deployment.

**Comment by harshavardhana** [comment]
> @harshavardhana when I was walking through the latest Operator Console UI, I didn't see a way to explicitly disable/configure prometheus/log search deployments in the way described above. I'll double check and see if I've missed something.
> 
> >

Yes, this should be possible - AFAIK in the UI // cc @Alevsk @bexsoft can fill you in.

**Comment by harshavardhana** [comment]
![configure](https://user-images.githubusercontent.com/622699/145292338-fc34c80e-9edd-4a2b-9cc9-5f1d827f6cee.png)

It's available in the `Configure` section @ravindk89 - I don't think the issue needs any further attention at this point in time. 

Closing this since everything is possible already with the current operator.

**Comment by harshavardhana** [comment]
However to clarify "ServiceMonitor" support is being removed here #920 and this will make it easier.  But there is no UI support for this.

**Comment by ravindk89** [comment]
@harshavardhana I'll check in the morning, but when I took a look neither of the Override sections had an obvious toggle for disabling the service entirely. Will check w/ latest Operator though.
