### ISSUE TITLE
minio tenant expand is not generating proper yaml

### ISSUE THREAD

**Issue by kesavkolla** [minio/operator#932]
When run tenant expand command with -o option the yaml got generated doesn't have proper kubernetes apiVersion and kind.

```sh
kubectl minio tenant expand ostore1 --servers 4 --volumes 4 --capacity 20Gi --storage-class topolvm-provisioner -o | tee expand1.yaml
kubectl apply -f expand1.yaml

error: error validating "expand.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```

## Expected Behavior
kubectl apply should work fine

## Current Behavior
validation errors with kubectl apply

## Your Environment

* Version used (`minio-operator`): v4.3.7
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.23.0
* Operating System and version (`uname -a`): Linux kesavserver1 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
The generated YAML here is not meant to be used as standalone and its not designed to be that way.
