### ISSUE TITLE
SSL issue when providing the external certificates for Minio Operator deployment

### ISSUE THREAD

**Issue by Vineeth-varma** [minio/operator#933]
### When using the external certificates minio tenant is not responding properly in EKS cluster. 

- We are exposing minio service using elastic LoadBalancer, When curling the minio console we are getting the error as shown below...when providing the external certificates 
- `curl -k https://xyz.elb.us-east-2.amazonaws.com:30023
curl: (35) Peer reports it experienced an internal error.`
- The above issue we are facing when providing the external certificates through `externalCertSecret' field.
![image](https://user-images.githubusercontent.com/60296821/146535069-c4a1252c-87c1-4191-ab8f-7a765a1c278f.png)
- We have verified the certs and have used for other services which are working fine. 
- We have even checked inside Minio Tenant pod whether certs were placed in the right path or not.
- We have tried with providing the CN = *.amazonaws.com" and CN = "*.namespace.svc.cluster.local" which were generated using CertsManager and have tried the CN,DNS details just like how operator is providing for default certs. But none of them worked.

Please consider this request and let us know how to fix this.

**Comment by Alevsk** [comment]
@Vineeth-varma Please share here the logs for all minio pods, also  share here the public key of your certificates, im interesting on checking the domains in the SAN name

**Comment by Alevsk** [comment]
@Vineeth-varma Please try this documentation, specially the part of the custom certificates generation https://github.com/minio/operator/blob/master/docs/examples.md#minio-tenant-with-tls-via-customer-provided-certificates

Assuming your tenant name is `storage` and your namespace is `minio-tenant` you need to include this domains in your certificate (for the inter-node communication)

```
"*.minio-tenant.svc.cluster.local"
"*.storage.minio-tenant.svc.cluster.local"
"*.storage-hl.minio-tenant.svc.cluster.local"
```

you can add any other domain you want but you must include the above ones.

**Comment by Vineeth-varma** [comment]
I have checked the logs but there is nothing recorded regarding ssl evyrthing looks okay there.

`@Vineeth-varma Please try this documentation, specially the part of the custom certificates generation https://github.com/minio/operator/blob/master/docs/examples.md#minio-tenant-with-tls-via-customer-provided-certificates`

I have generated the certs using the exact above link as well as using certs manager both I have tried.

`
"*.minio-tenant.svc.cluster.local"
"*.storage.minio-tenant.svc.cluster.local"
"*.storage-hl.minio-tenant.svc.cluster.local"
`
The same domains I have used.

* Here I was using the EKS cluster elasticLoadbalancer (elb). When I ping the minio console elb I am getting 1 IP, using that I was able to access the cluster in browser.

* When I am using the elasticLoadbalancer dns I was not able to open the console in browser and minio server through "mc client". 

* I want to know why this is happening as I am using the Ip of the same loadbalancer dns.

Please let us know why external certs are failing with elasticLoadbalancer dns ?

Thanks
@Alevsk
