### ISSUE TITLE
add more key/values to tenant CRD in helm

### ISSUE THREAD

**Issue by AdheipSingh** [minio/operator#938]
**Is your feature request related to a problem? Please describe.**
- https://github.com/minio/operator/blob/master/helm/tenant/templates/tenant.yaml
- tenant crd in helm has lot of key/values missing like ```exposeServices```, probes etc.

**Describe the solution you'd like**
- can template out and reference in values.yaml

**Comment by AdheipSingh** [comment]
ill be willing to PR this

**Comment by harshavardhana** [comment]
Thanks @AdheipSingh
