### ISSUE TITLE
Kubernetes API Server throws conversion webhook errors

### ISSUE THREAD

**Issue by mshanmu** [minio/operator#939]
Sometime back there was a bug relating to TLS certificates not getting automatically rotated. Due to that, I decided to disable the operator TLS.

Thereby, I did the following,

1. Updated the operator to disable TLS, by setting MINIO_OPERATOR_TLS_ENABLE=off using helm
2. Delete operator TLS secret and webhook in tenant namespaces

Everything seems to be working fine, since the webhook got re-generated with proper MINIO_ARGS etc.,

Only nuisance seems to be error getting logged in the API server, 

E1227 21:13:58.624694       1 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/minio.min.io/tenants: Failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post https://operator.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s: http: server gave HTTP response to HTTPS client

It seems that some configuration is not getting update to use HTTP instead of HTTPS.

## Expected Behavior

No errors in api server log

## Current Behavior

Seeing the following error message every second,

$ k -n kube-system logs -f --tail=20 kube-apiserver-minio-m1
E1227 21:13:58.624694       1 cacher.go:428] unexpected ListAndWatch error: storage/cacher.go:/minio.min.io/tenants: Failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post https://operator.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s: http: server gave HTTP response to HTTPS client

## Steps to Reproduce (for bugs)

1. Helm install Operator with tenant
2. Modify the operator helm chart to MINIO_OPERATOR_TLS_ENABLE=off 
3. Helm upgrade
4. Delete the TLS secrets and webhook from operator and tenant namespaces
5. Everything works
6. Notice the error in api server logs

## Your Environment

* Version used (`minio-operator`): v4.3.7
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by ShayBenyo11** [comment]
I'm facing the same issue and have been trying to debug it for days thinking maybe something's off in our air-gapped environment, as I have encountered this error in different environments.
Solution for this would be amazing!

**Comment by mshanmu** [comment]
Looks like this reproduces even with fresh installations, i.e., there is no need to do switch from HTTPS to HTTP.

**Comment by mshanmu** [comment]
I suspect this might be an API server restriction, i.e., it can only communicate using HTTPS to webhook.

**Comment by mshanmu** [comment]
Since, I was using the latest version (minio.min.io/v2), I did not have any impact due to this issue, other than the error message in api server every second.

But, for installations using minio.min.io/v1 tenants, they might have service outage, since the conversion webhook is not working.

**Comment by ShayBenyo11** [comment]
> minio
Can you maybe share your installation procedure, of how you managed to only use the minio.min.io/v2 without impact?
I have also installed using the 4.3.7 version, yet with couldn't manage to make the conversion webhook work as it kept looking for v1 objects while not succeeding in turning to v2.

**Comment by ShayBenyo11** [comment]
> Since, I was using the latest version (minio.min.io/v2), I did not have any impact due to this issue, other than the error message in api server every second.
> But, for installations using minio.min.io/v1 tenants, they might have service outage, since the conversion webhook is not working.

Can you maybe share your installation procedure, of how you managed to only use the minio.min.io/v2 without impact?
I have also installed using the 4.3.7 version, yet with couldn't manage to make the conversion webhook work as it kept looking for v1 objects while not succeeding in turning to v2.

**Comment by mshanmu** [comment]
@ShayBenyo11 , I have difficulty understanding your question, since I am new to MinIO as well. AFAIK, conversion webhook only matters if there are old tenants using minio.min.io/v1. 

In my case, when I did  a fresh install with TLS_ENABLE=off using helm, i.e., helm install <release name> <helm tgz>, operator and tenant pods come up fine and tenant gets initialized properly. I am able to do minio operations without any issues.

Also, when I do "kubectl -n <tenant namespace> describe tenant <tenant name> " , I can see it uses the minio.min.io/v2 api version, see below,

$kubectl -n <tenant namespace> describe tenant <tenant name>
Name:         <tenant name>
Namespace:    <tenant namespace>
Labels:       app=minio
              app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: <release name>
              meta.helm.sh/release-namespace: <operator namespace>
API Version:  minio.min.io/v2
Kind:         Tenant
Metadata:

**Comment by ShayBenyo11** [comment]
@mshanmu So for me, even in fresh-installing either using ArgoCD or the binary plugin (kubectl-minio) with the env variable set to 'off', it'll constantly show up this error. I have ONCE managed to somehow make it work for one cluster but then again the same changes didn't work for the other, so i'm looking for a permanent solution or maybe a pointing out to what may be missing/is restricted in our environments.

**Comment by mshanmu** [comment]
> @mshanmu So for me, even in fresh-installing either using ArgoCD or the binary plugin (kubectl-minio) with the env variable set to 'off', it'll constantly show up this error. I have ONCE managed to somehow make it work for one cluster but then again the same changes didn't work for the other, so i'm looking for a permanent solution or maybe a pointing out to what may be missing/is restricted in our environments. Can you maybe share on what platform you're deploying? Maybe Openshift is a troubeld environment in general for this.

@ShayBenyo11 I am using plain vanilla kubernetes cluster. I think Openshift is the problem in your environment.

**Comment by pjuarezd** [comment]
this issue was often seen in Openshift and k8s with broken TLS configs, starting operator 5.0.0 + conversion webhook was removed, as well Operator no longer needs a TLS certificate for himself to talk Tenants.

Solution will be to upgrade to latest operator versions.
