### ISSUE TITLE
certificate signed by unknown authority on Openshift

### ISSUE THREAD

**Issue by ShayBenyo11** [minio/operator#942]
Deloying 4.3.7 operator on Openshift 4.6 (Air-gapped) causes `x509 certificate signed by unknown authority` and `TLS handshake error from XXXX: remote error: tls: bad certificate` errors on operator pods.
API server pods also throws `unexpected ListAndWatch error: failed to list minio.min.io/v2, Kind=Tenant: conversion webhook for minio.min.io/v1, Kind=Tenant failed: Post "https://operator.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate signed by unknown authority; reinitializing`

## Expected Behavior
Signed operator certificates are authorized and trusted by API server

## Current Behavior
Operator pods can't communicate with the requested URL and tenant resources. 
Also API server can't reach tenant resources which results in being unable to create tenants, and error results from entering the Instances tab under the CRD. 
curl https://operator.minio-operator.svc:4222/webhook/v1/crd-conversion -vvv resulted in:
```
TLS alert, unknown CA
SSL Certificate problem: unable to get local issuer certificate
```

CSR is signed by legacy-unknown which for my understanding isn't good, but I couldn't find how to change the csr signer. Also the server certificate signer is kube-csr-signer.

## Possible Solution
Using MINIO_OPERATOR_TLS_ENABLE='off' causes other errors such as #939 so maybe solving that issue somehow
Or somehow be able to alter CA files inside the pods  (I thought maybe because we're in an air-gapped environment the CA's aren't valid, but I also tried mapping our own ca-bundle ConfigMap into the pod which didn't work, so maybe i'm missing something0

## Steps to Reproduce (for bugs)
1. Deploy operator 4.3.7 using kubectl-minio binary "kubectl-minio 4.3.7.... init --<IMAGES> -n minio-operator" 
--- also tried deploying with ArgoCD but in that way it doesn't automatically create operator-tls secret ---

## Context
Can't deploy operator, not even reach the stage of trying to create tenants. 

## Regression
I don't know, have seen older issues regarding the same problems am having but using the almost-latest version haven't solved it for me.

## Your Environment

* Version used (`minio-operator`): 4.3.7
* Environment name and version: Openshift 4.6.35, Kubernetes 1.19

**Comment by Rushmead** [comment]
I too had this issue and it seems that it's because the version of Kubernetes is less than 1.22 it uses the v1beta1 version of the Certificates API, even though the API has been stable since 1.19.  Not sure of a work around to this as of yet, perhaps the version check for using v1 could be brought down to 1.19?

**Comment by ianwijaya** [comment]
Hi, 

We also encountered this issue. The operator is already up and running, but when we tried creating the tenant with TLS enabled, it got stuck.
We saw some error generated from the Operator pods, complaining about the unknown authority: 

`I0511 08:45:22.220287       1 monitoring.go:176] 'minio-tenant/minio-tenant1' Failed to get storage info: Get "https://minio.minio-tenant.svc.cluster.local/minio/admin/v3/storageinfo": x509: certificate signed by unknown authority
`
curl-ing from the Operator pods to the tenant also verified this error : 
`sh-4.4$ curl -vvvk https://minio.minio-tenant.svc.cluster.local/minio/admin/v3/storageinfo
--lines omitted--
* Connected to minio.minio-tenant.svc.cluster.local (172.21.38.151) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
--lines omitted--
*  subject: O=system:nodes; CN=system:node:*.minio-tenant-testing-3-hl.minio-tenant.svc.cluster.local
*  start date: May 11 11:04:04 2022 GMT
*  expire date: May 29 10:54:00 2022 GMT
*  issuer: CN=**kube-csr-signer_@1651229640**
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.`

it's signed by the **kube-csr-signer**, however the operator doesn't seem to recognize this certificate. 
Our minio is running v4.4.17 on Openshift 4.10.3 

Any input? 
Thanks,
Ian

**Comment by davidkarlsen** [comment]
+1, it's flat out broken on openshift

**Comment by dnskr** [comment]
I've just reproduced the issue with OpenShift 4.10.28 and Operator 4.5.4

**Comment by mriehl** [comment]
still broken in openshift 4.11 and operator 4.5.7

**Comment by mriehl** [comment]
It's actually not broken, the README has a section about this:

> MinIO Tenants deploy with TLS enabled by default, where the MinIO Operator uses the Kubernetes certificates.k8s.io API to generate the required x.509 certificates. Each certificate is signed using the Kubernetes Certificate Authority (CA) configured during cluster deployment. While Kubernetes mounts this CA on Pods in the cluster, Pods do not trust that CA by default. You must copy the CA to a directory such that the update-ca-certificates utility can find and add it to the system trust store to enable validation of MinIO TLS certificates

So this is obviously not something that the minio operator can/should fix. But I guess it should be in the operator documentation.

**Comment by pjuarezd** [comment]
This kind of issue was very common in Openshift environments.
Starting operator version 5.0.0 + the conversion webhook is deprecarted, also Operator no longer issues a certificate for himself for the tenants to communicate with him.
