### ISSUE TITLE
Undocumented breaking change in CRD for Operator 4.3.9

### ISSUE THREAD

**Issue by neilclark-bgn** [minio/operator#955]
## Expected Behavior

I have just updated Minio Operator from version 4.3.5 to 4.3.9 in our development cluster using the Helm chart. Being a minor version change, with nothing of concern in the release notes, I expected the pods to restart and just work. 

## Current Behavior

4.3.9 appears to include a breaking change in the CRD within the Helm chart, relating to spec.prometheusOperator

CRD in 4.3.8:

`              prometheusOperator:
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    type: object
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                type: object`

CRD in 4.3.9:

`              prometheusOperator:
                type: boolean`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

This has resulted in our Tenants (Deployed in a Gitops workflow using Flux) failing to deploy with the following error:

_error validating data: ValidationError(Tenant.spec.prometheusOperator): invalid type for io.min.minio.v2.Tenant.spec.prometheusOperator: got "map", expected "boolean"; if you choose to ignore these errors, turn validation off with --validate=false_

I can find no reference to this change in the release notes and no documentation regarding how to use the new Prometheus Operator functionality. Previously we specified a label under spec.prometheusOperator.labels which ensured the ServiceMonitor would be picked up by the correct Prometheus server. I have no idea how to replicate this same functionality with the new CRD.

## Regression

Yes. PrometheusOperator functionality no longer works as expected.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

Minio operator 4.3.9 deployed with Flux using the Helm chart.
Multiple Tenants deployed by Flux. These do not using the Helm chart.

**Comment by dvaldivia** [comment]
@kanagarajkm @harshavardhana we should document this to avoid further confusion

**Comment by phlegx** [comment]
I'm also facing these issues. How can this be solved? Thanks!

**Comment by kanagarajkm** [comment]
@phlegx @neilclark-bgn using service monitor was creating multiple endpoints in prometheus. Prometheus was scrapping all the underlying pods of the service, this leads to duplicate data. Instead of service monitors, we will use additional scrape config https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md.

you can set  `prometheusOperator: true`, this will create additional config on promethues with the service endpoint.

`PROMETHEUS_NAMESPACE` env can be set if prometheus operator is not running on the default namespace.

**Comment by neilclark-bgn** [comment]
@kanagarajkm we are running many Prometheus instances created by the Prometheus operator. How can we select which Prometheus server the additional scrape config is added to?

Previously we could provide a label that would be passed to the ServiceMonitor to handle this.

**Comment by harshavardhana** [comment]
> @kanagarajkm we are running many Prometheus instances created by the Prometheus operator. How can we select which Prometheus server the additional scrape config is added to?
> 

Prometheus operator is one that is the one that you need to pick.

> Previously we could provide a label that would be passed to the ServiceMonitor to handle this.

This doesn't work with what we want so we had to remove it

**Comment by kanagarajkm** [comment]
@neilclark-bgn you can set `PROMETHEUS_NAME` if you want to select a particular prometheus instance.

**Comment by neilclark-bgn** [comment]
@kanagarajkm PROMETHEUS_NAME env sounds like what I'm looking for. I'll give that a try. Thank you.

**Comment by neilclark-bgn** [comment]
@kanagarajkm I have tested using `PROMETHEUS_NAME` & `PROMETHEUS_NAMESPACE` with the 4.4.3 operator Helm chart but the operator errored as follows:

`prometheuses.monitoring.coreos.com is forbidden: User "system:serviceaccount:minio-operator:minio-operator" cannot list resource "prometheuses" in API group "monitoring.coreos.com" in the namespace "monitoring"`

It seems that the ClusterRole version 4.4.3 of the Helm chart does not provide the required permissions.

I have patched the ClusterRole in my deployment and confirmed that with additional permissions, the env you provided works. Many thanks for your help.

**Comment by neilclark-bgn** [comment]
I'm inclined to agree with @pdf that this feels over complicated, although it works well in my experience once I had got it working.

The reason I raised this issue was not down to how the metrics are scraped, but because this broke the existing implementation for anyone already using it, and did so on a minor release with no mention in the release notes, and little to no documentation.

That still stands true today and in my opinion would benefit from being addressed. There is still no mention of this change in the 4.3.9 release notes. There is still no warning to users that type and functionality of the `prometheusOperator` key has changed and will potentially cause problems for anybody upgrading who uses it in the old way.

Additionally the documentation of the `prometheusOperator` functionality is still poor. In fact a quick scan of the examples from the `v4.4.18` release still shows the `prometheusOperator` key being using in the old way (albeit commented out) which no longer works - https://github.com/minio/operator/blob/v4.4.18/examples/kustomization/base/tenant.yaml

Anyway, just wanted to raise my head and say that this issue still feels relevant.

**Comment by mts-dyt** [comment]
Can someone share a valid helm value file?
The default helm value don't work If we follow the documentation with simple command provided: https://github.com/minio/operator/blob/master/helm/operator/README.md#creating-a-tenant
```
helm install --namespace tenant-ns  --create-namespace tenant minio/tenant
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Tenant.spec.prometheusOperator): invalid type for io.min.minio.v2.Tenant.spec.prometheusOperator: got "boolean", expected "map"
```

**Comment by ColonelBundy** [comment]
I'm also inclined to agree with @pdf and I also feel this issue is still relevant. Additionalscrapeconfigs feels like a overcomplicated fix for something that works just as fine using a servicemonitor.

**Comment by pdf** [comment]
Not stale

**Comment by blampe** [comment]
Previously, [VictoriaMetrics](http://victoriametrics.github.io) could consume the `ServiceMonitor` generated by Minio without issue. I've been unsuccessful getting things to work again after upgrading and setting `PROMETHEUS_NAMESPACE`/`PROMETHEUS_NAME` as recommended here ("No prometheus found on namespace monitoring"). I imagine this is because VM's operator doesn't expose the same API as Prometheus'.

I agree that using the ServiceMonitor CRD is less complicated, and also more compatible for those of us not using Prometheus.

**Comment by allanrogerr** [comment]
Could you retry on minio operator v5.0.11 or above please? See https://github.com/minio/operator/blob/master/UPGRADE.md
Note that: _Both Log Search API (.spec.log) and Prometheus (.spec.prometheus) deployments were removed,..._

For usage of minio metrics using the prometheus data model see https://min.io/docs/minio/linux/operations/monitoring/collect-minio-metrics-using-prometheus.html

**Comment by harshavardhana** [comment]
Please retry with v5.0.12 release

**Comment by orlovmyk** [comment]
@harshavardhana I am getting this in `operator` logs, not in `tenant`. For operator there is no `prometheusOperator` property in helm chart.

Operator logs:
```
E0301 21:10:48.045410       1 reflector.go:147] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1alpha1.MinIOJob: failed to list *v1alpha1.MinIOJob: miniojobs.job.min.io is forbidden: User "system:serviceaccount:minio:minio-operator" cannot list resource "miniojobs" in API group "job.min.io" at the cluster scope
E0301 21:10:53.496829       1 main-controller.go:744] error syncing 'dev/minio-dev': No prometheus found on namespace default
E0301 21:11:16.046183       1 main-controller.go:744] error syncing 'logs/minio-logs': No prometheus found on namespace default
W0301 21:11:28.466995       1 reflector.go:539] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1alpha1.MinIOJob: miniojobs.job.min.io is forbidden: User "system:serviceaccount:minio:minio-operator" cannot list resource "miniojobs" in API group "job.min.io" at the cluster scope
E0301 21:11:28.467019       1 reflector.go:147] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1alpha1.MinIOJob: failed to list *v1alpha1.MinIOJob: miniojobs.job.min.io is forbidden: User "system:serviceaccount:minio:minio-operator" cannot list resource "miniojobs" in API group "job.min.io" at the cluster scope
E0301 21:11:53.525687       1 main-controller.go:744] error syncing 'dev/minio-dev': No prometheus found on namespace default
E0301 21:12:16.079739       1 main-controller.go:744] error syncing 'logs/minio-logs': No prometheus found on namespace default
W0301 21:12:28.402926       1 reflector.go:539] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1alpha1.MinIOJob: miniojobs.job.min.io is forbidden: User "system:serviceaccount:minio:minio-operator" cannot list resource "miniojobs" in API group "job.min.io" at the cluster scope
E0301 21:12:28.402969       1 reflector.go:147] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1alpha1.MinIOJob: failed to list *v1alpha1.MinIOJob: miniojobs.job.min.io is forbidden: User "system:serviceaccount:minio:minio-operator" cannot list resource "miniojobs" in API group "job.min.io" at the cluster scope
E0301 21:12:53.540787       1 main-controller.go:744] error syncing 'dev/minio-dev': No prometheus found on namespace default
W0301 21:13:15.444528       1 reflector.go:539] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1alpha1.MinIOJob: miniojobs.job.min.io is forbidden: User "system:serviceaccount:minio:minio-operator" cannot list resource "miniojobs" in API group "job.min.io" at the cluster scope
E0301 21:13:15.444553       1 reflector.go:147] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1alpha1.MinIOJob: failed to list *v1alpha1.MinIOJob: miniojobs.job.min.io is forbidden: User "system:serviceaccount:minio:minio-operator" cannot list resource "miniojobs" in API group "job.min.io" at the cluster scope
E0301 21:13:16.113457       1 main-controller.go:744] error syncing 'logs/minio-logs': No prometheus found on namespace default
```
