### ISSUE TITLE
Error when Tenant is created

### ISSUE THREAD

**Issue by phlegx** [minio/operator#969]
Using the default values for values.yml from the git repository and applying the Tenant to my Kubernetes cluster. When I then go to the console I get the following error:

```
An error occurred, please try again
V2.TenantList.Items: []v2.Tenant: v2.Tenant.Spec: v2.TenantSpec.PrometheusOperator: readObjectStart: expect { or n, but found f, error found in #10 byte of ...|perator":false,"requ|..., bigger context ...|d"}},"volumesPerServer":1}],"prometheusOperator":false,"requestAutoCert":true,"s3":{"bucketDNS":fals|...
```

Any ideas what might causing this? Is there a way to make this more verbose? I assume this is some misconfiguration in my Yaml file or a Bug.

It used to work with an older version (4.3.x)  though.

## Your Environment
* Version used (`minio-operator`): 4.4.3
* Environment name and version (e.g. kubernetes v1.17.2): v1.20.8

**Comment by kkendzia** [comment]
Just came here to report the same issue.
kubernetes v1.22.5
minio-operator helm: 4.4.3
tenant helm: 4.4.3
