### ISSUE TITLE
Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted

### ISSUE THREAD

**Issue by seungweonpark** [minio/operator#985]
Deployed MinIO Operator/Console via Helm chart, and deployed Tenant as well via helm chart over 4 nodes, each node has 4 nvme drives with 1GB capacity partition on each, total 16GB. When deployed, tenant pods are up and running but entire tenant is not back online with the below errors:

1. Some pods have - Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation .minio.sys/backend-encrypted)
2. Other pods have - Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to initialize config system: migrateConfigToMinioSys: Storage resources are insufficient for the read operation .minio.sys/config/config.json)

## Expected Behavior
Expect it should be deployed with no issue on MinIO Operator v4.4.1

## Current Behavior
Getting errors, and health is unavailble. I can't find the the documentation regarding the error mesages.

## Steps to Reproduce (for bugs)
Tenant
```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    meta.helm.sh/release-name: minio-tenant
    meta.helm.sh/release-namespace: minio-tenant
  creationTimestamp: "2022-01-25T08:56:20Z"
  generation: 5
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
  name: minio-tenant
  namespace: minio-tenant
  resourceVersion: "39595"
  uid: 19eff50c-b1e2-4ade-a7ca-3a215776f49b
scheduler:
  name: ""
spec:
  credsSecret:
    name: minio1-secret
  env:
  - name: MINIO_BROWSER
    value: "on"
  - name: MINIO_STORAGE_CLASS_STANDARD
    value: EC:3
  image: quay.io/minio/minio:RELEASE.2022-01-04T07-41-07Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  mountPath: /mnt/data
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio-tenant
          topologyKey: kubernetes.io/hostname
    resources: {}
    servers: 4
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-storage
      status: {}
    volumesPerServer: 4
  prometheus:
    diskCapacityGB: 5
    resources: {}
  requestAutoCert: false
  s3:
    bucketDNS: false
  subPath: /data
status:
  availableReplicas: 4
  certificates:
    autoCertEnabled: false
  currentState: Initialized
  healthMessage: Service Unavailable
  healthStatus: red
  pools:
  - legacySecurityContext: false
    ssName: minio-tenant-ss-0
    state: PoolInitialized
  provisionedUsers: true
  revision: 0
  syncVersion: v4.3.0
  usage: {}
  writeQuorum: 13
```

```bash
# lsblk |grep nvme
nvme0n1     259:0    0   2.9T  0 disk
└─nvme0n1p1 259:8    0  1023M  0 part /var/lib/kubelet/pods/4ca0ea00-5bcd-478a-aca6-449dd3476077/volumes/kubernetes.io~local-volume/mnt-data-1-am09-19-cyp
nvme1n1     259:1    0   2.9T  0 disk
└─nvme1n1p1 259:9    0  1023M  0 part /var/lib/kubelet/pods/4ca0ea00-5bcd-478a-aca6-449dd3476077/volumes/kubernetes.io~local-volume/mnt-data-2-am09-19-cyp
nvme2n1     259:2    0   2.9T  0 disk
└─nvme2n1p1 259:10   0  1023M  0 part /var/lib/kubelet/pods/4ca0ea00-5bcd-478a-aca6-449dd3476077/volumes/kubernetes.io~local-volume/mnt-data-3-am09-19-cyp
nvme3n1     259:3    0   2.9T  0 disk
└─nvme3n1p1 259:11   0  1023M  0 part /var/lib/kubelet/pods/4ca0ea00-5bcd-478a-aca6-449dd3476077/volumes/kubernetes.io~local-volume/mnt-data-4-am09-19-cyp
```
```bash
# mount |grep data
/dev/nvme0n1p1 on /mnt/data0 type ext4 (rw,relatime)
/dev/nvme1n1p1 on /mnt/data1 type ext4 (rw,relatime)
/dev/nvme2n1p1 on /mnt/data2 type ext4 (rw,relatime)
/dev/nvme3n1p1 on /mnt/data3 type ext4 (rw,relatime)
/dev/nvme1n1p1 on /var/lib/kubelet/pods/4ca0ea00-5bcd-478a-aca6-449dd3476077/volumes/kubernetes.io~local-volume/mnt-data-2-am09-19-cyp type ext4 (rw,relatime)
/dev/nvme2n1p1 on /var/lib/kubelet/pods/4ca0ea00-5bcd-478a-aca6-449dd3476077/volumes/kubernetes.io~local-volume/mnt-data-3-am09-19-cyp type ext4 (rw,relatime)
/dev/nvme3n1p1 on /var/lib/kubelet/pods/4ca0ea00-5bcd-478a-aca6-449dd3476077/volumes/kubernetes.io~local-volume/mnt-data-4-am09-19-cyp type ext4 (rw,relatime)
/dev/nvme0n1p1 on /var/lib/kubelet/pods/4ca0ea00-5bcd-478a-aca6-449dd3476077/volumes/kubernetes.io~local-volume/mnt-data-1-am09-19-cyp type ext4 (rw,relatime)
```

```bash
# kubectl describe pv mnt-data-1-am09-19-cyp
Name:              mnt-data-1-am09-19-cyp
Labels:            <none>
Annotations:       pv.kubernetes.io/bound-by-controller: yes
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      local-storage
Status:            Bound
Claim:             minio-tenant/data3-minio-tenant-ss-0-1
Reclaim Policy:    Retain
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          1Gi
Node Affinity:
  Required Terms:
    Term 0:        kubernetes.io/hostname in [am09-19-cyp]
Message:
Source:
    Type:  LocalVolume (a persistent volume backed by local storage on a node)
    Path:  /mnt/data0
Events:    <none>
```
## Your Environment
* Version used (`minio-operator`): v4.4.1
* Environment name and version (e.g. kubernetes v1.17.2): 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
* Operating System and version (`uname -a`): Ubuntu 21.04.02 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by seungweonpark** [comment]
I guess if the nvme storage device names have the issue? or I have read [https://github.com/minio/minio/issues/9018](https://github.com/minio/minio/issues/9018) which has the same error message, wonder how I can change to the correct pattern for my case:

`args:
        - minio
        - server
        - http://{{ app_name }}-0.{{ app_name }}.{{ domain_name }}:{{ app_port }}/data{1...8}
        - http://{{ app_name }}-1.{{ app_name }}.{{ domain_name }}:{{ app_port }}/data{1...8}
        - http://{{ app_name }}-2.{{ app_name }}.{{ domain_name }}:{{ app_port }}/data{1...8}
        - http://{{ app_name }}-3.{{ app_name }}.{{ domain_name }}:{{ app_port }}/data{1...8}`

to 

`- http://{{ app_name }}-{0...3}.{{ app_name }}.{{ domain_name }}:{{ app_port }}/data{1...8}`

What is this for and where I can find more info?

**Comment by harshavardhana** [comment]
Pattern is automatically chosen by operator, this looks like your setup has few issues

- The disks are not writable i.e do not support O_DIRECT properly
- The network is not reachable to those drives 

I just tested operator on a local setup everything works fine.

**Comment by seungweonpark** [comment]
@harshavardhana Thank you for the answer!! I am not sure if my question is ok here but it might be helpful when someone has the same case. So mind if I ask that my ansible task has something wrong for parititioning for PV?

- name: create a new ext4 primary partition
  parted:
    name: "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].name }}"
    device: "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].device }}"
    label: gpt
    number: 1
    part_type: primary
    part_end: "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].capacity }}"
    flags: [ lvm ]
    state: present

**Comment by harshavardhana** [comment]
> @harshavardhana Thank you for the answer!! I am not sure if my question is ok here but it might be helpful when someone has the same case. So mind if I ask that my ansible task has something wrong for parititioning for PV?
> 
> * name: create a new ext4 primary partition
>   parted:
>   name: "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].name }}"
>   device: "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].device }}"
>   label: gpt
>   number: 1
>   part_type: primary
>   part_end: "{{ hostvars[inventory_hostname]['minio_pv'][ansible_loop.index0].capacity }}"
>   flags: [ lvm ]
>   state: present

Don't use ext4 - XFS is recommended @seungweonpark

**Comment by seungweonpark** [comment]
@harshavardhana Thank you so much for the tips. xfs works great as charm.
